# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("rh", "0094_datamigration_vacancy_number_filled"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionalId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "functional_type",
                    models.SmallIntegerField(
                        choices=[(1, "Servidor"), (2, "Membro")],
                        default=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assinado"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revogado"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "employee_registration",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Matricula"
                    ),
                ),
                (
                    "ingress_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de ingresso"
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome da m\xe3e",
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nome do pai",
                    ),
                ),
                (
                    "born_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "local_id_number",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="RG"
                    ),
                ),
                (
                    "local_id_issuance",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="RG expedido por",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Tipo sanguineo",
                    ),
                ),
                (
                    "organ_donor",
                    models.BooleanField(
                        default=False, verbose_name="Doador de \xf3rg\xe3o"
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Vers\xe3o"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Estado"),
                ),
                (
                    "born_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="rh.Localidade",
                        verbose_name="Local de nascimento",
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entregue por",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="have_functional_ids",
                        to="rh.Servidor",
                        verbose_name="Empregado",
                    ),
                ),
                (
                    "employee_sign_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ged.Arquivo",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revogado por",
                    ),
                ),
                (
                    "signatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="rh.Cargo",
                        verbose_name="Signat\xe1rio",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assinado por",
                    ),
                ),
                (
                    "validator_sign_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ged.Arquivo",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "-revoked_at",
                    "-signed_at",
                    "employee__pessoa_fisica__nome",
                ),
                "permissions": (
                    ("can_sign_functional_id", "Pode assinar carteiras funcionais."),
                    ("can_revoke_functional_id", "Pode revogar carteiras funcionais."),
                ),
            },
        ),
    ]
