# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 13:08
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 13:08
from __future__ import unicode_literals

import os

from django.db import migrations
from django.core.management import call_command
from django.conf import settings


FIXTURES = ("fixtures/01-choices.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "common", "functional_id", fixture)
        print(' * fixture "%s"' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("functional_id", "0001_initial"),
    ]

    operations = [migrations.RunPython(forward, backward)]
