# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functional_id", "0002_populate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionalid",
            name="functional_type",
            field=models.SmallIntegerField(
                choices=[
                    (2, "Membro do Ministério Público"),
                    (1, "Servidor do Ministério Público"),
                ],
                default=1,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="functionalid",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Editando"),
                    (2, "Confeccionando"),
                    (3, "Revogado"),
                    (4, "Entregue"),
                ],
                default=1,
                verbose_name="Estado",
            ),
        ),
    ]
