# Generated by Django 2.2.28 on 2023-07-26 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomeacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConviteNomeacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "classificado",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Classificado?"
                    ),
                ),
                (
                    "status_convocacao",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Status da Convocação",
                    ),
                ),
                (
                    "data_convocacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Convocação"
                    ),
                ),
                (
                    "data_email_convocacao",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data do Email de Convocação",
                    ),
                ),
                (
                    "data_desistencia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Desistência"
                    ),
                ),
                (
                    "data_resposta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "data_possivel_expericao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Possível Expiração"
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Expiração"
                    ),
                ),
                (
                    "sinc_form",
                    models.BooleanField(
                        default=True, verbose_name="Sincronizar Formulário"
                    ),
                ),
                (
                    "convidado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convite_nomeacao",
                        to="nomeacao.PessoaFisicaConvidado",
                        verbose_name="Convite Nomeação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite de Nomeação",
                "verbose_name_plural": "Convites de Nomeação",
                "ordering": ("convidado__nome_completo",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
