# Generated by Django 2.2.28 on 2023-09-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0267_auto_20230914_0842"),
        ("cadastramento", "0004_anexoconvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="convitenomeacao",
            name="provimento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="convite_Nomeação",
                to="rh.MovimentacaoPosse",
                verbose_name="Provimento",
            ),
        ),
    ]
