# Generated by Django 2.2.17 on 2020-12-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("message", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("send_at", models.DateTimeField(blank=True, null=True)),
                ("finalized", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Servidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de Controle de envio",
                "ordering": ["employee"],
                "permissions": (("is_administrator", "Administrador"),),
            },
        ),
    ]
