# Generated by Django 2.2.28 on 2022-09-30 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0199_auto_20220930_0922"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=400, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês de Competência",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(verbose_name="Ano de Competência"),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Local"
                    ),
                ),
                (
                    "time_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Total de Horas",
                    ),
                ),
                (
                    "capacitation_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Total de Horas",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Período"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=400, verbose_name="Nome")),
                (
                    "type_participant",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "PALESTRANTE"), (2, "CONVIDADO")],
                        default=1,
                        null=True,
                        verbose_name="Tipo de Participação",
                    ),
                ),
                (
                    "capacitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="ceaf.Capacitation",
                        verbose_name="Participantes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
