# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0060_auto_20190401_2021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="remunerationperiod",
            options={"ordering": ("-start", "remuneration__identifier")},
        ),
        migrations.AlterField(
            model_name="genreevent",
            name="config_transparency",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Portal Transpar\xeancia"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoprogressao",
            name="initial_expected_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data Prevista"),
        ),
    ]
