# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0061_auto_20190530_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhamodelo",
            name="para_indicativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGI\xc1RIO"),
                    ("M", "MEMBRO DO MINIST\xc9RIO P\xdaBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNT\xc1RIO"),
                    ("A", "JOVEM CIDAD\xc3O - APRENDIZ"),
                ],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Para os",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movimentacaoprogressao",
            unique_together=set([]),
        ),
    ]
