# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0092_auto_20190617_1447"),
        ("gfp", "0062_auto_20190618_1803"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movimentacaoprogressao",
            unique_together=set([("movimentacao_posse", "referencia_nivel2d")]),
        ),
    ]
