# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 12:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0063_auto_20190618_1803"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigSalaryProgression",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "start_validity",
                    models.DateField(verbose_name="In\xedcio vig\xeancia"),
                ),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vig\xeancia"
                    ),
                ),
                (
                    "class_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="config_salaryprogression",
                        to="standard.ClassCode",
                        verbose_name="C\xf3digo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AlterField(
            model_name="calculo",
            name="typeof",
            field=models.CharField(
                choices=[
                    ("CALCULO", "C\xe1lculos para FOPAG"),
                    ("LOADER", "Carregadores de arquivos"),
                ],
                db_index=True,
                default="CALCULO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contracheque",
            name="error_validations",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Erro de valida\xe7\xf5es"
            ),
        ),
        migrations.AlterField(
            model_name="estruturatabelasalarial",
            name="salary_unit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Por Hora"),
                    (2, "Por Dia"),
                    (3, "Por Semana"),
                    (4, "Por Quinzena"),
                    (5, "Por M\xeas"),
                    (6, "Por Tarefa"),
                    (7, "N\xe3o aplic\xe1vel"),
                ],
                default=5,
                verbose_name="Unidade de sal\xe1rio fixo",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="config_value",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                verbose_name="Cofigura\xe7\xe3o - valor",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=400, verbose_name="Decri\xe7\xe3o"
            ),
        ),
        migrations.AlterField(
            model_name="folhamensagem",
            name="label",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Refer\xeancia"
            ),
        ),
        migrations.AlterField(
            model_name="groupevents",
            name="type_event",
            field=models.CharField(
                blank=True,
                choices=[("D", "D\xc9BITO"), ("C", "CR\xc9DITO")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marginconsignable",
            name="maximum_cet",
            field=models.DecimalField(
                decimal_places=2, default=5, max_digits=19, verbose_name="CET m\xe1ximo"
            ),
        ),
        migrations.AlterField(
            model_name="marginconsignable",
            name="maximum_installment",
            field=models.PositiveSmallIntegerField(
                blank=True, default=200, verbose_name="Prazo m\xe1ximo"
            ),
        ),
        migrations.AlterField(
            model_name="marginconsignable",
            name="start_validity",
            field=models.DateField(
                default=datetime.date(1900, 1, 1), verbose_name="In\xedcio vig\xeancia"
            ),
        ),
        migrations.AlterField(
            model_name="modelotabelasalarial",
            name="quantidade_horizontal",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Quantidade n\xedveis horizontais"
            ),
        ),
        migrations.AlterField(
            model_name="modelotabelasalarial",
            name="quantidade_vertical",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Quantidade n\xedveis verticais"
            ),
        ),
        migrations.AlterField(
            model_name="paycheckdifference",
            name="source_differences",
            field=models.BooleanField(
                default=False, verbose_name="Gestor de diferen\xe7as?"
            ),
        ),
        migrations.AlterField(
            model_name="previdencia",
            name="pessoa_juridica",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="como_previdencia",
                to="rh.PessoaJuridica",
                verbose_name="Previd\xeancia",
            ),
        ),
        migrations.AlterField(
            model_name="previdencia",
            name="regime_previdenciario",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR")],
                default=2,
                verbose_name="Regime previdenci\xe1rio",
            ),
        ),
        migrations.AlterField(
            model_name="referencianiveis2d",
            name="referencia_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gfp.ReferenciaNiveis2D",
                verbose_name="Refer\xeancia anterior",
            ),
        ),
        migrations.AlterField(
            model_name="remunerationbase",
            name="onus",
            field=models.BooleanField(default=False, verbose_name="\xd4nus"),
        ),
        migrations.AlterField(
            model_name="transparencychoice",
            name="group",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (38, "OUTRAS REMUNERACOES/TEMPORARIAS"),
                    (42, "L\xcdQUIDO EXERC\xcdCIOS ANTERIORES"),
                    (101, "VERBAS REMUNERAT\xd3RIAS"),
                    (102, "VERBAS INDENIZAT\xd3RIAS"),
                    (119, "TOTAL GERAL"),
                ],
                null=True,
                verbose_name="Grupos",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoprogressao",
            name="configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gfp.ConfigSalaryProgression",
                verbose_name="Configura\xe7\xe3o",
            ),
        ),
    ]
