# Generated by Django 2.2.10 on 2020-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0064_auto_20190911_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="previdencia",
            name="progressive_aliquot",
            field=models.BooleanField(
                default=False, verbose_name="Alícota Progressiva?"
            ),
        ),
        migrations.AddField(
            model_name="previdenciafaixa",
            name="reducer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Redutor",
            ),
        ),
        migrations.AlterField(
            model_name="contracheque",
            name="alterado",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Alterado"
            ),
        ),
        migrations.AlterField(
            model_name="contracheque",
            name="blocked",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Bloqueado"
            ),
        ),
        migrations.AlterField(
            model_name="estruturatabelasalarial",
            name="ativo",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="lancamento",
            field=models.CharField(
                choices=[("F", "FIXO"), ("T", "TEMPORÁRIO")],
                max_length=1,
                verbose_name="Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="lancamento",
            field=models.CharField(
                blank=True, choices=[("F", "FIXO"), ("T", "TEMPORÁRIO")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CT", "CONTABILIZADO"),
                    ("NC", "NÃO CONTABILIZADO"),
                    ("RB", "RECUSADO PELO BANCO"),
                ],
                db_index=True,
                default="CT",
                max_length=2,
            ),
        ),
    ]
