# Generated by Django 2.2.11 on 2020-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0111_auto_20200304_1519"),
        ("gfp", "0065_auto_20200220_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previdenciafaixa",
            name="reducer",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="Redutor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folhaevento",
            unique_together={
                (
                    "contracheque",
                    "evento",
                    "info",
                    "servidor",
                    "reference_year",
                    "reference_month",
                    "cid",
                )
            },
        ),
    ]
