# Generated by Django 2.2.12 on 2020-04-15 14:39

from django.db import migrations, models


def update_reference_year(apps, schema_editor):
    OverviewReport = apps.get_model("gfp", "OverviewReport")
    FinancialReportPayroll = apps.get_model("gfp", "FinancialReportPayroll")
    Payroll = apps.get_model("gfp", "Folha")

    result = Payroll.objects.aggregate(
        min_year=models.Min("periodo__ano"), max_year=models.Max("periodo__ano")
    )
    ups_or = ups_fr = 0
    for year in range(result["min_year"], result["max_year"] + 1):
        ups_or += OverviewReport.objects.filter(payroll__periodo__ano=year).update(
            reference_year=year
        )
        ups_fr += FinancialReportPayroll.objects.filter(
            payroll__periodo__ano=year
        ).update(reference_year=year)

    print("OverviewReport(%s) FinancialReportPayroll(%s)" % (ups_or, ups_fr))


def _null_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0066_auto_20200306_0836"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialreportpayroll",
            name="reference_year",
            field=models.PositiveSmallIntegerField(
                default=2020, verbose_name="Exercicio"
            ),
        ),
        migrations.AddField(
            model_name="folhaevento",
            name="count_as_previous_exercise",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Exercício anterior?"
            ),
        ),
        migrations.AddField(
            model_name="overviewreport",
            name="reference_year",
            field=models.PositiveSmallIntegerField(
                default=2020, verbose_name="Exercicio"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialreportpayroll",
            unique_together={("payroll", "account_plan", "reference_year")},
        ),
        migrations.RunPython(update_reference_year, _null_function),
    ]
