# Generated by Django 2.2.17 on 2020-11-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0069_auto_20200819_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paycheckdifferenceitem",
            name="entry_difference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="difference_items",
                to="gfp.FolhaEvento",
            ),
        ),
    ]
