# Generated by Django 2.2.17 on 2020-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0070_auto_20201120_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="folha",
            name="paycheck_locked",
            field=models.BooleanField(
                default=False, verbose_name="Bloquear Contra-cheques?"
            ),
        ),
    ]
