# Generated by Django 2.2.17 on 2021-01-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0071_folha_paycheck_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhaevento",
            name="cid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="info",
            field=models.CharField(default="", max_length=150),
        ),
    ]
