# Generated by Django 2.2.24 on 2021-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0073_auto_20210223_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="lancamento",
            field=models.CharField(
                choices=[
                    ("F", "FIXO"),
                    ("T", "TEMPORÁRIO"),
                    ("U", "TEMPORÁRIO - ÚNICO"),
                ],
                max_length=1,
                verbose_name="Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="folha",
            name="complement",
            field=models.SmallIntegerField(
                blank=True, default=0, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="folha",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "EM PRODUÇÃO"),
                    (2, "EM ANALISE"),
                    (3, "FECHADO"),
                    (4, "PROCESSADO"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="lancamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "FIXO"),
                    ("T", "TEMPORÁRIO"),
                    ("U", "TEMPORÁRIO - ÚNICO"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="folhamodelo",
            name="para_indicativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Para os",
            ),
        ),
        migrations.AlterField(
            model_name="previdencia",
            name="regime_previdenciario",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR"), (4, "RPPE")],
                default=2,
                verbose_name="Regime previdenciário",
            ),
        ),
    ]
