# Generated by Django 2.2.20 on 2021-04-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0137_orgaogeral_order_weight"),
        ("gfp", "0073_auto_20210223_1040"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilySalary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=128, null=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Publicacao",
                        verbose_name="Publicação",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilySalaryRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inferior_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Limite Inferior"
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Limite Superior"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Valor"
                    ),
                ),
                (
                    "family_salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="gfp.FamilySalary",
                        verbose_name="Salário Familia",
                    ),
                ),
            ],
        ),
    ]
