# Generated by Django 2.2.24 on 2021-07-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0074_auto_20210625_1230"),
        ("gfp", "0074_auto_20210430_1157"),
    ]

    operations = []
