# Generated by Django 2.2.24 on 2021-08-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0076_auto_20210816_1700"),
        ("gfp", "0075_merge_20210712_1712"),
    ]

    operations = []
