# Generated by Django 2.2.24 on 2021-09-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0077_folha_apply_models"),
        ("gfp", "0077_merge_20210827_1333"),
    ]

    operations = []
