# Generated by Django 2.2.27 on 2022-02-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0079_folha_available_pvf"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="aplic_classification",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(2, "SALÁRIO MATERNIDADE")],
                null=True,
                verbose_name="Classificação Aplic",
            ),
        ),
    ]
