# Generated by Django 2.2.27 on 2022-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0080_auto_20220208_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="aplic_type",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "NAO SE APLICA"), (1, "BENEFICIO"), (2, "GRATIFICAÇÃO")],
                null=True,
                verbose_name="Tipo Aplic",
            ),
        ),
    ]
