# Generated by Django 2.2.28 on 2022-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0084_auto_20220412_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrapaymentperiod",
            name="decision_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Decisão"
            ),
        ),
        migrations.AlterField(
            model_name="extrapaymentperiod",
            name="end_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim efeito financeiro"
            ),
        ),
        migrations.AlterField(
            model_name="extrapaymentperiod",
            name="start_validity",
            field=models.DateField(verbose_name="Início efeito financeiro"),
        ),
    ]
