# Generated by Django 2.2.28 on 2022-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0086_auto_20220510_0822"),
    ]

    operations = [
        migrations.AddField(
            model_name="folha",
            name="dt_corte",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Corte"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="portal_classification",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "REMUNERAÇÃO DO CARGO EFETIVO"),
                    (2, "OUTRAS VERBAS REMUNERATÓRIAS, LEGAIS OU JUDICIAI"),
                    (3, "FUNÇÃO DE CONFIANÇA OU CARGO EM COMISSÃO"),
                    (4, "GRATIFICAÇÃO NATALINA"),
                    (5, "FÉRIAS (1/3 CONSTITUCIONAL)"),
                    (6, "ABONO DE PERMANENCIA"),
                    (7, "OUTRAS REMUNERAÇÕES TEMPORÁRIAS"),
                    (8, "VERBAS INDENIZATÓRIAS"),
                    (9, "CONTRIBUIÇÃO PREVIDENCIARIA"),
                    (10, "IMPOSTO DE RENDA"),
                    (11, "RETENÇÃO POR TETO CONSTITUCIONAL"),
                    (12, "DESCONTOS DIVERSOS"),
                    (9999, "SEM CALSSIFICAÇÃO"),
                ],
                default=9999,
                verbose_name="Classificação Portal",
            ),
        ),
    ]
