# Generated by Django 2.2.28 on 2022-06-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0173_auto_20220609_1144"),
        ("gfp", "0087_auto_20220608_1436"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodPayroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "qtd_diff",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Qtd Diferença"
                    ),
                ),
                (
                    "qtd_diff_applied",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Qtd Dif. Aplicada"
                    ),
                ),
                (
                    "qtd_diff_ignored",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Qtd Dif. Ignorada"
                    ),
                ),
                (
                    "calculate_last_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-month"),
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="DifferencePayroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competence_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Competência - Mês",
                    ),
                ),
                (
                    "competence_year",
                    models.PositiveIntegerField(verbose_name="Competência - Ano"),
                ),
                (
                    "qtd_event",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "qtd_max_event",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "correct_value_event",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "qtd_event_diff",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "qtd_max_event_diff",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "correct_value_diff",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAL", "Avaliar"),
                            ("APLI", "Aplicado"),
                            ("IGNO", "Ignorado"),
                        ],
                        default="AVAL",
                        max_length=4,
                    ),
                ),
                (
                    "type_diff",
                    models.CharField(
                        blank=True,
                        choices=[("DESC", "Desconto"), ("PROV", "Provimento")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_differences_payroll",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_differences_payroll",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "event_diff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_diff_differences_payroll",
                        to="gfp.Evento",
                        verbose_name="Evento de Diferença",
                    ),
                ),
                (
                    "paycheck_applied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paycheck_applied_differences_payroll",
                        to="gfp.Evento",
                        verbose_name="Contra Cheque - Aplicado",
                    ),
                ),
                (
                    "paycheck_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paycheck_differences_payroll",
                        to="gfp.Evento",
                        verbose_name="Contra Cheque",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="gfp.PeriodPayroll",
                    ),
                ),
            ],
            options={
                "ordering": ("-period", "correct_value_diff"),
            },
        ),
    ]
