# Generated by Django 2.2.28 on 2022-06-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0088_differencepayroll_periodpayroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="differencepayroll",
            name="paycheck_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paycheck_applied_differences_payroll",
                to="gfp.ContraCheque",
                verbose_name="Contra Cheque - Aplicado",
            ),
        ),
        migrations.AlterField(
            model_name="differencepayroll",
            name="paycheck_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paycheck_differences_payroll",
                to="gfp.ContraCheque",
                verbose_name="Contra Cheque",
            ),
        ),
    ]
