# Generated by Django 2.2.28 on 2022-06-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0089_auto_20220613_2130"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctionfactor",
            options={
                "ordering": (
                    "identifier",
                    "-ref_payment_year",
                    "-ref_payment_month",
                    "-ref_difference_year",
                    "-ref_difference_month",
                )
            },
        ),
        migrations.AddField(
            model_name="folhaevento",
            name="reason_difference",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Motivo"),
        ),
        migrations.AddField(
            model_name="paycheckdifference",
            name="reason_difference",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Motivo"),
        ),
    ]
