# Generated by Django 2.2.28 on 2022-07-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0091_auto_20220705_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="differencepayroll",
            name="value_diff",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
