# Generated by Django 2.2.28 on 2022-07-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0092_differencepayroll_value_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="differencepayroll",
            name="base_value_diff",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Base - Origem",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="base_value_event",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Base - Origem",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="contribution_base_diff",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Base Previdenciária - Diferença",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="contribution_base_event",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Base Previdenciária - Origem",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="employer_value_diff",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Patronal - Diferença",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="employer_value_event",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Patronal - Origem",
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="installment_paid_diff",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Parcela - Diferença"
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="installment_paid_event",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Parcela - Origem"
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="installments_diff",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Prazo - Diferença"
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="installments_event",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Prazo - Origem"
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="pct_event",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="pct_event_diff",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
    ]
