# Generated by Django 2.2.28 on 2022-07-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0093_auto_20220707_1903"),
        ("gfp", "0093_auto_20220713_1558"),
    ]

    operations = []
