# Generated by Django 2.2.28 on 2022-07-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0094_merge_20220720_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="differencepayroll",
            name="info_diff",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="differencepayroll",
            name="info_event",
            field=models.CharField(default="", max_length=150),
        ),
    ]
