# Generated by Django 2.2.28 on 2022-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0095_auto_20220722_0043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="differencepayroll",
            name="base_value_diff",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Base - Diferença",
            ),
        ),
    ]
