# Generated by Django 2.2.28 on 2022-08-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0184_auto_20220804_1153"),
        ("gfp", "0096_auto_20220727_1329"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contracheque",
            options={"ordering": ("folha", "servidor", "-pensioner", "benefit_number")},
        ),
        migrations.AlterModelOptions(
            name="tabelasalarial",
            options={"ordering": ("estrutura_salarial", "-start_validity")},
        ),
        migrations.RenameField(
            model_name="tabelasalarial",
            old_name="data_vigencia_fim",
            new_name="end_validity",
        ),
        migrations.RenameField(
            model_name="tabelasalarial",
            old_name="data_vigencia_inicio",
            new_name="start_validity",
        ),
        migrations.AddField(
            model_name="contracheque",
            name="benefit_number",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="folhaevento",
            name="event_esocial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tabelasalarial",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tabelasalarial",
            name="identifier",
            field=models.PositiveSmallIntegerField(choices=[(1, "PADRÃO")], default=1),
        ),
        migrations.AlterField(
            model_name="evento",
            name="lancamento",
            field=models.CharField(
                choices=[("F", "FIXO"), ("T", "TEMPORÁRIO")],
                max_length=1,
                verbose_name="Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="lancamento",
            field=models.CharField(
                blank=True, choices=[("F", "FIXO"), ("T", "TEMPORÁRIO")], max_length=1
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contracheque",
            unique_together={("servidor", "folha", "pensioner", "benefit_number")},
        ),
        migrations.AlterUniqueTogether(
            name="tabelasalarial",
            unique_together={
                ("estrutura_salarial", "info_adicional", "publicacao", "identifier")
            },
        ),
    ]
