# Generated by Django 2.2.28 on 2022-08-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0097_auto_20220804_1202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="lancamento",
            field=models.CharField(
                choices=[
                    ("F", "FIXO"),
                    ("T", "TEMPORÁRIO"),
                    ("U", "TEMPORÁRIO - ÚNICO"),
                ],
                max_length=1,
                verbose_name="Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="lancamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "FIXO"),
                    ("T", "TEMPORÁRIO"),
                    ("U", "TEMPORÁRIO - ÚNICO"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="tabelasalarial",
            name="start_validity",
            field=models.DateField(verbose_name="Início vigência"),
        ),
        migrations.CreateModel(
            name="SocialSecurityContributionsReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "mass_segregation_plan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Plano previdenciário ou único"),
                            (2, "Plano financeiro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "regime",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR"), (4, "RPPE")],
                        default=2,
                        verbose_name="Regime Previdenciário",
                    ),
                ),
                (
                    "type_by_possession",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EFE", "SERVIDOR EFETIVO"),
                            ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                            ("MBR", "MEMBRO"),
                            ("MEL", "MEMBRO COM CARGO ELETIVO"),
                            ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                            ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                            ("CMS", "SERVIDOR COMISSIONADO"),
                            ("REQ", "SERVIDOR REQUISITADO"),
                            ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                            ("EST", "ESTAGIÁRIO"),
                            ("TCR", "TERCEIRIZADO"),
                            ("VOL", "VOLUNTÁRIO"),
                            ("CTR", "SERVIDOR CONTRATADO"),
                            ("EXT", "EXTERNO SEM VÍNCULO"),
                            ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                            ("MAP", "MEMBRO APOSENTADO"),
                            ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                            ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                            ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                            ("XXX", "DESCONHECIDO"),
                            ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                            ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                            ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                            (
                                "MEC2",
                                "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO",
                            ),
                            ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                            ("APO", "SERVIDOR APOSENTADO"),
                            ("BFP", "BENEFICIARIO DE PENSÃO"),
                            ("REX", "SERVIDOR REQUISITADO EXTERNO"),
                        ],
                        default="EFE",
                        max_length=5,
                        verbose_name="Tipo do Servidor",
                    ),
                ),
                (
                    "employee_quantity",
                    models.IntegerField(verbose_name="Qtd. Servidores"),
                ),
                (
                    "dependents_quantity",
                    models.IntegerField(verbose_name="Qtd. Dependentes"),
                ),
                (
                    "remuneration_total",
                    models.FloatField(verbose_name="Remuneração Total"),
                ),
                (
                    "employee_base_calculation",
                    models.FloatField(verbose_name="Base Cálculo Servidor"),
                ),
                (
                    "employee_contribution",
                    models.FloatField(verbose_name="Contribuição Servidor"),
                ),
                (
                    "employer_base_calculation",
                    models.FloatField(verbose_name="Base Cálculo Patronal"),
                ),
                (
                    "employer_contribution",
                    models.FloatField(verbose_name="Contribuição Patronal"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gfp.Folha",
                        verbose_name="Folha",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
