# Generated by Django 2.2.28 on 2022-09-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0014_auto_20220809_0919"),
        ("gfp", "0098_auto_20220811_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="configevent",
            name="esocial_cp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configevent_cp",
                to="esocial.ItemTable",
                verbose_name="Incidência CP",
            ),
        ),
        migrations.AddField(
            model_name="configevent",
            name="esocial_cprp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configevent_cprp",
                to="esocial.ItemTable",
                verbose_name="Incidência CPRP",
            ),
        ),
        migrations.AddField(
            model_name="configevent",
            name="esocial_irrf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configevent_irrf",
                to="esocial.ItemTable",
                verbose_name="Incidência IRRF",
            ),
        ),
        migrations.AlterField(
            model_name="contracheque",
            name="classification",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "EFETIVO"),
                    (2, "MEMBRO"),
                    (3, "COMISSIONADO"),
                    (4, "A DISPOSIÇÃO"),
                    (5, "ESTAGIÁRIO"),
                    (6, "PENSIONISTA"),
                    (7, "PARTILHA"),
                    (8, "SEM VÍNCULO"),
                    (9, "APOSENTADO"),
                ],
                default=1,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="reason_difference",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Sem diferenças"),
                    (2, "Data Base"),
                    (3, "Progressões retroativas"),
                    (4, "Diferenças diversas"),
                ],
                default=1,
                verbose_name="Motivo",
            ),
        ),
        migrations.AlterField(
            model_name="paycheckdifference",
            name="reason_difference",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Sem diferenças"),
                    (2, "Data Base"),
                    (3, "Progressões retroativas"),
                    (4, "Diferenças diversas"),
                ],
                default=1,
                verbose_name="Motivo",
            ),
        ),
    ]
