# Generated by Django 2.2.28 on 2022-09-08 12:00
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import os


FIXTURES = ("gfp/fixtures/menu_conference.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0099_auto_20220905_0906"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferencePayroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado Em"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_conference_payroll",
                        to="rh.Servidor",
                        verbose_name="Criado Por",
                    ),
                ),
                (
                    "finished_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finished_conference_payroll",
                        to="rh.Servidor",
                        verbose_name="Finalizado Por",
                    ),
                ),
                (
                    "payroll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_conference",
                        to="gfp.Folha",
                        verbose_name="Folha",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ConferenceEventPayroll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked",
                    models.BooleanField(default=False, verbose_name="Conferido"),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_payroll",
                        to="gfp.ConferencePayroll",
                        verbose_name="Conferência Folha",
                    ),
                ),
                (
                    "event_paycheck_current",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_event_paycheck_current",
                        to="gfp.ContraCheque",
                        verbose_name="Contracheque Atual",
                    ),
                ),
                (
                    "event_paycheck_previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_event_paycheck_previous",
                        to="gfp.ContraCheque",
                        verbose_name="Contracheque Anterior",
                    ),
                ),
                (
                    "event_payroll_current",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_event_payroll_current",
                        to="gfp.FolhaEvento",
                        verbose_name="Folha Evento Atual",
                    ),
                ),
                (
                    "event_payroll_previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_event_payroll_previous",
                        to="gfp.FolhaEvento",
                        verbose_name="Folha Evento Anterior",
                    ),
                ),
            ],
        ),
        migrations.RunPython(up, down),
    ]
