# Generated by Django 2.2.28 on 2022-10-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0101_auto_20220927_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhaevento",
            name="contracheque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                to="gfp.ContraCheque",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                to="gfp.Evento",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="folha",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                to="gfp.Folha",
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="servidor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="rh.Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="socialsecuritycontributionsreport",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGIÁRIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNTÁRIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM VÍNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                    ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                    ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                    ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                    ("MEC2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO"),
                    ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                    ("APO", "SERVIDOR APOSENTADO"),
                    ("BFP", "BENEFICIARIO DE PENSÃO"),
                    ("REX", "SERVIDOR REQUISITADO EXTERNO"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo do Servidor",
            ),
        ),
    ]
