# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models

FIXTURES = (
    "gfp/fixtures/new_contenttypes.json",
    "gfp/fixtures/new_controllers.json",
)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0212_lotacao_tipo_lotacao"),
        ("ged", "0005_reorganization_of_storage_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0105_load_fixture_tag_decimo_terceiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="configevent",
            name="manual_incidence_esocial",
            field=models.BooleanField(
                default=False, verbose_name="Incidência eSocial manual?"
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="confirma_controle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirma_controle_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="folhaevento",
            name="confirma_folha",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirma_folha_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RemunerationRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "category_esocial",
                    models.IntegerField(
                        choices=[
                            (1, "1 - NÃO INFORMADO"),
                            (
                                101,
                                "101 - Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT",
                            ),
                            (
                                102,
                                "102 - Empregado - Trabalhador rural por pequeno prazo da Lei 11.718/2008",
                            ),
                            (103, "103 - Empregado - Aprendiz"),
                            (104, "104 - Empregado - Doméstico"),
                            (
                                105,
                                "105 - Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998",
                            ),
                            (
                                106,
                                "106 - Trabalhador temporário - Contrato nos termos da Lei 6.019/1974",
                            ),
                            (
                                107,
                                "107 - Empregado - Contrato de trabalho Verde e Amarelo - sem acordo para antecipação mensal da multa",
                            ),
                            (
                                108,
                                "108 - Empregado - Contrato de trabalho Verde e Amarelo - com acordo para antecipação mensal da multa rescisória do FGTS",
                            ),
                            (
                                111,
                                "111 - Empregado - Contrato de trabalho intermitente",
                            ),
                            (201, "201 - Trabalhador avulso portuário"),
                            (202, "202 - Trabalhador avulso não portuário"),
                            (
                                301,
                                "301 - Servidor público titular de cargo efetivo, magistrado, ministro de Tribunal de Contas, conselheiro de",
                            ),
                            (
                                302,
                                "302 - Servidor público ocupante de cargo exclusivo em comissão",
                            ),
                            (303, "303 - Exercente de mandato eletivo"),
                            (
                                304,
                                "304 - Servidor público exercente de mandato eletivo, inclusive com exercício de cargo em comissão",
                            ),
                            (
                                305,
                                "305 - Servidor público indicado para conselho ou órgão deliberativo, na condição de representante do governo",
                            ),
                            (
                                306,
                                "306 - Servidor público contratado por tempo determinado, sujeito a regime administrativo especial definido",
                            ),
                            (307, "307 - Militar"),
                            (308, "308 - Conscrito"),
                            (309, "309 - Agente público - Outros"),
                            (310, "310 - Servidor público eventual"),
                            (
                                311,
                                "311 - Ministros, juízes, procuradores, promotores ou oficiais de justiça à disposição da Justiça Eleitoral",
                            ),
                            (312, "312 - Auxiliar local"),
                            (
                                313,
                                "313 - Servidor público exercente de atividade de instrutoria, capacitação, treinamento, curso ou concurso",
                            ),
                            (
                                401,
                                "401 - Dirigente sindical - Informação prestada pelo sindicato",
                            ),
                            (
                                410,
                                "410 - Trabalhador cedido/exercício em outro órgão/juiz auxiliar - Informação prestada pelo cessionário/destino",
                            ),
                            (501, "501 - Dirigente sindical - Segurado especial"),
                            (
                                701,
                                "701 - Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias",
                            ),
                            (
                                711,
                                "711 - Contribuinte individual - Transportador autônomo de passageiros",
                            ),
                            (
                                712,
                                "712 - Contribuinte individual - Transportador autônomo de carga",
                            ),
                            (
                                721,
                                "721 - Contribuinte individual - Diretor não empregado, com FGTS",
                            ),
                            (
                                722,
                                "722 - Contribuinte individual - Diretor não empregado, sem FGTS",
                            ),
                            (
                                723,
                                "723 - Contribuinte individual - Empresário, sócio e membro de conselho de administração ou fiscal",
                            ),
                            (
                                731,
                                "731 - Contribuinte individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho",
                            ),
                            (
                                734,
                                "734 - Contribuinte individual - Transportador cooperado que presta serviços por intermédio de",
                            ),
                            (
                                738,
                                "738 - Contribuinte individual - Cooperado filiado a cooperativa de produção",
                            ),
                            (
                                741,
                                "741 - Contribuinte individual - Microempreendedor individual",
                            ),
                            (
                                751,
                                "751 - Contribuinte individual - Magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral",
                            ),
                            (
                                761,
                                "761 - Contribuinte individual - Associado eleito para direção de cooperativa, associação ou entidade de classe",
                            ),
                            (
                                771,
                                "771 - Contribuinte individual - Membro de conselho tutelar, nos termos da Lei 8.069/1990",
                            ),
                            (
                                781,
                                "781 - Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa",
                            ),
                            (901, "901 - Estagiário"),
                            (
                                902,
                                "902 - Médico residente ou residente em área profissional de saúde",
                            ),
                            (903, "903 - Bolsista"),
                            (
                                904,
                                "904 - Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário",
                            ),
                            (
                                906,
                                "906 - Beneficiário do Programa Nacional de Prestação de Serviço Civil Voluntário",
                            ),
                        ],
                        verbose_name="Categoria eSocial",
                    ),
                ),
                (
                    "remuneration",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Remuneração"
                    ),
                ),
                (
                    "inss_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor do INSS"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ordem"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do EDOC",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remunerationrelationship",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remunerationrelationship",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person_payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remunerationrelationship",
                        to="rh.Pessoa",
                        verbose_name="Fonte pagadora",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_validity",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
