# Generated by Django 2.2.28 on 2023-03-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0107_configevent_descricao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movimentacaoprogressao",
            unique_together=set(),
        ),
    ]
