# Generated by Django 2.2.28 on 2023-03-24 12:18
import os
from django.db import migrations
from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command

FIXTURES = ("fixtures/choices_process_type.json",)


def up_load_fixtures(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh/gfp", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down_load_fixtures(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0108_auto_20230307_2224"),
    ]

    operations = [
        migrations.AddField(
            model_name="rra",
            name="process_type",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(up_load_fixtures, down_load_fixtures),
    ]
