# Generated by Django 2.2.28 on 2023-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0109_rra_process_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="portal_classification",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "REMUNERAÇÃO DO CARGO EFETIVO"),
                    (2, "OUTRAS VERBAS REMUNERATÓRIAS, LEGAIS OU JUDICIAI"),
                    (3, "FUNÇÃO DE CONFIANÇA OU CARGO EM COMISSÃO"),
                    (4, "GRATIFICAÇÃO NATALINA"),
                    (5, "FÉRIAS (1/3 CONSTITUCIONAL)"),
                    (6, "ABONO DE PERMANENCIA"),
                    (7, "OUTRAS REMUNERAÇÕES TEMPORÁRIAS"),
                    (8, "VERBAS INDENIZATÓRIAS"),
                    (9, "CONTRIBUIÇÃO PREVIDENCIARIA"),
                    (10, "IMPOSTO DE RENDA"),
                    (11, "RETENÇÃO POR TETO CONSTITUCIONAL"),
                    (12, "DESCONTOS DIVERSOS"),
                    (9999, "SEM CLASSIFICAÇÃO"),
                ],
                default=9999,
                verbose_name="Classificação Portal",
            ),
        ),
        migrations.AlterField(
            model_name="extensionsalaryprogression",
            name="purpose",
            field=models.TextField(default="", verbose_name="Motivo"),
        ),
        migrations.AlterField(
            model_name="rra",
            name="process_type",
            field=models.PositiveIntegerField(
                choices=[(1, "ADMINISTRATIVO"), (2, "JUDICIAL")], default=1
            ),
        ),
    ]
