# Generated by Django 2.2.28 on 2023-04-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0112_load_fixture_entry_insertion_type_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhaevento",
            name="insertion_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Cálculo Automático"),
                    (2, "Manual"),
                    (3, "Importação"),
                    (4, "Gestor de Diferenças"),
                    (5, "GCPP"),
                    (6, "Gestor de Prestador Evental"),
                    (7, "Gestor de Férias"),
                    (8, "Exercício Cumulativo"),
                ],
                default=3,
                verbose_name="Tipo de Inserção",
            ),
        ),
    ]
