# Generated by Django 2.2.28 on 2023-05-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0113_auto_20230424_1540"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressionDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachment_progression_doc",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "progression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="gfp.MovimentacaoProgressao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentos de Progressão",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
