# Generated by Django 2.2.28 on 2023-05-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0114_progressiondocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorizontalProgressionConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="Progressão Destino",
                    ),
                ),
                (
                    "contribution_time",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Tempo de Casa (anos)"
                    ),
                ),
                (
                    "qtd_documents",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Quantidade de Documentos"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schooling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horizontal_prog_config",
                        to="gfp.EstruturaTabelaSalarial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Progressão Horizontal",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
