# Generated by Django 2.2.28 on 2023-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0115_horizontalprogressionconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressiondocument",
            name="doc_origin",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Origem do Documento"
            ),
        ),
    ]
