# Generated by Django 2.2.28 on 2023-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0116_progressiondocument_doc_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhamodelo",
            name="para_indicativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                    ("R", "RESIDENTE"),
                ],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Para os",
            ),
        ),
    ]
