# Generated by Django 2.2.28 on 2023-08-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0256_servidor_posicao_concurso"),
        ("gfp", "0117_auto_20230620_1628"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialsecuritycontributionsreport",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGIÁRIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNTÁRIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM VÍNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                    ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                    ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                    ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                    ("MEC2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO"),
                    ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                    ("APO", "SERVIDOR APOSENTADO"),
                    ("BFP", "BENEFICIARIO DE PENSÃO"),
                    ("REX", "SERVIDOR REQUISITADO EXTERNO"),
                    ("COE", "COLABORADOR EVENTUAL"),
                    ("RES", "RESIDENTE"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo do Servidor",
            ),
        ),
        migrations.CreateModel(
            name="FolhaEventoHistorico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "lancamento_antigo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "FIXO"),
                            ("T", "TEMPORÁRIO"),
                            ("U", "TEMPORÁRIO - ÚNICO"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "lancamento_novo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "FIXO"),
                            ("T", "TEMPORÁRIO"),
                            ("U", "TEMPORÁRIO - ÚNICO"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "qnt_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=0, max_digits=10
                    ),
                ),
                (
                    "qnt_novo",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=0, max_digits=10
                    ),
                ),
                (
                    "qnt_max_antigo",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "qnt_max_novo",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("parcela_antigo", models.PositiveIntegerField(blank=True, default=0)),
                ("parcela_novo", models.PositiveIntegerField(blank=True, default=0)),
                ("prazo_antigo", models.PositiveIntegerField(blank=True, default=0)),
                ("prazo_novo", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "pct_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "pct_novo",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "valor_novo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "valor_base_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "valor_base_novo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "patronal_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "patronal_novo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                ("info_antigo", models.CharField(default="", max_length=150)),
                ("info_novo", models.CharField(default="", max_length=150)),
                (
                    "base_previdencia_antigo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "base_previdencia_novo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=16
                    ),
                ),
                (
                    "status_antigo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "CONTABILIZADO"),
                            ("NC", "NÃO CONTABILIZADO"),
                            ("RB", "RECUSADO PELO BANCO"),
                            ("BS", "BASE"),
                            ("CE", "CONTABILIZADO EXTERNO"),
                        ],
                        db_index=True,
                        default="CT",
                        max_length=2,
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "CONTABILIZADO"),
                            ("NC", "NÃO CONTABILIZADO"),
                            ("RB", "RECUSADO PELO BANCO"),
                            ("BS", "BASE"),
                            ("CE", "CONTABILIZADO EXTERNO"),
                        ],
                        db_index=True,
                        default="CT",
                        max_length=2,
                    ),
                ),
                (
                    "json_calc_vars_antigo",
                    models.CharField(default="{}", max_length=256),
                ),
                ("json_calc_vars_novo", models.CharField(default="{}", max_length=256)),
                (
                    "automated_antigo",
                    models.BooleanField(default=False, verbose_name="Automatizado?"),
                ),
                (
                    "automated_novo",
                    models.BooleanField(default=False, verbose_name="Automatizado?"),
                ),
                (
                    "insertion_type_antigo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cálculo Automático"),
                            (2, "Manual"),
                            (3, "Importação"),
                            (4, "Gestor de Diferenças"),
                            (5, "GCPP"),
                            (6, "Gestor de Prestador Evental"),
                            (7, "Gestor de Férias"),
                            (8, "Exercício Cumulativo"),
                        ],
                        default=3,
                        verbose_name="Tipo de Inserção",
                    ),
                ),
                (
                    "insertion_type_novo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cálculo Automático"),
                            (2, "Manual"),
                            (3, "Importação"),
                            (4, "Gestor de Diferenças"),
                            (5, "GCPP"),
                            (6, "Gestor de Prestador Evental"),
                            (7, "Gestor de Férias"),
                            (8, "Exercício Cumulativo"),
                        ],
                        default=3,
                        verbose_name="Tipo de Inserção",
                    ),
                ),
                (
                    "contracheque",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_lancamentos",
                        to="gfp.ContraCheque",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_lancamentos",
                        to="gfp.Evento",
                    ),
                ),
                (
                    "folha",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_lancamentos",
                        to="gfp.Folha",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_entries",
                        to="rh.Servidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de FolhaEvento",
                "verbose_name_plural": "Históricos de FolhaEvento",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
