# Generated by Django 2.2.28 on 2023-09-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0120_auto_20230902_0030"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folhaeventohistorico",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="folhaeventohistorico",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="folhaeventohistorico",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="folhaeventohistorico",
            name="modified_by",
        ),
    ]
