# Generated by Django 2.2.28 on 2023-09-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0121_auto_20230904_1929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrachequehistorico",
            name="contracheque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historico",
                to="gfp.ContraCheque",
            ),
        ),
    ]
