# Generated by Django 2.2.28 on 2023-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0122_auto_20230921_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrachequehistorico",
            name="contracheque_ref_ano",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ano ContraCheque"
            ),
        ),
        migrations.AddField(
            model_name="contrachequehistorico",
            name="contracheque_ref_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="ContraCheque ID"
            ),
        ),
        migrations.AddField(
            model_name="contrachequehistorico",
            name="contracheque_ref_mes",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Mês ContraCheque"
            ),
        ),
        migrations.AddField(
            model_name="contrachequehistorico",
            name="servidor_ref_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Servidor ID"
            ),
        ),
    ]
