# Generated by Django 2.2.28 on 2023-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0124_update_contracheque_historico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhaevento",
            name="info",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
