# Generated by Django 2.2.28 on 2023-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0125_auto_20231011_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folhaeventohistorico",
            name="info",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
