# Generated by Django 2.2.28 on 2023-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0126_auto_20231016_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="conta_contabil",
            field=models.PositiveIntegerField(
                default=None, null=True, verbose_name="Conta Contábil"
            ),
        ),
    ]
