# Generated by Django 2.2.28 on 2024-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0128_evento_update_conta_contabil"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrf",
            name="valor_isencao_65_anos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor isenção 65 anos",
            ),
        ),
        migrations.AlterField(
            model_name="rra",
            name="process_type",
            field=models.PositiveIntegerField(
                choices=[(1, "ADMINISTRATIVO"), (2, "JUDICIAL")], default=1
            ),
        ),
    ]
