# Generated by Django 2.2.28 on 2024-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0129_auto_20240404_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankingconvenant",
            name="chave_pix",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chave PIX"
            ),
        ),
    ]
