# Generated by Django 2.2.28 on 2024-09-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0317_banco_chave_pix"),
        ("gfp", "0130_bankingconvenant_chave_pix"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="banco_consignacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banco_eventos_consignacoes",
                to="rh.Banco",
            ),
        ),
    ]
