# Generated by Django 4.2 on 2025-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0135_load_fixtures_esocial_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="data_corte_ferias",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Data Corte Férias"
            ),
        ),
    ]
