# Generated by Django 4.2 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0136_periodo_data_corte_ferias_alter_bankingconvenant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrf",
            name="deducao_benefica",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Dedução mais benéfica",
            ),
        ),
    ]
