# Generated by Django 2.2.17 on 2020-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupperiod",
            name="start_date_fruition",
            field=models.DateField(
                help_text="Início da fruição(período para fruição)",
                verbose_name="Início",
            ),
        ),
        migrations.AlterModelOptions(
            name="acquisitionperiod",
            options={
                "ordering": ("employee",),
                "permissions": (
                    ("dayoffadmin", "Pode administrar os Períodos Aquisitivos"),
                    ("can_block_ap", "Pode bloquear os Períodos Aquisitivos"),
                    ("can_unblock_ap", "Pode desbloquear os Períodos Aquisitivos"),
                ),
            },
        ),
    ]
