# Generated by Django 2.2.17 on 2020-11-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0002_start_date_fruition"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisitionperiod",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dayoff_acquisitionperiods",
                to="rh.AnotacaoGeral",
            ),
        ),
    ]
