# Generated by Django 2.2.19 on 2021-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0007_usufruct_departure"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisitionperiod",
            name="pendency",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Pendência"
            ),
        ),
    ]
