# Generated by Django 2.2.19 on 2021-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0008_acquisitionperiod_pendency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquisitionperiod",
            options={
                "ordering": ("-group_period__year_reference", "employee"),
                "permissions": (
                    ("dayoffadmin", "Pode administrar os Períodos Aquisitivos"),
                    ("can_block_ap", "Pode bloquear os Períodos Aquisitivos"),
                    ("can_unblock_ap", "Pode desbloquear os Períodos Aquisitivos"),
                    ("can_super_delete", "Pode desbloquear os Períodos Aquisitivos"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="groupperiod",
            options={
                "ordering": ("-year_reference", "-period"),
                "permissions": (("dayoffadmin", "Pode administrar os Grupos"),),
            },
        ),
        migrations.AlterField(
            model_name="acquisitionperiod",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Aguardando Liberação p/ Marcação"),
                    (2, "Em Andamento"),
                    (4, "Concluído"),
                    (8, "Indenizado Total ou Parcialmente"),
                    (12, "Prescrito"),
                ],
                default=1,
                help_text="Situação atual desse período aquisitivo",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="block_usufruct_departures",
            field=models.ManyToManyField(
                help_text="Bloqueia criação de usufrutos que conflitam com afastamentos",
                related_name="dayoff_configuration_blockusufructdepartures",
                to="standard.Choice",
                verbose_name="Bloqueia usufrutos que conflitam com afastamentos",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="suspend_acquisition_departures",
            field=models.ManyToManyField(
                help_text="Os afastamentos que suspendem a aquisição dos períodos",
                related_name="dayoff_configuration_suspendacquisitiondepartures",
                to="standard.Choice",
                verbose_name="Afastamentos que suspendem a aquisição dos períodos",
            ),
        ),
    ]
