# Generated by Django 2.2.20 on 2021-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0009_auto_20210309_2024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquisitionperiod",
            options={
                "ordering": ("-group_period__year_reference", "employee"),
                "permissions": (
                    ("dayoffadmin", "Pode administrar os Períodos Aquisitivos"),
                    ("can_block_ap", "Pode bloquear os Períodos Aquisitivos"),
                    ("can_unblock_ap", "Pode desbloquear os Períodos Aquisitivos"),
                    ("can_super_delete", "Pode desbloquear os Períodos Aquisitivos"),
                ),
                "verbose_name": "Período Aquisitivo",
            },
        ),
        migrations.AlterField(
            model_name="acquisitionperiod",
            name="info",
            field=models.TextField(blank=True, default="", verbose_name="Informação"),
        ),
        migrations.AlterField(
            model_name="acquisitionperiod",
            name="note",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Gerar anotação"
            ),
        ),
    ]
