# Generated by Django 2.2.24 on 2021-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0010_auto_20210504_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="run_signal",
            field=models.BooleanField(
                default=False,
                help_text="Executar sinal",
                verbose_name="Executar sinal ?",
            ),
        ),
        migrations.AlterField(
            model_name="usufruct",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Inclusão solicitada"),
                    (2, "Autorizado"),
                    (4, "Homologado"),
                    (8, "Alteração solicitada"),
                    (16, "Alterado"),
                    (32, "Interrompido"),
                    (64, "Suspenso"),
                    (128, "Em fruição"),
                    (256, "Usufruído"),
                    (512, "Não autorizado"),
                    (1024, "Substituto"),
                    (2048, "CANCELADO"),
                    (4096, "Vendido"),
                ],
                default=1,
                help_text="Situação atual desse usufruto",
                verbose_name="Situação",
            ),
        ),
    ]
