# Generated by Django 2.2.24 on 2021-07-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0010_auto_20210504_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="sub_type_of_usufruct",
            field=models.SmallIntegerField(
                default=0, help_text="Tipo", verbose_name="Subtipo de usufruto"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="type_of_usufruct",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Férias"),
                    (2, "Recesso"),
                    (3, "Folga de Aniversário"),
                    (4, "Folga Eleitoral"),
                    (5, "Folga de Plantão"),
                    (6, "Folga por Compensação"),
                    (7, "Licença Prêmio"),
                ],
                default=1,
                help_text="Tipo",
                verbose_name="Tipo de usufruto",
            ),
        ),
        migrations.AlterField(
            model_name="usufruct",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Inclusão solicitada"),
                    (2, "Autorizado"),
                    (4, "Homologado"),
                    (8, "Alteração solicitada"),
                    (16, "Alterado"),
                    (32, "Interrompido"),
                    (64, "Suspenso"),
                    (128, "Em fruição"),
                    (256, "Usufruído"),
                    (512, "Não autorizado"),
                    (1024, "Substituto"),
                    (2048, "CANCELADO"),
                    (4096, "Vendido"),
                ],
                default=1,
                help_text="Situação atual desse usufruto",
                verbose_name="Situação",
            ),
        ),
    ]
