# Generated by Django 2.2.23 on 2021-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0011_auto_20210706_1127"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquisitionperiod",
            options={
                "ordering": ("-group_period__year_reference", "employee"),
                "permissions": (
                    ("dayoffadmin", "Pode administrar os Períodos Aquisitivos"),
                    ("can_block_ap", "Pode bloquear os Períodos Aquisitivos"),
                    ("can_unblock_ap", "Pode desbloquear os Períodos Aquisitivos"),
                    ("can_super_delete", "Pode desbloquear os Períodos Aquisitivos"),
                    (
                        "dayoff_notify_admin",
                        "Recebe notificações sobre alteração de Períodos Aquisitivos",
                    ),
                ),
                "verbose_name": "Período Aquisitivo",
            },
        )
    ]
