# Generated by Django 2.2.24 on 2021-07-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dayoff", "0011_auto_20210715_1935"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcquisitionPeriodAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do período aquisitivo",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "information",
                    models.TextField(blank=True, default="", verbose_name="Informação"),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data início do exercício"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data fim do exercício"
                    ),
                ),
                (
                    "days_law",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade de Dias de direito",
                    ),
                ),
                (
                    "acquisition_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_acquisitionperiod",
                        to="dayoff.AcquisitionPeriod",
                        verbose_name="Periodo Aquisitivo",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia do anexo do periodo aquisitivo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachment_acquisitionperiod",
                        to="dayoff.Attachment",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo Período Aquisitivo",
                "ordering": ("-date_end",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
