# Generated by Django 2.2.24 on 2021-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0012_acquisitionperiodattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisitionperiodattachment",
            name="days_law",
            field=models.IntegerField(
                default=0, verbose_name="Quantidade de Dias de direito"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="sub_type_of_usufruct",
            field=models.SmallIntegerField(
                choices=[
                    (9000, "Férias Regulamentares"),
                    (9001, "Férias Individuais"),
                    (9002, "Recesso Forense "),
                    (9003, "Folga de Aniversário"),
                    (9004, "Folga Eleitoral"),
                    (9005, "Plantão (Servidores)"),
                    (9007, "Folgas Compensatórias de Membros"),
                    (9008, " Férias Compensatórias de Membros"),
                    (9009, "Licença Prêmio"),
                    (9010, "Recesso de Estagiário"),
                    (9011, "Concurso Promotor Substituto"),
                    (9012, "Concurso de Estagiários"),
                ],
                default=0,
                help_text="Tipo",
                verbose_name="Subtipo de usufruto",
            ),
        ),
    ]
