# Generated by Django 2.2.24 on 2021-08-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0012_auto_20210714_0909"),
        ("dayoff", "0013_auto_20210806_1501"),
    ]

    operations = []
