# Generated by Django 2.2.24 on 2021-10-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0013_auto_20210929_1049"),
        ("dayoff", "0014_merge_20210827_1333"),
    ]

    operations = []
