# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0165_auto_20220315_0915"),
        ("gfp", "0084_auto_20220412_1430"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dayoff", "0015_merge_20211008_1542"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "permissions": (
                    ("dayoffadmin", "Pode administrar os Anexos"),
                    ("dayoffpayment", "Pode modificar as informações de pagamentos"),
                )
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="delete_with_zero_days",
            field=models.BooleanField(
                default=False,
                help_text="Deleta usufrutos quando o periodo aquisitivo está zerado",
                verbose_name="Deletar usufrutos quando o periodo aquisitivo está zerado?",
            ),
        ),
        migrations.AddField(
            model_name="groupperiod",
            name="employee_not_create_usufrutcs",
            field=models.ManyToManyField(
                help_text="Servidores que serão excluídos da geração de Usufrutos",
                to="rh.Servidor",
                verbose_name="Servidores excluídos da geração de usufrutos",
            ),
        ),
        migrations.AddField(
            model_name="groupperiod",
            name="redo_automatic_book",
            field=models.BooleanField(
                default=False, verbose_name="Refazer a marcação automática de usufruto"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="continuous_period",
            field=models.BooleanField(
                default=False,
                help_text="Modo de avaliação do período aquisitivo. ANUAL: perído por ano.\n        CONTINUO: período de acordo com a data de exercício do servidor.",
                null=True,
                verbose_name="Período contínuo",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="sub_type_of_usufruct",
            field=models.SmallIntegerField(
                choices=[
                    (9000, "Férias Regulamentares"),
                    (9001, "Férias Individuais"),
                    (9002, "Recesso Forense "),
                    (9003, "Folga de Aniversário"),
                    (9004, "Folga Eleitoral"),
                    (9005, "Plantão (Servidores)"),
                    (9007, "Folgas Compensatórias de Membros"),
                    (9008, "Plantão de Recesso Forense - Membros "),
                    (9009, "Licença Prêmio"),
                    (9010, "Recesso de Estagiário"),
                    (9011, "Concurso Promotor Substituto"),
                    (9012, "Concurso de Estagiários"),
                    (9013, "Doação de Sangue"),
                ],
                default=0,
                help_text="Tipo",
                verbose_name="Subtipo de usufruto",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type_of",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Tipo do pagmento.", verbose_name="Tipo"
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        help_text="Informação sobre o pagamento",
                        max_length=50,
                        verbose_name="Informação",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descrição sobre o pagamento",
                        max_length=400,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "payment_oid",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Id do objeto da folha de pagamento",
                        null=True,
                        verbose_name="FOPAG Id",
                    ),
                ),
                (
                    "acquisition_period",
                    models.ForeignKey(
                        help_text="O período aquisitivo do servidor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="dayoff.AcquisitionPeriod",
                        verbose_name="Período aquisitivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry_payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lançamento da folha realacionado ao pagamento",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dayoff_payments",
                        to="gfp.FolhaEvento",
                        verbose_name="Lançamento",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usufruct",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usufruto relacionado ao pagamento.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dayoff.Usufruct",
                        verbose_name="Usufruto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
