# Generated by Django 2.2.28 on 2022-05-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0016_auto_20220412_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="prescription_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Quantidade em dias para a prescrição",
                null=True,
                verbose_name="Dias para prescrição",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="type_of_usufruct",
            field=models.SmallIntegerField(
                choices=[
                    (7, "Licença Prêmio"),
                    (1, "Férias"),
                    (2, "Recesso"),
                    (3, "Folga de Aniversário"),
                    (4, "Folga Eleitoral"),
                    (5, "Folga de Plantão"),
                    (6, "Folga por Compensação"),
                ],
                default=1,
                help_text="Tipo",
                verbose_name="Tipo de usufruto",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type_of",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Adicional de férias"), (2, "Venda"), (3, "Idenização")],
                default=1,
                help_text="Tipo do pagmento.",
                verbose_name="Tipo",
            ),
        ),
    ]
