# Generated by Django 2.2.28 on 2022-05-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0017_auto_20220530_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisitionperiodattachment",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Ativo"), (2, "Prescrito")],
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
