# Generated by Django 2.2.28 on 2022-06-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0018_acquisitionperiodattachment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisitionperiodattachment",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Ativo"), (2, "Prescrito")],
                default=1,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
