# Generated by Django 2.2.28 on 2022-06-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0019_auto_20220602_1610"),
    ]

    operations = []
