# Generated by Django 2.2.28 on 2022-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0019_auto_20220602_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupperiod",
            name="end_date_acquisition",
            field=models.DateField(
                blank=True,
                help_text="Fim aquisição(Quando preenchido)",
                null=True,
                verbose_name="Fim aquisição",
            ),
        ),
        migrations.AlterField(
            model_name="groupperiod",
            name="start_date_acquisition",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Início aquisição(Quando preenchido)",
            ),
        ),
    ]
