# Generated by Django 2.2.28 on 2022-06-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0020_merge_20220609_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisitionperiodattachment",
            name="status",
            field=models.SmallIntegerField(
                blank=True, default=1, null=True, verbose_name="Status"
            ),
        ),
    ]
