# Generated by Django 2.2.28 on 2022-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0022_auto_20220610_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="usufruct",
            name="justification",
            field=models.TextField(blank=True, null=True, verbose_name="Justificativa"),
        )
    ]
