# Generated by Django 2.2.28 on 2022-07-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0020_auto_20220628_1914"),
        ("dayoff", "0023_auto_20220623_2016"),
    ]

    operations = []
