# Generated by Django 2.2.28 on 2022-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0024_merge_20220717_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisitionperiodattachment",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Ativo"),
                    (2, "Prescrito"),
                    (3, "Prescrito para Usufruto"),
                ],
                default=1,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type_of_activity",
            field=models.SmallIntegerField(
                choices=[
                    (1, "MARCAÇÃO"),
                    (2, "ALTERAÇÃO"),
                    (3, "SUSPENSÃO"),
                    (4, "INTERRUPÇÃO"),
                    (5, "INDENIZAÇÃO"),
                    (7, "VENDA"),
                    (8, "RETIFICAÇÃO"),
                    (9, "CANCELAR"),
                    (10, "MARCAÇÃO REMANESCENTE"),
                    (11, "MARCAÇÃO/VENDA"),
                    (12, "CORRIGIR"),
                ],
                default=1,
                verbose_name="Tipo",
            ),
        ),
    ]
