# Generated by Django 2.2.28 on 2023-03-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0222_auto_20230302_1551"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dayoff", "0026_auto_20230112_1053"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsufructPaymentControl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Sem Análise"),
                            (2, "Declinado"),
                            (3, "Conferido"),
                        ],
                        default=1,
                        verbose_name="Status de Conferência",
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "observation",
                    models.TextField(
                        blank=True,
                        help_text="Observação referente a controle do usufruto",
                        null=True,
                        verbose_name="Obervação",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctrl_payment_checked",
                        to="rh.Servidor",
                        verbose_name="Conferido por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctrl_usufruct_payment",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usufruct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctrl_payments",
                        to="dayoff.Usufruct",
                        verbose_name="Usufrutos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle Controle de Pagamentos de Usufrutos",
                "unique_together": {("employee", "usufruct")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
