# Generated by Django 2.2.28 on 2023-03-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0228_movimentacaodesligamento_desligamento_automatico"),
        ("dayoff", "0029_auto_20230322_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="applied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aplicado em"
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ctrl_payment_applied",
                to="rh.Servidor",
                verbose_name="Aplicado por",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="calculated_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor calculado",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="confirmed_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor confirmado",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="manual_confirmation_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Confirmação manual de valor em"
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="manual_confirmation_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manual_confirmed_usufuct_control",
                to="rh.Servidor",
                verbose_name="Confirmação manual de valor por",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="manual_confirmation_payment",
            field=models.BooleanField(
                default=False,
                help_text="A confirmação do valor a pagar foi manual?",
                verbose_name="Inclusão manual",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="paid_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor a pagar",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="payment_installments",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parcelas de Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="payroll_ctrl_status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Em análise"),
                    (2, "Negado"),
                    (3, "Aprovado"),
                    (4, "Finalizado"),
                ],
                default=1,
                verbose_name="Status de Conferência de Folha",
            ),
        ),
        migrations.AddField(
            model_name="usufructpaymentcontrol",
            name="type_of_control",
            field=models.SmallIntegerField(
                choices=[(1, "Conferência de RH"), (2, "Conferência de Folha")],
                default=1,
                verbose_name="Tipo da Conferência Conferência",
            ),
        ),
        migrations.AlterField(
            model_name="usufructpaymentcontrol",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Sem Análise"), (2, "Declinado"), (3, "Conferido")],
                default=1,
                verbose_name="Status de Conferência do RH",
            ),
        ),
    ]
