# Generated by Django 2.2.28 on 2023-04-13 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dayoff", "0030_auto_20230323_1524"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usufructpaymentcontrol",
            name="payroll_ctrl_status",
            field=models.SmallIntegerField(
                default=1, verbose_name="Status de Conferência de Folha"
            ),
        ),
        migrations.AlterField(
            model_name="usufructpaymentcontrol",
            name="type_of_control",
            field=models.SmallIntegerField(
                default=1, verbose_name="Tipo da Conferência Conferência"
            ),
        ),
        migrations.CreateModel(
            name="ConfigurationSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date_sale",
                    models.DateField(verbose_name="Data Início da Venda"),
                ),
                (
                    "end_date_sale",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final da Venda"
                    ),
                ),
                (
                    "start_date_validity",
                    models.DateField(verbose_name="Data Início da Vigência"),
                ),
                (
                    "end_date_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final da Vigência"
                    ),
                ),
                (
                    "cutoff_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Corte"
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_sale",
                        to="dayoff.Configuration",
                        verbose_name="Configuração",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date_validity"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
