# Generated by Django 2.2.28 on 2023-05-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("dayoff", "0031_auto_20230413_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsale",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachment_config_sale",
                to="ged.Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="usufructpaymentcontrol",
            name="payroll_ctrl_status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Em análise"),
                    (2, "Negado"),
                    (3, "Aprovado"),
                    (4, "Finalizado"),
                ],
                default=1,
                verbose_name="Status de Conferência de Folha",
            ),
        ),
        migrations.AlterField(
            model_name="usufructpaymentcontrol",
            name="type_of_control",
            field=models.SmallIntegerField(
                choices=[(1, "Conferência de RH"), (2, "Conferência de Folha")],
                default=1,
                verbose_name="Tipo da Conferência Conferência",
            ),
        ),
    ]
