# Generated by Django 2.2.28 on 2024-10-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dayoff", "0036_load_fixture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPlantaoEleitoral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título",
                        max_length=100,
                        unique=True,
                        verbose_name="Título",
                    ),
                ),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "turno",
                    models.SmallIntegerField(
                        choices=[(1, "1º Turno"), (2, "2º Turno")],
                        help_text="Turno",
                        verbose_name="Turno",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Ativo", verbose_name="Ativo"
                    ),
                ),
                (
                    "configuracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_plantao_eleitoral",
                        to="dayoff.Configuration",
                        verbose_name="Configuração",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
