# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0024_auto_20190204_2000"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deadlinerecommendationattachments",
            options={
                "verbose_name": "Arquivo anexados na solicita\xe7\xe3o de dila\xe7\xe3o de prazo e outros"
            },
        ),
        migrations.RemoveField(
            model_name="deadlinerecommendationattachments",
            name="deadlinerecommendation",
        ),
        migrations.AddField(
            model_name="deadlinerecommendationattachments",
            name="inspection",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arquivos",
                to="inspection.Inspection",
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspector_prosecutors",
            field=models.ManyToManyField(
                blank=True, related_name="inspector_prosecutors", to="rh.Servidor"
            ),
        ),
    ]
