# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models
from corregedoria.inspection.models import Inspection


def apaga_teste(apps, schema_editor):
    Inspection.objects.filter(inspection_date_initial__year=2018).exclude(
        id=47
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0025_auto_20190626_1832"),
    ]

    operations = [migrations.RunPython(apaga_teste)]
