# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def up(apps, schema_editor):
    from corregedoria.inspection.models import Inspection

    for insp in Inspection.objects.filter():
        Inspection.objects.filter(pk=insp.pk).update(cache_rendered=insp.rendered)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("cirdir", "0011_auto_20191216_1757"),
        ("inspection", "0026_auto_20190627_1854"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_cirdir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cirdir.Address",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="cache_rendered",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teaching",
            name="teaching_cirdir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cirdir.Teaching",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cif.AddressCif",
            ),
        ),
        migrations.AlterField(
            model_name="processesforanalysisperformanceinaudiences",
            name="audience_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "N\xe3o informado"),
                    (2, "Concilia\xe7\xe3o"),
                    (3, "Instru\xe7\xe3o"),
                    (4, "Julgamento"),
                    (5, "Instru\xe7\xe3o e Julgamento"),
                    (6, "Preliminar"),
                    (7, "Interrogat\xf3rio"),
                    (8, "Inquiri\xe7\xe3o"),
                    (9, "Diploma\xe7\xe3o"),
                    (10, "Justifica\xe7\xe3o"),
                    (11, "Apresenta\xe7\xe3o"),
                    (12, "Apresenta\xe7\xe3o/Remiss\xe3o"),
                    (13, "Audi\xeancias gerais da Inf\xe2ncia e Juventude"),
                    (14, "Suspens\xe3o condicional do processo"),
                    (15, "Conciclia\xe7\xe3o, Instru\xe7\xe3o e Julgamento"),
                    (16, "Admonit\xf3ria"),
                    (17, "Audi\xeancia de Cust\xf3dia"),
                ],
                default=1,
                null=True,
                verbose_name="Tipo de Audi\xeancia",
            ),
        ),
        migrations.AlterField(
            model_name="teaching",
            name="teaching",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cif.Teaching",
            ),
        ),
        migrations.RunPython(up, down),
    ]
