# Generated by Django 2.2.16 on 2020-10-23 15:30

import common.document_access.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('diarias', '0033_auto_20200810_1625'),
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saci", "0010_add_permission_reports"),
        ("rh", "0123_datamigration_documentodigital_digitaldocument"),
        ("protocolo", "0026_envelop_undo_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "final_term",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Termo Final"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Nº do Documento"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Assunto")),
                (
                    "production_date",
                    models.DateTimeField(verbose_name="Data de produção"),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Mês"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "special_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=60, null=True
                    ),
                ),
                (
                    "is_committed",
                    models.BooleanField(default=True, verbose_name="Efetivado"),
                ),
            ],
            options={
                "verbose_name": "Controle de Acesso",
                "permissions": (
                    ("is_admin", "É administrador"),
                    (
                        "is_allowed_to_classify",
                        "Está autorizado a classificar controle de acesso",
                    ),
                    (
                        "is_allowed_to_reclassify",
                        "Está autorizado a reclassificar controle de acesso",
                    ),
                    (
                        "is_allowed_to_declassify",
                        "Está autorizado a desclassificar controle de acesso",
                    ),
                    (
                        "is_allowed_to_reduce_deadline",
                        "Está autorizado a reduzir prazo",
                    ),
                    (
                        "is_allowed_to_extend_deadline",
                        "Está autorizado a prorrogar prazo",
                    ),
                ),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ControlType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, verbose_name="Título")),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="É sigiloso"),
                ),
                (
                    "not_allow_admin_access",
                    models.BooleanField(
                        default=False, verbose_name="Desautoriza acesso da comissão"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        verbose_name="Número máximo de aditamentos"
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(verbose_name="Peso")),
                (
                    "max_period",
                    models.PositiveSmallIntegerField(
                        verbose_name="Prazo máximo (anos)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auth.Permission",
                        verbose_name="Permissão necessária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível de Acesso",
                "ordering": ("weight",),
                "permissions": (
                    (
                        "can_use_level_1_classification",
                        "Pode usar classificação nível 1",
                    ),
                    (
                        "can_use_level_2_classification",
                        "Pode usar classificação nível 2",
                    ),
                    (
                        "can_use_level_3_classification",
                        "Pode usar classificação nível 3",
                    ),
                    (
                        "can_use_level_4_classification",
                        "Pode usar classificação nível 4",
                    ),
                    (
                        "can_use_level_5_classification",
                        "Pode usar classificação nível 5",
                    ),
                    (
                        "can_use_level_6_classification",
                        "Pode usar classificação nível 6",
                    ),
                    (
                        "can_use_level_7_classification",
                        "Pode usar classificação nível 7",
                    ),
                    (
                        "can_use_level_8_classification",
                        "Pode usar classificação nível 8",
                    ),
                    (
                        "can_use_level_9_classification",
                        "Pode usar classificação nível 9",
                    ),
                    (
                        "can_use_level_10_classification",
                        "Pode usar classificação nível 10",
                    ),
                ),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="LegalPrerogative",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "control_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerogatives",
                        to="document_access.ControlType",
                        verbose_name="Nível de Acesso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hipótese Legal",
                "ordering": ("created_at",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("log_type", models.PositiveSmallIntegerField(verbose_name="Tipo")),
                (
                    "signed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "validation_bypassed",
                    models.BooleanField(
                        default=False, verbose_name="Validação ignorada"
                    ),
                ),
                (
                    "is_committed",
                    models.BooleanField(default=True, verbose_name="Efetivado"),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="document_access.Control",
                        verbose_name="Controle",
                    ),
                ),
                (
                    "control_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="document_access.ControlType",
                        verbose_name="Nível de Acesso",
                    ),
                ),
                (
                    "legal_prerogative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="document_access.LegalPrerogative",
                        verbose_name="Hipótese legal",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Mudanças",
                "ordering": ("-signed_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AddField(
            model_name="control",
            name="control_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controls",
                to="document_access.ControlType",
                verbose_name="Nível de Acesso",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controls",
                to="document_access.DocumentType",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="legal_prerogative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controls",
                to="document_access.LegalPrerogative",
                verbose_name="Hipótese legal",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.OrgaoGeral",
                verbose_name="Origem",
            ),
        ),
        migrations.CreateModel(
            name="ProtocolControl",
            fields=[
                (
                    "control_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="document_access.Control",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_control",
                        to="protocolo.Protocolo",
                        verbose_name="Protocolo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Sigilo de Protocolo",
            },
            bases=(
                common.document_access.models.ProtocolMixin,
                "document_access.control",
            ),
        ),
        migrations.CreateModel(
            name="DailyControl",
            fields=[
                (
                    "control_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="document_access.Control",
                    ),
                ),
                # ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_control', to='diarias.Solicitacao', verbose_name='Diária')),
            ],
            options={
                "verbose_name": "Controle de Sigilo de Diária",
            },
            bases=(
                common.document_access.models.ProtocolMixin,
                "document_access.control",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceControl",
            fields=[
                (
                    "control_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="document_access.Control",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_control",
                        to="saci.Attendance",
                        verbose_name="Atendimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controle de Sigilo de Atendimento",
            },
            bases=("document_access.control",),
        ),
        migrations.CreateModel(
            name="AllowedListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Autorizado em"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revogado em"
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowedlistitems",
                        to="document_access.Control",
                        verbose_name="Controle",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autorizado por",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revogado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Lista de Credenciais",
                "ordering": ("control", "granted_at"),
                "unique_together": {("control", "person", "revoked_at")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
