# Generated by Django 2.2.16 on 2020-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_access", "0002_populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="controltype",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Habilitado"),
        ),
    ]
