# Generated by Django 2.2.16 on 2020-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_access", "0003_add_field_enabled_to_controltype"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalprerogative",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Habilitado"),
        ),
    ]
