# Generated by Django 2.2.28 on 2024-05-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_access", "0005_auto_20230112_1053"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyControl",
        ),
    ]
