# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0007_auto_20190401_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ausenciafalecimento",
            name="pessoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ausenciafalecimento",
                to="rh.PessoaFisica",
                verbose_name="Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="licencasaude",
            name="acidente_transito",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "ATROPELAMENTO"), (2, "COLIS\xc3O"), (3, "OUTROS")],
                default=3,
            ),
        ),
    ]
