# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0009_load_permission_fixture"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="interrupt_vacation",
            field=models.BooleanField(default=False),
        ),
    ]
