# Generated by Django 2.2.11 on 2020-03-10 10:08

from django.conf import settings
from django.db import migrations

from django.core.management import call_command

import django.db.models.deletion
import os

FIXTURES = ("fixtures/new_tipo_base_licenca_afastamento_healthprevent.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        try:
            call_command("loaddata", filepath)
        except Exception as err:
            print(err)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0112_auto_20200310_1008"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("afastamento", "0012_auto_20200212_1658"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HealthWoman",
            new_name="HealthPrevent",
        ),
        migrations.AlterModelOptions(
            name="healthprevent",
            options={"verbose_name": "Usufruto Prevenção Saúde"},
        ),
        migrations.AlterModelTable(
            name="healthprevent",
            table="afastamento_healthprevent",
        ),
        migrations.RunPython(up, down),
    ]
