# Generated by Django 2.2.12 on 2020-05-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0115_auto_20200506_1551"),
        ("afastamento", "0013_auto_20200310_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="afastamentomandatoeletivo",
            name="organ_location",
            field=models.ForeignKey(
                default=697,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="afastamentomandatoeletivo_organ_location",
                to="rh.UnidadeAdministrativa",
                verbose_name="Órgão de destino",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="afastamentomandatoeletivo",
            name="localidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Localidade",
            ),
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="tipo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "BaseLicencaAfastamento"),
                    (2, "Afastamento"),
                    (3, "Licenca"),
                    (4, "Ausencia"),
                    (5, "FeriasAfastamento"),
                    (6, "Viagem"),
                    (7, "Recesso"),
                    (8, "LicencaSaude"),
                    (9, "LicencaSaude3Dias"),
                    (10, "LicencaSaudeJuntaMedica"),
                    (11, "LicencaDoencaPessoaFamilia"),
                    (12, "LicencaMaternidade"),
                    (13, "LicencaAdocao"),
                    (14, "LicencaAfastamentoConjuge"),
                    (15, "LicencaServicoMilitar"),
                    (16, "LicencaAtividadePolitica"),
                    (17, "LicencaCapacitacao"),
                    (18, "LicencaInteresseParticular"),
                    (19, "LicencaMandatoClassista"),
                    (20, "AfastamentoOutroOrgao"),
                    (21, "AfastamentoMandatoEletivo"),
                    (22, "AfastamentoEstudar"),
                    (23, "AfastamentoMissao"),
                    (24, "AfastamentoEleitoral"),
                    (25, "AfastamentoServirJuri"),
                    (26, "AfastamentoTreinamento"),
                    (27, "AfastamentoDeslocamento"),
                    (28, "AfastamentoCompeticao"),
                    (29, "AfastamentoCursoConcurso"),
                    (30, "AfastamentoPrisao"),
                    (31, "AusenciaDoacaoSangue"),
                    (32, "AusenciaEleitor"),
                    (33, "AusenciaCasamento"),
                    (34, "AusenciaNascimento"),
                    (35, "AusenciaFalecimento"),
                    (36, "AusenciaConclusao"),
                    (37, "LicencaSaude30Dias"),
                    (38, "FolgaEleitoral"),
                    (39, "AtuacaoGrupoTrabalho"),
                    (40, "DesempenhoFuncao"),
                    (41, "Plantao"),
                    (42, "FolgaCompensacao"),
                    (43, "FolgaAniversario"),
                    (44, "AfastamentoSuspensao"),
                    (45, "AfastamentoComparecimentoJuizo"),
                    (46, "AfastamentoDisponibilidade"),
                    (47, "BancoDeHoras"),
                    (48, "UsufrutoPrevencaoSaude"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="licencasaude",
            name="process_rectification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_lisense",
                to="rh.LegalProcess",
                verbose_name="Processo de Retificação",
            ),
        ),
    ]
