# Generated by Django 2.2.17 on 2020-11-23 17:07

from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings
from django.core.management import call_command
import os

FIXTURES = ("fixtures/new_tipo_base_licenca_afastamento_awardlicense.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0014_auto_20200506_1552"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardLicense",
            fields=[
                (
                    "licenca_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="afastamento.Licenca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Prêmio",
                "db_table": "afastamento_awardlicense",
            },
            bases=("afastamento.licenca",),
        ),
        migrations.RunPython(up, down),
    ]
