# Generated by Django 2.2.24 on 2021-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0016_auto_20210304_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencasaude",
            name="acidente_transito",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "ATROPELAMENTO"), (2, "COLISÃO"), (3, "OUTROS")],
                null=True,
            ),
        ),
    ]
