# Generated by Django 2.2.28 on 2022-04-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0018_auto_20220412_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencasaude",
            name="classification",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="licencasaude",
            name="health_certificate",
            field=models.ManyToManyField(
                related_name="health_license",
                to="afastamento.HealthCertificate",
                verbose_name="Atestados",
            ),
        ),
        migrations.AlterField(
            model_name="licencasaude",
            name="process_rectification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_license",
                to="rh.LegalProcess",
                verbose_name="Processo de Retificação",
            ),
        ),
    ]
