# Generated by Django 2.2.28 on 2022-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0019_auto_20220425_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="event_esocial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licencasaude",
            name="classification",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "NORMAL"), (2, "ANTECIPAÇÃO"), (3, "PRORROGAÇÃO")],
                default=1,
            ),
        ),
    ]
