# Generated by Django 2.2.28 on 2023-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0024_auto_20230413_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Vida Funcional"),
                    (2, "Tela de designações"),
                    (3, "Afastamento"),
                ],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="tipo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "BaseLicencaAfastamento"),
                    (2, "Afastamento"),
                    (3, "Licenca"),
                    (4, "Ausencia"),
                    (5, "FeriasAfastamento"),
                    (6, "Viagem"),
                    (7, "Recesso"),
                    (8, "LicencaSaude"),
                    (9, "LicencaSaude3Dias"),
                    (10, "LicencaSaudeJuntaMedica"),
                    (11, "LicencaDoencaPessoaFamilia"),
                    (12, "LicencaMaternidade"),
                    (13, "LicencaAdocao"),
                    (14, "LicencaAfastamentoConjuge"),
                    (15, "LicencaServicoMilitar"),
                    (16, "LicencaAtividadePolitica"),
                    (17, "LicencaCapacitacao"),
                    (18, "LicencaInteresseParticular"),
                    (19, "LicencaMandatoClassista"),
                    (20, "AfastamentoOutroOrgao"),
                    (21, "AfastamentoMandatoEletivo"),
                    (22, "AfastamentoEstudar"),
                    (23, "AfastamentoMissao"),
                    (24, "AfastamentoEleitoral"),
                    (25, "AfastamentoServirJuri"),
                    (26, "AfastamentoTreinamento"),
                    (27, "AfastamentoDeslocamento"),
                    (28, "AfastamentoCompeticao"),
                    (29, "AfastamentoCursoConcurso"),
                    (30, "AfastamentoPrisao"),
                    (31, "AusenciaDoacaoSangue"),
                    (32, "AusenciaEleitor"),
                    (33, "AusenciaCasamento"),
                    (34, "AusenciaNascimento"),
                    (35, "AusenciaFalecimento"),
                    (36, "AusenciaConclusao"),
                    (37, "LicencaSaude30Dias"),
                    (38, "FolgaEleitoral"),
                    (39, "AtuacaoGrupoTrabalho"),
                    (40, "DesempenhoFuncao"),
                    (41, "Plantao"),
                    (42, "FolgaCompensacao"),
                    (43, "FolgaAniversario"),
                    (44, "AfastamentoSuspensao"),
                    (45, "AfastamentoComparecimentoJuizo"),
                    (46, "AfastamentoDisponibilidade"),
                    (47, "BancoDeHoras"),
                    (48, "UsufrutoPrevencaoSaude"),
                    (59, "AwardLicense"),
                    (61, "AfastamentoParcialEstudar"),
                    (62, "AfastamentoSindicanciaAdm"),
                ],
                db_index=True,
                default=1,
            ),
        ),
    ]
