# Generated by Django 2.2.28 on 2023-06-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0025_auto_20230511_1137"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicencaSaudeHoras",
            fields=[
                (
                    "licencasaude_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="afastamento.LicencaSaude",
                    ),
                ),
                (
                    "hours",
                    models.IntegerField(
                        null=True, verbose_name="Quatidade de horas em licença"
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Saúde Horas",
                "db_table": "afastamento_licencasaudehoras",
            },
            bases=("afastamento.licencasaude",),
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="origin_register",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Origem do registro"
            ),
        ),
    ]
