# Generated by Django 2.2.28 on 2023-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0026_auto_20230628_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIDCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, verbose_name="Códigos da CID-10"),
                ),
            ],
            options={
                "verbose_name": "CIDCode",
                "verbose_name_plural": "CIDCodes",
            },
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="motivo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "FÉRIAS"),
                    (2, "LICENÇA"),
                    (3, "RECESSO NATALINO"),
                    (4, "PLANTÃO"),
                    (5, "VIAGEM A TRABALHO"),
                    (6, "DESEMPENHO DE FUNÇÃO"),
                    (7, "DISPOSIÇÃO DE OUTRO ÓRGÃO"),
                    (8, "REPRESENTAÇÃO DE CLASSE"),
                    (9, "ATUAÇÃO DE GRUPO DE TRABALHO"),
                    (10, "TRÂNSITO/PROMOÇÃO/REMOÇÃO"),
                    (12, "SUSPENSÃO"),
                    (62, "SINDICÂNCIA"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "VDF"), (2, "DSG"), (3, "AFT"), (4, "GAD")],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
        migrations.AlterField(
            model_name="baselicencaafastamento",
            name="tipo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "BaseLicencaAfastamento"),
                    (2, "Afastamento"),
                    (3, "Licenca"),
                    (4, "Ausencia"),
                    (5, "FeriasAfastamento"),
                    (6, "Viagem"),
                    (7, "Recesso"),
                    (8, "LicencaSaude"),
                    (9, "LicencaSaude3Dias"),
                    (10, "LicencaSaudeJuntaMedica"),
                    (11, "LicencaDoencaPessoaFamilia"),
                    (12, "LicencaMaternidade"),
                    (13, "LicencaAdocao"),
                    (14, "LicencaAfastamentoConjuge"),
                    (15, "LicencaServicoMilitar"),
                    (16, "LicencaAtividadePolitica"),
                    (17, "LicencaCapacitacao"),
                    (18, "LicencaInteresseParticular"),
                    (19, "LicencaMandatoClassista"),
                    (20, "AfastamentoOutroOrgao"),
                    (21, "AfastamentoMandatoEletivo"),
                    (22, "AfastamentoEstudar"),
                    (23, "AfastamentoMissao"),
                    (24, "AfastamentoEleitoral"),
                    (25, "AfastamentoServirJuri"),
                    (26, "AfastamentoTreinamento"),
                    (27, "AfastamentoDeslocamento"),
                    (28, "AfastamentoCompeticao"),
                    (29, "AfastamentoCursoConcurso"),
                    (30, "AfastamentoPrisao"),
                    (31, "AusenciaDoacaoSangue"),
                    (32, "AusenciaEleitor"),
                    (33, "AusenciaCasamento"),
                    (34, "AusenciaNascimento"),
                    (35, "AusenciaFalecimento"),
                    (36, "AusenciaConclusao"),
                    (37, "LicencaSaude30Dias"),
                    (38, "FolgaEleitoral"),
                    (39, "AtuacaoGrupoTrabalho"),
                    (40, "DesempenhoFuncao"),
                    (41, "Plantao"),
                    (42, "FolgaCompensacao"),
                    (43, "FolgaAniversario"),
                    (44, "AfastamentoSuspensao"),
                    (45, "AfastamentoComparecimentoJuizo"),
                    (46, "AfastamentoDisponibilidade"),
                    (47, "BancoDeHoras"),
                    (48, "UsufrutoPrevencaoSaude"),
                    (59, "AwardLicense"),
                    (61, "AfastamentoParcialEstudar"),
                    (62, "AfastamentoSindicanciaAdm"),
                    (63, "LicencaSaudeHoras"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="CID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(max_length=50, verbose_name="Capítulo da CID"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Código da CID")),
                (
                    "description",
                    models.CharField(max_length=244, verbose_name="Descrição da CID"),
                ),
                (
                    "cid_code",
                    models.ManyToManyField(
                        related_name="cids",
                        to="afastamento.CIDCode",
                        verbose_name="Códigos da CID-10",
                    ),
                ),
            ],
            options={
                "verbose_name": "CID",
                "verbose_name_plural": "CIDs",
            },
        ),
    ]
