# Generated by Django 2.2.28 on 2023-10-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0029_licencasaude_cid"),
    ]

    operations = [
        migrations.AddField(
            model_name="afastamentosuspensao",
            name="convertido_multa",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Convertido em Multa"
            ),
        ),
    ]
