# Generated by Django 2.2.28 on 2023-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0030_afastamentosuspensao_convertido_multa"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="desconta_tempo",
            field=models.IntegerField(
                choices=[(1, "Sim"), (2, "Não")], default=2, verbose_name="Desconta ?"
            ),
        ),
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="total_desconto",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="baselicencaafastamento",
            name="total_parcial",
            field=models.IntegerField(
                choices=[(1, "Sim"), (2, "Não")],
                default=2,
                verbose_name="Desconto Parcial ?",
            ),
        ),
    ]
