# Generated by Django 2.2.28 on 2024-12-12 15:29

from django.db import migrations

from common.services.scripts.create_job_users import cria_usuarios


def forward(apps, schema_editor):
    print("Running forward...")
    cria_usuarios()


def backward(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0031_auto_20231123_1612"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
