# Generated by Django 2.2.28 on 2022-12-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("health", "0001_initial"),
        ("rh", "0209_auto_20221212_1119"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte do corpo atingida",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="CauserAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente Causador do Acidente de Trabalho",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="CauserAgentAccident",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente Causador ou Situação do Acidente de Trabalho",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="EnvironmentWorkingCondition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "type_environment",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tipo de ambiente"
                    ),
                ),
                (
                    "description_departament",
                    models.CharField(
                        max_length=100, verbose_name="Descrição do lugar administrativo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environmentworkingcondition",
                        to="rh.PessoaFisica",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environmentworkingcondition",
                        to="rh.Lotacao",
                        verbose_name="Lotação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condição Ambiental de Trabalho",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesão",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="MonitorOccupationalHealth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("monitoring_date", models.DateTimeField(verbose_name="Data")),
                (
                    "type_aso",
                    models.PositiveSmallIntegerField(default=99, verbose_name="Tipo"),
                ),
                (
                    "result",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Resultado"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoroccupationalhealth",
                        to="rh.PessoaFisica",
                        verbose_name="Médico ASO",
                    ),
                ),
                (
                    "doctor_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoroccupationalhealth_doctormanager",
                        to="rh.PessoaFisica",
                        verbose_name="Médico PCMSO",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoroccupationalhealth",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoramento da Saúde do Trabalhador",
                "ordering": ("employee",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="HarmfulAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente Nocivo",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ExposureEmployeeEnvironment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "description_activity",
                    models.CharField(
                        max_length=999, verbose_name="Descrição das atividade"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposureemployeeenvironment",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "environment_working_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exposureemployeeenvironment",
                        to="sst.EnvironmentWorkingCondition",
                        verbose_name="Condição Ambiental de Trabalho",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exposição do Servidor",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ExamSst",
            fields=[
                (
                    "exam_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="health.Exam",
                    ),
                ),
                (
                    "monitor_occupational_health",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examsst",
                        to="sst.MonitorOccupationalHealth",
                        verbose_name="Monitoração de saúde",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("health.exam",),
        ),
        migrations.CreateModel(
            name="Epi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=255, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=999, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EPI",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="EnvironmentHarmfulAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type_evaluation",
                    models.PositiveSmallIntegerField(
                        default=99, verbose_name="Tipo de avaliação do agente nocivo."
                    ),
                ),
                (
                    "intensity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Intensidade, concentração ou dose da exposição",
                    ),
                ),
                (
                    "limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Limite de tolerância calculado para agentes específicos",
                    ),
                ),
                (
                    "measure_unit",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Dose ou unidade de medida da intensidade ou concentração do agente.",
                    ),
                ),
                (
                    "measurement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Técnica utilizada para medição da intensidade ou concentração",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Descrição do agente nocivo",
                    ),
                ),
                (
                    "epc",
                    models.PositiveSmallIntegerField(
                        default=99,
                        verbose_name="Implementa medidas de proteção coletiva(EPC)",
                    ),
                ),
                (
                    "efficiency_epc",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Os EPCs são eficazes na neutralização do risco ao trabalhador?",
                    ),
                ),
                (
                    "epi",
                    models.PositiveSmallIntegerField(
                        default=99, verbose_name="Utilização de EPI"
                    ),
                ),
                (
                    "efficiency_epi",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Os EPIs são eficazes na neutralização do risco ao trabalhador?",
                    ),
                ),
                (
                    "implement_protection",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Foi tentada a implementação de medidas de proteção coletiva?",
                    ),
                ),
                (
                    "working_condition",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Foram observadas as condições de funcionamento do EPI?",
                    ),
                ),
                (
                    "uninterrupted_use",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Foi observado o uso ininterrupto do EPI ao longo do tempo?",
                    ),
                ),
                (
                    "expiry_date_on_purchase",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Foi observado o prazo de validade do CA no momento da compra do EPI?",
                    ),
                ),
                (
                    "change_frequency",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="É observada a periodicidade de troca?",
                    ),
                ),
                (
                    "sanitation",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="É observada a higienização conforme orientação do fabricante nacional ou importador?",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=999, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment_working_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="environmentharmfulagent",
                        to="sst.EnvironmentWorkingCondition",
                        verbose_name="Condição Ambiental de Trabalho",
                    ),
                ),
                (
                    "epis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="environmentharmfulagent",
                        to="sst.Epi",
                        verbose_name="EPI",
                    ),
                ),
                (
                    "harmful_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="harmfulagent",
                        to="sst.HarmfulAgent",
                        verbose_name="Agente Nocivo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente Nocivo do Ambiente",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="WorkAccidentCommunication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "accident_date",
                    models.DateTimeField(verbose_name="Data e hora do acidente"),
                ),
                (
                    "type_accident",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tipo de acidente"
                    ),
                ),
                (
                    "work_hours_before_accident",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Horas trabalhadas antes do acidente",
                    ),
                ),
                (
                    "type_cat",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tipo da CAT"
                    ),
                ),
                (
                    "death",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Indicativo de óbito"
                    ),
                ),
                (
                    "death_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do óbito"
                    ),
                ),
                (
                    "police_communication",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Comunicação à polícia"
                    ),
                ),
                (
                    "initiator_cat",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Quem iniciou a CAT"
                    ),
                ),
                (
                    "note_cat",
                    models.CharField(
                        blank=True,
                        max_length=999,
                        null=True,
                        verbose_name="Observação CAT",
                    ),
                ),
                (
                    "last_work_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Último dia trabalhado"
                    ),
                ),
                (
                    "leave_work_accident",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Afastamento do trabalho",
                    ),
                ),
                (
                    "type_address_accident",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Tipo de local do acidente"
                    ),
                ),
                (
                    "address_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição do local do acidente",
                    ),
                ),
                (
                    "laterality",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Lateralidade"
                    ),
                ),
                (
                    "attest_date",
                    models.DateTimeField(verbose_name="Data e horário de atendimento"),
                ),
                (
                    "hospitalization",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Internação"
                    ),
                ),
                (
                    "duration_treatment",
                    models.SmallIntegerField(
                        verbose_name="Duração estimada do tratamento"
                    ),
                ),
                (
                    "leave_work_treatment",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Afastamento do trabalho para tratamento",
                    ),
                ),
                (
                    "nature_injury_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descrição da natureza da lesão",
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Provável diagnóstico",
                    ),
                ),
                ("cid", models.CharField(max_length=4, verbose_name="CID")),
                (
                    "note_attest",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="rh.Endereco",
                        verbose_name="Endereço do acidente",
                    ),
                ),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="sst.BodyPart",
                        verbose_name="Parte do corpo atingida",
                    ),
                ),
                (
                    "causer_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="sst.CauserAgent",
                        verbose_name="Agente causador",
                    ),
                ),
                (
                    "causer_agent_accident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="sst.CauserAgentAccident",
                        verbose_name="Agente causador",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor_attest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="rh.PessoaFisica",
                        verbose_name="Médico atestado",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workaccidentecommunication",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nature_injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="sst.Injury",
                        verbose_name="Natureza da lesão",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workaccidentecommunication",
                        to="sst.WorkAccidentCommunication",
                        verbose_name="CAT anterior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicação de Acidente de Trabalho",
                "ordering": ("accident_date", "employee"),
                "unique_together": {("accident_date", "type_accident", "employee")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
