# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sst", "0002_load_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentharmfulagent",
            name="epc",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (99, "Não se aplica"),
                    (1, "Não implementa"),
                    (2, "Implementa"),
                ],
                default=99,
                verbose_name="Implementa medidas de proteção coletiva(EPC)",
            ),
        ),
        migrations.AlterField(
            model_name="environmentharmfulagent",
            name="epi",
            field=models.PositiveSmallIntegerField(
                choices=[(99, "Não se aplica"), (1, "Não utilizado"), (2, "Utilizado")],
                default=99,
                verbose_name="Utilização de EPI",
            ),
        ),
        migrations.AlterField(
            model_name="environmentharmfulagent",
            name="measure_unit",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (99, "Não informado"),
                    (1, "dose diária de ruído"),
                    (2, "decibel linear(dB(linear))"),
                    (3, "decibel(C)(dB(C))"),
                    (4, "decibel(A)(dB(A))"),
                    (5, "metro por segundo ao quadrado(m/s2)"),
                    (6, "metro por segundo elevado a 1, 75 (m/s1, 75)"),
                    (
                        7,
                        "parte de vapor ou gás por milhão de partes de ar contaminado(ppm)",
                    ),
                    (8, "miligrama por metro cúbico de ar(mg/m3)"),
                    (9, "fibra por centímetro cúbico(f/cm3)"),
                    (10, "grau Celsius(oC)"),
                    (11, "metro por segundo(m/s)"),
                    (12, "porcentual"),
                    (13, "lux(lx)"),
                    (14, "unidade formadora de colônias por metro cúbico (ufc/m3)"),
                    (15, "dose diária"),
                    (16, "dose mensal"),
                    (17, "dose trimestral"),
                    (18, "dose anual"),
                    (19, "watt por metro quadrado(W/m2)"),
                    (20, "ampère por metro(A/m)"),
                    (21, "militesla(mT)"),
                    (22, "microtesla(μT)"),
                    (23, "miliampère(mA)"),
                    (24, "quilovolt por metro(kV/m)"),
                    (25, "volt por metro(V/m)"),
                    (26, "joule por metro quadrado(J/m2)"),
                    (27, "milijoule por centímetro quadrado(mJ/cm2)"),
                    (28, "milisievert(mSv)"),
                    (29, "milhão de partículas por decímetro cúbico(mppdc)"),
                    (30, "umidade relativa do ar (UR ( % ))"),
                ],
                default=1,
                verbose_name="Dose ou unidade de medida da intensidade ou concentração do agente.",
            ),
        ),
        migrations.AlterField(
            model_name="environmentharmfulagent",
            name="type_evaluation",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (99, "Não informado"),
                    (1, "Critério quantitativo"),
                    (2, "Critério qualitativo"),
                ],
                default=99,
                verbose_name="Tipo de avaliação do agente nocivo.",
            ),
        ),
        migrations.AlterField(
            model_name="environmentworkingcondition",
            name="type_environment",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Estabelecimento do próprio empregador"),
                    (2, "Estabelecimento de terceiros"),
                ],
                default=1,
                verbose_name="Tipo de ambiente",
            ),
        ),
        migrations.AlterField(
            model_name="monitoroccupationalhealth",
            name="type_aso",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Exame médico periódico, conforme Norma"),
                    (2, "Exame médico de retorno ao trabalho"),
                    (
                        3,
                        "Exame médico de mudança de função ou de mudança de risco ocupacional",
                    ),
                    (
                        4,
                        "Exame médico de monitoração pontual, não enquadrado nos demais casos",
                    ),
                    (9, "Exame médico demissional"),
                    (99, "Exame médico admissional"),
                ],
                default=99,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="workaccidentcommunication",
            name="initiator_cat",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Empregador"),
                    (2, "Ordem judicial"),
                    (3, "Determinação de órgão fiscalizador"),
                ],
                default=1,
                verbose_name="Quem iniciou a CAT",
            ),
        ),
        migrations.AlterField(
            model_name="workaccidentcommunication",
            name="laterality",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (99, "Não aplicável"),
                    (1, "Esquerda"),
                    (2, "Direita"),
                    (3, "Ambas"),
                ],
                default=1,
                verbose_name="Lateralidade",
            ),
        ),
        migrations.AlterField(
            model_name="workaccidentcommunication",
            name="type_accident",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "TÍPICO"), (2, "DOENÇA"), (3, "TRAJETO")],
                default=1,
                verbose_name="Tipo de acidente",
            ),
        ),
        migrations.AlterField(
            model_name="workaccidentcommunication",
            name="type_address_accident",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Estabelecimento do empregador no Brasil"),
                    (2, "Estabelecimento do empregador no exterior"),
                    (
                        3,
                        "Estabelecimento de terceiros onde o empregador presta serviços",
                    ),
                    (4, "Via pública"),
                    (5, "Área rural"),
                    (6, "Embarcação"),
                    (9, "Outros"),
                ],
                default=1,
                verbose_name="Tipo de local do acidente",
            ),
        ),
        migrations.AlterField(
            model_name="workaccidentcommunication",
            name="type_cat",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Inicial"),
                    (2, "Reabertura"),
                    (3, "Comunicação de óbito"),
                ],
                default=1,
                verbose_name="Tipo da CAT",
            ),
        ),
    ]
