export enum PendingTypeEnum {
    APROVACOES_PENDENTES = 'APROVACOES_PENDENTES',
    REGISTRO_PONTO_ENTRADA = 'REGISTRO_PONTO_ENTRADA',
    RELATORIO_SEMESTRAL_PENDENTE = 'RELATORIO_SEMESTRAL_PENDENTE',
    ENVIO_TELETRABALHO_PENDENTE = 'ENVIO_TELETRABALHO_PENDENTE',
    PRESTACAO_CONTAS_DIARIAS = 'PRESTACAO_CONTAS_DIARIAS',
    APROVACOES_DIARIAS_PENDENTES = 'APROVACOES_DIARIAS_PENDENTES',
    DESBLOQUEIO_TELETRABALHO = 'DESBLOQUEIO_TELETRABALHO',
    AVALIACOES_PENDENTES_DIARIAS = 'AVALIACOES_PENDENTES_DIARIAS',
}
