# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0021_add_special_type"),
        ("requestform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileLiabilityStatement",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("imei", models.CharField(max_length=50, verbose_name="Imei")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="N\xba da Linha"),
                ),
                (
                    "phone_description",
                    models.TextField(verbose_name="Descri\xe7\xe3o do Bem"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
