# Generated by Django 2.2.11 on 2020-03-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requestform", "0002_mobileliabilitystatement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebitAuthorization",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "debit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Débito em porcentagem",
                    ),
                ),
                (
                    "suspended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Suspenso em"
                    ),
                ),
                (
                    "suspension_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da suspensão"
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Suspenso por",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
