# Generated by Django 2.2.12 on 2020-05-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0114_datamigration_document_naturalperson"),
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0017_funeralallowance"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyDeclaration",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
                (
                    "possession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.MovimentacaoPosse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
