# Generated by Django 2.2.12 on 2020-05-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0018_vacancydeclaration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancydeclaration",
            name="possession",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="rh.MovimentacaoPosse",
                verbose_name="Cargo",
            ),
        ),
        migrations.CreateModel(
            name="Resignation",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
                (
                    "possession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.MovimentacaoPosse",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
