# Generated by Django 2.2.12 on 2020-05-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0019_resignation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealAllowance",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "working_time",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Carga horária",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "previous_public_institution",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Órgão de origem",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefone de contato",
                    ),
                ),
                (
                    "option_term",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (
                                1,
                                "Quero receber o auxílio pelo MP, pois não recebo em outro órgão público.",
                            ),
                            (
                                2,
                                "Quero receber o auxílio pelo MP, deixando de receber no outro órgão público.",
                            ),
                            (
                                3,
                                "Quero continuar recebendo o auxílio em outro órgão público e não pelo MP.",
                            ),
                        ],
                        null=True,
                        verbose_name="Termo de opção",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        )
    ]
