# Generated by Django 2.2.12 on 2020-05-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0021_load_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildcareAllowance",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefone de contato",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Conta"
                    ),
                ),
                (
                    "child_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome da criança",
                    ),
                ),
                (
                    "child_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "Filho(a)"), (1, "Dependente")],
                        null=True,
                        verbose_name="Tipo vínculo",
                    ),
                ),
                (
                    "child_birth_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de nascimento da criança",
                    ),
                ),
                (
                    "child_cpf",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="CPF da criança",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Servidor",
                        verbose_name="Recebedor",
                    ),
                ),
                (
                    "spouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Servidor",
                        verbose_name="Cônjuge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
