# Generated by Django 2.2.12 on 2020-05-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0023_load_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialNeedsAllowance",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefone de contato",
                    ),
                ),
                (
                    "dependent_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do dependente",
                    ),
                ),
                (
                    "dependent_birth_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de nascimento do dependente",
                    ),
                ),
                (
                    "dependent_cpf",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="CPF do dependente",
                    ),
                ),
                (
                    "dependent_rg",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="RG do dependente",
                    ),
                ),
                (
                    "dependent_address",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "icd",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="CID-10 (Código Internacional da Doença)",
                    ),
                ),
                (
                    "disability_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Física"),
                            (2, "Auditiva"),
                            (3, "Visual"),
                            (4, "Mental"),
                            (5, "Múltipla"),
                            (6, "Outra"),
                        ],
                        null=True,
                        verbose_name="Tipo de deficiência",
                    ),
                ),
                (
                    "dependent_uf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="UF",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Servidor",
                        verbose_name="Recebedor",
                    ),
                ),
                (
                    "spouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Servidor",
                        verbose_name="Cônjuge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
