# Generated by Django 2.2.12 on 2020-05-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0026_functionalidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdBadge",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "is_reissue",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="2ª via"
                    ),
                ),
                (
                    "reissue_reason",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "EXTRAVIO / ROUBO"),
                            (2, "ALTERAÇÃO"),
                            (3, "SUBSTITUIÇÃO"),
                        ],
                        null=True,
                        verbose_name="Motivo da 2ª via",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome para constar no crachá",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        )
    ]
