# Generated by Django 2.2.12 on 2020-05-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0022_auto_20200327_1611"),
        ("requestform", "0027_idbadge"),
    ]

    operations = [
        migrations.CreateModel(
            name="DependentInclusion",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefone de contato",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.AlterField(
            model_name="employeerequest",
            name="request_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Afastamentos p/ cursos, seminários e congressos (Apenas aqueles autorizados pelo MPE)",
                    ),
                    (2, "Anotações diversas em ficha funcional"),
                    (3, "Averbação de tempo de serviço"),
                    (4, "Certidões ou declarações para fins específicos"),
                    (5, "Recesso natalino"),
                    (6, "Licença para trato de interesse particular"),
                    (7, "Domicílio bancário"),
                    (8, "Atividade política"),
                    (9, "Licença para capacitação"),
                    (10, "Outros"),
                ],
                null=True,
                verbose_name="Tipo requerimento",
            ),
        ),
        migrations.AlterField(
            model_name="memberrequest",
            name="request_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Afastamentos p/ cursos, seminários e congressos"),
                    (2, "Anotações diversas em ficha funcional"),
                    (3, "Aposentadoria"),
                    (4, "Averbação de tempo de serviço"),
                    (5, "Certidões ou declarações para fins específicos"),
                    (6, "Recesso natalino"),
                    (7, "Férias"),
                    (8, "Imposto de Renda - Exclusão de dependente."),
                    (
                        9,
                        "Inclusão de dependentes para todos os fins de direito, inclusive Imposto de Renda",
                    ),
                    (10, "Licença Casamento/Luto"),
                    (11, "Licença Eleitoral"),
                    (12, "Licença paternidade"),
                    (13, "Licença saúde até trinta dias"),
                    (14, "Licença por motivo de doença em pessoa da família"),
                    (15, "Retificação de nome ou dados cadastrais"),
                    (16, "Atividade Política"),
                    (17, "Domicílio bancário"),
                    (18, "Contra - Cheque"),
                    (19, "Levantamento de Tempo de Contribuição Averbado junto ao"),
                    (20, "Outros"),
                ],
                null=True,
                verbose_name="Tipo requerimento",
            ),
        ),
        migrations.AlterField(
            model_name="transitpass",
            name="request_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Autorização de desconto"), (1, "Suspensão de desconto")],
                null=True,
                verbose_name="Tipo requerimento",
            ),
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome do dependente"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, verbose_name="CPF do dependente"),
                ),
                (
                    "degree_of_kinship",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO(A) - UNIÃO ESTÁVEL"),
                            (3, "FILHO(A) NÃO EMANCIPADO MENOR DE 21 ANOS"),
                            (
                                4,
                                "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (5, "PAI(MÃE) COM DEPENDÊNCIA ECONÔMICA"),
                            (
                                6,
                                "IRMÃO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                7,
                                "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (8, "ENTEADO NÃO EMANCIPADO MENOR DE 21"),
                            (
                                9,
                                "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (
                                10,
                                "MENOR TUTELADO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA OU GUARDA JUDICIAL",
                            ),
                            (
                                11,
                                "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (12, "AVÓS COM DEPENDENCIA ECONOMICA"),
                            (13, "BISAVÓS COM DEPENDENCIA ECONOMICA"),
                            (
                                14,
                                "NETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                15,
                                "BISNETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (16, " EX-CÔNJUGE"),
                            (
                                17,
                                "FILHO(A) OU ENTEADO(A) UNIVERSITÁRIO(A) OU CURSANDO ESCOLA TÉCNICA DE 2ºGRAU, ATÉ 24 ANOS",
                            ),
                            (18, "AGREGADO/OUTROS"),
                        ],
                        verbose_name="Grau de Parentesco",
                    ),
                ),
                ("unimpeded_as_taxpayer_dependent", models.BooleanField(default=False)),
                (
                    "dependent_inclusion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="requestform.DependentInclusion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados de Dependentes",
            },
        ),
    ]
