# Generated by Django 2.2.13 on 2020-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requestform", "0031_nonanticipationthirteenth"),
    ]

    operations = [
        migrations.AddField(
            model_name="electorallicense",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Informe uma ou mais datas de licença",
            ),
        ),
    ]
