# Generated by Django 2.2.13 on 2020-07-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0118_auto_20200513_1820"),
        ("requestform", "0033_remove_electorallicense_license_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullTimeHomeOffice",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
                ("elderly", models.BooleanField(default=False, verbose_name="Idosos")),
                (
                    "pregnant",
                    models.BooleanField(default=False, verbose_name="Gestantes"),
                ),
                (
                    "chronic_diseases",
                    models.BooleanField(default=False, verbose_name="Doenças crônicas"),
                ),
                (
                    "pneumopathy_diseases",
                    models.BooleanField(
                        default=False, verbose_name="Portadores de pneumopatias"
                    ),
                ),
                (
                    "kidney_diseases",
                    models.BooleanField(
                        default=False, verbose_name="Portadores de doenças renais"
                    ),
                ),
                (
                    "cardiovascular_diseases",
                    models.BooleanField(
                        default=False,
                        verbose_name="Portadores de doenças cardiovasculares",
                    ),
                ),
                (
                    "obese",
                    models.BooleanField(
                        default=False, verbose_name="Pessoas com obesidades"
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Servidor",
                        verbose_name="Chefia imediata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
