# Generated by Django 2.2.16 on 2020-11-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0124_auto_20201022_1500"),
        ("protocolo", "0026_envelop_undo_fix"),
        ("requestform", "0035_comebybike"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileReturnStatement",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("imei", models.CharField(max_length=50, verbose_name="Imei")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Nº da Linha"),
                ),
                (
                    "phone_description",
                    models.CharField(max_length=256, verbose_name="Descrição do bem"),
                ),
                (
                    "returned_battery_charger",
                    models.BooleanField(
                        default=False, verbose_name="Carregador de bateria devolvido"
                    ),
                ),
                (
                    "returned_headphone",
                    models.BooleanField(
                        default=False, verbose_name="Fone de ouvido devolvido"
                    ),
                ),
                (
                    "returned_sim_ejector",
                    models.BooleanField(
                        default=False, verbose_name="Extrator de SIM card devolvido"
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Servidor",
                        verbose_name="Sucessor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
