# Generated by Django 2.2.24 on 2021-08-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0028_alter_commondestination_to_use_cascade"),
        ("requestform", "0038_load_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthcareAllowanceForActiveEmployee",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "request_type",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tipo requerimento"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="HealthcareAllowanceForInactiveEmployee",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=166, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de contato",
                    ),
                ),
                (
                    "beneficiary_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Aposentado(a)"), (2, "Pensionista")],
                        null=True,
                        verbose_name="Tipo de beneficiário",
                    ),
                ),
                (
                    "request_type",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tipo de requerimento"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.AlterField(
            model_name="thirteenthanticipation",
            name="option_term",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Antecipação de 75% do líquido"),
                    (2, "Antecipação de 90% do líquido"),
                    (3, "Antecipação complementar para alcançar 90% do líquido"),
                ],
                null=True,
                verbose_name="Termo de opção",
            ),
        ),
    ]
