# Generated by Django 2.2.24 on 2021-09-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0028_alter_commondestination_to_use_cascade"),
        ("requestform", "0040_load_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermoCompromissoManutencaoSigilo",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.AlterField(
            model_name="healthcareallowanceforactiveemployee",
            name="request_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Concessão do auxílio-saúde. Ao ensejo, DECLARO que não recebo benefício de natureza semelhante",
                    ),
                    (
                        2,
                        "Alteração de valores do plano ou seguro de assistência à saúde",
                    ),
                    (3, "Mudança de plano ou seguro de assistência à saúde"),
                    (4, "Cancelamento do benefício"),
                    (5, "Reativação do benefício"),
                ],
                null=True,
                verbose_name="Tipo de requerimento",
            ),
        ),
        migrations.AlterField(
            model_name="healthcareallowanceforinactiveemployee",
            name="request_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Concessão do auxílio-saúde. Ao ensejo, DECLARO que não recebo benefício de natureza semelhante",
                    ),
                    (
                        2,
                        "Alteração de valores do plano ou seguro de assistência à saúde",
                    ),
                    (3, "Mudança de plano ou seguro de assistência à saúde"),
                    (4, "Cancelamento do benefício"),
                    (5, "Reativação do benefício"),
                ],
                null=True,
                verbose_name="Tipo de requerimento",
            ),
        ),
    ]
