# Generated by Django 2.2.28 on 2022-06-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0173_auto_20220609_1144"),
        ("protocolo", "0029_auto_20211026_1459"),
        ("requestform", "0042_auto_20220412_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeOfficeForEmployee",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "request_type",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tipo de requerimento"
                    ),
                ),
                ("justification", models.TextField(verbose_name="Justificativa")),
                (
                    "activities_goals",
                    models.TextField(verbose_name="Atividades e Objetivos"),
                ),
                ("schedule", models.TextField(verbose_name="Cronograma")),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="RemoveNotificationApplication",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "position_start_concurso",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Posição no concurso de ingresso",
                    ),
                ),
                (
                    "option_interest",
                    models.TextField(verbose_name="Vagas de interesse"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="RemoveNotificationResistance",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "cancellation_vacancies",
                    models.TextField(verbose_name="Vagas de desistência"),
                ),
                (
                    "resistance_declaration",
                    models.TextField(verbose_name="Declaração de desistência"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.AlterField(
            model_name="thirteenthanticipation",
            name="option_term",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Antecipação de 75% do líquido"),
                    (2, "Antecipação de 90% do líquido"),
                    (3, "Antecipação complementar para alcançar 90% do líquido"),
                ],
                null=True,
                verbose_name="Termo de opção",
            ),
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "cumpliance_activities_goals",
                    models.TextField(verbose_name="Cumprimento das atividades e metas"),
                ),
                (
                    "employee_date_established",
                    models.BooleanField(
                        null=True,
                        verbose_name="O servidor cumpriu os prazos estabelecidos?",
                    ),
                ),
                (
                    "employee_working_established",
                    models.BooleanField(
                        null=True,
                        verbose_name="O servidor cumpriu a jornada estabelecida?",
                    ),
                ),
                (
                    "employee_available",
                    models.BooleanField(
                        null=True,
                        verbose_name="O servidor estava disponível através dos canais de comunicação no horário habitual de expediente?",
                    ),
                ),
                (
                    "employee_addaption_working",
                    models.BooleanField(
                        null=True, verbose_name="O servidor se adaptou ao teletrabalho?"
                    ),
                ),
                (
                    "employee_disobey_working",
                    models.BooleanField(
                        null=True,
                        verbose_name="O servidor descumpriu algum dever a si estabelecido durante o teletrabalho?",
                    ),
                ),
                (
                    "ask_affirmation_working",
                    models.TextField(
                        verbose_name="Em caso afirmativo da pergunta acima, elencar quais deveres foram descumpridos:"
                    ),
                ),
                ("note", models.TextField(verbose_name="Observações")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de término"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
