# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0031_auto_20220811_2016"),
        ("requestform", "0043_auto_20220628_1910"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensateExpense",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("finality", models.TextField(verbose_name="Finalidade")),
                (
                    "output_date",
                    models.DateField(blank=True, null=True, verbose_name="Saída"),
                ),
                (
                    "return_date",
                    models.DateField(blank=True, null=True, verbose_name="Retorno"),
                ),
                (
                    "total_compensate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("material", models.TextField(verbose_name="Material")),
                ("service", models.TextField(verbose_name="Serviço")),
                (
                    "combustible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("note", models.TextField(verbose_name="Observação")),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="IntimationWhatsAppAuthenticityVerifiable",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "name_intimate",
                    models.CharField(max_length=100, verbose_name="Nome do indiciado"),
                ),
                (
                    "cpf_intimate",
                    models.CharField(max_length=20, verbose_name="CPF do indiciado"),
                ),
                (
                    "name_victim",
                    models.CharField(max_length=100, verbose_name="Nome da vítima"),
                ),
                (
                    "cpf_victim",
                    models.CharField(max_length=20, verbose_name="CPF da vítima"),
                ),
                (
                    "number_inquiry_police",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Inquérito Policial",
                    ),
                ),
                ("is_victim", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="IntimationWhatsAppAuthenticityVerifiableIntimate",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "name_intimate",
                    models.CharField(max_length=100, verbose_name="Nome do indiciado"),
                ),
                (
                    "cpf_intimate",
                    models.CharField(max_length=20, verbose_name="CPF do indiciado"),
                ),
                (
                    "number_inquiry_police",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Inquérito Policial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="IntimationWhatsAppAuthenticityVerifiableVictim",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "name_intimate",
                    models.CharField(max_length=100, verbose_name="Nome do indiciado"),
                ),
                (
                    "cpf_intimate",
                    models.CharField(max_length=20, verbose_name="CPF do indiciado"),
                ),
                (
                    "name_victim",
                    models.CharField(max_length=100, verbose_name="Nome da vítima"),
                ),
                (
                    "cpf_victim",
                    models.CharField(max_length=20, verbose_name="CPF da vítima"),
                ),
                (
                    "number_inquiry_police",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Inquérito Policial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="MedicalLicense",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "grade_familiar",
                    models.CharField(
                        max_length=100, verbose_name="Parentesco familiar"
                    ),
                ),
                ("is_familiar", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="MedicalLicenseEmployee",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="MedicalLicenseFamiliar",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                (
                    "grade_familiar",
                    models.CharField(
                        max_length=100, verbose_name="Parentesco familiar"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="CompensateExpenseItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "company",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Nome da empresa ou do prestador do serviço",
                    ),
                ),
                (
                    "venc_date_nf",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimento da nota fiscal"
                    ),
                ),
                (
                    "nota_material",
                    models.BooleanField(default=False, verbose_name="Nota de material"),
                ),
                (
                    "nota_service",
                    models.BooleanField(default=False, verbose_name="Nota de serviço"),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "compensate_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensate_item",
                        to="requestform.CompensateExpense",
                        verbose_name="Ressarcimento",
                    ),
                ),
            ],
        ),
    ]
