# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastralquality", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationquery",
            options={"ordering": ("-id",)},
        ),
    ]
