# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apd", "0006_auto_20181130_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="deadline_begin",
            field=models.SmallIntegerField(
                blank=True, default=40, verbose_name="Dias para In\xedcio"
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="deadline_delay",
            field=models.SmallIntegerField(
                blank=True, default=60, verbose_name="Dias para bloqueio"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_appeal",
            field=models.SmallIntegerField(
                default=0, verbose_name="Dias para Interpor Recurso"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_judge_resource",
            field=models.SmallIntegerField(
                default=0, verbose_name="Dias para comiss\xe3o julgar recurso"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_reconsideration",
            field=models.SmallIntegerField(
                default=0,
                verbose_name="Dias para Solicitar a Reconsidera\xe7\xe3o de Avalia\xe7\xe3o",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_rectification_commission",
            field=models.SmallIntegerField(
                default=0,
                verbose_name="Dias para Comiss\xe3o realizar retifica\xe7\xe3o da nota",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_rectify_evaluation",
            field=models.SmallIntegerField(
                default=0, verbose_name="Dias para o chefe retificar Avalia\xe7\xe3o"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="deadline_science_resul_evaluation",
            field=models.SmallIntegerField(
                default=0,
                verbose_name="Dias para avaliado dar ciente do resultado da avalia\xe7\xe3o",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="interval_periodic_evaluation",
            field=models.SmallIntegerField(
                default=0, verbose_name="Intervalo de Avalia\xe7\xf5es em Meses"
            ),
        ),
        migrations.AlterField(
            model_name="periodicevaluationperformance",
            name="copied_from_stage",
            field=models.BooleanField(
                default=False, verbose_name="Copiado do est\xe1gio?"
            ),
        ),
    ]
