# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apd", "0007_auto_20190827_1454"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="deadline_delay",
        ),
        migrations.AddField(
            model_name="configuration",
            name="deadline_blocking",
            field=models.SmallIntegerField(
                blank=True, default=15, verbose_name="Dias para bloqueio"
            ),
        ),
    ]
