# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apd", "0008_auto_20190827_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercommission",
            name="type_participant",
            field=models.CharField(
                choices=[
                    ("1", "PRESIDENTE"),
                    ("2", "SECRETÁRIO"),
                    ("3", "INTEGRANTE"),
                    ("4", "SUPLENTE"),
                ],
                default=4,
                max_length=1,
                verbose_name="Tipo de Membro",
            ),
        ),
        migrations.AlterField(
            model_name="periodicevaluationperformance",
            name="state_evaluation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "NOVO"),
                    ("2", "AVALIADO"),
                    ("3", "MANIFESTADO"),
                    ("4", "FINALIZADO"),
                ],
                default=1,
                max_length=1,
            ),
        ),
    ]
