# Generated by Django 2.2.28 on 2022-06-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apd", "0009_auto_20220412_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicevaluationperformance",
            name="lock_in",
            field=models.SmallIntegerField(
                default=30, verbose_name="Dias até o bloqueio"
            ),
        ),
        migrations.AlterField(
            model_name="periodicevaluationperformance",
            name="commission",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apd.Commission",
                verbose_name="Comissão de Avaliação",
            ),
        ),
    ]
