# Generated by Django 2.2.28 on 2022-07-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0013_auto_20220718_1602"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledservices",
            name="classcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standard.ClassCode",
                verbose_name="ClassCode",
            ),
        ),
    ]
