# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_statuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "ordering": ("create_datetime",),
                "verbose_name": "Logging",
                "verbose_name_plural": "Logging",
            },
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NOTSET"),
                    (20, "INFO"),
                    (30, "WARNING"),
                    (10, "DEGUB"),
                    (40, "ERROR"),
                    (50, "FATAL"),
                ],
                db_index=True,
                default=40,
            ),
        ),
    ]
