# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-03 20:15
from __future__ import unicode_literals

import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations

FIXTURES = (
    "standard/fixtures/resident_email_templates_agendamento_notificacao.json",
    "standard/fixtures/resident_classcodes.json",
    "common/services/fixtures/resident_schedule_services.json",
)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20230112_1053"),
    ]

    operations = [migrations.RunPython(forward, backward)]
