# Generated by Django 2.2.28 on 2024-09-18 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0009_load_folhaponto_import_batidas_scheduledservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledservices",
            name="executado",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Executado"
            ),
        ),
        migrations.AddField(
            model_name="scheduledservices",
            name="executado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Executado em"
            ),
        ),
        migrations.AddField(
            model_name="scheduledservices",
            name="executado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="historico_servico",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executado por",
            ),
        ),
    ]
