# Generated by Django 2.2.28 on 2025-01-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0051_load_fixtures_template_email_metas"),
        ("services", "0012_historicoservico"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduledservices",
            unique_together={("classcode", "command")},
        ),
    ]
