# Generated by Django 4.2 on 2025-03-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_atualizar_tipo_execucao_hist_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledservices",
            name="em_execucao",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Em execução"
            ),
        ),
    ]
