# Generated by Django 2.2.24 on 2021-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0161_merge_20211028_1550"),
        ("gfp", "0078_merge_20210915_1209"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_event",
                    models.IntegerField(
                        choices=[(1, "PROVENTO"), (2, "DESCONTO"), (3, "INDIFERENTE")],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "section",
                    models.IntegerField(
                        choices=[
                            (10, "010 - APOSENTADOS"),
                            (20, "020 - MILITARES"),
                            (30, "030 - PENSIONISTAS"),
                            (40, "040 - SERVIDORES ATIVOS "),
                            (50, "050 - SENTENCAS JUDICIAIS"),
                            (60, "060 - DESPESAS DE EXERCICIOS ANTERIORES"),
                            (65, "065 - INDENIZACOES E RESTITUICOES TRABALHISTAS"),
                            (70, "070 - OUTROS BENEFICIOS ASSISTENCIAIS"),
                            (80, "080 - AUXILIO ALIMENTACAO "),
                            (90, "090 - INDENIZACOES E RESTITUICOES"),
                            (100, "100 - OBRIGACOES PATRONAIS"),
                            (110, "110 - RESUMO"),
                            (500, "500 - FOLHA DE PAGAMENTO"),
                            (510, "510 - ADIANTAMENTO DE 13 SALARIO"),
                            (520, "520 - ADICIONAL DE FERIAS"),
                            (530, "530 - OUTROS VENCIMENTOS"),
                            (540, "540 - OUTRAS DESPESAS VARIAVEIS"),
                            (900, "900 - REPASSES DA FOLHA DO MES"),
                        ],
                        verbose_name="Seção",
                    ),
                ),
                (
                    "type_report",
                    models.IntegerField(
                        choices=[(1, "Empenhos"), (2, "LRF")],
                        default=1,
                        verbose_name="Tipo Relatório",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Natureza"
                    ),
                ),
                (
                    "subelement",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="SubElemento"
                    ),
                ),
                (
                    "creditor",
                    models.IntegerField(blank=True, null=True, verbose_name="Credor"),
                ),
                ("text", models.TextField(verbose_name="Texo")),
                (
                    "transfer_type",
                    models.IntegerField(
                        choices=[
                            (1, "Financeiro"),
                            (2, "Contabil"),
                            (3, "Apenas totalizador Financeiro"),
                            (4, "Apenas totalizador Contabil"),
                            (5, "Não Exibir"),
                        ],
                        verbose_name="Tipo Repasse",
                    ),
                ),
                (
                    "type_formula",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Padrão"), (2, "Cadastro"), (3, "SQL")],
                        null=True,
                        verbose_name="Tipo Formula",
                    ),
                ),
                (
                    "type_by_possession",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Categoria"
                    ),
                ),
                (
                    "formula",
                    models.TextField(blank=True, null=True, verbose_name="Fórmula"),
                ),
                (
                    "exclude_funds",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_exclude_funds",
                        to="gfp.Evento",
                        verbose_name="Excluir Verba",
                    ),
                ),
                (
                    "exclude_job_positions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_exclude_jobs",
                        to="rh.Cargo",
                        verbose_name="Excluir Cargo",
                    ),
                ),
                (
                    "exclude_registration",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_exclude_registration",
                        to="rh.Servidor",
                        verbose_name="Excluir Matricula",
                    ),
                ),
                (
                    "exclude_workplaces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_exclude_workplaces",
                        to="rh.Lotacao",
                        verbose_name="Excluir Lotação",
                    ),
                ),
                (
                    "include_funds",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_include_funds",
                        to="gfp.Evento",
                        verbose_name="Incluir Verba",
                    ),
                ),
                (
                    "include_job_positions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_include_jobs",
                        to="rh.Cargo",
                        verbose_name="Incluir Cargo",
                    ),
                ),
                (
                    "include_registration",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_include_registration",
                        to="rh.Servidor",
                        verbose_name="Incluir Matricula",
                    ),
                ),
                (
                    "include_workplaces",
                    models.ManyToManyField(
                        blank=True,
                        related_name="config_include_workplaces",
                        to="rh.Lotacao",
                        verbose_name="Incluir Lotação",
                    ),
                ),
            ],
            options={
                "ordering": ("section", "subelement"),
            },
        ),
    ]
