# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_auto_20211210_1559"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configreport",
            options={"ordering": ("section", "type_event", "nature", "subelement")},
        ),
        migrations.AlterField(
            model_name="configreport",
            name="section",
            field=models.IntegerField(
                choices=[
                    (10, "010 - APOSENTADOS"),
                    (20, "020 - MILITARES"),
                    (30, "030 - PENSIONISTAS"),
                    (40, "040 - SERVIDORES ATIVOS"),
                    (50, "050 - SENTENCAS JUDICIAIS"),
                    (60, "060 - DESPESAS DE EXERCICIOS ANTERIORES"),
                    (65, "065 - INDENIZACOES E RESTITUICOES TRABALHISTAS"),
                    (70, "070 - OUTROS BENEFICIOS ASSISTENCIAIS"),
                    (80, "080 - AUXILIO ALIMENTACAO"),
                    (90, "090 - INDENIZACOES E RESTITUICOES"),
                    (100, "100 - OBRIGACOES PATRONAIS"),
                    (110, "110 - RESUMO"),
                    (500, "500 - FOLHA DE PAGAMENTO"),
                    (510, "510 - ADIANTAMENTO DE 13 SALARIO"),
                    (520, "520 - ADICIONAL DE FERIAS"),
                    (530, "530 - OUTROS VENCIMENTOS"),
                    (540, "540 - OUTRAS DESPESAS VARIAVEIS"),
                    (900, "900 - REPASSES DA FOLHA DO MES"),
                ],
                verbose_name="Seção",
            ),
        ),
    ]
