# Generated by Django 2.2.13 on 2020-10-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_auto_20170224_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="meta",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Meta opção de voto"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="publication_end",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Fim da publicação"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="publication_start",
            field=models.DateTimeField(
                db_index=True, null=True, verbose_name="Inicio da publicação"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Título da votação"),
        ),
        migrations.CreateModel(
            name="CountedPolls",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counted_poll",
                        to="poll.Poll",
                    ),
                ),
            ],
        ),
    ]
