# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 17:17
from __future__ import unicode_literals

from datetime import datetime, time

from django.db import migrations

from contrib.middleware import get_current_user, set_current_user

set_current_user("athenas")
user = get_current_user()


def forwards_data_migration(apps, schema_editor):
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("+++ Starting Feriado Migration for NonWorkingDay +++")
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

    Feriado = apps.get_model("ponto", "Feriado")
    NonWorkingDay = apps.get_model("usefulday", "NonWorkingDay")
    ParseNonWorkingDay = apps.get_model("usefulday", "ParseNonWorkingDay")

    parse_objs = []

    for count, holiday in enumerate(Feriado.objects.all().order_by("id")):
        print(
            "Starting the migration of the holiday %s - %s - %s"
            % (count + 1, holiday.titulo, holiday.data)
        )

        if holiday.parte_dia == 1:
            start_time = time(8, 0, 0)
            end_time = time(12, 0, 0)
            is_partial = True
        elif holiday.parte_dia == 2:
            start_time = time(14, 0, 0)
            end_time = time(18, 0, 0)
            is_partial = True
        elif holiday.parte_dia == 3:
            start_time = time(18, 0, 0)
            end_time = time(23, 59, 59)
            is_partial = True
        else:
            start_time = time(0)
            end_time = None
            is_partial = False

        dt = holiday.data
        start_date = datetime.combine(dt, start_time)

        if end_time is not None:
            end_date = datetime.combine(dt, end_time)
        else:
            end_date = None

        if holiday.tipo in [4, 5]:
            abrangency = 3 if holiday.localidades is not None else 1
            kind = 2 if holiday.tipo == 4 else 3
        else:
            abrangency = holiday.tipo
            kind = 1

        nonworkingday = NonWorkingDay.objects.create(
            description=holiday.titulo,
            is_partial=is_partial,
            start_date=start_date,
            end_date=end_date,
            abrangency=abrangency,
            kind=kind,
            created_by_id=user.id,
            modified_by_id=user.id,
        )
        if nonworkingday.abrangency == 3:
            if holiday.localidades.all().exists():
                for place in holiday.localidades.all():
                    nonworkingday.places.add(place)
                    parse_objs.append(
                        ParseNonWorkingDay(
                            nonworkingday=nonworkingday,
                            parse_date=nonworkingday.start_date,
                            place=place,
                            is_partial=nonworkingday.is_partial,
                            processed=True,
                            created_by_id=user.id,
                            modified_by_id=user.id,
                        )
                    )
            else:
                parse_objs.append(
                    ParseNonWorkingDay(
                        nonworkingday=nonworkingday,
                        parse_date=nonworkingday.start_date,
                        is_partial=nonworkingday.is_partial,
                        processed=True,
                        created_by_id=user.id,
                        modified_by_id=user.id,
                    )
                )
        else:
            parse_objs.append(
                ParseNonWorkingDay(
                    nonworkingday=nonworkingday,
                    parse_date=nonworkingday.start_date,
                    is_partial=nonworkingday.is_partial,
                    processed=True,
                    created_by_id=user.id,
                    modified_by_id=user.id,
                )
            )

    ParseNonWorkingDay.objects.bulk_create(parse_objs)


def reverse_data_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("usefulday", "0003_parsenonworkingday_is_partial"),
    ]

    operations = [migrations.RunPython(forwards_data_migration, reverse_data_migration)]
