# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usefulday", "0004_feriado_to_nonworkingday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nonworkingday",
            options={"ordering": ("start_date", "abrangency")},
        ),
    ]
