# Generated by Django 2.2.28 on 2025-01-15 10:25
import os
from django.conf import settings
from django.db import migrations
from django.core.management import call_command

FIXTURES = ("fixtures/03-choices_kind.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "common", "usefulday", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("usefulday", "0005_auto_20230112_1053"),
    ]

    operations = [migrations.RunPython(forward, backward)]
