# Generated by Django 2.2.28 on 2025-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulday", "0006_load_fixtures_kind_usefulday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonworkingday",
            name="abrangency",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Nacional"), (2, "Estadual"), (3, "Municipal")],
                null=True,
                verbose_name="Abrangência",
            ),
        ),
        migrations.AlterField(
            model_name="nonworkingday",
            name="kind",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Feriado"),
                    (2, "Ponto Facultativo"),
                    (3, "Suspensão"),
                    (4, "Recesso"),
                ],
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="nonworkingday",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                related_name="nonworkingdays",
                to="rh.Localidade",
                verbose_name="Cidades",
            ),
        ),
    ]
