# Generated by Django 2.2.24 on 2021-08-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("esocial", "0005_auto_20210709_1439"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="previous_event",
        ),
        migrations.AddField(
            model_name="event",
            name="closed_by_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="close_event",
                to="esocial.Event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="modify_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_by_event",
                to="esocial.Event",
            ),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_cod_inc_cp",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_cod_inc_fgts",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_cod_inc_irrf",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_dsc_rubr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_nat_rubr",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s1010",
            name="dados_rubrica_tp_rubr",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.PositiveIntegerField(verbose_name="ID objeto origem")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="esocial.Event",
                    ),
                ),
            ],
            options={
                "unique_together": {("oid", "content_type", "event")},
            },
        ),
    ]
