# Generated by Django 2.2.28 on 2022-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0010_auto_20220425_1102"),
    ]

    operations = [
        migrations.AddField(
            model_name="demonstrativeitem",
            name="oid_rubr",
            field=models.CharField(
                db_index=True, default=1, max_length=32, verbose_name="ID objeto origem"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="control_oid",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=11,
                null=True,
                verbose_name="Controle de OID",
            ),
        ),
        migrations.AlterField(
            model_name="batchevent",
            name="delivery_status",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Criando"),
                    (2, "Aguardando envio"),
                    (201, "Lote recebido com Sucesso"),
                    (202, "Lote recebido com advertências"),
                    (301, "Erro servidor eSocial"),
                    (401, "Lote incorreto - Erro preenchimento"),
                    (402, "Lote incorreto - Schema inválido"),
                    (403, "Lote incorreto - Versão do schema não permitida"),
                    (404, "Lote incorreto - Erro certificado"),
                    (405, "Lote incorreto - Lote nulo ou vazio"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="returnresult",
            name="delivery_status",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Criando"),
                    (2, "Aguardando envio"),
                    (201, "Lote recebido com Sucesso"),
                    (202, "Lote recebido com advertências"),
                    (301, "Erro servidor eSocial"),
                    (401, "Lote incorreto - Erro preenchimento"),
                    (402, "Lote incorreto - Schema inválido"),
                    (403, "Lote incorreto - Versão do schema não permitida"),
                    (404, "Lote incorreto - Erro certificado"),
                    (405, "Lote incorreto - Lote nulo ou vazio"),
                ],
                null=True,
            ),
        ),
    ]
