# Generated by Django 2.2.28 on 2022-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0012_auto_20220713_1550"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="s1200",
            options={"verbose_name": "Remuneração do Trabalhador - RGPS"},
        ),
        migrations.AlterModelOptions(
            name="s1202",
            options={"verbose_name": "Remuneração do Trabalhador - RPPS"},
        ),
        migrations.AlterModelOptions(
            name="s1207",
            options={"verbose_name": "Benefícios - Entes Públicos"},
        ),
        migrations.AddField(
            model_name="batchevent",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arquivado"),
        ),
        migrations.AlterField(
            model_name="demonstrative",
            name="ide_adc",
            field=models.ManyToManyField(
                related_name="demonstrative", to="esocial.IdeAdc"
            ),
        ),
        migrations.AlterField(
            model_name="demonstrative",
            name="info_per_apur_ide_estab_lot",
            field=models.ManyToManyField(
                related_name="demonstrative", to="esocial.IdeEstabLot"
            ),
        ),
        migrations.AlterField(
            model_name="demonstrative1202",
            name="ide_period",
            field=models.ManyToManyField(
                related_name="demonstrative1202", to="esocial.IdePeriod"
            ),
        ),
        migrations.AlterField(
            model_name="demonstrative1202",
            name="info_per_apur_ide_estab_lot",
            field=models.ManyToManyField(
                related_name="demonstrative1202", to="esocial.IdeEstabLot"
            ),
        ),
        migrations.AlterField(
            model_name="demonstrative1207",
            name="ide_period",
            field=models.ManyToManyField(
                related_name="demonstrative1207", to="esocial.IdePeriod1207"
            ),
        ),
        migrations.AlterField(
            model_name="demonstrative1207",
            name="info_per_apur_ide_estab_lot",
            field=models.ManyToManyField(
                related_name="demonstrative1207", to="esocial.IdeEstabLot1207"
            ),
        ),
        migrations.AlterField(
            model_name="ideadc",
            name="ide_period",
            field=models.ManyToManyField(related_name="ideadc", to="esocial.IdePeriod"),
        ),
        migrations.AlterField(
            model_name="ideestablot",
            name="remun_period",
            field=models.ManyToManyField(
                related_name="ideestablot", to="esocial.RemunPeriod"
            ),
        ),
        migrations.AlterField(
            model_name="ideestablot1207",
            name="itens_remun",
            field=models.ManyToManyField(
                related_name="ideestablot1207", to="esocial.DemonstrativeItem"
            ),
        ),
        migrations.AlterField(
            model_name="ideperiod",
            name="info_per_ant_ide_estab_lot",
            field=models.ManyToManyField(
                related_name="ideperiod", to="esocial.IdeEstabLot"
            ),
        ),
        migrations.AlterField(
            model_name="ideperiod1207",
            name="info_per_ant_ide_estab_lot",
            field=models.ManyToManyField(
                related_name="ideperiod1207", to="esocial.IdeEstabLot1207"
            ),
        ),
        migrations.AlterField(
            model_name="remunperiod",
            name="itens_remun",
            field=models.ManyToManyField(
                related_name="remunperiod", to="esocial.DemonstrativeItem"
            ),
        ),
        migrations.AlterField(
            model_name="s1200",
            name="dm_dev",
            field=models.ManyToManyField(
                related_name="s1200", to="esocial.Demonstrative"
            ),
        ),
        migrations.AlterField(
            model_name="s1202",
            name="dm_dev",
            field=models.ManyToManyField(
                related_name="s1202", to="esocial.Demonstrative1202"
            ),
        ),
        migrations.AlterField(
            model_name="s1207",
            name="dm_dev",
            field=models.ManyToManyField(
                related_name="s1207", to="esocial.Demonstrative1207"
            ),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="info_contrato_cod_categ",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="nascimento_dt_nascto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="nascimento_pais_nac",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="nascimento_pais_nascto",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="trabalhador_grau_instr",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="trabalhador_raca_cor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="trabalhador_sexo",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="vinculo_matricula",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="vinculo_tp_reg_prev",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2200",
            name="vinculo_tp_reg_trab",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2205",
            name="dados_trabalhador_grau_instr",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s2205",
            name="dados_trabalhador_pais_nac",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="s2205",
            name="dados_trabalhador_raca_cor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2205",
            name="dados_trabalhador_sexo",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2299",
            name="info_deslig_mtv_deslig",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="nascimento_dt_nascto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="nascimento_pais_nac",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="nascimento_pais_nascto",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="trabalhador_grau_instr",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="trabalhador_raca_cor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2300",
            name="trabalhador_sexo",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2400",
            name="beneficiario_est_civ",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2400",
            name="beneficiario_inc_fis_men",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2400",
            name="beneficiario_raca_cor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2405",
            name="dados_benef_est_civ",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2405",
            name="dados_benef_inc_fis_men",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2405",
            name="dados_benef_nm_benefic",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="s2405",
            name="dados_benef_raca_cor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="s2405",
            name="dados_benef_sexo",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
