# Generated by Django 2.2.28 on 2022-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0013_auto_20220804_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="employee_benefit",
            field=models.ManyToManyField(
                related_name="employeebenefit_esocialconfiguration",
                to="rh.Servidor",
                verbose_name="Matriculas escolhidas em casos de beneficiários com mais de um beneficio",
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="employee_benefit_exclude",
            field=models.ManyToManyField(
                related_name="employebenefitexclude_esocialconfiguration",
                to="rh.Servidor",
                verbose_name="Matriculas excluidas em casos de beneficiários com mais de um beneficio",
            ),
        ),
    ]
