# Generated by Django 2.2.28 on 2022-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0014_auto_20220809_0919"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": (
                    "group",
                    "registry_employee",
                    "registry_person",
                    "start_validity",
                    "acronym",
                    "created_at",
                )
            },
        ),
        migrations.AddField(
            model_name="batchevent",
            name="success_events_cache",
            field=models.BooleanField(default=False, verbose_name="Sucesso"),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemtable",
            name="info",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="Número"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemtable",
            unique_together={("code", "esocial_table", "info")},
        ),
    ]
