# Generated by Django 2.2.28 on 2022-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0015_auto_20221004_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideestablot",
            name="ide_adc",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ide Adc"
            ),
        ),
        migrations.AlterField(
            model_name="ideestablot1207",
            name="ide_adc",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ide Adc"
            ),
        ),
        migrations.AlterField(
            model_name="ideperiod",
            name="ide_adc",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ide Adc"
            ),
        ),
        migrations.AlterField(
            model_name="ideperiod1207",
            name="ide_adc",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ide Adc"
            ),
        ),
    ]
