# Generated by Django 2.2.28 on 2022-12-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0016_auto_20221117_1656"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epi",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("epi_doc_aval", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("exame_dt_exm", models.DateField()),
                ("exame_proc_realizado", models.CharField(max_length=4)),
                (
                    "exame_obs_proc",
                    models.CharField(blank=True, max_length=999, null=True),
                ),
                ("exame_ord_exame", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exame_ind_result",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="HarmfulAgent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ag_noc_cod_ag_noc", models.CharField(max_length=9)),
                (
                    "ag_noc_dsc_ag_noc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ag_noc_tp_aval", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ag_noc_int_conc",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ag_noc_lim_tol",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("ag_noc_un_med", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ag_noc_tec_medicao",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "epc_epi_utiliz_epc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "epc_epi_efic_epc",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epc_epi_utiliz_epi",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "epc_epi_efic_epi",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_med_protecao",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_cond_functo",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_uso_inint",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_prz_valid",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_periodic_troca",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi_compl_higienizacao",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "epi",
                    models.ManyToManyField(
                        related_name="harmfulagent", to="esocial.Epi"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="ResponsibleS2240",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("resp_reg_cpf_resp", models.CharField(max_length=11)),
                ("resp_reg_ide_oc", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resp_reg_dsc_oc",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "resp_reg_nr_oc",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "resp_reg_uf_oc",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "obs_obs_compl",
                    models.CharField(blank=True, max_length=999, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="S2210",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ide_vinculo_cpf_trab", models.CharField(max_length=11)),
                (
                    "ide_vinculo_matricula",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "ide_vinculo_cod_categ",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cat_dt_acid", models.DateField()),
                ("cat_tp_acid", models.PositiveIntegerField()),
                ("cat_hr_acid", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "cat_hrs_trab_antes_acid",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("cat_tp_cat", models.PositiveIntegerField()),
                ("cat_ind_cat_obito", models.CharField(max_length=1)),
                ("cat_dt_obito", models.DateField(blank=True, null=True)),
                ("cat_ind_comun_policia", models.CharField(max_length=1)),
                ("cat_cod_sit_geradora", models.PositiveIntegerField()),
                ("cat_iniciat_cat", models.PositiveIntegerField()),
                (
                    "cat_obs_cat",
                    models.CharField(blank=True, max_length=999, null=True),
                ),
                ("cat_ult_dia_trab", models.DateField(blank=True, null=True)),
                (
                    "cat_houve_afast",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("local_acidente_tp_local", models.PositiveIntegerField()),
                (
                    "local_acidente_dsc_local",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "local_acidente_tp_lograd",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("local_acidente_dsc_lograd", models.CharField(max_length=100)),
                ("local_acidente_nr_lograd", models.CharField(max_length=10)),
                (
                    "local_acidente_complemento",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "local_acidente_bairro",
                    models.CharField(blank=True, max_length=90, null=True),
                ),
                (
                    "local_acidente_cep",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "local_acidente_cod_munic",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "local_acidente_uf",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "local_acidente_pais",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "local_acidente_cod_postal",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "ide_local_acid_tp_insc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ide_local_acid_nr_insc",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("parte_atingida_cod_parte_ating", models.PositiveIntegerField()),
                ("parte_atingida_lateralidade", models.PositiveIntegerField()),
                ("agente_causador_cod_agnt_causador", models.PositiveIntegerField()),
                ("atestado_dt_atendimento", models.DateField()),
                ("atestado_hr_atendimento", models.CharField(max_length=4)),
                ("atestado_ind_internacao", models.CharField(max_length=1)),
                ("atestado_dur_trat", models.PositiveIntegerField()),
                ("atestado_ind_afast", models.CharField(max_length=1)),
                ("atestado_dsc_lesao", models.PositiveIntegerField()),
                (
                    "atestado_dsc_comp_lesao",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "atestado_diag_provavel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("atestado_cod_cid", models.CharField(max_length=4)),
                (
                    "atestado_observacao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emitente_nm_emit", models.CharField(max_length=70)),
                ("emitente_ide_oc", models.PositiveIntegerField()),
                ("emitente_nr_oc", models.CharField(max_length=14)),
                (
                    "emitente_uf_oc",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "cat_origem_nr_rec_cat_orig",
                    models.CharField(blank=True, max_length=23, null=True),
                ),
            ],
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="S2240",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ide_vinculo_cpf_trab", models.CharField(max_length=11)),
                (
                    "ide_vinculo_matricula",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "ide_vinculo_cod_categ",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("info_exp_risco_dt_ini_condicao", models.DateField()),
                (
                    "info_exp_risco_dt_fim_condicao",
                    models.DateField(blank=True, null=True),
                ),
                ("info_amb_local_amb", models.PositiveIntegerField()),
                ("info_amb_dsc_setor", models.CharField(max_length=100)),
                ("info_amb_tp_insc", models.PositiveIntegerField()),
                ("info_amb_nr_insc", models.CharField(max_length=14)),
                ("info_ativ_dsc_ativ_des", models.CharField(max_length=999)),
                (
                    "ag_noc",
                    models.ManyToManyField(
                        related_name="s2240", to="esocial.HarmfulAgent"
                    ),
                ),
                (
                    "resp_reg",
                    models.ManyToManyField(
                        related_name="s2240", to="esocial.ResponsibleS2240"
                    ),
                ),
            ],
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="S2220",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ide_vinculo_cpf_trab", models.CharField(max_length=11)),
                (
                    "ide_vinculo_matricula",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "ide_vinculo_cod_categ",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ex_med_ocup_tp_exame_ocup", models.PositiveIntegerField()),
                ("aso_dt_aso", models.DateField()),
                ("aso_res_aso", models.PositiveIntegerField(blank=True, null=True)),
                ("medico_nm_med", models.CharField(max_length=70)),
                ("medico_nr_crm", models.CharField(max_length=8)),
                ("medico_uf_crm", models.CharField(max_length=2)),
                (
                    "resp_monit_cpf_resp",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "resp_monit_nm_resp",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                (
                    "resp_monit_nr_crm",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "resp_monit_uf_crm",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "exam",
                    models.ManyToManyField(related_name="s2220", to="esocial.Exam"),
                ),
            ],
            bases=("esocial.event",),
        ),
    ]
