# Generated by Django 2.2.28 on 2023-03-24 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models
import os
from django.core.management import call_command

FIXTURES = (
    "fixtures/initialdb_0003_controllers.json",
    "fixtures/choices_acronym_s5012_s5501.json",
)


def up_load_fixtures(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "esocial", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down_load_fixtures(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("esocial", "0017_epi_exam_harmfulagent_responsibles2240_s2210_s2220_s2240"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayCalculatedIrrf",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("per_apur_dia", models.PositiveIntegerField(blank=True, null=True)),
                ("cr_dia", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "vlr_cr_dia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "vlr_cr_dia_susp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoTribute",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("per_ref", models.CharField(max_length=7)),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="MonthlyCalculatedIrrf",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("cr_men", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "vlr_cr_men",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "vlr_cr_men_susp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "apur_dia",
                    models.ManyToManyField(
                        related_name="dmdevinfoir_demonstrativetot",
                        to="esocial.DayCalculatedIrrf",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("month", models.PositiveIntegerField(verbose_name="Mês")),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                ("sent", models.BooleanField(default=False, verbose_name="Enviado")),
                ("closed", models.BooleanField(default=False, verbose_name="Fechado")),
                (
                    "pendency_cache",
                    models.BooleanField(default=False, verbose_name="Pendência"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Arquivado"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-month"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.RenameField(
            model_name="infocrcontrib",
            old_name="info_cr_contrib_tp_cr",
            new_name="tp_cr",
        ),
        migrations.RenameField(
            model_name="infocrcontrib",
            old_name="info_cr_contrib_vr_cr",
            new_name="vr_cr",
        ),
        migrations.RenameField(
            model_name="infocrcontrib",
            old_name="info_cr_contrib_vr_cr_susp",
            new_name="vr_cr_susp",
        ),
        migrations.RenameField(
            model_name="infoirrf",
            old_name="info_ir_tp_valor",
            new_name="tp_info_ir",
        ),
        migrations.RenameField(
            model_name="infoirrf",
            old_name="info_ir_valor",
            new_name="valor",
        ),
        migrations.RenameField(
            model_name="s2299",
            old_name="quarentena_dt_fim_quar",
            new_name="remun_apos_deslig_dt_fim_remun",
        ),
        migrations.RenameField(
            model_name="s2399",
            old_name="remuntr_empr_vlr_remun_oe",
            new_name="desp_proc_jud_vlr_desp_advogados",
        ),
        migrations.RenameField(
            model_name="s2399",
            old_name="remuntr_empr_cod_categ",
            new_name="ide_adv_tp_insc",
        ),
        migrations.RenameField(
            model_name="s2399",
            old_name="remuntr_empr_tp_insc",
            new_name="info_rra_tp_proc_rra",
        ),
        migrations.RemoveField(
            model_name="s2399",
            name="remuntr_empr_nr_insc",
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_bc_cp00_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_bc_cp15_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_bc_cp20_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_bc_cp25_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_susp_bc_cp00_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_susp_bc_cp15_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_susp_bc_cp20_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="basesremun",
            name="bases_cp_vr_susp_bc_cp25_va",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="desp_proc_jud_vlr_desp_advogados",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="desp_proc_jud_vlr_desp_custas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="dm_dev_ind_rra",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="ide_adv_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="ide_adv_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="ide_adv_vlr_adv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_pgto_dt_pgto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_pgto_vr_liq",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_rra_desc_rra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_rra_nr_proc_rra",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_rra_qtd_meses_rra",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="info_rra_tp_proc_rra",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative",
            name="rra",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="RRA"
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="desp_proc_jud_vlr_desp_advogados",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="desp_proc_jud_vlr_desp_custas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="dm_dev_ind_rra",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="ide_adv_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="ide_adv_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="ide_adv_vlr_adv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_pgto_dt_pgto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_pgto_vr_liq",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_rra_desc_rra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_rra_nr_proc_rra",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_rra_qtd_meses_rra",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="info_rra_tp_proc_rra",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="rra",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="RRA"
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="desp_proc_jud_vlr_desp_advogados",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="desp_proc_jud_vlr_desp_custas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="dm_dev_ind_rra",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="ide_adv_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="ide_adv_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="ide_adv_vlr_adv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_pgto_dt_pgto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_pgto_vr_liq",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_rra_desc_rra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_rra_nr_proc_rra",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_rra_qtd_meses_rra",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="info_rra_tp_proc_rra",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="rra",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="RRA"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="batch_cache",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="modified_by_event_cache",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ideestablot5011",
            name="info_estab_cnpj_resp",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_bairro",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_cidade",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_cod_postal",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_complem",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_dsc_lograd",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_estado",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_end_nr_lograd",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="end_ext_telef",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="info_pgto_ext_frm_tribut",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="info_pgto_ext_ind_nif",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="infopgto",
            name="info_pgto_ext_nif_benef",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s1210",
            name="info_pgto_pais_resid_ext",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="s1299",
            name="info_fech_evt_pgtos",
            field=models.CharField(default="S", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="s2299",
            name="desp_proc_jud_vlr_desp_advogados",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="desp_proc_jud_vlr_desp_custas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="dm_dev_ind_rra",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_adv_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_adv_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_adv_vlr_adv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_rra_desc_rra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_rra_nr_proc_rra",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_rra_qtd_meses_rra",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_rra_tp_proc_rra",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="remun_apos_deslig_ind_remun",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="desp_proc_jud_vlr_desp_custas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2399",
            name="dm_dev_ind_rra",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="ide_adv_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="ide_adv_vlr_adv",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2399",
            name="info_rra_desc_rra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="info_rra_nr_proc_rra",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="info_rra_qtd_meses_rra",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_apos_term_dt_fim_remun",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_apos_term_ind_remun",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_outr_empr_cod_categ",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_outr_empr_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_outr_empr_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="remun_outr_empr_vlr_remun_oe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s5011",
            name="info_pj_ind_trib_folha_pis_cofins",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="s2399",
            name="ide_estab_lot_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.CreateModel(
            name="S5501",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ide_evento_nr_rec_arq_base", models.CharField(max_length=23)),
                ("ide_proc_nr_proc_trab", models.CharField(max_length=20)),
                ("ide_proc_per_apur", models.CharField(max_length=7)),
                (
                    "event_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventconnection_s5501",
                        to="esocial.Event",
                    ),
                ),
                (
                    "info_tributos",
                    models.ManyToManyField(
                        related_name="infotributos_s5501", to="esocial.InfoTribute"
                    ),
                ),
            ],
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="S5012",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_irrf_nr_rec_arq_base", models.CharField(max_length=23)),
                ("info_irrf_ind_exist_info", models.PositiveIntegerField()),
                (
                    "event_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventconnection_s5012",
                        to="esocial.Event",
                    ),
                ),
                (
                    "tot_apur_men",
                    models.ManyToManyField(
                        related_name="S5012", to="esocial.MonthlyCalculatedIrrf"
                    ),
                ),
            ],
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="PendencyPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("type_pendency", models.PositiveSmallIntegerField(default=1)),
                ("resume", models.CharField(max_length=256, verbose_name="Problema")),
                ("text", models.TextField(verbose_name="Texto")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendencyperiod",
                        to="esocial.Event",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendencies",
                        to="esocial.PayrollPeriod",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="s1298",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrollperiod_s1298",
                to="esocial.Event",
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="s1299",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrollperiod_s1299",
                to="esocial.Event",
            ),
        ),
        migrations.AddField(
            model_name="infotribute",
            name="info_cr_contrib",
            field=models.ManyToManyField(
                related_name="info_cr_contrib_s5501", to="esocial.InfoCRContrib"
            ),
        ),
        migrations.AddField(
            model_name="infotribute",
            name="info_cr_irrf",
            field=models.ManyToManyField(
                related_name="info_cr_irrf_s5501", to="esocial.InfoCRContrib"
            ),
        ),
        migrations.AddField(
            model_name="demonstrativetot",
            name="tot_apur_men",
            field=models.ManyToManyField(
                related_name="dmdevinfoir_demonstrativetot",
                to="esocial.MonthlyCalculatedIrrf",
            ),
        ),
        migrations.RunPython(up_load_fixtures, down_load_fixtures),
    ]
