# Generated by Django 2.2.28 on 2023-06-16 19:50

from django.conf import settings
from django.db import migrations, models
import os
from django.core.management import call_command

FIXTURES = (
    #'fixtures/initialdb_0004_itemtable.json',
    #'fixtures/acronym_update.json',
)


def up_load_fixtures(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "esocial", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down_load_fixtures(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0018_auto_20230324_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s5012",
            name="tot_apur_men",
            field=models.ManyToManyField(
                related_name="s5012", to="esocial.MonthlyCalculatedIrrf"
            ),
        ),
        migrations.RunPython(up_load_fixtures, down_load_fixtures),
    ]
