# Generated by Django 2.2.28 on 2024-01-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0019_auto_20230616_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedBenfPen",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("benef_pen_cpf_dep", models.CharField(max_length=11)),
                (
                    "benef_pen_vlr_depen_susp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="DedDependente",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ded_depen_tp_rend", models.PositiveIntegerField()),
                ("ded_depen_cpf_dep", models.CharField(max_length=11)),
                (
                    "ded_depen_vlr_ded_dep",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="DedPenAlim",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("pen_alim_tp_rend", models.PositiveIntegerField()),
                ("pen_alim_cpf_dep", models.CharField(max_length=11)),
                (
                    "pen_alim_vlr_ded_pen_alim",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="DedSuspProcRet",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("ded_susp_ind_tp_deducao", models.PositiveIntegerField()),
                (
                    "ded_susp_vlr_ded_susp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "ded_susp_cnpj_entid_pc",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "ded_susp_vlr_patroc_funp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "ded_susp_benf_pen",
                    models.ManyToManyField(
                        related_name="dedsuspprocret", to="esocial.DedBenfPen"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoDepSau",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_dep_sau_cpf_dep", models.CharField(max_length=11)),
                (
                    "info_dep_sau_vlr_saude_dep",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfodetReembTit",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("det_reemb_tit_tp_insc", models.PositiveIntegerField()),
                ("det_reemb_tit_nr_insc", models.CharField(max_length=14)),
                (
                    "det_reemb_tit_vlr_reemb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "det_reemb_tit_vlr_reemb_ant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoIRDepedente",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_dep_cpf_dep", models.CharField(max_length=11)),
                ("info_dep_dt_nascto", models.DateField()),
                ("info_dep_nome", models.CharField(max_length=70)),
                (
                    "info_dep_dep_irrf",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "info_dep_tp_dep",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "info_dep_descr_dep",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoIRPrevidCompl",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("previd_compl_tp_prev", models.PositiveIntegerField()),
                ("previd_compl_cnpj_entid_pc", models.CharField(max_length=14)),
                (
                    "previd_compl_vlr_ded_pc",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "previd_compl_vlr_patroc_funp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoValoresProcRet",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                (
                    "info_valores_vlr_n_retido",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "info_valores_vlr_dep_jud",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "info_valores_vlr_cmp_ano_cal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "info_valores_vlr_cmp_ano_ant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "info_valores_vlr_rend_susp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.RemoveField(
            model_name="daycalculatedirrf",
            name="vlr_cr_dia_susp",
        ),
        migrations.RemoveField(
            model_name="monthlycalculatedirrf",
            name="vlr_cr_men_susp",
        ),
        migrations.RemoveField(
            model_name="s2200",
            name="hor_contratual_dsc_tp_jorn",
        ),
        migrations.AddField(
            model_name="dependent",
            name="dependente_descr_dep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="harmfulagent",
            name="ag_noc_nr_proc_jud",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="aprend_cnpj_ent_qual",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="aprend_cnpj_prat",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="aprend_ind_aprend",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="hor_contratual_dsc_jorn",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="hor_contratual_hor_noturno",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s2200",
            name="info_celetista_mat_anot_jud",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s2206",
            name="aprend_cnpj_ent_qual",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2206",
            name="aprend_cnpj_prat",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2206",
            name="aprend_ind_aprend",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_deslig_ind_pdv",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="info_mand_elet_categ_orig",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="info_mand_elet_cnpj_orig",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="info_mand_elet_dt_exerc_orig",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="info_mand_elet_matric_orig",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="local_trab_geral_desc_comp",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="local_trab_geral_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2300",
            name="local_trab_geral_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2306",
            name="local_trab_geral_desc_comp",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="s2306",
            name="local_trab_geral_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2306",
            name="local_trab_geral_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InfoReembMed",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_reemb_med_ind_org_reemb", models.PositiveIntegerField()),
                ("info_reemb_med_cnpj_oper", models.CharField(max_length=14)),
                ("info_reemb_med_reg_ans", models.CharField(max_length=6)),
                (
                    "info_reemb_dep_cpf_benef",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "info_det_reemb_tit",
                    models.ManyToManyField(
                        related_name="inforeembmed", to="esocial.InfodetReembTit"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoPlanSaude",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("plan_saude_cnpj_oper", models.CharField(max_length=14)),
                ("plan_saude_reg_ans", models.CharField(max_length=6)),
                (
                    "plan_saude_vlr_saude_tit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "info_dep_saude",
                    models.ManyToManyField(
                        related_name="infoplansaude", to="esocial.InfoDepSau"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoIRProcRet",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_proc_ret_tp_proc_ret", models.PositiveIntegerField()),
                ("info_proc_ret_nr_proc_ret", models.CharField(max_length=21)),
                (
                    "info_proc_ret_cod_susp",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ded_susp_proc_ret",
                    models.ManyToManyField(
                        related_name="infoirprocret", to="esocial.DedSuspProcRet"
                    ),
                ),
                (
                    "info_valores_proc_ret",
                    models.ManyToManyField(
                        related_name="infoirprocret", to="esocial.InfoValoresProcRet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoIrCr",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                (
                    "info_ircr_tp_cr",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "ded_dependente",
                    models.ManyToManyField(
                        related_name="infoircr", to="esocial.DedDependente"
                    ),
                ),
                (
                    "ded_pen_alim",
                    models.ManyToManyField(
                        related_name="infoircr", to="esocial.DedPenAlim"
                    ),
                ),
                (
                    "info_ir_previd_compl",
                    models.ManyToManyField(
                        related_name="infoircr", to="esocial.InfoIRPrevidCompl"
                    ),
                ),
                (
                    "info_ir_proc_ret",
                    models.ManyToManyField(
                        related_name="infoircr", to="esocial.InfoIRProcRet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.CreateModel(
            name="InfoIrComplemen",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="esocial.Event",
                    ),
                ),
                ("info_ir_complem_dt_laudo", models.DateField(blank=True, null=True)),
                (
                    "info_ir_cr",
                    models.ManyToManyField(
                        related_name="infoircomplem", to="esocial.InfoIrCr"
                    ),
                ),
                (
                    "info_ir_dependente",
                    models.ManyToManyField(
                        related_name="infoircomplem", to="esocial.InfoIRDepedente"
                    ),
                ),
                (
                    "info_ir_remb_med",
                    models.ManyToManyField(
                        related_name="infoircomplem", to="esocial.InfoReembMed"
                    ),
                ),
                (
                    "info_plan_saude",
                    models.ManyToManyField(
                        related_name="infoircomplem", to="esocial.InfoPlanSaude"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("esocial.event",),
        ),
        migrations.AddField(
            model_name="s1210",
            name="info_ir_complemen",
            field=models.ManyToManyField(
                related_name="info_ir_complemen_s1210", to="esocial.InfoIrComplemen"
            ),
        ),
    ]
