# Generated by Django 2.2.28 on 2024-09-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("esocial", "0020_auto_20240118_0952"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="certificado_a1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuration_certificado_a1",
                to="ged.Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="certificado_cas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuration_certificado_cas",
                to="ged.Arquivo",
            ),
        ),
    ]
