# Generated by Django 2.2.28 on 2024-12-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0021_auto_20240916_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="s1010",
            name="dados_rubrica_cod_inc_pis_pasep",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="s1010",
            name="ide_processo_pis_pasep",
            field=models.ManyToManyField(
                related_name="ide_processo_pis_pasep_S1010", to="esocial.IdeProcesso"
            ),
        ),
        migrations.AddField(
            model_name="s1200",
            name="info_interm_dia",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s1200",
            name="info_interm_hrs_trab",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
