# Generated by Django 2.2.28 on 2024-12-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0022_auto_20241202_1924"),
    ]

    operations = [
        migrations.RenameField(
            model_name="s5011",
            old_name="info_pj_ind_trib_folha_pis_cofins",
            new_name="info_pj_ind_trib_folha_pis_pasep",
        ),
        migrations.AddField(
            model_name="demonstrativeitem",
            name="desc_folha_inst_financ",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="demonstrativeitem",
            name="desc_folha_nr_doc",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="demonstrativeitem",
            name="desc_folha_observacao",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="demonstrativeitem",
            name="desc_folha_tp_desc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="infoircomplemen",
            name="per_ant_nr_rec1210_orig",
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AddField(
            model_name="infoircomplemen",
            name="per_ant_per_ref_ajuste",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="infoirprevidcompl",
            name="previd_compl_vlr_ded_pc13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="infoirprevidcompl",
            name="previd_compl_vlr_patroc_funp13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="infoirrf",
            name="info_ir_desc_rendimento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_base_pis_pasep_ind13",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_base_pis_pasep_tp_valor_pis_pasep",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_base_pis_pasep_valor_pis_pasep",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_categ_pis_pasep_cod_categ",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_categ_pis_pasep_matricula",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s5001",
            name="info_interm_hrs_trab",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="s5011",
            name="bases_pis_pasep_vr_bc_pis_pasep",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s5011",
            name="bases_pis_pasep_vr_bc_pis_pasep_susp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="infoirprevidcompl",
            name="previd_compl_vlr_ded_pc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
