# Generated by Django 2.2.28 on 2024-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0023_auto_20241203_1822"),
    ]

    operations = [
        migrations.AddField(
            model_name="s2299",
            name="desc_folha_inst_financ",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="desc_folha_nr_doc",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="desc_folha_observacao",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="desc_folha_tp_desc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="info_interm_hrs_trab",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="desc_folha_inst_financ",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="desc_folha_nr_doc",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="desc_folha_observacao",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="s2399",
            name="desc_folha_tp_desc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
