# Generated by Django 2.2.28 on 2024-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0024_auto_20241205_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_cod_rubr",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_fator_rubr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_ide_tab_rubr",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_ind_apur_ir",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_qtd_rubr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_estab_lot_det_verbas_vr_rubr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_periodo_ide_estab_lot_cod_lotacao",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_periodo_ide_estab_lot_nr_insc",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="s2299",
            name="ide_periodo_ide_estab_lot_tp_insc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
