# Generated by Django 2.2.28 on 2025-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0026_auto_20250123_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="demonstrative1202",
            name="cod_susp",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Código do indicativo da suspensão, atribuído pelo empregador em S-1070",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="nr_proc_ret",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=21,
                null=True,
                verbose_name="Preencher com o código correspondente ao tipo de processo",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="tp_proc_ret",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Preencher com o código correspondente ao tipo de processo",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1202",
            name="vlr_rend_susp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="cod_susp",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Código do indicativo da suspensão, atribuído pelo empregador em S-1070",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="nr_proc_ret",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=21,
                null=True,
                verbose_name="Preencher com o código correspondente ao tipo de processo",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="tp_proc_ret",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Preencher com o código correspondente ao tipo de processo",
            ),
        ),
        migrations.AddField(
            model_name="demonstrative1207",
            name="vlr_rend_susp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
