# Generated by Django 4.2 on 2025-02-26 17:33
from django.conf import settings
from django.db import migrations
from django.core.management import call_command
import os


FIXTURES = ("fixtures/config_dias_evento_afastamento.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "esocial", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0027_auto_20250124_1948"),
    ]
    operations = [migrations.RunPython(forward, backward)]
