# -*- coding: utf-8 -*-

FPSFPASEP = {
    "fps900-1": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "04.1",
            "lenght": 228,
        },
        1: {"label": "type_registro", "value": 1, "size": 1, "type": "N"},
        2: {"label": "nome_arquivo", "value": "FPSF900", "size": 7, "type": "A"},
        3: {"label": "data_geracao", "value": 0, "size": 8, "type": "N"},
        4: {"label": "cnpj_entidade", "value": 0, "size": 14, "type": "N"},
        5: {"label": "numero_remessa", "value": 0, "size": 6, "type": "N"},
        6: {"label": "agencia_controle", "value": 0, "size": 4, "type": "N"},
        7: {"label": "digito_agencia_controle", "value": "", "size": 1, "type": "A"},
        8: {"label": "data_pagamento", "value": 0, "size": 8, "type": "N"},
        9: {"label": "numero_convenio", "value": 0, "size": 6, "type": "N"},
        10: {"label": "codigo_repasse", "value": 1, "size": 1, "type": "N"},
        11: {"label": "agencia_lancamento", "value": 0, "size": 4, "type": "N"},
        12: {"label": "digito_agencia_lancamento", "value": "", "size": 1, "type": "A"},
        13: {"label": "conta_lancamento", "value": 0, "size": 11, "type": "N"},
        14: {"label": "digito_conta_lancamento", "value": "", "size": 1, "type": "A"},
        15: {"label": "codigo_lancamento_gru", "value": 0, "size": 14, "type": "N"},
        16: {"label": "codigo_banco", "value": 0, "size": 3, "type": "N"},
        17: {"label": "digito_banco", "value": "", "size": 1, "type": "A"},
        18: {"label": "filler1", "value": "", "size": 14, "type": "A"},
        19: {"label": "email", "value": "", "size": 80, "type": "A"},
        20: {"label": "filler2", "value": "", "size": 43, "type": "A"},
    },
    "fps900-2": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "04.1",
            "lenght": 228,
        },
        1: {"label": "type_registro", "value": 2, "size": 1, "type": "N"},
        2: {"label": "pasep", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 50, "type": "A"},
        4: {"label": "matricula", "value": "", "size": 15, "type": "A"},
        5: {"label": "endereco", "value": "", "size": 50, "type": "A"},
        6: {"label": "numero", "value": 0, "size": 5, "type": "N"},
        7: {"label": "complemento", "value": "", "size": 15, "type": "A"},
        8: {"label": "bairro", "value": "", "size": 30, "type": "A"},
        9: {"label": "municipio", "value": "", "size": 30, "type": "A"},
        10: {"label": "uf", "value": "", "size": 2, "type": "A"},
        11: {"label": "cep", "value": 0, "size": 8, "type": "N"},
        12: {"label": "filler1", "value": "", "size": 11, "type": "A"},
    },
    "fps900-9": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "04.1",
            "lenght": 228,
        },
        1: {"label": "type_registro", "value": 9, "size": 1, "type": "N"},
        2: {"label": "filler1", "value": "", "size": 221, "type": "A"},
        3: {"label": "total", "value": 0, "size": 6, "type": "N"},
    },
}
