# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dirf", "0016_auto_20210127_1026"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demonstrativo",
            options={"ordering": ("declaracao", "-version")},
        ),
    ]
