# Generated by Django 2.2.17 on 2020-12-15 18:13

from django.db import migrations


def recreate_journal_urls(apps, schema):

    from common.official_journal.models import Journal

    qs = Journal.objects.all()
    total = qs.count()
    index = 0
    message = ""
    errors = ""
    for j in qs:
        try:
            j.save()
            index += 1
            message = f"{index} de {total} diários"
            print(message, end="")
        except Exception as e:
            print(f"Erro: {e}", end="")


class Migration(migrations.Migration):

    dependencies = [
        ("official_journal", "0002_auto_20190502_1444"),
    ]

    operations = [
        migrations.RunPython(
            recreate_journal_urls, reverse_code=migrations.RunPython.noop
        ),
    ]
