# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_auto_20160818_0806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "not send"),
                    (2, "send"),
                    (4, "send error"),
                    (8, "received"),
                    (16, "abandoned"),
                ],
                default=2,
                verbose_name="Status of Notification",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("SYS", "System"),
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("ONTOP", "On top"),
                ],
                default="SYS",
                max_length=10,
                verbose_name="Type of Notification",
            ),
        ),
    ]
