# Generated by Django 2.2.20 on 2021-07-07 09:02
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import os

FIXTURES = (
    "pvf/fixtures/choices.json",
    "pvf/fixtures/initialdb_0001_controllers.json",
    #'pvf/fixtures/initialdb_0002_groups.json'
)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0136_auto_20210405_1457"),
        ("dayoff", "0009_auto_20210309_2024"),
        ("afastamento", "0016_auto_20210304_1044"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.IntegerField(
                        choices=[
                            (1, "Programação"),
                            (2, "Ausência"),
                            (3, "Documento"),
                            (4, "Alteração Jornada"),
                        ],
                        verbose_name="Tipo de Solicitação",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da Solicitação")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Aguardando Ciência do Substituto"),
                            (2, "Aguardando Aprovador"),
                            (3, "Aguardando Efetivação"),
                            (4, "Efetivado"),
                            (5, "Indeferido"),
                        ],
                        default=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "step_current",
                    models.IntegerField(
                        choices=[
                            (1, "Aprovador"),
                            (2, "DG"),
                            (3, "Asessoria Corregedoria"),
                            (4, "Corregedoria"),
                            (5, "PGJ"),
                            (7, "DGP"),
                        ],
                        default=1,
                        verbose_name="Etapa Atual",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="portal_request_approver_current",
                        to="rh.Servidor",
                        verbose_name="Aprovador Atual",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="portal_request_employee",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="portal_request_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PortalRequestDoc",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "Certidão para fins previdenciários"),
                            (2, "Certidão para fins bancários"),
                        ],
                        verbose_name="Documento",
                    ),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
        migrations.CreateModel(
            name="PortalRequestWorkload",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Data início")),
                (
                    "from_workload",
                    models.IntegerField(verbose_name="da carga de horária"),
                ),
                (
                    "to_workload",
                    models.IntegerField(verbose_name="para carga de horária"),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
        migrations.CreateModel(
            name="PortalRequestSubstitute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data início")),
                ("end_date", models.DateField(verbose_name="Data Fim")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="request_exercise",
                        to="rh.ServidorLotacao",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="request_local",
                        to="rh.Lotacao",
                    ),
                ),
                (
                    "portal_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_request_substitute",
                        to="pvf.PortalRequest",
                        verbose_name="Solicitação",
                    ),
                ),
                (
                    "provision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="request_provision",
                        to="rh.MovimentacaoPosse",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="request_substitute",
                        to="rh.Servidor",
                        verbose_name="Substituto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalRequestHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da ação")),
                (
                    "group",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Grupo"
                    ),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (1, "Solicitação"),
                            (2, "Deferir"),
                            (3, "Indeferir"),
                            (4, "Ciência"),
                            (5, "Anotação"),
                            (6, "Efetivação"),
                        ],
                        verbose_name="Ação Realizada",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "portal_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pvf.PortalRequest",
                        verbose_name="Solicitação",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="portal_request_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalRequestUsufruct",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "activity",
                    models.ManyToManyField(
                        related_name="activity_requests",
                        to="dayoff.Activity",
                        verbose_name="Atividade",
                    ),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
        migrations.CreateModel(
            name="PortalRequestAbsence",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "absence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="portal_request_absence",
                        to="afastamento.BaseLicencaAfastamento",
                    ),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
        migrations.RunPython(up, down),
    ]
