# Generated by Django 2.2.20 on 2021-08-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dayoff", "0011_auto_20210715_1935"),
        ("pvf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalRetificationSchedule",
            fields=[
                (
                    "portalrequestusufruct_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestUsufruct",
                    ),
                ),
            ],
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.AlterModelOptions(
            name="portalrequest",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="portalrequesthistory",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                ],
                verbose_name="Tipo de Solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando Ciência do Substituto"),
                    (2, "Aguardando Aprovador"),
                    (3, "Aguardando Efetivação"),
                    (4, "Efetivado"),
                    (5, "Indeferido"),
                    (6, "Cancelado DGP"),
                    (7, "Cancelado Solicitante"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="step_current",
            field=models.IntegerField(
                choices=[
                    (1, "Aprovador"),
                    (2, "DG"),
                    (3, "Asessoria Corregedoria"),
                    (4, "Corregedoria"),
                    (5, "PGJ"),
                    (7, "DGP"),
                ],
                verbose_name="Etapa Atual",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequesthistory",
            name="action",
            field=models.IntegerField(
                choices=[
                    (1, "Solicitação"),
                    (2, "Deferir"),
                    (3, "Indeferir"),
                    (4, "Ciência"),
                    (5, "Anotação"),
                    (6, "Efetivação"),
                    (7, "Cancelado"),
                ],
                verbose_name="Ação Realizada",
            ),
        ),
        migrations.CreateModel(
            name="PortalCancelSchedule",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "usufruct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cancel_usufruct",
                        to="dayoff.Usufruct",
                        verbose_name="Usufruto",
                    ),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
    ]
