# Generated by Django 2.2.20 on 2021-09-08 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0002_auto_20210812_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalrequestabsence",
            name="days",
            field=models.IntegerField(default=0, verbose_name="Quantidade de dias"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portalrequestabsence",
            name="end_date",
            field=models.DateField(
                db_index=True, default=None, verbose_name="Data Fim"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portalrequestabsence",
            name="start_date",
            field=models.DateField(
                db_index=True, default=None, verbose_name="Data Início"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portalrequestabsence",
            name="type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "BaseLicencaAfastamento"),
                    (2, "Afastamento"),
                    (3, "Licenca"),
                    (4, "Ausencia"),
                    (5, "FeriasAfastamento"),
                    (6, "Viagem"),
                    (7, "Recesso"),
                    (8, "LicencaSaude"),
                    (9, "LicencaSaude3Dias"),
                    (10, "LicencaSaudeJuntaMedica"),
                    (11, "LicencaDoencaPessoaFamilia"),
                    (12, "LicencaMaternidade"),
                    (13, "LicencaAdocao"),
                    (14, "LicencaAfastamentoConjuge"),
                    (15, "LicencaServicoMilitar"),
                    (16, "LicencaAtividadePolitica"),
                    (17, "LicencaCapacitacao"),
                    (18, "LicencaInteresseParticular"),
                    (19, "LicencaMandatoClassista"),
                    (20, "AfastamentoOutroOrgao"),
                    (21, "AfastamentoMandatoEletivo"),
                    (22, "AfastamentoEstudar"),
                    (23, "AfastamentoMissao"),
                    (24, "AfastamentoEleitoral"),
                    (25, "AfastamentoServirJuri"),
                    (26, "AfastamentoTreinamento"),
                    (27, "AfastamentoDeslocamento"),
                    (28, "AfastamentoCompeticao"),
                    (29, "AfastamentoCursoConcurso"),
                    (30, "AfastamentoPrisao"),
                    (31, "AusenciaDoacaoSangue"),
                    (32, "AusenciaEleitor"),
                    (33, "AusenciaCasamento"),
                    (34, "AusenciaNascimento"),
                    (35, "AusenciaFalecimento"),
                    (36, "AusenciaConclusao"),
                    (37, "LicencaSaude30Dias"),
                    (38, "FolgaEleitoral"),
                    (39, "AtuacaoGrupoTrabalho"),
                    (40, "DesempenhoFuncao"),
                    (41, "Plantao"),
                    (42, "FolgaCompensacao"),
                    (43, "FolgaAniversario"),
                    (44, "AfastamentoSuspensao"),
                    (45, "AfastamentoComparecimentoJuizo"),
                    (46, "AfastamentoDisponibilidade"),
                    (47, "BancoDeHoras"),
                    (48, "UsufrutoPrevencaoSaude"),
                    (59, "AwardLicense"),
                ],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="portalcancelschedule",
            name="usufruct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancel_usufruct",
                to="dayoff.Usufruct",
                verbose_name="Usufruto",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portal_request_approver_current",
                to="rh.Servidor",
                verbose_name="Aprovador Atual",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_request_employee",
                to="rh.Servidor",
                verbose_name="Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_request_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                ],
                verbose_name="Tipo de Solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestabsence",
            name="absence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_request_absence",
                to="afastamento.BaseLicencaAfastamento",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequesthistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_request_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestsubstitute",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_exercise",
                to="rh.ServidorLotacao",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestsubstitute",
            name="local",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_local",
                to="rh.Lotacao",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestsubstitute",
            name="provision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_provision",
                to="rh.MovimentacaoPosse",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestsubstitute",
            name="substitute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_substitute",
                to="rh.Servidor",
                verbose_name="Substituto",
            ),
        ),
    ]
