# Generated by Django 2.2.20 on 2021-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0003_auto_20210908_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalrequestusufruct",
            name="parcel_number",
            field=models.IntegerField(
                blank=True,
                choices=[(2, "2 "), (3, "3"), (4, "4")],
                null=True,
                verbose_name="Número de Parcelas",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                ],
                verbose_name="Tipo de Solicitação",
            ),
        ),
    ]
