# Generated by Django 2.2.20 on 2021-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0004_auto_20210916_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalrequest",
            name="step_current",
            field=models.IntegerField(
                choices=[
                    (1, "Aprovador"),
                    (2, "DG"),
                    (3, "Assessoria da Corregedoria"),
                    (4, "Corregedoria"),
                    (5, "PGJ"),
                    (7, "DGP"),
                ],
                verbose_name="Etapa Atual",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequesthistory",
            name="date",
            field=models.DateTimeField(verbose_name="Data da ação"),
        ),
    ]
