# Generated by Django 2.2.24 on 2021-10-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0005_auto_20210922_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalrequest",
            name="step_current",
            field=models.IntegerField(
                choices=[
                    (1, "Aprovador"),
                    (2, "DG"),
                    (3, "Assessoria da Corregedoria"),
                    (4, "Corregedoria"),
                    (5, "PGJ"),
                    (7, "DGP"),
                ],
                verbose_name="Etapa Atual",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestsubstitute",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_local",
                to="rh.Lotacao",
            ),
        ),
    ]
