# Generated by Django 2.2.28 on 2022-10-19 16:51

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.core.management import call_command
import os

FIXTURES = (
    "pvf/fixtures/initialdb_0002_controllers.json",
    "pvf/fixtures/type_shift_choices.json",
)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        (
            "pvf",
            "0008_marktelework_pointjustification_sendingtelework_sendingtimesheet",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_shift", models.IntegerField(verbose_name="Tipo")),
                (
                    "days",
                    models.PositiveIntegerField(verbose_name="Quantidade de dias"),
                ),
                ("start_date", models.DateField(verbose_name="Data Início")),
                ("end_date", models.DateField(verbose_name="Data Fim")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_employee",
                        to="rh.Servidor",
                        verbose_name="Plantonista",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_owner",
                        to="rh.Servidor",
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_workplace",
                        to="rh.Lotacao",
                        verbose_name="Lotação",
                    ),
                ),
            ],
        ),
        migrations.RunPython(up, down),
    ]
