# Generated by Django 2.2.28 on 2022-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0009_auto_20221019_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointjustification",
            name="number_hours",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
