# Generated by Django 2.2.28 on 2022-11-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0010_auto_20221025_1048"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApproveServerDuty",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="server_duty",
                        to="pvf.ShiftManager",
                        verbose_name="Plantão",
                    ),
                ),
            ],
            bases=("pvf.portalrequest",),
        ),
    ]
