# Generated by Django 2.2.28 on 2022-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0011_auto_20221103_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="PSPendencies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_report",
                    models.IntegerField(
                        choices=[(1, "Saldo Negativo"), (2, "Faltas não justificadas")],
                        verbose_name="Tipo relatório",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=7, verbose_name="Referência"),
                ),
                (
                    "enrollment",
                    models.CharField(max_length=20, verbose_name="Matricula"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nome")),
                (
                    "balance_negative",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Negativo Mês"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Data")),
            ],
        )
    ]
