# Generated by Django 2.2.28 on 2022-12-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0012_auto_20221213_2106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pspendencies",
            name="balance_negative",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Total Negativo Mês"
            ),
        ),
    ]
