# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0013_auto_20221214_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marktelework",
            name="mark_situation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Alcançada"),
                    (2, "Parcialmente Alcançada"),
                    (3, "Não Alcançada"),
                ],
                null=True,
                verbose_name="Situação da Meta",
            ),
        ),
        migrations.AlterField(
            model_name="pointjustification",
            name="reason_type",
            field=models.IntegerField(
                choices=[
                    (1, "Informar Falta (Somente para dispensados do ponto)"),
                    (2, "Abono por Chefia"),
                    (3, "Consulta profissional de saúde (Menos de um dia)"),
                    (4, "Esquecimento no registro ponto"),
                    (5, "Registro em duplicidade"),
                    (6, "Relógio ponto inoperante"),
                    (7, "Compensado durante o mês"),
                    (8, "A ser compensado no mês subsequente"),
                    (9, "Suspensão de expediente Detetização/Desinfecção Covid"),
                    (10, "Férias (Somente para cedidos)"),
                    (11, "Licença prêmio  (Somente para cedidos)"),
                    (12, "Afastamentos  (Somente para cedidos)"),
                    (13, "Licença Médica  (Somente para cedidos)"),
                    (14, "Convocado por Chefia Imediata"),
                    (15, "Compensado por Convocação Chefia Imediata"),
                    (16, "Dispensa de ponto"),
                    (17, "Teletrabalho"),
                    (18, "Outros"),
                    (19, "Doação de Sangue"),
                    (20, "Folga Aniversário(Doador Regular/Medula)"),
                ],
                verbose_name="Motivo",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                    (7, "Teletrabalho"),
                    (8, "Confirmação de realização do plantão"),
                    (12, "Folha Ponto"),
                ],
                verbose_name="Tipo de Solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando Ciência do Substituto"),
                    (2, "Aguardando Aprovador"),
                    (3, "Aguardando Efetivação"),
                    (4, "Efetivado"),
                    (5, "Indeferido"),
                    (6, "Cancelado DGP"),
                    (7, "Cancelado Solicitante"),
                    (8, "Aguardando Assessoria da Corregedoria"),
                    (9, "Aguadando Envio"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="step_current",
            field=models.IntegerField(
                choices=[
                    (1, "Aprovador"),
                    (2, "DG"),
                    (3, "Assessoria da Corregedoria"),
                    (4, "Corregedoria"),
                    (5, "PGJ"),
                    (7, "DGP"),
                    (8, "-"),
                ],
                verbose_name="Etapa Atual",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequesthistory",
            name="action",
            field=models.IntegerField(
                choices=[
                    (1, "Solicitação"),
                    (2, "Deferido"),
                    (3, "Indeferido"),
                    (4, "Ciência"),
                    (5, "Anotação"),
                    (6, "Efetivado"),
                    (7, "Cancelado"),
                    (8, "Abrir Solicitação"),
                    (9, "Devolver ao Solicitante"),
                    (10, "Devolver ao Aprovador"),
                    (11, "Aprovado automaticamente"),
                    (12, "Aprovado"),
                ],
                verbose_name="Ação Realizada",
            ),
        ),
        migrations.AlterField(
            model_name="pspendencies",
            name="type_report",
            field=models.IntegerField(verbose_name="Tipo relatório"),
        ),
        migrations.AlterField(
            model_name="shiftmanager",
            name="type_shift",
            field=models.IntegerField(
                choices=[
                    (1, "Final de Semana"),
                    (2, "Recesso"),
                    (3, "Eleitoral"),
                    (4, "DTI"),
                ],
                verbose_name="Tipo",
            ),
        ),
    ]
