# Generated by Django 2.2.28 on 2023-02-20 13:00
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import os

FIXTURES = ("pvf/fixtures/portal_request_type_choices.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0014_auto_20230112_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalrequest",
            name="portal_request_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Férias Regulamentares"),
                    (2, "Férias Individuais"),
                    (3, "Recesso Forense"),
                    (4, "Folga de Aniversário"),
                    (5, "Folga Eleitoral"),
                    (6, "Plantões\u200c(Servidores)"),
                    (7, "Folgas Compensatórias de Membros"),
                    (8, "Plantão de Recesso Forense - Membros "),
                    (9, "Licença Prêmio"),
                    (10, "Recesso de Estagiário"),
                    (11, "Concurso Promotor Substituto"),
                    (12, "Concurso de Estagiários"),
                    (13, "Tratamento de Saúde até 15 dias - Servidor"),
                    (14, "Tratamento de saúde até 30 dias - Membro"),
                    (15, "Tratamento de saúde junta médica"),
                    (16, "Doença em pessoa da família"),
                    (17, "Maternidade/Tutoria ou Adoção"),
                    (18, "Paternidade/Tutoria ou Adoção"),
                    (19, "Falecimento (Luto)"),
                    (20, "Casamento (Gala)"),
                    (21, "Alteração de Jornada"),
                    (22, "Cancelamento"),
                    (23, "Retificação"),
                    (24, "Folha Ponto"),
                    (25, "Relatório Teletrabalho"),
                    (26, "Solicitação de Plantão"),
                ],
                null=True,
                verbose_name="Tipos de Solicitações VDF",
            ),
        ),
        migrations.RunPython(up, down),
    ]
