# Generated by Django 2.2.28 on 2023-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0015_auto_20230220_1300"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFElectoralSlack",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFForensicRecess",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFIndividualVacation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFRegularVacation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFServerShift",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.AlterField(
            model_name="pointjustification",
            name="reason_type",
            field=models.IntegerField(
                choices=[
                    (1, "Informar Falta (Somente para dispensados do ponto)"),
                    (2, "Abono por Chefia"),
                    (3, "Consulta profissional de saúde (Menos de um dia)"),
                    (4, "Esquecimento no registro ponto"),
                    (5, "Registro em duplicidade"),
                    (6, "Relógio ponto inoperante"),
                    (7, "Compensado durante o mês"),
                    (8, "A ser compensado no mês subsequente"),
                    (9, "Suspensão de expediente Detetização/Desinfecção Covid"),
                    (10, "Férias (Somente para cedidos)"),
                    (11, "Licença prêmio  (Somente para cedidos)"),
                    (12, "Afastamentos  (Somente para cedidos)"),
                    (13, "Licença Médica  (Somente para cedidos)"),
                    (14, "Convocado por Chefia Imediata"),
                    (15, "Compensado por Convocação Chefia Imediata"),
                    (16, "Dispensa de ponto"),
                    (17, "Teletrabalho"),
                    (18, "Outros"),
                    (19, "Doação de Sangue"),
                    (20, "Folga Aniversário(Doador Regular/Medula)"),
                    (21, "DIA DA JUSTIÇA"),
                    (22, "RECESSO FORENSE"),
                ],
                verbose_name="Motivo",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="portal_request_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Férias Regulamentares"),
                    (2, "Férias Individuais"),
                    (3, "Recesso Forense"),
                    (4, "Folga de Aniversário"),
                    (5, "Folga Eleitoral"),
                    (6, "Plantões\u200c(Servidores)"),
                    (7, "Folgas Compensatórias de Membros"),
                    (8, "Plantão de Recesso Forense - Membros "),
                    (9, "Licença Prêmio"),
                    (10, "Recesso de Estagiário"),
                    (11, "Concurso Promotor Substituto"),
                    (12, "Concurso de Estagiários"),
                    (13, "Tratamento de Saúde até 15 dias - Servidor"),
                    (14, "Tratamento de saúde até 30 dias - Membro"),
                    (15, "Tratamento de saúde junta médica"),
                    (16, "Doença em pessoa da família"),
                    (17, "Maternidade/Tutoria ou Adoção"),
                    (18, "Paternidade/Tutoria ou Adoção"),
                    (19, "Falecimento (Luto)"),
                    (20, "Casamento (Gala)"),
                    (21, "Alteração de Jornada"),
                    (22, "Cancelamento"),
                    (23, "Retificação"),
                    (24, "Folha Ponto"),
                    (25, "Relatório Teletrabalho"),
                    (26, "Solicitação de Plantão"),
                    (27, "Doação de Sangue"),
                ],
                null=True,
                verbose_name="Tipos de Solicitações VDF",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando Ciência do Substituto"),
                    (2, "Aguardando Aprovador"),
                    (3, "Aguardando Efetivação"),
                    (4, "Efetivado"),
                    (5, "Indeferido"),
                    (6, "Cancelado DGP"),
                    (7, "Cancelado Solicitante"),
                    (8, "Aguardando Assessoria da Corregedoria"),
                    (9, "Aguardando Envio"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="step_current",
            field=models.IntegerField(
                choices=[
                    (1, "Aprovador"),
                    (2, "DG"),
                    (3, "Assessoria da Corregedoria"),
                    (4, "Corregedoria"),
                    (5, "PGJ"),
                    (7, "DGP"),
                    (8, "-"),
                    (9, "Aprovador Geral Membros"),
                ],
                verbose_name="Etapa Atual",
            ),
        ),
    ]
