# Generated by Django 2.2.28 on 2023-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0018_auto_20230530_1445"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFBloodDonation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.AddField(
            model_name="prprogressionhdocument",
            name="doc_origin",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Origem do Documento"
            ),
        ),
    ]
