# Generated by Django 2.2.28 on 2023-07-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0006_auto_20230705_1531"),
        ("rh", "0251_auto_20230705_1531"),
        ("pvf", "0019_auto_20230612_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointjustification",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="point_justification",
                to="rh.Servidor",
                verbose_name="Servidor",
            ),
        ),
        migrations.AddField(
            model_name="pointjustification",
            name="fault",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_justification",
                to="ponto.Falta",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="portal_request_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Férias Regulamentares"),
                    (2, "Férias Individuais"),
                    (3, "Recesso Forense"),
                    (4, "Folga de Aniversário"),
                    (5, "Folga Eleitoral"),
                    (6, "Plantões\u200c(Servidores)"),
                    (7, "Folgas Compensatórias de Membros"),
                    (8, "Plantão de Recesso Forense - Membros "),
                    (9, "Licença Prêmio"),
                    (10, "Recesso de Estagiário"),
                    (11, "Concurso Promotor Substituto"),
                    (12, "Concurso de Estagiários"),
                    (13, "Tratamento de Saúde até 15 dias - Servidor"),
                    (14, "Tratamento de saúde até 30 dias - Membro"),
                    (15, "Tratamento de saúde junta médica"),
                    (16, "Doença em pessoa da família"),
                    (17, "Maternidade/Tutoria ou Adoção"),
                    (18, "Paternidade/Tutoria ou Adoção"),
                    (19, "Falecimento (Luto)"),
                    (20, "Casamento (Gala)"),
                    (21, "Alteração de Jornada"),
                    (22, "Cancelamento"),
                    (23, "Retificação"),
                    (24, "Folha Ponto"),
                    (25, "Relatório Teletrabalho"),
                    (26, "Solicitação de Plantão"),
                    (27, "Ausência Doação de Sangue"),
                    (28, "Progressão Vertical"),
                    (29, "Progressão Horizontal"),
                    (30, "Doação de Sangue"),
                ],
                null=True,
                verbose_name="Tipos de Solicitações VDF",
            ),
        ),
    ]
