# Generated by Django 2.2.28 on 2023-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0021_auto_20230723_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointjustification",
            name="cancelado",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Cancelado"
            ),
        ),
        migrations.AddField(
            model_name="pointjustification",
            name="origem",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Vida Funcional"), (2, "Gestor de Faltas")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                    (7, "Teletrabalho"),
                    (8, "Confirmação de realização do plantão"),
                    (12, "Folha Ponto"),
                    (13, "Progressão Vertical"),
                    (14, "Progressão Horizontal"),
                ],
                verbose_name="Tipo agrupado de solicitação",
            ),
        ),
    ]
