# Generated by Django 2.2.28 on 2023-09-13 20:37

from django.db import migrations
from rh.pvf.models import PortalRequestAbsence


def atualizar_tipo_solicitacao(apps, schema_editor):
    """
    Atualizar o portal_request_type dos tipos de solicitação de licença saude horas
    """
    PortalRequestAbsence.objects.filter(type=63).update(portal_request_type=31)
    PortalRequestAbsence.objects.filter(type=10, portal_request_type=13).update(
        portal_request_type=15
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0022_auto_20230821_1114"),
    ]

    operations = [
        migrations.RunPython(atualizar_tipo_solicitacao),
    ]
