# Generated by Django 2.2.28 on 2023-10-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0276_corrigir_classificacao_lotacoes"),
        ("pvf", "0023_auto_20230913_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFSolicitacaoEstagiario",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFSolicitacaoResidente",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequestusufruct",),
        ),
        migrations.CreateModel(
            name="PVFExercicioCumulativo",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "substituicoes",
                    models.ManyToManyField(
                        related_name="pvf_exercicio_cumulativos",
                        to="rh.MovimentacaoSubstituicao",
                        verbose_name="Substituições",
                    ),
                ),
            ],
            options={
                "db_table": "pvf_exerciciocumulativo",
            },
            bases=("pvf.portalrequest",),
        ),
    ]
