# Generated by Django 2.2.28 on 2023-11-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0024_auto_20231010_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendingtelework",
            name="cancelado_solicitacao",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PVFCancelamentoTeletrabalho",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "envios_teletrabalho",
                    models.ManyToManyField(
                        related_name="pvf_envios_teletrabalho", to="pvf.SendingTelework"
                    ),
                ),
            ],
            options={
                "db_table": "pvf_cancelamentoteletrabalho",
            },
            bases=("pvf.portalrequest",),
        ),
    ]
