# Generated by Django 2.2.28 on 2023-11-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0025_auto_20231121_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalrequestprogression",
            name="progression",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portal_request_progression",
                to="gfp.MovimentacaoProgressao",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestprogressionh",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portal_request_progression_h",
                to="gfp.HorizontalProgressionConfig",
                verbose_name="Configuração de Progressão Horizontal",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestprogressionh",
            name="progression",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portal_request_progression_h",
                to="gfp.MovimentacaoProgressao",
                verbose_name="Movimentação Progressão",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequestprogressionh",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_request_progression_h",
                to="rh.Publicacao",
                verbose_name="Publicação Movimentação",
            ),
        ),
        migrations.AlterField(
            model_name="prprogressionhdocument",
            name="pr_progression_h",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document",
                to="pvf.PortalRequestProgressionH",
            ),
        ),
    ]
