# Generated by Django 2.2.28 on 2024-01-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0290_auto_20231207_1419"),
        ("pvf", "0029_auto_20240115_1636"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspelhoPlanoTeletrabalhoSemestral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ato",
                    models.IntegerField(
                        choices=[
                            (862, "ATO 862/2019 "),
                            (1058, "ATO 1058/2021"),
                            (1149, "ATO 1.149/2022"),
                        ],
                        verbose_name="Tipo Ato",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                (
                    "gedoc",
                    models.TextField(blank=True, null=True, verbose_name="GEDOC"),
                ),
                (
                    "ato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Publicacao",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plano_teletrabalho_semestral",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relatoriosemestralteletrabalho",
            name="espelho_mov_teletrabalhos",
            field=models.ManyToManyField(
                related_name="relatorios_semestrais_teletrabalho",
                to="pvf.EspelhoPlanoTeletrabalhoSemestral",
            ),
        ),
    ]
