# Generated by Django 2.2.28 on 2024-02-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0030_auto_20240118_1126"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftmanager",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="sendingtelework",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anexo_sending_telework",
                to="ged.Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="portal_request_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Férias Regulamentares(Servidores)"),
                    (2, "Férias Individuais(Membros)"),
                    (3, "Recesso Forense"),
                    (4, "Folga de Aniversário"),
                    (5, "Folga Eleitoral"),
                    (6, "Plantões\u200c(Servidores)"),
                    (7, "Folgas Compensatórias de Membros"),
                    (8, "Plantão de Recesso Forense - Membros "),
                    (9, "Licença Prêmio"),
                    (10, "Recesso de Estagiário"),
                    (11, "Concurso Promotor Substituto"),
                    (12, "Concurso de Estagiários"),
                    (13, "Tratamento de Saúde até 15 dias - Servidor"),
                    (14, "Tratamento de saúde até 30 dias - Membro"),
                    (15, "Tratamento de saúde junta médica"),
                    (16, "Doença em pessoa da família"),
                    (17, "Maternidade/Tutoria ou Adoção"),
                    (18, "Paternidade/Tutoria ou Adoção"),
                    (19, "Falecimento (Luto)"),
                    (20, "Casamento (Gala)"),
                    (21, "Alteração de Jornada"),
                    (22, "Cancelamento"),
                    (23, "Retificação"),
                    (24, "Folha Ponto"),
                    (25, "Relatório Teletrabalho"),
                    (26, "Solicitação de Plantão"),
                    (27, "Ausência Doação de Sangue"),
                    (28, "Progressão Vertical"),
                    (29, "Progressão Horizontal"),
                    (30, "Doação de Sangue"),
                    (31, "Tratamento de saúde Horas"),
                    (33, "Exercício Cumulativo"),
                    (34, "Cancelamento Teletrabalho"),
                    (35, "Relatorio Semestral Teletrabalho"),
                ],
                null=True,
                verbose_name="Tipos de Solicitações VDF",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                    (7, "Teletrabalho"),
                    (8, "Solicitação de Plantão"),
                    (12, "Folha Ponto"),
                    (13, "Progressão Vertical"),
                    (14, "Progressão Horizontal"),
                    (15, "Exercício cumulativo"),
                    (16, "Cancelamento Teletrabalho"),
                    (17, "Relatório Semestral do Teletrabalho"),
                ],
                verbose_name="Tipo agrupado de solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando Ciência do Substituto"),
                    (2, "Aguardando Aprovador"),
                    (3, "Aguardando Efetivação"),
                    (4, "Efetivado"),
                    (5, "Indeferido"),
                    (6, "Cancelado DGP"),
                    (7, "Cancelado Solicitante"),
                    (8, "Aguardando Assessoria da Corregedoria"),
                    (9, "Aguardando Envio"),
                    (10, "Escala Enviada"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="shiftmanager",
            name="type_shift",
            field=models.IntegerField(
                choices=[
                    (1, "Integrado"),
                    (2, "Recesso"),
                    (3, "Eleitoral"),
                    (4, "DTI"),
                    (5, "PGJ"),
                ],
                verbose_name="Tipo",
            ),
        ),
    ]
