# Generated by Django 2.2.28 on 2024-03-07 09:58

from django.db import migrations, models
import django.db.models.deletion
from rh.pvf.scripts.atualiza_metas_teletrabalho import atualiza_metas


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0031_auto_20240220_1001"),
    ]

    def forward(apps, schema_editor):
        print("Running forward...")
        atualiza_metas()

    def backward(apps, schema_editor):
        print("Running backward...")

    operations = [
        migrations.AddField(
            model_name="marktelework",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anexo_mark_telework",
                to="ged.Arquivo",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
