# Generated by Django 2.2.28 on 2024-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0034_cancelar_justificativas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marktelework",
            name="anexo",
        )
    ]
