# Generated by Django 2.2.28 on 2024-05-28 12:31
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
from django.conf import settings
import os


FIXTURES = (
    "fixtures/portal_request_type_choices.json",
    "fixtures/request_type_choices.json",
)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", "pvf", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0304_atualizar_mov_subs_pagos"),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0036_acoes_aprovador_choice_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFSolicitacaoAuxilioCrecheDepenIR",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "dependente_aux_creche",
                    models.BooleanField(
                        default=False, verbose_name="Dependente do Auxílio Creche"
                    ),
                ),
                (
                    "dependente_ir",
                    models.BooleanField(default=False, verbose_name="Dependente do IR"),
                ),
                (
                    "capacidade",
                    models.IntegerField(
                        choices=[(1, "VÁLIDO"), (2, "INVÁLIDO")], default=1, null=True
                    ),
                ),
                (
                    "tipo_parentesco",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO"),
                            (3, "FILHO(A)"),
                            (4, "PAI/MÃE"),
                            (5, "IRMÃO"),
                            (6, "ENTEADO"),
                            (7, "MENOR TUTELADO"),
                            (8, "EX-CÔNJUGE"),
                            (9, "NETOS"),
                            (10, "OUTROS"),
                            (11, "OUTROS - DEPENDÊNCIA ECONÔMICA"),
                        ],
                        null=True,
                        verbose_name="Dependente Tipo IRRF",
                    ),
                ),
                (
                    "dependente_tipo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO(A) - UNIÃO ESTÁVEL"),
                            (3, "FILHO(A) NÃO EMANCIPADO MENOR DE 21 ANOS"),
                            (
                                4,
                                "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (5, "PAI(MÃE) COM DEPENDÊNCIA ECONÔMICA"),
                            (
                                6,
                                "IRMÃO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                7,
                                "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (8, "ENTEADO NÃO EMANCIPADO MENOR DE 21"),
                            (
                                9,
                                "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (
                                10,
                                "MENOR TUTELADO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA OU GUARDA JUDICIAL",
                            ),
                            (
                                11,
                                "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (12, "AVÓS COM DEPENDENCIA ECONOMICA"),
                            (13, "BISAVÓS COM DEPENDENCIA ECONOMICA"),
                            (
                                14,
                                "NETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                15,
                                "BISNETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (16, " EX-CÔNJUGE"),
                            (
                                17,
                                "FILHO(A) OU ENTEADO(A) UNIVERSITÁRIO(A) OU CURSANDO ESCOLA TÉCNICA DE 2ºGRAU, ATÉ 24 ANOS",
                            ),
                            (18, "AGREGADO/OUTROS"),
                        ],
                        null=True,
                        verbose_name="Dependente Tipo",
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "anexo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_auxiliocrechedepenir",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "pessoa_familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_auxiliocrechedepenir",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "db_table": "pvf_solicitacaoauxiliocrechedepenir",
            },
            bases=("pvf.portalrequest",),
        ),
        migrations.RunPython(forward, backward),
    ]
