# Generated by Django 2.2.28 on 2024-09-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0039_auto_20240909_1922"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftmanager",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shiftmanger",
                to="ged.Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="shiftmanager",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
    ]
