# Generated by Django 2.2.28 on 2024-10-15 11:18
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import os

FIXTURES = (
    "fixtures/acoes_aprovador_choices.json",
    "fixtures/acoes_historico_choices.json",
    "fixtures/portal_request_type_choices.json",
    "fixtures/request_type_choices.json",
)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", "pvf", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0040_auto_20240930_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFSolicitacaoDesbloqueioTeletrabalho",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pvf.portalrequest",),
        ),
        migrations.AddField(
            model_name="portalrequesthistory",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portalrequesthistory",
                to="ged.Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="pointjustification",
            name="origem",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Vida Funcional"),
                    (2, "Gestor de Faltas"),
                    (3, "Feriado muncipal"),
                    (4, "Folha ponto"),
                    (5, "Importação triello"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="portal_request_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Férias Regulamentares(Servidores)"),
                    (2, "Férias Individuais(Membros)"),
                    (3, "Recesso Forense"),
                    (4, "Folga de Aniversário"),
                    (5, "Folga Eleitoral"),
                    (6, "Plantões\u200c(Servidores)"),
                    (7, "Folgas Compensatórias de Membros"),
                    (8, "Plantão de Recesso Forense - Membros "),
                    (9, "Licença Prêmio"),
                    (10, "Recesso de Estagiário"),
                    (11, "Concurso Promotor Substituto"),
                    (12, "Concurso de Estagiários"),
                    (13, "Tratamento de Saúde até 15 dias - Servidor"),
                    (14, "Tratamento de saúde até 30 dias - Membro"),
                    (15, "Tratamento de saúde junta médica"),
                    (16, "Doença em pessoa da família"),
                    (17, "Maternidade/Tutoria ou Adoção"),
                    (18, "Paternidade/Tutoria ou Adoção"),
                    (19, "Falecimento (Luto)"),
                    (20, "Casamento (Gala)"),
                    (21, "Alteração de Jornada"),
                    (22, "Cancelamento"),
                    (23, "Retificação"),
                    (24, "Folha Ponto"),
                    (25, "Relatório Teletrabalho"),
                    (26, "Solicitação de Plantão"),
                    (27, "Ausência Doação de Sangue"),
                    (28, "Progressão Vertical"),
                    (29, "Progressão Horizontal"),
                    (30, "Doação de Sangue"),
                    (31, "Tratamento de saúde Horas"),
                    (32, "Recesso de Residente"),
                    (33, "Exercício Cumulativo"),
                    (34, "Cancelamento Teletrabalho"),
                    (35, "Relatorio Semestral Teletrabalho"),
                    (36, "Solicitação de Crédito de Folga"),
                    (37, "Doença pessoa da família (Junta Médica)"),
                    (38, "Solicitação de auxilio creche e dependente IR"),
                    (39, "Solicitação de desbloqueio do teletrabalho"),
                ],
                null=True,
                verbose_name="Tipos de Solicitações VDF",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequest",
            name="request_type",
            field=models.IntegerField(
                choices=[
                    (1, "Programação"),
                    (2, "Ausência"),
                    (3, "Documento"),
                    (4, "Alteração Jornada"),
                    (5, "Cancelamento"),
                    (6, "Retificação"),
                    (7, "Teletrabalho"),
                    (8, "Solicitação de Plantão"),
                    (12, "Folha Ponto"),
                    (13, "Progressão Vertical"),
                    (14, "Progressão Horizontal"),
                    (15, "Exercício cumulativo"),
                    (16, "Cancelamento Teletrabalho"),
                    (17, "Relatório Semestral do Teletrabalho"),
                    (18, "Solicitação de Crédito de Folgas"),
                    (19, "Solicitação de auxilio creche e dependente IR"),
                    (20, "Desbloqueio do teletrabalho"),
                ],
                verbose_name="Tipo agrupado de solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="portalrequesthistory",
            name="action",
            field=models.IntegerField(
                choices=[
                    (1, "Solicitação"),
                    (2, "Deferido"),
                    (3, "Indeferido"),
                    (4, "Ciência"),
                    (5, "Anotação"),
                    (6, "Efetivado"),
                    (7, "Cancelado"),
                    (8, "Abrir Solicitação"),
                    (9, "Devolver ao Solicitante"),
                    (10, "Devolver ao Aprovador"),
                    (11, "Aprovado automaticamente"),
                    (12, "Aprovado"),
                    (13, "Editado"),
                    (14, "Enviar Sub"),
                ],
                verbose_name="Ação Realizada",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
