# Generated by Django 2.2.28 on 2024-10-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0041_auto_20241015_1118"),
    ]

    operations = [
        migrations.CreateModel(
            name="PVFSolicitacaoCreditoDispensaEleitoral",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(db_index=True, verbose_name="Data Início"),
                ),
                ("data_fim", models.DateField(db_index=True, verbose_name="Data Fim")),
                (
                    "anexo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_solicitacao_dispensa_eleitoral",
                        to="ged.Arquivo",
                    ),
                ),
            ],
            options={
                "db_table": "pvf_solicitacaodispensaeleitoral",
            },
            bases=("pvf.portalrequest",),
        ),
    ]
