# Generated by Django 2.2.28 on 2024-10-23 11:08
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import os


FIXTURES = ("fixtures/etapas_vdf_choices.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", "pvf", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0320_historicomovteletrabalho"),
        ("pvf", "0045_pvfsolicitacaocreditodispensaeleitoral_observacao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PVFSolicitacaoDesbloqueioTeletrabalho",
        ),
        migrations.CreateModel(
            name="PVFSolicitacaoDesbloqueioTeletrabalho",
            fields=[
                (
                    "portalrequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequest",
                    ),
                ),
                ("referencia_mes", models.IntegerField(verbose_name="Referência mês")),
                ("referencia_ano", models.IntegerField(verbose_name="Referência ano")),
                (
                    "plano_teletrabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacao_desbloqueio_tele",
                        to="rh.MovimentacaoTeletrabalho",
                        verbose_name="Plano de Trabalho",
                    ),
                ),
            ],
            options={
                "db_table": "pvf_solicitacaodesbloqueioteletrabalho",
            },
            bases=("pvf.portalrequest",),
        ),
        migrations.RunPython(forward, backward),
    ]
