# Generated by Django 2.2.28 on 2024-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0047_auto_20241112_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="marktelework",
            name="saldo_devedor_anterior",
            field=models.IntegerField(default=0),
        ),
    ]
