# Generated by Django 4.2 on 2025-03-27 09:55
from django.conf import settings
from django.db import migrations
from django.core.management import call_command
import os


FIXTURES = (
    "fixtures/choices_status_step_action.json",
    "fixtures/command_fixtures_job.json",
)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", "pvf", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("pvf", "0049_load_employee_pointjustification"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
