# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def chave_para_campo(apps, schema_editor):
    # Mozart 22 de nov 14:39
    Minute = apps.get_model("contrato.Minute")

    for m in Minute.objects.all():
        m.process_number_new = (
            m.process_number.codigo_processo if m.process_number else None
        )

        m.parent_process_new = (
            m.parent_process.codigo_processo if m.parent_process else None
        )

        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0021_remove_srp_agreements"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="parent_process_new",
            field=models.TextField(
                blank=True, null=True, verbose_name="N\xfamero do Processo M\xe3e"
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="process_number_new",
            field=models.TextField(
                blank=True, null=True, verbose_name="N\xfamero do Processo"
            ),
        ),
        migrations.RunPython(chave_para_campo),
        migrations.RemoveField(
            model_name="minute",
            name="parent_process",
        ),
        migrations.RemoveField(
            model_name="minute",
            name="process_number",
        ),
        migrations.RenameField(
            model_name="minute",
            old_name="parent_process_new",
            new_name="parent_process",
        ),
        migrations.RenameField(
            model_name="minute",
            old_name="process_number_new",
            new_name="process_number",
        ),
    ]
