# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def order_to_orders(apps, schema_editor):
    # Mozart 29 de nov 14:10
    Contrato = apps.get_model("contrato.Contrato")

    for c in Contrato.objects.all():
        if c.solicitation:
            c.order.add(c.solicitation)


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0022_desabilita_epadm"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="order",
            field=models.ManyToManyField(
                related_name="pedidos", to="contrato.MinuteSolicitation"
            ),
        ),
        migrations.RunPython(order_to_orders),
        migrations.RemoveField(
            model_name="contrato",
            name="solicitation",
        ),
    ]
