# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0023_multiplos_pedidos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="order",
            field=models.ManyToManyField(
                related_name="contratos", to="contrato.MinuteSolicitation"
            ),
        ),
    ]
