# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0024_modificando_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="objeto_contrato",
            field=models.TextField(verbose_name="Objeto do Contrato"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero",
            field=models.CharField(max_length=60, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_processo_mae",
            field=models.CharField(max_length=60, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_processo",
            field=models.CharField(max_length=60, null=True, blank=True),
        ),
    ]
