from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0026_preenche_unidade"),
    ]
    # choices=Choice.get_choices_for('contrato', 'MINUTE_ITEM_UNIT_MEASURE', empty=True, empty_label='Nenhum')
    operations = [
        migrations.AlterField(
            model_name="minuteitem",
            name="unit_measure",
            field=models.SmallIntegerField(
                default=61,
                choices=[
                    (61, "UN"),
                    (56, "SV"),
                    (15, "CX"),
                    (40, "M2"),
                    (1, "AMPOLA"),
                    (2, "BALDE"),
                    (3, "BANDEJ"),
                    (4, "BARRA"),
                    (5, "BISNAGA"),
                    (6, "BLOCO"),
                    (7, "BOBINA"),
                    (8, "BOMB"),
                    (9, "CAPS"),
                    (10, "CART"),
                    (11, "CENTO"),
                    (12, "CJ"),
                    (13, "CM"),
                    (14, "CM2"),
                    (16, "CX2"),
                    (17, "CX3"),
                    (18, "CX5"),
                    (19, "CX10"),
                    (20, "CX15"),
                    (21, "CX20"),
                    (22, "CX25"),
                    (23, "CX50"),
                    (24, "CX100"),
                    (25, "DISP"),
                    (26, "DUZIA"),
                    (27, "EMBAL"),
                    (28, "FARDO"),
                    (29, "FOLHA"),
                    (30, "FRASCO"),
                    (31, "GALAO"),
                    (32, "GF"),
                    (33, "GRAMAS"),
                    (34, "JOGO"),
                    (35, "KG"),
                    (36, "KIT"),
                    (37, "LATA"),
                    (38, "LITRO"),
                    (39, "M"),
                    (41, "M3"),
                    (42, "MILHEI"),
                    (43, "ML"),
                    (44, "MWH"),
                    (45, "PACOTE"),
                    (46, "PALETE"),
                    (47, "PARES"),
                    (48, "PÇ"),
                    (49, "POTE"),
                    (50, "K"),
                    (51, "RESMA"),
                    (52, "ROLO"),
                    (53, "SACO"),
                    (54, "SACOLA"),
                    (55, "SER"),
                    (57, "TAMBOR"),
                    (58, "TANQUE"),
                    (59, "TON"),
                    (60, "TUBO"),
                    (62, "VASIL"),
                    (63, "VIDRO"),
                ],
            ),
        ),
    ]
