# Generated by Django 2.2.17 on 2020-11-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contrato", "0031_remove_campo_sei"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementAnnotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Anotação"),
                            (2, "Lembrete"),
                            (3, "Ocorrência"),
                            (4, "Punição"),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da anotação"
                    ),
                ),
                (
                    "schedule",
                    models.BooleanField(default=False, verbose_name="Agendar Data?"),
                ),
                (
                    "schedule_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data agendamento"
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="contrato.Contrato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
