# Generated by Django 2.2.24 on 2021-10-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0042_creating_corporate_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="cnpj",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="active",
        ),
        migrations.AlterField(
            model_name="agreementsupervisor",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreementsupervisors",
                to="rh.Servidor",
                verbose_name="Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="index",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Não reajusta"),
                    (2, "IPCA/IBGE"),
                    (3, "INPC/IBGE"),
                    (4, "IGP-M/FGV"),
                    (5, "INCC-M/FGV"),
                    (6, "IST/ANATEL"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_processo",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_processo_mae",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="reference_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Janeiro"),
                    (2, "Fevereiro"),
                    (3, "Março"),
                    (4, "Abril"),
                    (5, "Maio"),
                    (6, "Junho"),
                    (7, "Julho"),
                    (8, "Agosto"),
                    (9, "Setembro"),
                    (10, "Outubro"),
                    (11, "Novembro"),
                    (12, "Dezembro"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Contrato"),
                    (2, "SRP"),
                    (3, "NE"),
                    (4, "Locação"),
                    (5, "Serviços Contínuos"),
                    (6, "Fornecimento"),
                    (7, "Dispensa"),
                    (8, "Inexigência"),
                    (9, "NE Fornecimento"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="adhesions_quantity",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (100, "Nenhuma"),
                ],
                verbose_name="Quantidade de Adesões",
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="bidding_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Dispensa de Licitação"),
                    (2, "Inexigibilidade de Licitação"),
                    (3, "Pregão Eletrônico"),
                    (4, "Pregão Presencial"),
                    (5, "Adesão a Ata SRP"),
                    (6, "Concorrência"),
                    (100, "Registro de Preço"),
                ],
                verbose_name="Tipo de Licitação",
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="management_organ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="minutes",
                to="rh.OrgaoGeral",
                verbose_name="Órgão Gerenciador",
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="object_execution",
            field=models.TextField(verbose_name="Execução do Objeto"),
        ),
        migrations.AlterField(
            model_name="minute",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minutes",
                to="rh.Pessoa",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="minutesolicitation",
            name="situation",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Em Edição"),
                    (2, "Solicitado"),
                    (3, "Aprovado"),
                    (4, "Recusado"),
                    (5, "Cancelado"),
                    (6, "Requisitado"),
                    (7, "Contratado"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="minutesolicitationaction",
            name="action",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Adicionar"),
                    (2, "Solicitar Aprovação"),
                    (3, "Aprovar"),
                    (4, "Recusar"),
                    (5, "Cancelar"),
                    (6, "Requisitar"),
                    (7, "Contratar"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="minutesolicitationrequisition",
            name="object_execution",
            field=models.TextField(verbose_name="Execução do Objeto"),
        ),
        migrations.AlterField(
            model_name="valorcontrato",
            name="data_assinatura",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Assinatura"
            ),
        ),
        migrations.AlterField(
            model_name="valorcontrato",
            name="data_reajuste",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Reajuste"
            ),
        ),
        migrations.AlterField(
            model_name="valorcontrato",
            name="tipo_valor_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Principal"),
                    (2, "Prazo"),
                    (3, "Valor"),
                    (4, "Outros"),
                    (5, "Apostilamento"),
                ],
                default=100,
                null=True,
            ),
        ),
    ]
