# Generated by Django 2.2.24 on 2021-10-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0045_migrating_enterprises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minute",
            name="enterprise_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minutes",
                to="contrato.Enterprise",
                verbose_name="Fornecedor",
            ),
        ),
    ]
