# Generated by Django 2.2.24 on 2021-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion
from standard.models import Choice


def adding_index(apps, schema_editor):
    Choice.objects.create(
        app_label="contrato",
        name="INDICE_REAJUSTE",
        cvalue=7,
        label="Convenção Coletiva",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0048_auto_20211015_0935"),
    ]

    operations = [migrations.RunPython(adding_index)]
