# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contrato", "0049_new_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ged.Arquivo"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.RemoveField(
            model_name="valorcontrato",
            name="data_reajuste",
        ),
        migrations.RemoveField(
            model_name="valorcontrato",
            name="permite_reajuste",
        ),
        migrations.RemoveField(
            model_name="valorcontrato",
            name="valor_reajuste",
        ),
        migrations.AddField(
            model_name="valorcontrato",
            name="schedule_annotation",
            field=models.BooleanField(default=False, verbose_name="Gera Anotação?"),
        ),
        migrations.AlterField(
            model_name="agreementannotation",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="contrato.Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="agreementannotation",
            name="kind",
            field=models.SmallIntegerField(verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="index",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Não reajusta"),
                    (2, "IPCA/IBGE"),
                    (3, "INPC/IBGE"),
                    (4, "IGP-M/FGV"),
                    (5, "INCC-M/FGV"),
                    (6, "IST/ANATEL"),
                    (7, "Convenção Coletiva"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Contrato"),
                    (2, "SRP"),
                    (3, "NE"),
                    (4, "Locação"),
                    (5, "Serviços Contínuos"),
                    (6, "Fornecimento"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="motive",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Empresa pública"),
                    (2, "Sem quadro societário"),
                    (3, "Não se aplica"),
                    (4, "Informação Indisponível"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hired",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired",
                to="contrato.Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="valorcontrato",
            name="tipo_valor_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Principal"), (2, "Prazo"), (3, "Valor"), (4, "Outros")],
                default=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MinuteAnnotation",
            fields=[
                (
                    "agreementannotation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contrato.AgreementAnnotation",
                    ),
                ),
                (
                    "minute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="contrato.Minute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("contrato.agreementannotation",),
        ),
        migrations.CreateModel(
            name="BalancedSolicitationItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitation_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contrato.MinuteSolicitationItem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ValueDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contrato.Document",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contrato.ValorContrato",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("contrato.document",),
        ),
        migrations.CreateModel(
            name="MinuteDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contrato.Document",
                    ),
                ),
                (
                    "minute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contrato.Minute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("contrato.document",),
        ),
        migrations.CreateModel(
            name="AgreementDocument",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contrato.Document",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contrato.Contrato",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("contrato.document",),
        ),
    ]
