# Generated by Django 2.2.28 on 2022-06-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contrato", "0050_auto_20220412_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementannotation",
            name="kind",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Anotação"),
                    (2, "Lembrete"),
                    (3, "Ocorrência"),
                    (4, "Punição"),
                ],
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="index",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Não reajusta"),
                    (2, "IPCA/IBGE"),
                    (3, "INPC/IBGE"),
                    (4, "IGP-M/FGV"),
                    (5, "INCC-M/FGV"),
                    (6, "IST/ANATEL"),
                    (7, "INCC-DI/FGV"),
                    (8, "INCC-10/FGV"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="tipo_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Contrato"),
                    (2, "SRP"),
                    (3, "NE"),
                    (4, "Locação"),
                    (5, "Serviços Contínuos"),
                    (6, "Fornecimento"),
                    (7, "Dispensa"),
                    (8, "Inexigência"),
                    (9, "NE Fornecimento"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="motive",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Empresa pública"),
                    (2, "Sem quadro societário"),
                    (3, "Não se aplica"),
                    (4, "Informação Indisponível"),
                    (5, "Estrutura Cadastrável"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="minutesolicitation",
            name="situation",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Em Edição"),
                    (2, "Solicitado"),
                    (3, "Aprovado"),
                    (4, "Recusado"),
                    (5, "Cancelado"),
                    (6, "Requisitado"),
                    (7, "Contratado"),
                    (8, "Contratado e Reequilibrado"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="rideitem",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contrato.Ride",
                verbose_name="Carona",
            ),
        ),
        migrations.AlterField(
            model_name="valorcontrato",
            name="tipo_valor_contrato",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Principal"),
                    (2, "Prazo"),
                    (3, "Valor"),
                    (4, "Outros"),
                    (5, "Apostilamento"),
                ],
                default=100,
                null=True,
            ),
        ),
    ]
