# Generated by Django 2.2.19 on 2021-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raf", "0028_auto_20190624_1843"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataeext",
            name="codclass",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataeext",
            name="codmatter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataeext",
            name="codmovement",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataeext",
            name="employee_registration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="autoreference",
            name="source_add",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "E-PROC"),
                    (2, "E-EXT"),
                    (3, "SIACMP"),
                    (4, "REGISTRO INTERNO"),
                    (5, "SEEU"),
                    (6, "PROJUDI"),
                ],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dataadjustment",
            name="source",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "E-PROC"),
                    (2, "E-EXT"),
                    (3, "SIACMP"),
                    (4, "REGISTRO INTERNO"),
                    (5, "SEEU"),
                    (6, "PROJUDI"),
                ],
                default=1,
                null=True,
                verbose_name="Origem",
            ),
        ),
    ]
