# Generated by Django 2.2.28 on 2024-05-06 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("rh", "0303_merge_20240426_1111"),
        ("diarias", "0002_load_fixtures_configs_iniciais"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "pref_turno_ultimo_destino",
                    models.CharField(
                        choices=[
                            ("MANHA", "Manhã"),
                            ("TARDE", "Tarde"),
                            ("NOITE", "Noite"),
                        ],
                        db_index=True,
                        default="MANHA",
                        max_length=50,
                        verbose_name="Preferência de turno do último destino",
                    ),
                ),
                (
                    "acomp_tipo_autoridade",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Acompanhar ao Corregedor-Geral Adjunto de Justiça ou representante",
                            ),
                            (
                                2,
                                "Acompanhar ao Corregedor-Geralde Justiça ou representante",
                            ),
                            (
                                3,
                                "Acompanhamento ao Procurador Geral de Justiça ou representante",
                            ),
                            (4, "Viagem sem Acompanhante"),
                        ],
                        null=True,
                        verbose_name="Acompanhante - Tipo de autoridade",
                    ),
                ),
                (
                    "total_diarias_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "total_diarias_definido",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "autoridade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiario_autoridade",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "conta_bancaria_pgto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_beneficiario",
                        to="rh.DadoBancarioPessoa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_viagens",
                        to="rh.Servidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiário",
                "verbose_name_plural": "Beneficiários",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_viagem",
                    models.CharField(
                        choices=[
                            ("ESTADUAL", "Estadual"),
                            ("NACIONAL", "Nacional"),
                            ("NACIONAL_ESTADUAL", "Nacional/Estadual"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        db_index=True,
                        default="ESTADUAL",
                        max_length=50,
                        verbose_name="Tipo de viagem",
                    ),
                ),
                (
                    "hospedagem_anfitriao",
                    models.BooleanField(
                        default=False, verbose_name="Hospedagem pelo anfitrião"
                    ),
                ),
                (
                    "motivo_viagem",
                    models.IntegerField(
                        choices=[
                            (7, "Autorização"),
                            (3, "Obras Técnicas"),
                            (2, "A Pedido"),
                            (1, "Convocação"),
                            (6, "Designação"),
                            (5, "Pos Grad. Art.1 §7 In.II Ato Adm. n°1.122/2022-PGJ"),
                            (4, "Cap Art 1 §7 Inci. I - Ato Adm. n° 1.122/2022-PGJ"),
                            (8, "Representação"),
                            (9, "Substituição"),
                        ],
                        null=True,
                        verbose_name="Motivo da viagem",
                    ),
                ),
                (
                    "finalidade_viagem",
                    models.IntegerField(
                        choices=[
                            (1, "Suporte Técnico"),
                            (2, "Audiência"),
                            (3, "Simpósio"),
                            (4, "esignação"),
                            (5, "urso"),
                            (6, "ongresso"),
                            (7, "ubstituição"),
                            (8, "eunião"),
                            (9, "Importação Base de Dados*"),
                            (10, "ficina de Trabalho"),
                            (11, "Realizar Perícia"),
                            (12, "Diligência"),
                            (13, "Representar"),
                            (14, "Apoio"),
                            (15, "Acompanhar"),
                            (16, "Acompanhar/Obra"),
                            (17, "Fiscalizar"),
                            (18, "Seminário"),
                            (19, "Coadjuvando"),
                            (20, "Sindicância"),
                            (21, "Palestra"),
                            (22, "Correição"),
                            (23, "GAECO"),
                            (24, "Visita Técnica"),
                            (25, "Geap"),
                            (26, "Planejamento"),
                            (27, "Comissão"),
                            (28, "apoio"),
                            (29, "Conferência"),
                            (30, "Visita Institucional"),
                            (31, "Realizar o Cerimonial"),
                            (32, "Realizar Cobertura Jornalística"),
                            (33, "Designação e Substituição"),
                            (34, "Levantamento Patrimonial"),
                            (35, "Feira"),
                            (36, "Fórum"),
                            (37, "Auxiliar"),
                            (38, "Assessorar"),
                            (39, "Participar da Assembléia Geral"),
                            (40, "Participar de Audiência"),
                            (41, "Treinamento de Avaliação de Desempenho."),
                            (42, "Certificação Digital"),
                            (43, "Evento Regional"),
                            (44, "Convocação"),
                            (45, "Participar de Solenidades"),
                            (46, "Participar de Inauguração"),
                            (47, "Cobertura Jornalística"),
                            (48, "Sessão Extraordinária"),
                            (49, "sis"),
                            (50, "orrecionais"),
                            (51, "Visita de Inspenção"),
                            (52, "Sessão Ordinária e Congresso Nacional"),
                            (53, "ncontro"),
                            (54, "Realizar Auditoria"),
                            (55, "Reunião Ordinária"),
                            (56, "Sessão Ordinária"),
                            (57, "Grupo de Estudo"),
                            (58, "Agenda Institucional"),
                            (59, "Procedimento Administrativo Displinar"),
                            (60, "Segurança Institucional"),
                            (61, "Audiência Pública"),
                            (62, "isdias"),
                            (63, "Tribunal do Juri"),
                            (64, "Instalação"),
                            (65, "Vistoria Técnica"),
                            (66, "Visita de Inspeção"),
                            (67, "Evento"),
                            (68, "Treinamento"),
                            (69, "Workshop"),
                            (70, "Estágio"),
                            (
                                71,
                                "Acompanhamento Corregedor Geral de Justica ou representantes",
                            ),
                            (
                                72,
                                "Acompanhamento Corregedor Corregedor-Geral Adjunto ou representantes",
                            ),
                            (
                                73,
                                "Acompanhamento ao Procurador Geral de Justica ou representantes",
                            ),
                            (74, "vistoria"),
                            (75, "Responder cumulativamente"),
                            (76, "NACO"),
                            (77, "Pós-Graduação"),
                            (78, "Reunião Extraordinária"),
                            (79, "realizar inventário"),
                        ],
                        null=True,
                        verbose_name="Finalidade da viagem",
                    ),
                ),
                (
                    "custeada_por",
                    models.CharField(
                        choices=[
                            ("PROCURADORIA", "Procuradoria"),
                            ("BENEFICIARIO", "Beneficiário"),
                            ("OUTROS", "Outros"),
                        ],
                        db_index=True,
                        default="PROCURADORIA",
                        max_length=50,
                        verbose_name="Custeada por",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data início da viagem"
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data fim da viagem"
                    ),
                ),
                (
                    "resumo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resumo sobre a viagem"
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Justificativa"
                    ),
                ),
                (
                    "situacao_solicitacao",
                    models.IntegerField(
                        choices=[
                            (1, "Aguardando empenho"),
                            (2, "Aguardando assinatura empenho"),
                            (3, "Aguardando assinatura Ordenador de Despesas"),
                            (4, "Aguardando Analise - DAA"),
                            (5, "Aguardando Nota Liquidação"),
                            (6, "Aguardando Ordem Bancária"),
                            (7, "Aguardando Pagamento"),
                            (8, "Pago"),
                            (9, "Aguardando Prestação de Contas"),
                            (10, "Aguardando Validação Prestação de Contas"),
                            (11, "Finalizado"),
                            (12, "Aguardando Ajustes pelo Solicitante"),
                            (13, "Rascunho"),
                        ],
                        null=True,
                        verbose_name="Situação da solicitação",
                    ),
                ),
                (
                    "etapa_solicitacao",
                    models.IntegerField(
                        choices=[
                            (1, "Assessoria da DG"),
                            (2, "DAA"),
                            (3, "DEPLAN-  Executor"),
                            (4, "DEPLAN-  Gestor"),
                            (5, "CEAF"),
                            (6, "Solicitante"),
                            (7, "SUB"),
                            (8, "Assessoria da Sub"),
                            (9, "DG"),
                            (10, "DEFIN"),
                            (11, "DEFIN- Gerencia Financeira"),
                            (12, "DEFIN- Gerencia de Tomada de contas"),
                        ],
                        null=True,
                        verbose_name="Etapa da solicitação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
                "ordering": ("-data_inicio",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ViagemAnexo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos_viagem",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos_viagem",
                        to="diarias.Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de Viagem",
                "verbose_name_plural": "Anexos de Viagem",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "forma_deslocamento",
                    models.CharField(
                        choices=[
                            ("0", "Ônibus"),
                            ("1", "Van"),
                            ("2", "Avião"),
                            ("3", "Veículo Próprio"),
                            ("4", "Veículo Oficial MP"),
                            ("5", "Veículo Locado"),
                            ("6", "Aeronave Fretada"),
                            ("7", "Outros"),
                            ("9", "Veículo Externo"),
                            ("8", "Veiculo Acautelado"),
                        ],
                        db_index=True,
                        default="7",
                        max_length=10,
                        verbose_name="Forma de deslocamento",
                    ),
                ),
                (
                    "pref_turno_ida",
                    models.CharField(
                        choices=[
                            ("MANHA", "Manhã"),
                            ("TARDE", "Tarde"),
                            ("NOITE", "Noite"),
                        ],
                        db_index=True,
                        default="MANHA",
                        max_length=50,
                        verbose_name="Preferência de turno da ida",
                    ),
                ),
                (
                    "data_ida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de ida para o destino"
                    ),
                ),
                (
                    "data_saida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de saída do destino"
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destinos",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_destinos_mun_destino",
                        to="rh.Localidade",
                    ),
                ),
                (
                    "municipio_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_destinos_mun_origem",
                        to="rh.Localidade",
                    ),
                ),
                (
                    "uf_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_destinos_uf_destino",
                        to="rh.Estado",
                    ),
                ),
                (
                    "uf_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diarias_destinos_uf_origem",
                        to="rh.Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="CargoDiarias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="viagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiarios",
                to="diarias.Viagem",
            ),
        ),
    ]
