# Generated by Django 2.2.28 on 2024-05-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diarias", "0004_load_fixtures_tipo_solicitante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="data_ida",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="data_saida",
        ),
        migrations.RemoveField(
            model_name="viagem",
            name="etapa_solicitacao",
        ),
        migrations.RemoveField(
            model_name="viagem",
            name="situacao_solicitacao",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="etapa_solicitacao",
            field=models.IntegerField(
                choices=[
                    (1, "Assessoria da DG"),
                    (2, "DAA"),
                    (3, "DEPLAN-  Executor"),
                    (4, "DEPLAN-  Gestor"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (7, "SUB"),
                    (8, "Assessoria da Sub"),
                    (9, "DG"),
                    (10, "DEFIN"),
                    (11, "DEFIN- Gerencia Financeira"),
                    (12, "DEFIN- Gerencia de Tomada de contas"),
                ],
                null=True,
                verbose_name="Etapa da solicitação",
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="situacao_solicitacao",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura empenho"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (4, "Aguardando Analise - DAA"),
                    (5, "Aguardando Nota Liquidação"),
                    (6, "Aguardando Ordem Bancária"),
                    (7, "Aguardando Pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando Prestação de Contas"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                    (13, "Rascunho"),
                ],
                null=True,
                verbose_name="Situação da solicitação",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="data_hora_ida",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data e hora de ida para o destino"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="data_hora_ida_bilhete",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data e hora de ida do bilhete para o destino",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="data_hora_saida",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data e hora de saída do destino"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="data_hora_saida_bilhete",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data e hora de saída do bilhete do destino",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="tipo_solicitante",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura empenho"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (4, "Aguardando Analise - DAA"),
                    (5, "Aguardando Nota Liquidação"),
                    (6, "Aguardando Ordem Bancária"),
                    (7, "Aguardando Pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando Prestação de Contas"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                    (13, "Rascunho"),
                ],
                null=True,
                verbose_name="Tipo de solicitante",
            ),
        ),
        migrations.CreateModel(
            name="VeiculoViagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("placa", models.CharField(max_length=100, verbose_name="Placa")),
                (
                    "kilometragem",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kilometragem",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Marca"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Modelo"
                    ),
                ),
                (
                    "renavam",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Renavam"
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="diarias.Destino",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="PassagemAeriaViagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "numero_bilhete",
                    models.CharField(max_length=100, verbose_name="Número do bilhete"),
                ),
                (
                    "nome_companhia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome da companhia",
                    ),
                ),
                (
                    "nome_terminal",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do terminal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passagens",
                        to="diarias.Destino",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passagem aéria",
                "verbose_name_plural": "Passagens aéria",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
