# Generated by Django 2.2.28 on 2024-05-09 18:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diarias", "0008_load_fixtures_adicionais_e_cond_fluxo_viagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fluxoviagem",
            name="condicionais",
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="etapa_solicitacao",
            field=models.IntegerField(
                choices=[
                    (1, "Assessoria da DG"),
                    (2, "DAA"),
                    (3, "DEPLAN-  Executor"),
                    (4, "DEPLAN-  Gestor"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (7, "SUB"),
                    (8, "Assessoria da Sub"),
                    (9, "DG"),
                    (10, "DEFIN"),
                    (11, "DEFIN- Gerencia Financeira"),
                    (12, "DEFIN- Gerencia de Tomada de contas"),
                    (13, "Beneficiário"),
                ],
                null=True,
                verbose_name="Etapa da solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="situacao_solicitacao",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura empenho"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (4, "Aguardando Analise - DAA"),
                    (5, "Aguardando Nota Liquidação"),
                    (6, "Aguardando Ordem Bancária"),
                    (7, "Aguardando Pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando Prestação de Contas"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                    (13, "Rascunho"),
                    (14, "Aguardando análise"),
                    (15, "Aguardando aprovador"),
                    (16, "Aguardando ciência do participante"),
                ],
                null=True,
                verbose_name="Situação da solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="etapa",
            field=models.IntegerField(
                choices=[
                    (1, "Assessoria da DG"),
                    (2, "DAA"),
                    (3, "DEPLAN-  Executor"),
                    (4, "DEPLAN-  Gestor"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (7, "SUB"),
                    (8, "Assessoria da Sub"),
                    (9, "DG"),
                    (10, "DEFIN"),
                    (11, "DEFIN- Gerencia Financeira"),
                    (12, "DEFIN- Gerencia de Tomada de contas"),
                    (13, "Beneficiário"),
                ],
                null=True,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura empenho"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (4, "Aguardando Analise - DAA"),
                    (5, "Aguardando Nota Liquidação"),
                    (6, "Aguardando Ordem Bancária"),
                    (7, "Aguardando Pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando Prestação de Contas"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                    (13, "Rascunho"),
                    (14, "Aguardando análise"),
                    (15, "Aguardando aprovador"),
                    (16, "Aguardando ciência do participante"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.CreateModel(
            name="CondicionalFluxoViagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "condicionais",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condicionais",
                        to="diarias.FluxoViagem",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Condicional do Fluxo de viagem",
                "verbose_name_plural": "Condicionais do Fluxo de viagem",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
