# Generated by Django 2.2.28 on 2024-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0011_valordiarias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fluxoviagem",
            name="notificar_servidores",
            field=models.ManyToManyField(
                blank=True,
                related_name="fluxos_viagens_notificacoes",
                to="rh.Servidor",
                verbose_name="Notificar Servidores",
            ),
        ),
    ]
