# Generated by Django 2.2.28 on 2024-05-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0012_auto_20240517_0830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiario",
            name="conta_bancaria_pgto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diarias_beneficiario",
                to="rh.DadoBancarioPessoa",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="etapa_solicitacao",
            field=models.IntegerField(
                choices=[
                    (12, "DEFIN- Gerencia de Tomada de contas"),
                    (11, "DEFIN- Gerencia Financeira"),
                    (4, "DEPLAN-  Gestor"),
                    (3, "DEPLAN-  Executor"),
                    (13, "Beneficiário"),
                    (2, "DAA"),
                    (9, "DG"),
                    (1, "Assessoria da DG"),
                    (7, "SUB"),
                    (8, "Assessoria da Sub"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (10, "DEFIN"),
                ],
                null=True,
                verbose_name="Etapa da solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="situacao_solicitacao",
            field=models.IntegerField(
                choices=[
                    (11, "Finalizado"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (9, "Aguardando Prestação de Contas"),
                    (8, "Pago"),
                    (7, "Aguardando Pagamento"),
                    (6, "Aguardando Ordem Bancária"),
                    (5, "Aguardando Nota Liquidação"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (2, "Aguardando assinatura empenho"),
                    (1, "Aguardando empenho"),
                    (16, "Aguardando ciência do participante"),
                    (4, "Aguardando Analise - DAA"),
                    (15, "Aguardando aprovador"),
                    (14, "Aguardando análise"),
                    (13, "Rascunho"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                ],
                null=True,
                verbose_name="Situação da solicitação",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="etapa",
            field=models.IntegerField(
                choices=[
                    (12, "DEFIN- Gerencia de Tomada de contas"),
                    (11, "DEFIN- Gerencia Financeira"),
                    (4, "DEPLAN-  Gestor"),
                    (3, "DEPLAN-  Executor"),
                    (13, "Beneficiário"),
                    (2, "DAA"),
                    (9, "DG"),
                    (1, "Assessoria da DG"),
                    (7, "SUB"),
                    (8, "Assessoria da Sub"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (10, "DEFIN"),
                ],
                null=True,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (11, "Finalizado"),
                    (10, "Aguardando Validação Prestação de Contas"),
                    (9, "Aguardando Prestação de Contas"),
                    (8, "Pago"),
                    (7, "Aguardando Pagamento"),
                    (6, "Aguardando Ordem Bancária"),
                    (5, "Aguardando Nota Liquidação"),
                    (3, "Aguardando assinatura Ordenador de Despesas"),
                    (2, "Aguardando assinatura empenho"),
                    (1, "Aguardando empenho"),
                    (16, "Aguardando ciência do participante"),
                    (4, "Aguardando Analise - DAA"),
                    (15, "Aguardando aprovador"),
                    (14, "Aguardando análise"),
                    (13, "Rascunho"),
                    (12, "Aguardando Ajustes pelo Solicitante"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
    ]
