# Generated by Django 2.2.28 on 2024-05-22 13:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0304_atualizar_mov_subs_pagos"),
        ("diarias", "0013_auto_20240521_1633"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoAprovador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do grupo"),
                ),
                (
                    "grupos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="grupos_aprovadores_viagens",
                        to="rh.Servidor",
                        verbose_name="Servidores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Aprovadores de Viagens",
                "verbose_name_plural": "Grupos de Aprovadores de Viagens",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
