# Generated by Django 2.2.28 on 2024-05-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0016_auto_20240522_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="fluxo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viagens",
                to="diarias.FluxoViagem",
            ),
        ),
    ]
