# Generated by Django 2.2.28 on 2024-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0017_viagem_fluxo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fluxoviagem",
            name="ordem",
            field=models.SmallIntegerField(
                db_index=True, null=True, verbose_name="Ordem"
            ),
        ),
    ]
