# Generated by Django 2.2.28 on 2024-05-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0017_viagem_fluxo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="data_hora_ida_bilhete",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="data_hora_saida_bilhete",
        ),
        migrations.AddField(
            model_name="passagemaeriaviagem",
            name="data_hora_ida_bilhete",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data e hora de ida do bilhete para o destino",
            ),
        ),
        migrations.AddField(
            model_name="passagemaeriaviagem",
            name="data_hora_saida_bilhete",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data e hora de saída do bilhete do destino",
            ),
        ),
        migrations.AlterField(
            model_name="passagemaeriaviagem",
            name="destino",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="passagem",
                to="diarias.Destino",
            ),
        ),
    ]
