# Generated by Django 2.2.28 on 2024-05-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0018_auto_20240524_1010"),
        ("diarias", "0018_auto_20240523_1054"),
    ]

    operations = []
