# Generated by Django 2.2.28 on 2024-06-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diarias", "0020_auto_20240529_1535"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoFluxoViagemBeneficiario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("viagem", "Viagem"),
                            ("beneficiario", "Beneficiário"),
                        ],
                        db_index=True,
                        default="VIAGEM",
                        max_length=50,
                        verbose_name="Tipo de histórico",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_fluxos",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fluxo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_fluxos",
                        to="diarias.FluxoViagem",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_fluxos",
                        to="diarias.Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Fluxos para uma Viagem e seus Beneficiários",
                "verbose_name_plural": "Histórico de Fluxos para uma Viagem e seus Beneficiários",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
