# Generated by Django 2.2.28 on 2024-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0022_auto_20240607_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="total_receber",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Total a receber",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="desc_alimentacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Desconto alimentação",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="desc_transporte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Desconto transporte",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="total_bruto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Total bruto",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="total_desc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Total desconto",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="total_liquido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Total líquido",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="valor_diaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor da diária",
            ),
        ),
    ]
