# Generated by Django 2.2.28 on 2024-06-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diarias", "0023_auto_20240607_1413"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destino",
            name="data_hora_ida",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="data_hora_saida",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="desc_alimentacao",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="desc_transporte",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="total_bruto",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="total_desc",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="total_liquido",
        ),
        migrations.AddField(
            model_name="destino",
            name="data",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data"),
        ),
        migrations.AddField(
            model_name="fluxoviagem",
            name="calcular",
            field=models.BooleanField(default=False, verbose_name="Calcular"),
        ),
        migrations.CreateModel(
            name="CalculoConsolidado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "total_diarias",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Quantidade tota de diárias",
                    ),
                ),
                (
                    "valor_subsidio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor do subsídio",
                    ),
                ),
                (
                    "valor_transporte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor do transporte",
                    ),
                ),
                (
                    "valor_base_desc_alimentacao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor base de desconto em alimentação",
                    ),
                ),
                (
                    "valor_base_desc_transporte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor base de desconto em transporte",
                    ),
                ),
                (
                    "valor_total_diarias_dentro_estado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total dentro do Estado MT",
                    ),
                ),
                (
                    "valor_total_diarias_fora_estado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total fora do Estado MT",
                    ),
                ),
                (
                    "valor_total_veiculo_mp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total com veículo do MPMT",
                    ),
                ),
                (
                    "valor_total_desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total de desconto",
                    ),
                ),
                (
                    "valor_total_bruto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total bruto",
                    ),
                ),
                (
                    "valor_total_liquido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="Valor total líquido",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculos_diarias_consolidados",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cálculo consolidado",
                "verbose_name_plural": "Cálculos consolidado",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
