# Generated by Django 2.2.28 on 2024-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0025_configurar_calcular_fluxos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="total_diarias_definido",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="total_diarias_deferido",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias deferido",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="qtd_diarias",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Quantidade da diárias",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="total_diarias_calculado",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias calculado",
            ),
        ),
    ]
