# Generated by Django 2.2.28 on 2024-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0026_auto_20240617_1342"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="total_diarias_calculado",
        ),
        migrations.RemoveField(
            model_name="beneficiario",
            name="total_diarias_deferido",
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="total_diarias_deferido",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias deferido",
            ),
        ),
    ]
