# Generated by Django 2.2.28 on 2024-06-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0028_destino_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="data",
            field=models.DateField(blank=True, null=True, verbose_name="Data"),
        ),
    ]
