# Generated by Django 2.2.28 on 2024-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0029_auto_20240618_1146"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculoconsolidado",
            old_name="total_diarias_deferido",
            new_name="qtd_total_diarias_deferido",
        ),
        migrations.RemoveField(
            model_name="calculoconsolidado",
            name="total_diarias",
        ),
        migrations.RemoveField(
            model_name="calculoconsolidado",
            name="valor_subsidio",
        ),
        migrations.RemoveField(
            model_name="calculoconsolidado",
            name="valor_transporte",
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_dentro_estado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias dentro do Estado MT",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_fora_estado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias fora do Estado MT",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="valor_base_subsidio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor base do subsídio",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="valor_desc_alimentacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor de desconto em alimentação",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="valor_desc_transporte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor de desconto em transporte",
            ),
        ),
    ]
