# Generated by Django 2.2.28 on 2024-06-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0032_auto_20240626_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="beneficiario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculos_diarias_consolidados",
                to="diarias.Beneficiario",
            ),
        ),
    ]
