# Generated by Django 2.2.28 on 2024-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0033_auto_20240626_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxoviagem",
            name="deferir_todos_beneficiarios",
            field=models.BooleanField(
                default=False, verbose_name="Deferir Todos os Beneficiários"
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="motivo_viagem",
            field=models.IntegerField(
                choices=[
                    (7, "Autorização"),
                    (3, "Obras Técnicas"),
                    (2, "A Pedido"),
                    (1, "Convocação"),
                    (6, "Designação"),
                    (5, "Pos Grad. Art.1 §7 In.II Ato Adm. n°1.122/2022-PGJ"),
                    (4, "Cap Art 1 §7 Inci. I - Ato Adm. n° 1.122/2022-PGJ"),
                    (8, "Representação"),
                    (9, "Substituição"),
                ],
                null=True,
                verbose_name="Motivo da viagem",
            ),
        ),
    ]
