# Generated by Django 2.2.28 on 2024-07-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0309_incluir_localidades"),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("diarias", "0035_set_deferir_todos_beneficiarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="CnabPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "cnab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cnabs",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CNAB Pagamento",
                "verbose_name_plural": "CNABs Pagamentos",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="motivo_viagem",
            field=models.IntegerField(
                choices=[
                    (7, "Autorização"),
                    (3, "Obras Técnicas"),
                    (2, "A Pedido"),
                    (1, "Convocação"),
                    (6, "Designação"),
                    (5, "Pós Graduação - Art.1 §7 In.II Ato Adm. n°1.122/2022-PGJ"),
                    (4, "Capacitação - Art 1 §7 Inci. I - Ato Adm. n° 1.122/2022-PGJ"),
                    (8, "Representação"),
                    (9, "Substituição"),
                ],
                null=True,
                verbose_name="Motivo da viagem",
            ),
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "assinado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assinado em"
                    ),
                ),
                (
                    "data_pgto",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("cnab_criado", "CNAB Criado"),
                            ("pago", "Pago"),
                        ],
                        default="aguardando",
                        max_length=15,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "assinado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assinaturas",
                        to="rh.PessoaFisica",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "cnab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="diarias.CnabPagamento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
