# Generated by Django 2.2.28 on 2024-07-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("rh", "0309_incluir_localidades"),
        ("diarias", "0036_auto_20240710_1220"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestacaoContas",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "viagem_realizada",
                    models.BooleanField(default=True, verbose_name="Viagem Realizada?"),
                ),
                (
                    "viagem_total",
                    models.BooleanField(
                        default=True,
                        verbose_name="Viagem foi finalizada na totalidade?",
                    ),
                ),
                (
                    "data_limite",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data limite de entrega da prestação de contas",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de entrega da prestação de contas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("entregue", "Entregue"),
                            ("atrasado", "Atrasado"),
                        ],
                        default="aguardando",
                        max_length=15,
                        verbose_name="Status da Prestação de Contas",
                    ),
                ),
                (
                    "obs_servicos_executados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Serviços executados"
                    ),
                ),
                (
                    "obs_resultado",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resultados alcançados"
                    ),
                ),
                (
                    "obs_anlaise",
                    models.TextField(
                        blank=True, null=True, verbose_name="Obs. da análise"
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes_prestacoes_contas_diarias",
                        to="rh.Servidor",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestacoes_contas",
                        to="diarias.Beneficiario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestação de Contas",
                "verbose_name_plural": "Prestações de Contas",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="PrestacaoContasAnexo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestacao_contas_arquivos",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos",
                        to="diarias.PrestacaoContas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de Prestação de Contas",
                "verbose_name_plural": "Anexos de Prestação de Contas",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
