# Generated by Django 2.2.28 on 2024-07-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0038_load_create_job_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="assinado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Assinado em"
            ),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="assinado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assinaturas_prestacaocontas",
                to="rh.PessoaFisica",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="assinado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assinaturas_pagamento",
                to="rh.PessoaFisica",
            ),
        ),
    ]
