# Generated by Django 2.2.28 on 2024-07-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0039_auto_20240715_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="data_validacao",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data da Validação da prestação de contas ",
            ),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="obs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Obs. do beneficiário"
            ),
        ),
    ]
