# Generated by Django 2.2.28 on 2024-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0040_auto_20240729_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestacaocontas",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("entregue", "Entregue"),
                    ("atrasado", "Atrasado"),
                    ("com_pendencias", "Com Pendencias"),
                    ("aprovado", "Aprovado"),
                ],
                default="aguardando",
                max_length=15,
                verbose_name="Status da Prestação de Contas",
            ),
        ),
    ]
