# Generated by Django 2.2.28 on 2024-07-31 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0041_auto_20240731_1017"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viagem",
            options={
                "ordering": ("-data_inicio_viagem",),
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
            },
        ),
        migrations.RenameField(
            model_name="viagem",
            old_name="data_fim",
            new_name="data_fim_viagem",
        ),
        migrations.RenameField(
            model_name="viagem",
            old_name="data_inicio",
            new_name="data_inicio_viagem",
        ),
        migrations.RemoveField(
            model_name="beneficiario",
            name="pref_turno_ultimo_destino",
        ),
        migrations.RemoveField(
            model_name="beneficiario",
            name="total_receber",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="qtd_diarias",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="uf_destino",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="uf_origem",
        ),
        migrations.RemoveField(
            model_name="destino",
            name="valor_diaria",
        ),
        migrations.RemoveField(
            model_name="viagem",
            name="custeada_por",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="datas_evento",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="tipo_locomocao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("veiculo_proprio", "Veículo próprio"),
                    ("veiculo_mpmt", "Veículo oficial do MPMT"),
                    ("solic_passagem_aerea", "Solicitação de passagem aérea"),
                ],
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="Tipo de locomoção",
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="titulo_evento",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Título do evento"
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="valor_total_liquido_deferido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor total líquido deferido",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="tipo_viagem",
            field=models.CharField(
                choices=[
                    ("ESTADUAL", "Estadual"),
                    ("NACIONAL", "Nacional"),
                    ("INTERNACIONAL", "Internacional"),
                ],
                db_index=True,
                default="ESTADUAL",
                max_length=50,
                verbose_name="Tipo de viagem",
            ),
        ),
    ]
