# Generated by Django 2.2.28 on 2024-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0043_eventobeneficiario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="data",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data"),
        ),
    ]
