# Generated by Django 2.2.28 on 2024-08-02 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ged", "0005_reorganization_of_storage_directory"),
        ("diarias", "0045_load_fixtures_template_email_prestacao_contas"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="numero_empenho",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Empenho"
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="numero_nota_liquidacao",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Número da Nota de Liquidação",
            ),
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="numero_ordem_bancaria",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Número da Ordem Bancária",
            ),
        ),
        migrations.AddField(
            model_name="historicofluxoviagembeneficiario",
            name="obs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações - Avaliação"
            ),
        ),
        migrations.CreateModel(
            name="HistoricoAnexo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_fluxo_viagem_benef_arquivos",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "historico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anexos",
                        to="diarias.HistoricoFluxoViagemBeneficiario",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de Histórico do Fluxo de Viagem/Beneficiário",
                "verbose_name_plural": "Anexos de Histórico do Fluxo de Viagem/Beneficiário",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
