# Generated by Django 2.2.28 on 2024-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0046_auto_20240802_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventobeneficiario",
            name="titulo",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Título do evento"
            ),
        ),
    ]
