# Generated by Django 2.2.28 on 2024-09-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0055_load_fixtures_conds_fluxo_diarias"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="gedoc_numero",
            field=models.TextField(
                blank=True, max_length=50, null=True, verbose_name="Número GEDOC"
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="excedente",
            field=models.BooleanField(default=False, verbose_name="Viagem Excedente"),
        ),
        migrations.AddField(
            model_name="viagem",
            name="viagem_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viagens_excedentes",
                to="diarias.Viagem",
            ),
        ),
    ]
