# Generated by Django 2.2.28 on 2024-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0056_auto_20240910_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_calculadas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias calculadas",
            ),
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_excedente",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias excedentes",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_deferido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias deferido",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_dentro_estado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias dentro do Estado MT",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_fora_estado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Qtd total de diárias fora do Estado MT",
            ),
        ),
        migrations.AlterField(
            model_name="historicofluxoviagembeneficiario",
            name="decisao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferido", "Deferido"),
                    ("indeferido", "Indeferido"),
                    ("encaminhado", "Encaminhado"),
                ],
                max_length=10,
                null=True,
                verbose_name="Decisão",
            ),
        ),
    ]
