# Generated by Django 2.2.28 on 2024-09-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0057_auto_20240911_1529"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="etapa_solicitacao",
        ),
        migrations.RemoveField(
            model_name="beneficiario",
            name="situacao_solicitacao",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="fluxo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiarios",
                to="diarias.FluxoViagem",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="etapa",
            field=models.IntegerField(
                choices=[
                    (1, "Assessoria da DG"),
                    (2, "DAA"),
                    (3, "DEPLAN - Executor"),
                    (4, "DEPLAN - Gestor"),
                    (5, "CEAF"),
                    (6, "Solicitante"),
                    (7, "SUB ADM"),
                    (8, "Assessoria da SUB ADM"),
                    (9, "DG"),
                    (10, "DEFIN"),
                    (11, "DEFIN - Gerência financeira"),
                    (12, "DEFIN - Gerência de tomada de contas"),
                    (13, "Beneficiário"),
                    (14, "Chefe imediato"),
                    (15, "SUB JUR"),
                    (16, "Assessoria da SUB JUR"),
                    (17, "PGJ"),
                    (18, "Assessoria da PGJ"),
                    (19, "Análise da PGJ"),
                    (20, "Indeferido"),
                ],
                null=True,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="fluxoviagem",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura do empenho"),
                    (3, "Aguardando assinatura do ordenador de despesas"),
                    (4, "Aguardando análise - DAA"),
                    (5, "Aguardando nota liquidação"),
                    (6, "Aguardando ordem bancária"),
                    (7, "Aguardando pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando prestação de contas"),
                    (10, "Aguardando validação da prestação de contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando ajustes pelo solicitante"),
                    (13, "Rascunho"),
                    (14, "Aguardando análise"),
                    (15, "Aguardando aprovador"),
                    (16, "Aguardando ciência do participante"),
                    (17, "Aguardando ciência"),
                    (18, "Análise Afastamentos"),
                    (19, "Cancelado"),
                    (20, "Excedente"),
                    (21, "Adiamento da viagem"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
    ]
