# Generated by Django 2.2.28 on 2024-09-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0058_auto_20240912_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicofluxoviagembeneficiario",
            name="decisao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferido", "Deferido"),
                    ("indeferido", "Indeferido"),
                    ("encaminhado", "Encaminhado"),
                ],
                max_length=15,
                null=True,
                verbose_name="Decisão",
            ),
        ),
    ]
