# Generated by Django 2.2.28 on 2024-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0061_auto_20240916_1724"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="acomp_tipo_autoridade",
        ),
        migrations.AddField(
            model_name="beneficiario",
            name="acomp_autoridade_deferimento",
            field=models.BooleanField(
                default=False,
                verbose_name="Deferimento do acompanhamento de autoridade",
            ),
        ),
    ]
