# Generated by Django 2.2.28 on 2024-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0062_auto_20240919_1418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_calculadas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias calculadas",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_deferido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias deferido",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_dentro_estado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias dentro do Estado MT",
            ),
        ),
        migrations.AlterField(
            model_name="calculoconsolidado",
            name="qtd_total_excedente",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias excedentes",
            ),
        ),
    ]
