# Generated by Django 2.2.28 on 2024-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0063_auto_20240920_1506"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculoconsolidado",
            old_name="qtd_total_diarias_dentro_estado",
            new_name="qtd_total_diarias_dentro_uf",
        ),
        migrations.RemoveField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_fora_estado",
        ),
        migrations.AddField(
            model_name="calculoconsolidado",
            name="qtd_total_diarias_fora_uf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Qtd total de diárias fora do Estado MT",
            ),
        ),
    ]
