# Generated by Django 2.2.28 on 2024-09-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0067_load_create_job_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="passagemaeriaviagem",
            name="numero_bilhete",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Número do bilhete"
            ),
        ),
    ]
