# Generated by Django 2.2.28 on 2024-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0068_passagemaeriaviagem_numero_bilhete"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculoconsolidado",
            name="valor_base_diaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor base da diária",
            ),
        ),
    ]
