# Generated by Django 2.2.28 on 2024-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0069_calculoconsolidado_valor_base_diaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicofluxoviagembeneficiario",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positivo", "Negativo"),
                    ("negativo", "Positivo"),
                    ("alerta", "Alerta"),
                ],
                max_length=15,
                null=True,
                verbose_name="Feedback",
            ),
        ),
    ]
