# Generated by Django 2.2.28 on 2024-10-17 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diarias", "0076_auto_20241011_1610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculoviagem",
            name="destino",
        ),
        migrations.AddField(
            model_name="veiculoviagem",
            name="capacidade_passageiros",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Capacidade de Passageiros"
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="motorista",
            field=models.BooleanField(default=False, verbose_name="Motorista"),
        ),
        migrations.CreateModel(
            name="VeiculoPassageiro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "motorista",
                    models.BooleanField(default=False, verbose_name="Motorista"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passageiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculo_passageiros",
                        to="diarias.Destino",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculo",
                        to="diarias.VeiculoViagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo Passageiro",
                "verbose_name_plural": "Veículo Passageiros",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
