# Generated by Django 2.2.28 on 2024-10-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0080_load_fixtures_fluxo_viagem"),
        ("diarias", "0080_load_fixtures_template_email_mov_etapa"),
    ]

    operations = []
