# Generated by Django 2.2.28 on 2024-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0081_merge_20241025_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculoconsolidado",
            name="reanalise",
            field=models.BooleanField(
                default=False, verbose_name="Reanalise devido alterações do DAA"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="data_daa",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data segundo análise do DAA"
            ),
        ),
    ]
