# Generated by Django 2.2.28 on 2024-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0083_load_fixtures_0030_template_itens_config_os_diarias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fluxoviagem",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Aguardando empenho"),
                    (2, "Aguardando assinatura do empenho"),
                    (3, "Aguardando assinatura do ordenador de despesas"),
                    (4, "Aguardando análise - DAA"),
                    (5, "Aguardando nota liquidação"),
                    (6, "Aguardando ordem bancária"),
                    (7, "Aguardando pagamento"),
                    (8, "Pago"),
                    (9, "Aguardando prestação de contas"),
                    (10, "Aguardando validação da prestação de contas"),
                    (11, "Finalizado"),
                    (12, "Aguardando ajustes pelo solicitante"),
                    (13, "Rascunho"),
                    (14, "Aguardando análise"),
                    (15, "Aguardando aprovador"),
                    (16, "Aguardando ciência do participante"),
                    (17, "Aguardando ciência"),
                    (18, "Análise afastamentos"),
                    (19, "Cancelado"),
                    (20, "Excedente"),
                    (21, "Adiamento da viagem"),
                    (22, "Aguardando ciência de cancelamento"),
                    (23, "Aguardando reanálise"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
    ]
