# Generated by Django 2.2.28 on 2024-11-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0087_load_fixtures_fluxo_viagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxoviagem",
            name="link_informacao",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
