# Generated by Django 2.2.28 on 2025-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0095_auto_20250123_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="valor_devolvido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor devolvido",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando - ordem pendente"),
                    ("cnab_criado", "Cnab Criado - Aguardando pagamento"),
                    ("pago", "Pago"),
                ],
                default="aguardando",
                max_length=15,
                verbose_name="Status do Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaocontas",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("entregue", "Entregue"),
                    ("em_analise", "Em Análise"),
                    ("atrasado", "Atrasado"),
                    ("com_pendencias", "Com Pendencias"),
                    ("aprovado", "Aprovado"),
                ],
                default="aguardando",
                max_length=15,
                verbose_name="Status da Prestação de Contas",
            ),
        ),
    ]
