# Generated by Django 2.2.28 on 2025-01-29 12:12

from django.db import migrations
from django.conf import settings
from django.core.management import call_command
import os

FIXTURES = ("fixtures/0038_adicionar_fluxos_condicional.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "diarias", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0096_auto_20250127_2016"),
    ]

    operations = [migrations.RunPython(forward, backward)]
