# Generated by Django 2.2.28 on 2025-01-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0097_auto_20250129_1212"),
        ("diarias", "0096_auto_20250129_1337"),
    ]

    operations = []
