# Generated by Django 4.2 on 2025-03-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diarias", "0100_apagar_diarias_importadas_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="doc_encerramento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestacao_contas_doc_encerramento",
                to="ged.arquivo",
            ),
        ),
    ]
