# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_profile_printer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="company_child",
                serialize=False,
                to="mailing.Common",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="position_child",
                serialize=False,
                to="mailing.Common",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="profile_child",
                serialize=False,
                to="mailing.Common",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="state_child",
                serialize=False,
                to="mailing.Common",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="treatment_child",
                serialize=False,
                to="mailing.Common",
            ),
        ),
    ]
