# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_auto_20190930_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinguser",
            name="permission",
            field=models.CharField(
                choices=[
                    ("basic", "Básico"),
                    ("reviser", "Revisor"),
                    ("admin", "Administrador"),
                ],
                db_index=True,
                default="basic",
                max_length=12,
            ),
        ),
    ]
