# Generated by Django 2.2.28 on 2022-09-27 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0195_auto_20220927_1005"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0101_auto_20220927_1005"),
    ]

    operations = [
        migrations.CreateModel(
            name="PFProviderEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_day",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "gross_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Valor Bruto",
                    ),
                ),
                (
                    "inss_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Valor INSS",
                    ),
                ),
                (
                    "inss_exempt",
                    models.BooleanField(default=False, verbose_name="Isento INSS"),
                ),
                (
                    "nature_activity",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "TRABALHO URBANO"), (2, "TRABALHO RURAL")],
                        default=1,
                        null=True,
                        verbose_name="Natureza da Atividade",
                    ),
                ),
                (
                    "cbo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_providers",
                        to="rh.Cbo",
                        verbose_name="CBO",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "natural_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_providers",
                        to="rh.PessoaFisica",
                        verbose_name="Pessoa Física",
                    ),
                ),
                (
                    "paycheck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_providers",
                        to="gfp.ContraCheque",
                        verbose_name="ContraCheque",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_providers",
                        to="gfp.Folha",
                        verbose_name="Folha",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
