# Generated by Django 2.2.28 on 2022-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pfproviderentry",
            options={"verbose_name": "Entradas do Provedor PF"},
        ),
        migrations.AddField(
            model_name="pfproviderentry",
            name="contributed",
            field=models.BooleanField(
                default=False,
                verbose_name="Existe contribuição parcial em outro local?",
            ),
        ),
        migrations.AddField(
            model_name="pfproviderentry",
            name="ir_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Valor IR"
            ),
        ),
        migrations.AddField(
            model_name="pfproviderentry",
            name="liquid_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Valor líquido"
            ),
        ),
        migrations.AddField(
            model_name="pfproviderentry",
            name="partial_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=16,
                verbose_name="Contribuição parcial em outro local",
            ),
        ),
    ]
