# Generated by Django 2.2.28 on 2022-10-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0203_auto_20221018_1647"),
        ("defin", "0002_auto_20221003_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="pfproviderentry",
            name="workplace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pf_providers",
                to="rh.Lotacao",
                verbose_name="Lotação",
            ),
        ),
        migrations.AlterField(
            model_name="pfproviderentry",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pf_providers",
                to="gfp.Folha",
                verbose_name="Folha",
            ),
        ),
    ]
