# Generated by Django 2.2.28 on 2022-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defin", "0003_auto_20221018_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pfproviderentry",
            name="gross_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Bruto",
            ),
        ),
        migrations.AlterField(
            model_name="pfproviderentry",
            name="inss_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor INSS",
            ),
        ),
        migrations.AlterField(
            model_name="pfproviderentry",
            name="partial_contribution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Contribuição parcial em outro local",
            ),
        ),
    ]
