# Generated by Django 2.2.28 on 2022-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defin", "0004_auto_20221026_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="pfproviderentry",
            name="applied_payroll",
            field=models.BooleanField(default=False, verbose_name="Aplicado em Folha"),
        ),
    ]
