# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tac", "0002_auto_20171211_0952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="process_number_fine",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
