# Generated by Django 2.2.15 on 2020-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0011_auto_20190130_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="order_weight",
            field=models.SmallIntegerField(
                blank=True, default=0, verbose_name="Peso ordenação"
            ),
        ),
        migrations.AlterField(
            model_name="classcode",
            name="typeof",
            field=models.CharField(
                choices=[
                    ("CALCULO", "Cálculos para FOPAG"),
                    ("LOADER", "Carregadores de arquivos"),
                ],
                db_index=True,
                default="CALCULO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type_of",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Numérico"), (2, "Booleano"), (3, "Texto")],
                default=3,
                null=True,
                verbose_name="Tipo",
            ),
        ),
    ]
