# Generated by Django 2.2.28 on 2022-11-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0013_auto_20220718_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classcode",
            name="typeof",
            field=models.CharField(
                choices=[
                    ("CALCULO", "Cálculos para FOPAG"),
                    ("LOADER", "Carregadores de arquivos"),
                    ("JOB", "Executor de Tarefas"),
                ],
                db_index=True,
                default="CALCULO",
                max_length=20,
            ),
        ),
    ]
