# Generated by Django 2.2.28 on 2022-12-07 11:22

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.core.management import call_command
import os


FIXTURES = ("fixtures/initialdb_0003_controllers.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "standard", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0014_auto_20221117_1647"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=150, verbose_name="Local")),
                (
                    "prosecution",
                    models.CharField(max_length=150, verbose_name="Promotoria"),
                ),
                ("network", models.CharField(max_length=20, verbose_name="Rede")),
                (
                    "initial_ip",
                    models.CharField(max_length=20, verbose_name="IP inicial"),
                ),
                ("final_ip", models.CharField(max_length=20, verbose_name="IP Final")),
            ],
        ),
        migrations.RunPython(up, down),
    ]
