# Generated by Django 2.2.28 on 2022-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0015_configpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configpoint",
            name="final_ip",
        ),
        migrations.RemoveField(
            model_name="configpoint",
            name="initial_ip",
        ),
    ]
