# Generated by Django 2.2.28 on 2023-01-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0016_auto_20221207_1726"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Assunto"
                    ),
                ),
                (
                    "contents",
                    models.TextField(blank=True, null=True, verbose_name="Conteúdo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
        ),
    ]
