# Generated by Django 2.2.28 on 2023-01-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0017_emailtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="JustificationItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="standard.Item",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "max_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Máximo em horas"
                    ),
                ),
                (
                    "min_value",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mínimo em horas"
                    ),
                ),
            ],
            options={
                "ordering": ("configuration", "value"),
            },
            bases=("standard.item",),
        ),
    ]
