# Generated by Django 2.2.28 on 2023-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0018_justificationitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="justificationitem",
            options={"ordering": ("configuration", "key")},
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="all_tbp",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Todos Tipos de Servidor",
            ),
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="paid",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Sim"), (2, "Não")],
                default=3,
                null=True,
                verbose_name="Abonado?",
            ),
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="payroll",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Folha"
            ),
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="premium_license",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Licença Prêmio"
            ),
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="type_by_possession",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tipo de Servidor"
            ),
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="vertical_progression",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Progressão Vertical"
            ),
        ),
    ]
