# Generated by Django 2.2.28 on 2023-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0019_auto_20230414_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="justificationitem",
            name="mandatory_document",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Sim"), (2, "Não")],
                default=2,
                null=True,
                verbose_name="Documento Obrigatório?",
            ),
        ),
    ]
