# Generated by Django 2.2.28 on 2023-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0021_load_resident_choices_fixtures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configpoint",
            options={"ordering": ["place", "prosecution"]},
        ),
        migrations.AddField(
            model_name="justificationitem",
            name="gera_falta",
            field=models.IntegerField(
                choices=[(1, "Sim"), (2, "Não")], default=1, verbose_name="Gera Falta"
            ),
        ),
    ]
