# Generated by Django 2.2.28 on 2024-11-26 14:12
import os
from django.conf import settings
from django.core.management import call_command
from django.db import migrations

FIXTURES = ("fixtures/gratifications_vacation_servers.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "standard", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0049_load_fixture_config_email__teletrabalho_bloqueado"),
    ]

    operations = [migrations.RunPython(forward, backward)]
