# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_auto_20160510_0854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="common",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="edge",
            name="edge_hash",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="common_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="workflow_child",
                serialize=False,
                to="workflow.Common",
            ),
        ),
    ]
