# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0002_auto_20150810_1114"),
        ("afastamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gecap", "0003_auto_20150810_1114"),
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="afastamento",
            field=models.ForeignKey(
                related_name="substituicao",
                to="afastamento.BaseLicencaAfastamento",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="posse",
            field=models.ForeignKey(
                related_name="substituicoes",
                to="rh.MovimentacaoPosse",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="publicacao_fim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="servidor_substituido",
            field=models.ForeignKey(
                related_name="substituido",
                verbose_name="Servidor substitu\xeddo",
                blank=True,
                to="rh.Servidor",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoreversao",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_reversao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaorequisicao",
            name="orgao_origem",
            field=models.ForeignKey(
                related_name="requisicao_origem",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.UnidadeAdministrativa",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaorequisicao",
            name="posse_origem",
            field=models.ForeignKey(
                related_name="requisicao",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocaomembro",
            name="lotacao_destino",
            field=models.ForeignKey(
                related_name="lotacao_remocao_membro",
                verbose_name="Lota\xe7\xe3o de destino",
                blank=True,
                to="rh.Lotacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocaomembro",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_remocaomembro",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocaomembro",
            name="servidor_permuta",
            field=models.ForeignKey(
                related_name="permuta_remocao_membro",
                verbose_name="Servidor da permuta",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocao",
            name="lotacao_destino",
            field=models.ForeignKey(
                related_name="lotacao_remocao",
                verbose_name="Lota\xe7\xe3o de destino",
                blank=True,
                to="rh.Lotacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocao",
            name="permuta",
            field=models.ForeignKey(
                blank=True,
                to="rh.MovimentacaoRemocao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoremocao",
            name="servidor_permuta",
            field=models.ForeignKey(
                related_name="permuta_remocao",
                verbose_name="Servidor da permuta",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoreintegracao",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_reintegracao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoredistribuicao",
            name="movimentacao_posse",
            field=models.ForeignKey(
                related_name="posse",
                verbose_name="Posse",
                to="rh.MovimentacaoPosse",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoredistribuicao",
            name="orgao_destino",
            field=models.ForeignKey(
                related_name="orgao_destino",
                verbose_name="\xd3rg\xe3o Destino",
                blank=True,
                to="rh.UnidadeAdministrativa",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoredistribuicao",
            name="quadro",
            field=models.ForeignKey(
                related_name="quadro",
                verbose_name="Cargo",
                to="rh.Quadro",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoreconducao",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_reconducao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoreadaptacao",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_readaptacao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopromocao",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_promocao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="anotacao_geral_exercicio",
            field=models.ForeignKey(
                related_name="anotgeral_exercicio",
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                to="rh.AnotacaoGeral",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="anotacao_geral_nomeacao",
            field=models.ForeignKey(
                related_name="anotgeral_nomeacao",
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                to="rh.AnotacaoGeral",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="public_concurrence",
            field=models.ForeignKey(
                related_name="employees",
                verbose_name="Concurso",
                blank=True,
                to="rh.PublicConcurrence",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="quadro",
            field=models.ForeignKey(
                blank=True, to="rh.Quadro", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="anotacao_geral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                verbose_name="Anota\xe7\xe3o Geral",
                blank=True,
                to="rh.AnotacaoGeral",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="publicacao_alteracao",
            field=models.ForeignKey(
                related_name="movimentacao",
                verbose_name="Publica\xe7\xe3o Altera\xe7\xe3o",
                blank=True,
                to="rh.Publicacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="publicacao_movimentacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                verbose_name="Publica\xe7\xe3o Movimenta\xe7\xe3o",
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="servidor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                verbose_name="Servidor",
                blank=True,
                to="rh.Servidor",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoestabilizacao",
            name="posse",
            field=models.ForeignKey(
                related_name="estabilizacoes",
                to="rh.MovimentacaoPosse",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaodesligamento",
            name="movimentacao_posse",
            field=models.ForeignKey(
                related_name="desligamento",
                to="rh.MovimentacaoPosse",
                unique=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacaoaproveitamento",
            name="posse_anterior",
            field=models.ForeignKey(
                related_name="posse_aproveitamento",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.MovimentacaoPosse",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="molestia",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="molestia",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="molestia",
            name="publicacao",
            field=models.ForeignKey(
                verbose_name="Laudo",
                blank=True,
                to="rh.Publicacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="microregiao",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="microregiao",
            name="meso_regiao",
            field=models.ForeignKey(
                to="rh.MesoRegiao", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="microregiao",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="mesoregiao",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="mesoregiao",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="comarca",
            field=models.ForeignKey(
                blank=True, to="rh.Comarca", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="entrancia",
            field=models.ForeignKey(
                verbose_name="Entr\xe2ncia",
                blank=True,
                to="rh.Entrancia",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="grupo",
            field=models.ManyToManyField(to="rh.Lotacao", null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="instancia",
            field=models.ForeignKey(
                verbose_name="Inst\xe2ncia",
                blank=True,
                to="rh.Instancia",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="localidade",
            field=models.ForeignKey(
                to="rh.Localidade", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="pai",
            field=models.ForeignKey(
                related_name="lotacoes_subordinadas",
                verbose_name="Lota\xe7\xe3o superior",
                blank=True,
                to="rh.Lotacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="responsavel",
            field=models.ForeignKey(
                related_name="responsavel_por",
                verbose_name="Respons\xe1vel",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="lotacao",
            name="responsible_substituted",
            field=models.ForeignKey(
                verbose_name="Respons\xe1vel substitu\xeddo",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localidade",
            name="comarca",
            field=models.ForeignKey(
                blank=True, to="rh.Comarca", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localidade",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localidade",
            name="estado",
            field=models.ForeignKey(
                to="rh.Estado", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localidade",
            name="microregiao",
            field=models.ForeignKey(
                blank=True, to="rh.MicroRegiao", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localidade",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="instancia",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="instancia",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="incapacidade",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="incapacidade",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="afastamento",
            field=models.ForeignKey(
                related_name="inativacaocargomembro",
                to="afastamento.BaseLicencaAfastamento",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="publicacao_alteracao",
            field=models.ForeignKey(
                related_name="inativacao",
                verbose_name="Documento Revoga\xe7\xe3o",
                blank=True,
                to="rh.Publicacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="publicacao_ativacao",
            field=models.ForeignKey(
                related_name="agendamentoinativacao_publicacao_ativacao",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="inativacaocargomembro",
            name="publicacao_inativacao",
            field=models.ForeignKey(
                related_name="agendamentoinativacao_publicacao_inativacao",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="grupocomarca",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="grupocomarca",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="grauinstrucao",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="grauinstrucao",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="estado",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="estado",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="estado",
            name="pais",
            field=models.ForeignKey(
                verbose_name="Pa\xeds", to="rh.Pais", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="especialidade",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="especialidade",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="entrancia",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="entrancia",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="endereco",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="endereco",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="endereco",
            name="municipio",
            field=models.ForeignKey(
                to="rh.Localidade", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="encargofinanceiro",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="encargofinanceiro",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="encargofinanceiro",
            name="requisicao",
            field=models.ForeignKey(
                related_name="encargos_financeiros",
                to="rh.MovimentacaoRequisicao",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documentodigital",
            name="arquivo",
            field=models.ForeignKey(
                verbose_name="Arquivo",
                blank=True,
                to="ged.Arquivo",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documentodigital",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documentodigital",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="arquivo",
            field=models.ForeignKey(
                blank=True, to="ged.Arquivo", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="dados_especificos",
            field=models.ManyToManyField(
                to="rh.DocsDadosEspecificos",
                null=True,
                verbose_name="Dados Espec\xedficos",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="estado_expedicao",
            field=models.ForeignKey(
                verbose_name="Estado de Expedi\xe7\xe3o",
                blank=True,
                to="rh.Estado",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="docsdadosespecificos",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="docsdadosespecificos",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependente",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependente",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependente",
            name="pessoa_fisica",
            field=models.ForeignKey(
                related_name="dependentes_pessoa",
                verbose_name="Pessoa F\xedsica",
                to="rh.PessoaFisica",
                unique=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependente",
            name="responsavel",
            field=models.ForeignKey(
                related_name="dependentes_",
                verbose_name="Respons\xe1vel",
                blank=True,
                to="rh.PessoaFisica",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependente",
            name="servidor",
            field=models.ForeignKey(
                related_name="dependentes",
                verbose_name="Servidor",
                to="rh.Servidor",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependencia",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependencia",
            name="dependente",
            field=models.ForeignKey(
                related_name="dependencias",
                verbose_name="Depend\xeancia",
                to="rh.Dependente",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dependencia",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name="dependencia",
            unique_together=set([("dependente", "tipo")]),
        ),
        migrations.AddField(
            model_name="declaracaoatividade",
            name="lotacao",
            field=models.ForeignKey(
                verbose_name="Lota\xe7\xe3o estagi\xe1rio",
                blank=True,
                to="rh.Lotacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="declaracaoatividade",
            name="quadro",
            field=models.ForeignKey(
                blank=True, to="rh.Quadro", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dadobancariopessoa",
            name="pessoa",
            field=models.ForeignKey(
                related_name="dadosbancarios", to="rh.Pessoa", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dadobancarioconsignatario",
            name="pessoa_juridica",
            field=models.ForeignKey(
                to="rh.PessoaJuridica", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="banco",
            field=models.ForeignKey(
                to="rh.Banco", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="curso",
            name="area_conhecimento",
            field=models.ForeignKey(
                verbose_name="\xc1rea de conhecimento",
                to="gecap.AreaConhecimento",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="curso",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="curso",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="comarca",
            name="circunscricao",
            field=models.ForeignKey(
                blank=True, to="rh.Circunscricao", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="comarca",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="comarca",
            name="grupo_comarca",
            field=models.ForeignKey(
                blank=True, to="rh.GrupoComarca", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="comarca",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="circunscricao",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="circunscricao",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoprevidenciario",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoprevidenciario",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoprevidenciario",
            name="servidor",
            field=models.ForeignKey(
                verbose_name="Servidor", to="rh.Servidor", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoestudo",
            name="cidade",
            field=models.ForeignKey(
                blank=True, to="rh.Localidade", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoestudo",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoestudo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="censoestudo",
            name="servidor",
            field=models.ForeignKey(
                verbose_name="Servidor", to="rh.Servidor", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cbo",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cbo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="carreira",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="carreira",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="cargo",
            field=models.ForeignKey(
                related_name="quadros", to="rh.Cargo", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="especialidade",
            field=models.ForeignKey(
                blank=True, to="rh.Especialidade", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="publicacao_alteracao",
            field=models.ForeignKey(
                related_name="publicacao_alteracao",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="publicacao_criacao",
            field=models.ForeignKey(
                related_name="publicacao_criacao",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="publicacao_extincao",
            field=models.ForeignKey(
                related_name="publicacao_publicacao",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="carreira",
            field=models.ForeignKey(
                blank=True, to="rh.Carreira", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="cbo",
            field=models.ForeignKey(
                to="rh.Cbo", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="entrancia",
            field=models.ForeignKey(
                verbose_name="Entr\xe2ncia",
                blank=True,
                to="rh.Entrancia",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="instancia",
            field=models.ForeignKey(
                verbose_name="Inst\xe2ncia",
                blank=True,
                to="rh.Instancia",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="lotacao_responsavel",
            field=models.ForeignKey(
                related_name="cargo_responsavel",
                verbose_name="Respons\xe1vel pela Lota\xe7\xe3o",
                blank=True,
                to="rh.Lotacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargo",
            name="unidade_administrativa",
            field=models.ForeignKey(
                verbose_name="\xd3rg\xe3o",
                to="rh.UnidadeAdministrativa",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="anotacao_geral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                verbose_name="Anota\xe7\xe3o Geral",
                blank=True,
                to="rh.AnotacaoGeral",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="publicacao",
            field=models.ForeignKey(
                blank=True, to="rh.Publicacao", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="servidor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                verbose_name="Servidor",
                blank=True,
                to="rh.Servidor",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="capacidade",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="capacidade",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="banco",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="banco",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="banco",
            name="pessoajuridica",
            field=models.ForeignKey(
                related_name="como_banco",
                to="rh.PessoaJuridica",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anothorespdados",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anothorespdados",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="pessoa_juridica",
            field=models.ForeignKey(
                verbose_name="Pessoa Jur\xeddica",
                blank=True,
                to="rh.PessoaJuridica",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="tempo_servico_finalidade",
            field=models.ForeignKey(
                to="rh.TempoServicoFinalidade", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="unidade_administrativa",
            field=models.ForeignKey(
                blank=True,
                to="rh.UnidadeAdministrativa",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaopenadisciplinar",
            name="penalidade",
            field=models.ForeignKey(
                to="rh.Penalidade", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaopenadisciplinar",
            name="responsavel",
            field=models.ForeignKey(
                verbose_name="Respons\xe1vel",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaohorarioespecial",
            name="dados_horario",
            field=models.ManyToManyField(
                to="rh.AnotHorEspDados",
                null=True,
                verbose_name="Dados Hor\xe1rio",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaogeral",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaogeral",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaogeral",
            name="movimento_origem",
            field=models.ForeignKey(
                related_name="anotacoes",
                blank=True,
                to="rh.MovimentacaoPessoal",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaogeral",
            name="publicacao",
            field=models.ForeignKey(
                verbose_name="Publica\xe7\xe3o",
                blank=True,
                to="rh.Publicacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaogeral",
            name="servidor",
            field=models.ForeignKey(
                related_name="anotacoes",
                verbose_name="Servidor",
                to="rh.Servidor",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaoevento",
            name="certificado",
            field=models.ForeignKey(
                related_name="anotacao_evento",
                verbose_name="Certificado",
                blank=True,
                to="ged.Arquivo",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaoevento",
            name="patrocinador",
            field=models.ForeignKey(
                default=None,
                blank=True,
                to="rh.Patrocinador",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaoenquadramento",
            name="quadro",
            field=models.ForeignKey(
                to="rh.Quadro", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anotacaoelogio",
            name="responsavel",
            field=models.ForeignKey(
                blank=True, to="rh.PessoaFisica", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
    ]
