# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0068_datamigration_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replacement",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="out_off_distribution_list",
            field=models.BooleanField(
                default=False, verbose_name="Fora da lista de distribui\xe7\xe3o"
            ),
        ),
        migrations.AlterField(
            model_name="anotacaogeral",
            name="tipo_documento",
            field=models.IntegerField(
                verbose_name="Tipo Documento",
                choices=[
                    (3, "PORTARIA"),
                    (1, "ATO"),
                    (2, "DECRETO"),
                    (4, "OF\xcdCIO"),
                    (5, "DESPACHO"),
                    (6, "TERMO"),
                    (7, "MEMORANDO"),
                    (8, "REQUERIMENTO"),
                    (9, "CONCESS\xc3O"),
                    (10, "ACORDO COOPERA\xc7\xc3O T\xc9CNICA"),
                    (11, "LEI"),
                    (12, "APOSTILA"),
                    (14, "DECRETO LEGISLATIVO"),
                    (15, "RESOLU\xc7\xc3O"),
                    (16, "CIRCULAR"),
                    (17, "PROCESSO"),
                    (18, "DECIS\xc3O"),
                    (95, "DECLARA\xc7\xc3O DE ENTRADA EM ATIVIDADE"),
                    (96, "TERMO LOTA\xc7\xc3O"),
                    (97, "TERMO EXERC\xcdCIO"),
                    (98, "TERMO POSSE"),
                    (99, "OUTROS"),
                    (100, "DOCUMENTO DIGITAL"),
                    (101, "PORTARIA DE INSTAURA\xc7\xc3O"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="cumulative",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="Acumul\xe1vel",
                choices=[
                    (1, "N\xc3O ACUMUL\xc1VEL"),
                    (2, "PROFISSIONAL DE SA\xdaDE"),
                    (3, "PROFESSOR"),
                    (4, "T\xc9CNICO/CIENT\xcdFICO"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="cumulative",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="Acumul\xe1vel",
                choices=[
                    (1, "N\xc3O ACUMUL\xc1VEL"),
                    (2, "PROFISSIONAL DE SA\xdaDE"),
                    (3, "PROFESSOR"),
                    (4, "T\xc9CNICO/CIENT\xcdFICO"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dependente",
            name="tipo",
            field=models.IntegerField(
                null=True,
                verbose_name="Tipo",
                choices=[
                    (1, "C\xd4NJUGE"),
                    (2, "COMPANHEIRO(A) - UNI\xc3O EST\xc1VEL"),
                    (3, "FILHO(A) N\xc3O EMANCIPADO MENOR DE 21 ANOS"),
                    (4, "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (5, "PAI(M\xc3E) COM DEPEND\xcaNCIA ECON\xd4MICA"),
                    (
                        6,
                        "IRM\xc3O N\xc3O EMANCIPADO MENOR DE 21 ANOS COM DEPEND\xcaNCIA ECON\xd4MICA E GUARDA JUDICIAL",
                    ),
                    (7, "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (8, "ENTEADO N\xc3O EMANCIPADO MENOR DE 21"),
                    (9, "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (
                        10,
                        "MENOR TUTELADO N\xc3O EMANCIPADO MENOR DE 21 ANOS COM DEPEND\xcaNCIA ECON\xd4MICA OU GUARDA JUDICIAL",
                    ),
                    (11, "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (12, "AV\xd3S COM DEPENDENCIA ECONOMICA"),
                    (13, "BISAV\xd3S COM DEPENDENCIA ECONOMICA"),
                    (
                        14,
                        "NETO(A) N\xc3O EMANCIPADO MENOR DE 21 ANOS COM DEPEND\xcaNCIA ECON\xd4MICA E GUARDA JUDICIAL",
                    ),
                    (
                        15,
                        "BISNETO(A) N\xc3O EMANCIPADO MENOR DE 21 ANOS COM DEPEND\xcaNCIA ECON\xd4MICA E GUARDA JUDICIAL",
                    ),
                    (16, " EX-C\xd4NJUGE"),
                    (
                        17,
                        "FILHO(A) OU ENTEADO(A) UNIVERSIT\xc1RIO(A) OU CURSANDO ESCOLA T\xc9CNICA DE 2\xbaGRAU, AT\xc9 24 ANOS",
                    ),
                    (18, "AGREGADO/OUTROS"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                verbose_name="Tipo de Documento",
                choices=[
                    (56, "COMPROVANTE VOTA\xc7\xc3O 2018 - GERAL"),
                    (55, "COMPROVANTE VOTA\xc7\xc3O 2018 - SUPLEMENTAR"),
                    (1, "T\xcdTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTID\xc3O DE NASCIMENTO"),
                    (51, "CERTID\xc3O DE CASAMENTO"),
                    (52, "COMPROVANTE DE ENDERE\xc7O"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="docsdadosespecificos",
            name="especificidade",
            field=models.IntegerField(
                verbose_name="Especificidade",
                choices=[
                    (1, "T\xcdTULO DE ELEITOR.ZONA"),
                    (2, "T\xcdTULO DE ELEITOR.SE\xc7\xc3O"),
                    (3, "T\xcdTULO DE ELEITOR.UF"),
                    (4, "CNH.CATEGORIA"),
                    (5, "RESERVISTA.CLASSE"),
                    (6, "CTPS.S\xc9RIE"),
                    (7, "T\xcdTULO DE ELEITOR.MUNICIPIO"),
                    (8, "CTPS.UF"),
                    (9, "RIC.EMISSOR"),
                    (10, "RNE.EMISSOR"),
                    (11, "CONSELHO PROFISSIONAL.EMISSOR"),
                    (12, "CNH.DATA PRIMEIRA HABILITA\xc7\xc3O"),
                    (13, "RG.\xd3RG\xc3O EMISSOR"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="legalprocess",
            name="cod_authorship",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Autoria",
                choices=[
                    (1, "Pr\xf3prio contribuinte"),
                    (2, "Outra entidade, empresa ou empregado"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="legalprocess",
            name="matter_process",
            field=models.PositiveSmallIntegerField(
                verbose_name="Mat\xe9ria do processo",
                choices=[
                    (1, "Tribut\xe1ria"),
                    (2, "Autoriza\xe7\xe3o de trabalho de menor"),
                    (
                        3,
                        "Dispensa, ainda que parcial, de contrata\xe7\xe3o de pessoa com defici\xeancia (PCD)",
                    ),
                    (
                        4,
                        "Dispensa, ainda que parcial, de contrata\xe7\xe3o de aprendiz",
                    ),
                    (5, "Seguran\xe7a e Sa\xfade do Trabalho"),
                    (6, "Convers\xe3o de Licen\xe7a Sa\xfade em Acidente de Trabalho"),
                    (
                        7,
                        "FGTS ou Contribui\xe7\xe3o Social Rescis\xf3ria (Lei Complementar 110/2001)",
                    ),
                    (8, "Contribui\xe7\xe3o sindical"),
                    (9, "Contribui\xe7\xf5es para o RPPS/regime militar"),
                    (99, "Outros assuntos"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="legalprocess",
            name="type_process",
            field=models.PositiveIntegerField(
                verbose_name="Tipo de processo",
                choices=[
                    (1, "Administrativo"),
                    (2, "Judicial"),
                    (3, "N\xfamero de Benef\xedcio (NB) do INSS"),
                    (4, "Processo FAP"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="processsuspension",
            name="extension_decision",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="Extens\xe3o",
                choices=[
                    (1, "Contribui\xe7\xe3o Previdenci\xe1ria Patronal"),
                    (
                        2,
                        "Contribui\xe7\xe3o Previdenci\xe1ria Patronal + Descontada dos Segurados",
                    ),
                    (3, "Descontada dos Segurados"),
                    (99, "N\xe3o se aplica"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="processsuspension",
            name="indicative_suspension",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Indicativo suspens\xe3o",
                choices=[
                    (1, "Liminar em Mandado de Seguran\xe7a"),
                    (2, "Dep\xf3sito Judicial do Montante Integral"),
                    (3, "Dep\xf3sito Administrativo do Montante Integral"),
                    (4, "Antecipa\xe7\xe3o de Tutela"),
                    (5, "Liminar em Medida Cautelar"),
                    (
                        8,
                        "Senten\xe7a em Mandado de Seguran\xe7a Favor\xe1vel ao Contribuinte",
                    ),
                    (
                        9,
                        "Senten\xe7a em A\xe7\xe3o Ordin\xe1ria Favor\xe1vel ao Contribuinte e Confirmada",
                    ),
                    (10, "Ac\xf3rd\xe3o do TRF Favor\xe1vel ao Contribuinte"),
                    (
                        11,
                        "Ac\xf3rd\xe3o do STJ em Recurso Especial Favor\xe1vel ao Contribuinte",
                    ),
                    (
                        12,
                        "Ac\xf3rd\xe3o do STF em Recurso Extraordin\xe1rio Favor\xe1vel ao Contribuinte",
                    ),
                    (
                        13,
                        "Senten\xe7a 1a inst\xe2ncia n\xe3o transitada em julgado com efeito suspensivo",
                    ),
                    (14, "Contesta\xe7\xe3o Administrativa FAP"),
                    (90, "Decis\xe3o Definitiva a favor do contribuinte"),
                    (92, "Sem suspens\xe3o da exigibilidade"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="processsuspension",
            name="scope_decision",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="Abrang\xeancia",
                choices=[
                    (1, "IRRF"),
                    (2, "Contribui\xe7\xf5es Sociais do Trabalhador"),
                    (3, "FGTS"),
                    (4, "Contribui\xe7\xe3o sindical"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="tipo",
            field=models.IntegerField(
                verbose_name="Tipo de Publica\xe7\xe3o",
                choices=[
                    (3, "PORTARIA"),
                    (1, "ATO"),
                    (2, "DECRETO"),
                    (4, "OF\xcdCIO"),
                    (5, "DESPACHO"),
                    (6, "TERMO"),
                    (7, "MEMORANDO"),
                    (8, "REQUERIMENTO"),
                    (9, "CONCESS\xc3O"),
                    (10, "ACORDO COOPERA\xc7\xc3O T\xc9CNICA"),
                    (11, "LEI"),
                    (12, "APOSTILA"),
                    (14, "DECRETO LEGISLATIVO"),
                    (15, "RESOLU\xc7\xc3O"),
                    (16, "CIRCULAR"),
                    (17, "PROCESSO"),
                    (18, "DECIS\xc3O"),
                    (95, "DECLARA\xc7\xc3O DE ENTRADA EM ATIVIDADE"),
                    (96, "TERMO LOTA\xc7\xc3O"),
                    (97, "TERMO EXERC\xcdCIO"),
                    (98, "TERMO POSSE"),
                    (99, "OUTROS"),
                    (100, "DOCUMENTO DIGITAL"),
                    (101, "PORTARIA DE INSTAURA\xc7\xc3O"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="veiculo_publicacao",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Ve\xedculo Publica\xe7\xe3o",
                choices=[
                    (34, "DI\xc1RIO ELETR\xd4NICO DO MPE"),
                    (1, "DOE ACRE"),
                    (2, "DOE AMAPA"),
                    (3, "DOE AMAZONAS"),
                    (4, "DOE RORAIMA"),
                    (5, "DOE RONDONIA"),
                    (6, "DOE PARA"),
                    (7, "DOE TOCANTINS"),
                    (8, "DOE CEARA"),
                    (9, "DOE RIO GRANDE DO NORTE"),
                    (10, "DOE PERNAMBUCO"),
                    (11, "DOE PARAIBA"),
                    (12, "DOE SERGIPE"),
                    (13, "DOE BAHIA"),
                    (14, "DOE MARANHAO"),
                    (15, "DOE PIAUI"),
                    (16, "DOE MINAS GERAIS"),
                    (17, "DOE SAO PAULO"),
                    (18, "DOE ESPIRITO SANTO"),
                    (19, "DOE RIO DE JANEIRO"),
                    (21, "DOE PARANA"),
                    (22, "DOE SANTA CATARINA"),
                    (23, "DOE RIO GRANDE DO SUL"),
                    (24, "DOE MATO GROSSO DO SUL"),
                    (25, "DOE GOIAS"),
                    (26, "DOE DISTRITO FEDERAL"),
                    (27, "DOE MATO GROSSO"),
                    (28, "DIARIO JUSTICA"),
                    (29, "DIARIO JUSTICA ELEITORAL"),
                    (30, "DIARIO OFICIAL DA UNIAO"),
                    (31, "DIARIO OFICIAL DO MUNICIPIO DE PALMAS TO"),
                    (32, "REGISTRO CIVIL DAS PESSOAS NATURAIS"),
                    (33, "PLACAR"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="legal_nature",
            field=models.IntegerField(
                default=1058,
                blank=True,
                verbose_name="Natureza jur\xeddica",
                choices=[
                    (1015, "\xd3rg\xe3o P\xfablico do Poder Executivo Federal"),
                    (
                        1023,
                        "\xd3rg\xe3o P\xfablico do Poder Executivo Estadual ou do Distrito Federal",
                    ),
                    (1031, "\xd3rg\xe3o P\xfablico do Poder Executivo Municipal"),
                    (1040, "\xd3rg\xe3o P\xfablico do Poder Legislativo Federal"),
                    (
                        1058,
                        "\xd3rg\xe3o P\xfablico do Poder Legislativo Estadual ou do Distrito Federal",
                    ),
                    (1066, "\xd3rg\xe3o P\xfablico do Poder Legislativo Municipal"),
                    (1074, "\xd3rg\xe3o P\xfablico do Poder Judici\xe1rio Federal"),
                    (1082, "\xd3rg\xe3o P\xfablico do Poder Judici\xe1rio Estadual"),
                    (1104, "Autarquia Federal"),
                    (1112, "Autarquia Estadual ou do Distrito Federal"),
                    (1120, "Autarquia Municipal"),
                    (1139, "Funda\xe7\xe3o P\xfablica de Direito P\xfablico Federal"),
                    (
                        1147,
                        "Funda\xe7\xe3o P\xfablica de Direito P\xfablico Estadual ou do Distrito Federal",
                    ),
                    (1155, "Funda\xe7\xe3o P\xfablica de Direito P\xfablico Municipal"),
                    (1163, "\xd3rg\xe3o P\xfablico Aut\xf4nomo Federal"),
                    (
                        1171,
                        "\xd3rg\xe3o P\xfablico Aut\xf4nomo Estadual ou do Distrito Federal",
                    ),
                    (1180, "\xd3rg\xe3o P\xfablico Aut\xf4nomo Municipal"),
                    (1198, "Comiss\xe3o Polinacional"),
                    (1201, "Fundo P\xfablico"),
                    (
                        1210,
                        "Cons\xf3rcio P\xfablico de Direito P\xfablico (Associa\xe7\xe3o P\xfablica)",
                    ),
                    (1228, "Cons\xf3rcio P\xfablico de Direito Privado"),
                    (1236, "Estado ou Distrito Federal"),
                    (1244, "Munic\xedpio"),
                    (1252, "Funda\xe7\xe3o P\xfablica de Direito Privado Federal"),
                    (
                        1260,
                        "Funda\xe7\xe3o P\xfablica de Direito Privado Estadual ou do Distrito Federal",
                    ),
                    (1279, "Funda\xe7\xe3o P\xfablica de Direito Privado Municipal"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="subtetus_reference",
            field=models.IntegerField(
                default=1,
                blank=True,
                verbose_name="Poder que se refere o subteto",
                choices=[
                    (1, "Executivo"),
                    (2, "Judici\xe1rio"),
                    (3, "Legislativo"),
                    (9, "Todos os poderes"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="tax_classification",
            field=models.IntegerField(
                default=1,
                blank=True,
                verbose_name="Classifica\xe7\xe3o tribut\xe1ria",
                choices=[
                    (
                        1,
                        "Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1riasubstitu\xedda",
                    ),
                    (
                        2,
                        "Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1ria n\xe3osubstitu\xedda",
                    ),
                    (
                        3,
                        "Empresa enquadrada no regime de tributa\xe7\xe3o Simples Nacional com tributa\xe7\xe3o previdenci\xe1riasubstitu\xedda e n\xe3o substitu\xedda",
                    ),
                    (4, "MEI - Micro Empreendedor Individual"),
                    (6, "Agroind\xfastria"),
                    (8, "Cons\xf3rcio Simplificado de Produtores Rurais"),
                    (9, "\xd3rg\xe3o Gestor de M\xe3o de Obra"),
                    (10, "Entidade Sindical a que se refere a Lei 12.023/2009"),
                    (
                        11,
                        "Associa\xe7\xe3o Desportiva que mant\xe9m Clube de Futebol Profissional",
                    ),
                    (
                        13,
                        "Banco, caixa econ\xf4mica, sociedade de cr\xe9dito, financiamento e investimento e demais empresas relacionadas no par\xe1grafo",
                    ),
                    (
                        14,
                        "Sindicatos em geral, exceto aquele classificado no c\xf3digo [10]",
                    ),
                    (21, "Pessoa F\xedsica, exceto Segurado Especial"),
                    (22, "Segurado Especial"),
                    (
                        60,
                        "Miss\xe3o Diplom\xe1tica ou Reparti\xe7\xe3o Consular de carreira estrangeira",
                    ),
                    (70, "Empresa de que trata o Decreto 5.436/2005"),
                    (
                        80,
                        "Entidade Beneficente de Assist\xeancia Social isenta de contribui\xe7\xf5es sociais",
                    ),
                    (
                        85,
                        "Administra\xe7\xe3o Direta da Uni\xe3o, Estados, Distrito Federal e Munic\xedp\xedos; Autarquias e Funda\xe7\xf5es P\xfablicas",
                    ),
                    (99, "Pessoas Jur\xeddicas em Geral"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="workhourinterval",
            name="type_interval",
            field=models.IntegerField(
                default=2, choices=[(1, "FIXO"), (2, "VARI\xc1VEL")]
            ),
        ),
    ]
