# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-13 14:10
from __future__ import unicode_literals

from django.db import migrations, models

from datetime import datetime


def _null_function(apps, schema_editor):
    pass


def update_active_workload(apps, schema_editor):

    WorkLoad = apps.get_model("rh", "CargaHoraria")
    today = datetime.now().date()
    query = WorkLoad.objects.filter(
        models.Q(data_inicio__lte=today)
        & (models.Q(data_fim__gte=today) | models.Q(data_fim=None))
    )
    count = 0
    total = query.count()
    for one in query:
        count += 1
        WorkLoad.objects.filter(pk=one.pk).update(active=True)
        print("TOTAL ... %s - > %s" % (total, count))


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0088_auto_20190506_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargahoraria",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="class_organ",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Conselho Regional de Medicina (CRM)"),
                    (2, "Conselho Regional de Odontologia (CRO)"),
                    (3, "Registro do Minist\xe9rio da Sa\xfade (RMS)"),
                    (99, "Outros"),
                ],
                default=99,
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="categoria_cache",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="workhourinterval",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Dura\xe7\xe3o"),
        ),
        migrations.RunPython(update_active_workload, _null_function),
    ]
