# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0091_loadfixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGI\xc1RIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNT\xc1RIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM V\xcdNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUN\xc7\xc3O"),
                    ("EFC", "SERVIDOR EFETIVO COM FUN\xc7\xc3O"),
                    ("JCA", "JOVEM CIDAD\xc3O - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo",
            ),
        ),
    ]
