# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0092_auto_20190617_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacaoferias",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTERRUPCAO", "Interrup\xe7\xe3o"),
                    ("HOMOLOGACAO", "Homologa\xe7\xe3o"),
                    ("ALTERACAO", "Altera\xe7\xe3o"),
                    ("SUSPENSAO", "Suspens\xe3o"),
                    ("MARCACAO", "Marca\xe7\xe3o"),
                ],
                default="HOMOLOGACAO",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoestabilizacao",
            name="data_vigencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="In\xedcio vig\xeancia"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="judicial_decision",
            field=models.BooleanField(
                default=False, verbose_name="Decorrente de decis\xe3o judicial"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="judicial_deposit",
            field=models.BooleanField(
                default=False, verbose_name="Pagamento realizado em ju\xedzo"
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="regime_previdenciario",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR")],
                default=2,
                verbose_name="Regime previdenci\xe1rio",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGI\xc1RIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNT\xc1RIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM V\xcdNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUN\xc7\xc3O"),
                    ("EFC", "SERVIDOR EFETIVO COM FUN\xc7\xc3O"),
                    ("JCA", "JOVEM CIDAD\xc3O - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2\xaa ENTR\xc2NCIA"),
                    ("MEL2", "MEMBRO DE 2\xaa ENTR\xc2NCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2\xaa ENTR\xc2NCIA COM CARGO COMISSIONADO"),
                    (
                        "MEC2",
                        "MEMBRO DE 2\xaa ENTR\xc2NCIA COM CARGO ELETIVO E COMISSIONADO",
                    ),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="socialsecurityconfig",
            name="regime",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR")],
                default=2,
                verbose_name="Regime previdenci\xe1rio",
            ),
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="vacancy_number_filled_cache",
            field=models.IntegerField(
                default=0, verbose_name="Quantidade de Vagas Preenchidas"
            ),
            preserve_default=False,
        ),
    ]
