# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0095_load_new_choice_fixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoafisica",
            name="fator_rh",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "-"), (2, "+")],
                default=3,
                null=True,
                verbose_name="Fator RH",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="sangue",
            field=models.IntegerField(
                blank=True, choices=[(1, "B"), (2, "AB"), (3, "O"), (4, "A")], default=5
            ),
        ),
    ]
