# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0096_auto_20190913_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="situacaofuncional",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cargoquadro",
            name="vacancy_number_filled_cache",
            field=models.IntegerField(
                blank=True, verbose_name="Quantidade de Vagas Preenchidas"
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="fator_rh",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "-"), (2, "+"), (3, "NAO INFORMADO")],
                default=3,
                null=True,
                verbose_name="Fator RH",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="sangue",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "B"), (2, "AB"), (3, "O"), (4, "A"), (5, "NAO INFORMADO")],
                default=5,
            ),
        ),
    ]
