# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0098_datamigration_active_functional_situation"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacaogeral",
            name="my_type",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaopessoal",
            name="my_type",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
