# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0100_datamigration_my_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitaldocument",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digital_document",
                to="rh.AnotacaoGeral",
                verbose_name="Anota\xe7\xe3o",
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="my_origin_cache_unicode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cache"
            ),
        ),
        migrations.AddField(
            model_name="digitaldocument",
            name="personal_moviment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digital_document",
                to="rh.MovimentacaoPessoal",
                verbose_name="Afastamento",
            ),
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (56, "COMPROVANTE VOTA\xc7\xc3O 2018 - GERAL"),
                    (55, "COMPROVANTE VOTA\xc7\xc3O 2018 - SUPLEMENTAR"),
                    (1, "T\xcdTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTID\xc3O DE NASCIMENTO"),
                    (51, "CERTID\xc3O DE CASAMENTO/DIV\xd3RCIO"),
                    (52, "COMPROVANTE DE ENDERE\xc7O"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTA\xc7\xc3O"),
                ],
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
