# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0102_digitaldocument_load_fixture"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeHoursWorkContractWorkload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "date_start",
                    models.DateField(verbose_name="In\xedcio de Vig\xeancia"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim de Vig\xeancia"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rh.Servidor"
                    ),
                ),
            ],
            options={
                "ordering": ("employee", "date_start"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.RenameField(
            model_name="hoursworkcontract",
            old_name="data_end",
            new_name="date_end",
        ),
        migrations.RemoveField(
            model_name="cargahoraria",
            name="workhourcontract",
        ),
        migrations.RemoveField(
            model_name="hoursworkcontractworkload",
            name="week_days",
        ),
        migrations.RemoveField(
            model_name="hoursworkcontractworkload",
            name="workhour_contract",
        ),
        migrations.RemoveField(
            model_name="hoursworkcontractworkload",
            name="workload",
        ),
        migrations.RemoveField(
            model_name="workhourinterval",
            name="data_end",
        ),
        migrations.RemoveField(
            model_name="workhourinterval",
            name="date_start",
        ),
        migrations.AddField(
            model_name="cargahoraria",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Dura\xe7\xe3o em Minutos"
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontract",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hoursworkcontract",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.Publicacao",
                verbose_name="Publica\xe7\xe3o",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=845,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day1",
                to="rh.HoursWorkContract",
                verbose_name="Domingo",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day2",
                to="rh.HoursWorkContract",
                verbose_name="Segunda",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day3",
                to="rh.HoursWorkContract",
                verbose_name="Ter\xe7a",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day4",
                to="rh.HoursWorkContract",
                verbose_name="Quarta",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day5",
                to="rh.HoursWorkContract",
                verbose_name="Quinta",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day6",
                to="rh.HoursWorkContract",
                verbose_name="Sexta",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="day_7",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workloads_day7",
                to="rh.HoursWorkContract",
                verbose_name="S\xe1bado",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                verbose_name="Dura\xe7\xe3o da Jornada em Minutos",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=845,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="quantity_active",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="texto",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cargahoraria",
            name="tipo",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="hoursworkcontract",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                verbose_name="Dura\xe7\xe3o da Jornada em Minutos",
            ),
        ),
        migrations.AlterField(
            model_name="hoursworkcontract",
            name="title",
            field=models.CharField(
                default="N\xc3O INFORMADO", max_length=100, verbose_name="T\xedtulo"
            ),
        ),
        migrations.AlterField(
            model_name="workhourinterval",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Dura\xe7\xe3o em Minutos"
            ),
        ),
        migrations.AlterField(
            model_name="workhourinterval",
            name="hours_work_contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intervals",
                to="rh.HoursWorkContract",
            ),
        ),
        migrations.AddField(
            model_name="employeehoursworkcontractworkload",
            name="hours_work_contract_workload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.HoursWorkContractWorkload",
            ),
        ),
        migrations.AddField(
            model_name="employeehoursworkcontractworkload",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="employees",
            field=models.ManyToManyField(
                related_name="hoursworkcontractworkloads",
                through="rh.EmployeeHoursWorkContractWorkload",
                to="rh.Servidor",
                verbose_name="Servidores",
            ),
        ),
        migrations.AlterModelOptions(
            name="cargahoraria",
            options={"ordering": ("servidor", "-data_inicio")},
        ),
        migrations.AddField(
            model_name="hoursworkcontract",
            name="duration_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Dura\xe7\xe3o da Jornada em Horas",
            ),
        ),
        migrations.AddField(
            model_name="hoursworkcontractworkload",
            name="duration_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Dura\xe7\xe3o da Jornada em Horas",
            ),
        ),
        migrations.AddField(
            model_name="workhourinterval",
            name="duration_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Dura\xe7\xe3o em Horas",
            ),
        ),
    ]
