# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0105_datamigration_install_hoursworkload"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="name_cache",
            field=models.CharField(default="", max_length=100, verbose_name="Nome"),
        ),
    ]
