# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0107_datamigration_name_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacaogeral",
            name="data_documento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Documento"
            ),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="name_cache",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nome"
            ),
        ),
    ]
