# Generated by Django 2.2.11 on 2020-03-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0110_datamigration_movimentacaosubstituicao_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacaoferias",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOMOLOGACAO", "Homologação"),
                    ("MARCACAO", "Marcação"),
                    ("ALTERACAO", "Alteração"),
                    ("SUSPENSAO", "Suspensão"),
                    ("INTERRUPCAO", "Interrupção"),
                ],
                default="HOMOLOGACAO",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="acumulavel",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Acumulável"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="ativo",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="designa_exercicio",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Designa Exercício"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="professor",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="remunerated",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Remunerado"
            ),
        ),
        migrations.AlterField(
            model_name="cargoquadro",
            name="health",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cargoquadro",
            name="military",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cargoquadro",
            name="teacher",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="carreira",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="configcareer",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="designates_exercise",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Designa Exercício"
            ),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="health",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="military",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="remunerated",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Remunerado"
            ),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="teacher",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="curso",
            name="grau_instrucao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "ANALFABETO"),
                    (2, "ALFABETIZADO SEM CURSOS REGULARES"),
                    (3, "FUNDAMENTAL INCOMPLETO"),
                    (4, "FUNDAMENTAL COMPLETO"),
                    (5, "MÉDIO INCOMPLETO"),
                    (6, "MÉDIO COMPLETO"),
                    (13, "TÉCNICO"),
                    (7, "SUPERIOR INCOMPLETO"),
                    (8, "SUPERIOR COMPLETO OU EQUIVALENTE LEGAL"),
                    (9, "ESPECIALIZAÇÃO/PÓS-GRADUAÇÃO"),
                    (10, "MESTRADO"),
                    (11, "DOUTORADO"),
                    (12, "PÓS-DOUTORADO"),
                ],
                default=1,
                null=True,
                verbose_name="Grau de Instrução",
            ),
        ),
        migrations.AlterField(
            model_name="dadobancariopessoa",
            name="principal",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Principal"
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoatividade",
            name="ativo",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="deficiencyinformation",
            name="quota",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Pertencente a cota"
            ),
        ),
        migrations.AlterField(
            model_name="deficiencyinformation",
            name="rehabilitation",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Reabilitação"
            ),
        ),
        migrations.AlterField(
            model_name="dependente",
            name="incapacity",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Incapacidade física/mental"
            ),
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="active",
            field=models.BooleanField(blank=True, default=False, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="employeeworkplacehistory",
            name="ordinance",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Por portaria"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="rh.Pais",
                verbose_name="País(Residentes no Exterior)",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="outsider",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Exterior"
            ),
        ),
        migrations.AlterField(
            model_name="foreigninformation",
            name="married_br",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Casado(a) com brasileiro(a)"
            ),
        ),
        migrations.AlterField(
            model_name="foreigninformation",
            name="son_br",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Filhos brasileiros"
            ),
        ),
        migrations.AlterField(
            model_name="localidade",
            name="indicador_municipio",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Indicador Município"
            ),
        ),
        migrations.AlterField(
            model_name="localidade",
            name="sede_termo",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="designacao",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="grupo_lotacao",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Grupo de Lotações"
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="organograma",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="ouvidoria",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="ativo",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="bond",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Gerar vínculo"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="out_off_distribution_list",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Fora da lista de distribuição"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="tipo_movcarreira",
            field=models.CharField(
                choices=[
                    ("NOMEACAO", "Nomeação"),
                    ("APROVEITAMENTO", "Aproveitamento"),
                    ("READAPTACAO", "Readaptação"),
                    ("RECONDUCAO", "Recondução"),
                    ("REINTEGRACAO", "Reintegração"),
                    ("REVERSAO", "Reversão"),
                    ("TITULARIZACAO", "Titularização"),
                    ("PROGRESSAO", "Progressão"),
                    ("ENQUADRAMENTO", "Enquadramento"),
                    ("REMOCAO", "Remoção"),
                    ("PROMOCAO", "Promoção"),
                ],
                default="NOMEACAO",
                max_length=30,
                verbose_name="Provimento",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosubstituicao",
            name="ordinance",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Por portaria"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosubstituicaomembro",
            name="automatic_substitute",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="doador",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Doador de órgãos"
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="has_serious_diseases",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Doença Grave"
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="necessidade_especial",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Necessidade Especial"
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="veiculo_publicacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (34, "DIÁRIO ELETRÔNICO DO MPE"),
                    (1, "DOE ACRE"),
                    (2, "DOE AMAPA"),
                    (3, "DOE AMAZONAS"),
                    (4, "DOE RORAIMA"),
                    (5, "DOE RONDONIA"),
                    (6, "DOE PARA"),
                    (7, "DOE TOCANTINS"),
                    (8, "DOE CEARA"),
                    (9, "DOE RIO GRANDE DO NORTE"),
                    (10, "DOE PERNAMBUCO"),
                    (11, "DOE PARAIBA"),
                    (12, "DOE SERGIPE"),
                    (13, "DOE BAHIA"),
                    (14, "DOE MARANHAO"),
                    (15, "DOE PIAUI"),
                    (16, "DOE MINAS GERAIS"),
                    (17, "DOE SAO PAULO"),
                    (18, "DOE ESPIRITO SANTO"),
                    (19, "DOE RIO DE JANEIRO"),
                    (21, "DOE PARANA"),
                    (22, "DOE SANTA CATARINA"),
                    (23, "DOE RIO GRANDE DO SUL"),
                    (24, "DOE MATO GROSSO DO SUL"),
                    (25, "DOE GOIAS"),
                    (26, "DOE DISTRITO FEDERAL"),
                    (27, "DOE MATO GROSSO"),
                    (28, "DIARIO JUSTICA"),
                    (29, "DIARIO JUSTICA ELEITORAL"),
                    (30, "DIARIO OFICIAL DA UNIAO"),
                    (31, "DIARIO OFICIAL DO MUNICIPIO DE PALMAS TO"),
                    (32, "REGISTRO CIVIL DAS PESSOAS NATURAIS"),
                    (33, "PLACAR"),
                    (35, "DOE MUNICÍPIO DE TOCANTÍNIA TO"),
                    (36, "DOE MINISTÉRIO PUBLICO DE GOIÁS"),
                    (37, "DOE MUNICÍPIO DE ARRAIAS TO"),
                ],
                null=True,
                verbose_name="Veículo Publicação",
            ),
        ),
        migrations.AlterField(
            model_name="quadro",
            name="requires_profissional_council",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Exige Conselho Profissional"
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="ativo",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="bond",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Cria Vínculo?"
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="situacao_funcional_cache",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Ativo: Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Ativo: Licenciado - Tratamento de Saúde"),
                    (
                        "ATIVO_LIC_DOENCA",
                        "Ativo: Licenciado - Doença em Pessoa da Família",
                    ),
                    ("ATIVO_LIC_MATERNIDADE", "Ativo: Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Ativo: Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Ativo: Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Ativo: Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Ativo: Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Ativo: Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Ativo: Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Ativo: Licenciado - Desempenho de Mandato Classista",
                    ),
                    (
                        "ATIVO_AFA_DISPONIBILIDADE",
                        "Ativo: Afastado - Em disponibilidade",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Ativo: Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Ativo: Afastado - Comparecer a juízo"),
                    (
                        "ATIVO_AFA_ELETIVO",
                        "Ativo: Afastado - Exercício de Mandato Eletivo",
                    ),
                    ("ATIVO_AFA_ESTUDAR", "Ativo: Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_MISSAO",
                        "Ativo: Afastado - Missão Oficial no Exterior",
                    ),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Ativo: Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Ativo: Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Ativo: Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Ativo: Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Ativo: Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Ativo: Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Ativo: Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ativo: Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ativo: Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ativo: Ausente - Casamento"),
                    (
                        "ATIVO_AUS_NASCIMENTO",
                        "Ativo: Ausente - Nascimento/adoção de filho",
                    ),
                    ("ATIVO_AUS_FALECIMENTO", "Ativo: Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ativo: Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Ativo: Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Ativo: Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Ativo: Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Ativo: Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Ativo: Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Ativo: Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Ativo: Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_SAUDEMULHER", "Ativo: Fruindo Folga Saúde Mulher"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Ativo: Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Ativo: Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Ativo: Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Ativo: - Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Inativo: Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Inativo: Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Inativo: Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Inativo: Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Inativo: Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Inativo: Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Inativo: Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Inativo: Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Inativo: Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Inativo: Demitido"),
                    ("INATIVO_DEVOLVIDO", "Inativo: Devolvido ao Órgão de Origem"),
                    (
                        "INATIVO_OUTRO_CARGO",
                        "Inativo: Posse em outro cargo inacumulável",
                    ),
                ],
                default="NOT_FOUND",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="ordinance",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Por portaria"
            ),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="active",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Ativo: Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Ativo: Licenciado - Tratamento de Saúde"),
                    (
                        "ATIVO_LIC_DOENCA",
                        "Ativo: Licenciado - Doença em Pessoa da Família",
                    ),
                    ("ATIVO_LIC_MATERNIDADE", "Ativo: Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Ativo: Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Ativo: Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Ativo: Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Ativo: Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Ativo: Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Ativo: Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Ativo: Licenciado - Desempenho de Mandato Classista",
                    ),
                    (
                        "ATIVO_AFA_DISPONIBILIDADE",
                        "Ativo: Afastado - Em disponibilidade",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Ativo: Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Ativo: Afastado - Comparecer a juízo"),
                    (
                        "ATIVO_AFA_ELETIVO",
                        "Ativo: Afastado - Exercício de Mandato Eletivo",
                    ),
                    ("ATIVO_AFA_ESTUDAR", "Ativo: Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_MISSAO",
                        "Ativo: Afastado - Missão Oficial no Exterior",
                    ),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Ativo: Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Ativo: Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Ativo: Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Ativo: Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Ativo: Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Ativo: Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Ativo: Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ativo: Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ativo: Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ativo: Ausente - Casamento"),
                    (
                        "ATIVO_AUS_NASCIMENTO",
                        "Ativo: Ausente - Nascimento/adoção de filho",
                    ),
                    ("ATIVO_AUS_FALECIMENTO", "Ativo: Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ativo: Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Ativo: Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Ativo: Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Ativo: Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Ativo: Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Ativo: Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Ativo: Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Ativo: Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_SAUDEMULHER", "Ativo: Fruindo Folga Saúde Mulher"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Ativo: Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Ativo: Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Ativo: Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Ativo: - Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Inativo: Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Inativo: Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Inativo: Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Inativo: Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Inativo: Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Inativo: Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Inativo: Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Inativo: Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Inativo: Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Inativo: Demitido"),
                    ("INATIVO_DEVOLVIDO", "Inativo: Devolvido ao Órgão de Origem"),
                    (
                        "INATIVO_OUTRO_CARGO",
                        "Inativo: Posse em outro cargo inacumulável",
                    ),
                ],
                default="ATIVO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="main",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Principal"
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="publico",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Público"
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="federative_body_owner",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Ente federativo responsável?"
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="main",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Principal do órgão"
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="rpps",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Possui RPPS?"
            ),
        ),
    ]
