# Generated by Django 2.2.11 on 2020-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0111_auto_20200304_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="situacao_funcional_cache",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Ativo: Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Ativo: Licenciado - Tratamento de Saúde"),
                    (
                        "ATIVO_LIC_DOENCA",
                        "Ativo: Licenciado - Doença em Pessoa da Família",
                    ),
                    ("ATIVO_LIC_MATERNIDADE", "Ativo: Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Ativo: Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Ativo: Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Ativo: Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Ativo: Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Ativo: Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Ativo: Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Ativo: Licenciado - Desempenho de Mandato Classista",
                    ),
                    (
                        "ATIVO_AFA_DISPONIBILIDADE",
                        "Ativo: Afastado - Em disponibilidade",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Ativo: Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Ativo: Afastado - Comparecer a juízo"),
                    (
                        "ATIVO_AFA_ELETIVO",
                        "Ativo: Afastado - Exercício de Mandato Eletivo",
                    ),
                    ("ATIVO_AFA_ESTUDAR", "Ativo: Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_MISSAO",
                        "Ativo: Afastado - Missão Oficial no Exterior",
                    ),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Ativo: Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Ativo: Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Ativo: Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Ativo: Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Ativo: Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Ativo: Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Ativo: Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ativo: Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ativo: Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ativo: Ausente - Casamento"),
                    (
                        "ATIVO_AUS_NASCIMENTO",
                        "Ativo: Ausente - Nascimento/adoção de filho",
                    ),
                    ("ATIVO_AUS_FALECIMENTO", "Ativo: Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ativo: Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Ativo: Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Ativo: Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Ativo: Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Ativo: Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Ativo: Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Ativo: Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Ativo: Fruindo Folga Banco de Horas"),
                    ("PREVENCAOSAUDE", "Ativo: Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Ativo: Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Ativo: Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Ativo: Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Ativo: - Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Inativo: Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Inativo: Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Inativo: Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Inativo: Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Inativo: Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Inativo: Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Inativo: Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Inativo: Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Inativo: Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Inativo: Demitido"),
                    ("INATIVO_DEVOLVIDO", "Inativo: Devolvido ao Órgão de Origem"),
                    (
                        "INATIVO_OUTRO_CARGO",
                        "Inativo: Posse em outro cargo inacumulável",
                    ),
                ],
                default="NOT_FOUND",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Ativo: Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Ativo: Licenciado - Tratamento de Saúde"),
                    (
                        "ATIVO_LIC_DOENCA",
                        "Ativo: Licenciado - Doença em Pessoa da Família",
                    ),
                    ("ATIVO_LIC_MATERNIDADE", "Ativo: Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Ativo: Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Ativo: Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Ativo: Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Ativo: Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Ativo: Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Ativo: Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Ativo: Licenciado - Desempenho de Mandato Classista",
                    ),
                    (
                        "ATIVO_AFA_DISPONIBILIDADE",
                        "Ativo: Afastado - Em disponibilidade",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Ativo: Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Ativo: Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Ativo: Afastado - Comparecer a juízo"),
                    (
                        "ATIVO_AFA_ELETIVO",
                        "Ativo: Afastado - Exercício de Mandato Eletivo",
                    ),
                    ("ATIVO_AFA_ESTUDAR", "Ativo: Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_MISSAO",
                        "Ativo: Afastado - Missão Oficial no Exterior",
                    ),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Ativo: Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Ativo: Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Ativo: Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Ativo: Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Ativo: Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Ativo: Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Ativo: Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ativo: Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ativo: Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ativo: Ausente - Casamento"),
                    (
                        "ATIVO_AUS_NASCIMENTO",
                        "Ativo: Ausente - Nascimento/adoção de filho",
                    ),
                    ("ATIVO_AUS_FALECIMENTO", "Ativo: Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ativo: Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Ativo: Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Ativo: Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Ativo: Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Ativo: Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Ativo: Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Ativo: Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Ativo: Fruindo Folga Banco de Horas"),
                    ("PREVENCAOSAUDE", "Ativo: Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Ativo: Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Ativo: Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Ativo: Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Ativo: - Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Inativo: Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Inativo: Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Inativo: Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Inativo: Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Inativo: Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Inativo: Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Inativo: Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Inativo: Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Inativo: Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Inativo: Demitido"),
                    ("INATIVO_DEVOLVIDO", "Inativo: Devolvido ao Órgão de Origem"),
                    (
                        "INATIVO_OUTRO_CARGO",
                        "Inativo: Posse em outro cargo inacumulável",
                    ),
                ],
                default="ATIVO",
                max_length=30,
            ),
        ),
    ]
