# Generated by Django 2.2.12 on 2020-05-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0114_datamigration_document_naturalperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="immigrant_entry_condition",
            field=models.IntegerField(
                default=10, verbose_name="Condição de ingresso do imigrante"
            ),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="immigrant_residence_time",
            field=models.IntegerField(
                default=10, verbose_name="Tempo de residência do imigrante"
            ),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="nationality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="naturalperson_nationality",
                to="rh.Pais",
                verbose_name="Nacionalidade",
            ),
        ),
    ]
