# Generated by Django 2.2.12 on 2020-04-28 16:32

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import standard.models


def migrate_previdencia_to_socialsecurity(apps, schema_editor):
    Previdencia = apps.get_model("gfp", "Previdencia")
    SocialSecurity = apps.get_model("rh", "SocialSecurity")
    User = apps.get_model("auth", "User")

    user = User.objects.get(username="athenas")
    pj = rp = next = None
    for p in Previdencia.objects.order_by(
        "pessoa_juridica", "regime_previdenciario", "-data_vigencia"
    ):

        endv = None
        percentage_of_employer = 0
        if pj != p.pessoa_juridica or rp != p.regime_previdenciario:
            next = None
        if next:
            endv = next.data_vigencia - timedelta(1)

        result = p.faixas.aggregate(
            avg=models.Avg("pct_patronal"), max=models.Max("pct_patronal")
        )
        if result["max"] == result["avg"] and result["max"]:
            percentage_of_employer = result["max"]
        print(
            f"{p.get_regime_previdenciario_display()} {p.get_identifier_display()} {p.data_vigencia} {p}",
            end="",
        )
        ss, created = SocialSecurity.objects.get_or_create(
            legal_person=p.pessoa_juridica,
            identifier=p.identifier,
            start_validity=p.data_vigencia,
            end_validity=endv,
            publication=p.publicacao,
            socialsecurity_regime=p.regime_previdenciario,
            percentage_of_employer=percentage_of_employer,
            created_by=user,
            modified_by=user,
        )
        for f in p.faixas.all():
            ssr, createdr = ss.ranges.get_or_create(
                socialsecurity=ss,
                lower_limite=f.limite_inferior,
                upper_limite=f.limite_superior,
                percentage=f.pct,
                reducer=f.reducer,
                created_by=user,
                modified_by=user,
            )
        print(f' {"OK" if created else "**"}')

        pj = p.pessoa_juridica
        rp = p.regime_previdenciario
        next = p


def _null_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0117_auto_20200513_1732"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialSecurity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "identifier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1")], default=1, verbose_name="Identificador"
                    ),
                ),
                (
                    "socialsecurity_regime",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR")],
                        default=2,
                        verbose_name="Regime previdenciário",
                    ),
                ),
                (
                    "percentage_of_employer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem do Patrão",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socialsecurity",
                        to="rh.PessoaJuridica",
                        verbose_name="Previdência",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Publicacao",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_validity", "legal_person"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.RenameField(
            model_name="socialsecurityconfig", old_name="end", new_name="end_validity"
        ),
        migrations.RenameField(
            model_name="socialsecurityconfig",
            old_name="start",
            new_name="start_validity",
        ),
        migrations.AddField(
            model_name="socialsecurityconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialsecurityconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=845,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialsecurityconfig",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="socialsecurityconfig",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="socialsecurityconfig",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=845,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="immigrant_entry_condition",
            field=models.IntegerField(
                choices=[
                    (10, "NÃO É IMIGRANTE"),
                    (1, "Refugiado"),
                    (2, "Solicitante de refúgio"),
                    (3, "Permanência no Brasil em razão de reunião familiar"),
                    (4, "Beneficiado pelo acordo entre países do Mercosul"),
                    (
                        5,
                        "Dependente de agente diplomático/consular de países que mantêm acordo de reciprocidade p/ exercício atividade remunerada",
                    ),
                    (
                        6,
                        "Beneficiado pelo Tratado de Amizade, Cooperação e Consulta entre a República Federativa do Brasil e República Portuguesa",
                    ),
                    (7, "Outra condição"),
                ],
                default=10,
                verbose_name="Condição de ingresso do imigrante",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="immigrant_residence_time",
            field=models.IntegerField(
                choices=[
                    (10, "NÃO É IMIGRANTE"),
                    (1, "PRAZO INDETERMINADO"),
                    (2, "PRAZO DETERMINADO"),
                ],
                default=10,
                verbose_name="Tempo de residência do imigrante",
            ),
        ),
        migrations.CreateModel(
            name="SocialSecurityRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "lower_limite",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Limite Inferior"
                    ),
                ),
                (
                    "upper_limite",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Limite Superior"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Porcentagem do Empregado",
                    ),
                ),
                (
                    "reducer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=16,
                        verbose_name="Redutor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "socialsecurity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="rh.SocialSecurity",
                        verbose_name="Previdência",
                    ),
                ),
            ],
            options={
                "ordering": ["socialsecurity", "lower_limite"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="naturalperson_nationality",
                to="rh.Pais",
                verbose_name="Nacionalidade",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="nationality_birth",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="naturalperson_nationality_birth",
                to="rh.Pais",
                verbose_name="País de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="socialsecurityconfig",
            name="end_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Fim vigência"),
        ),
        migrations.AlterField(
            model_name="socialsecurityconfig",
            name="start_validity",
            field=models.DateField(verbose_name="Início vigência"),
        ),
        migrations.RunPython(migrate_previdencia_to_socialsecurity, _null_function),
    ]
