# Generated by Django 2.2.16 on 2020-09-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0120_load_fixture_workplacemigrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="electoral_zone",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Zona Eleitoral"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="electoral_zone_coverage",
            field=models.TextField(
                blank=True, null=True, verbose_name="Abrangência da Zona Eleitoral"
            ),
        ),
        migrations.AlterField(
            model_name="banco",
            name="pessoajuridica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="como_banco",
                to="rh.PessoaJuridica",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="nationality_birth",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="naturalperson_nationality_birth",
                to="rh.Pais",
                verbose_name="País de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="targetworkplacemigrate",
            name="type_of_target",
            field=models.IntegerField(
                choices=[
                    (1, "EDOC"),
                    (2, "E-EXT"),
                    (3, "DIÁRIAS"),
                    (4, "LOTAÇÃO E EXERCÍCIO"),
                ],
                default=1,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="workplacemigrate",
            name="type_of_migrate",
            field=models.IntegerField(
                choices=[(1, "INATIVAÇÃO"), (2, "EXTINÇÃO")],
                default=1,
                verbose_name="Tipo",
            ),
        ),
    ]
