# Generated by Django 2.2.16 on 2020-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0124_auto_20201022_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="is_contact_displayed",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Exibir nos contatos do Site?"
            ),
        ),
    ]
