# Generated by Django 2.2.17 on 2020-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0125_lotacao_is_contact_displayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeworkplacehistory",
            name="annotate",
            field=models.BooleanField(blank=True, default=True, verbose_name="Anotar?"),
        ),
        migrations.AddField(
            model_name="servidorlotacao",
            name="annotate",
            field=models.BooleanField(blank=True, default=True, verbose_name="Anotar?"),
        ),
        migrations.AlterField(
            model_name="anotacaoferias",
            name="identificador",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identificador"
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="code_cnmp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="main",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Próprio órgão?"
            ),
        ),
    ]
