# Generated by Django 2.2.17 on 2020-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0126_add_annotate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotacaogeral",
            name="texto",
            field=models.TextField(blank=True, null=True),
        ),
    ]
