# Generated by Django 2.2.17 on 2020-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0127_alter_field_texto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgaogeral",
            old_name="cache_id",
            new_name="cache_identifier",
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (59, "COMPROVANTE DE VOTAÇÂO - ELEIÇÕES MUNICIPAIS 2020"),
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                ],
                default=57,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
