# Generated by Django 2.2.16 on 2020-09-16 10:42

from django.db import migrations, models
from contrib.utils import make_phonetic

import django.db.models.deletion


def up_fill_phonetic_fields_of_person(apps, editor_schema):
    Person = apps.get_model("rh.Pessoa")

    query = Person.objects.filter(phonetic_name=None)
    total = query.count()
    pos = 0
    message = ""

    for person in query:
        person.phonetic_name = make_phonetic(person.nome)
        person.save()
        print("\b" * len(message), end="")
        pos += 1
        message = f" {pos} de {total} pessoas"
        print(message, end="")
    else:
        print("\b" * len(message), end="")
        print(" " * len(message), end="")
        print("\b" * len(message), end="")


def up_fill_phonetic_fields_of_natural_person(apps, editor_schema):
    NaturalPerson = apps.get_model("rh.PessoaFisica")

    query = NaturalPerson.objects.filter(
        models.Q(phonetic_father_name=None) | models.Q(phonetic_mother_name=None)
    )

    total = query.count()
    pos = 0
    message = ""

    for person in query:
        person.phonetic_father_name = (
            None if not person.nome_pai else make_phonetic(person.nome_pai)
        )
        person.phonetic_mother_name = (
            None if not person.nome_mae else make_phonetic(person.nome_mae)
        )
        person.save()
        print("\b" * len(message), end="")
        pos += 1
        message = f" {pos} de {total} pessoas fisicas"
        print(message, end="")
    else:
        print("\b" * len(message), end="")
        print(" " * len(message), end="")
        print("\b" * len(message), end="")


def up_fill_phonetic_fields_of_legal_person(apps, editor_schema):
    LegalPerson = apps.get_model("rh.PessoaJuridica")

    query = LegalPerson.objects.filter(phonetic_social_name=None)

    total = query.count()
    pos = 0
    message = ""

    for person in query:
        person.phonetic_social_name = (
            None if not person.razao_social else make_phonetic(person.razao_social)
        )
        person.save()
        print("\b" * len(message), end="")
        pos += 1
        message = f" {pos} de {total} pessoas juridicas"
        print(message, end="")
    else:
        print("\b" * len(message), end="")
        print(" " * len(message), end="")
        print("\b" * len(message), end="")


def empty_method(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0130_add_oab_in_natural_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="phonetic_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="banco",
            name="pessoajuridica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="como_banco",
                to="rh.PessoaJuridica",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="nationality_birth",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="naturalperson_nationality_birth",
                to="rh.Pais",
                verbose_name="País de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="targetworkplacemigrate",
            name="type_of_target",
            field=models.IntegerField(
                choices=[
                    (1, "EDOC"),
                    (2, "E-EXT"),
                    (3, "DIÁRIAS"),
                    (4, "LOTAÇÃO E EXERCÍCIO"),
                ],
                default=1,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="workplacemigrate",
            name="type_of_migrate",
            field=models.IntegerField(
                choices=[(1, "INATIVAÇÃO"), (2, "EXTINÇÃO")],
                default=1,
                verbose_name="Tipo",
            ),
        ),
        migrations.RunPython(up_fill_phonetic_fields_of_person, empty_method),
        migrations.AddField(
            model_name="pessoafisica",
            name="phonetic_father_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="phonetic_mother_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(up_fill_phonetic_fields_of_natural_person, empty_method),
        migrations.AddField(
            model_name="pessoajuridica",
            name="phonetic_social_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(up_fill_phonetic_fields_of_legal_person, empty_method),
    ]
