# Generated by Django 2.2.17 on 2020-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0132_add_repeat_marker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repeatpersonincident",
            options={
                "permissions": (
                    (
                        "can_mark_repeatincident_discarted",
                        "Pode marcar como discartado",
                    ),
                    (
                        "can_mark_repeatincident_simple_merged",
                        "Pode marcar como mesclado",
                    ),
                    (
                        "can_mark_repeatincident_merged",
                        "Pode marcar como mesclado (Empregado/Dependente)",
                    ),
                )
            },
        ),
        migrations.AddField(
            model_name="movimentacaodesligamento",
            name="termination_process",
            field=models.BooleanField(
                default=True, verbose_name="Finaliza férias, afastamentos e lotação."
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="situacao_funcional_cache",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                ],
                default="NOT_FOUND",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                ],
                default="ATIVO",
                max_length=30,
            ),
        ),
    ]
