# Generated by Django 2.2.17 on 2021-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0133_auto_20201211_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidorlotacao",
            name="provisional_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo Provisória"
            ),
        )
    ]
