# Generated by Django 2.2.19 on 2021-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0134_auto_20210115_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaldocument",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=260, verbose_name="Nome"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaodesligamento",
            name="termination_process",
            field=models.BooleanField(
                default=True, verbose_name="Finaliza férias, afastamentos e lotação"
            ),
        ),
    ]
