# Generated by Django 2.2.19 on 2021-04-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0135_auto_20210317_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeworkplacehistory",
            name="main_schedule_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data agendada para marcar principal",
            ),
        ),
        migrations.AddField(
            model_name="employeeworkplacehistory",
            name="provisional_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo Provisória"
            ),
        ),
        migrations.AddField(
            model_name="servidorlotacao",
            name="main_schedule_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data agendada para marcar principal",
            ),
        ),
    ]
