# Generated by Django 2.2.20 on 2021-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0136_auto_20210405_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgaogeral",
            name="order_weight",
            field=models.SmallIntegerField(
                blank=True, default=0, verbose_name="Peso ordenação"
            ),
        ),
    ]
