# Generated by Django 2.2.20 on 2021-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0137_orgaogeral_order_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracaoatividade",
            name="main",
            field=models.BooleanField(default=False, verbose_name="Principal"),
        ),
        migrations.AddField(
            model_name="declaracaoatividade",
            name="main_schedule_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data agendada para marcar principal",
            ),
        ),
    ]
