# Generated by Django 2.2.21 on 2021-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0138_auto_20210506_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="indicativo",
            field=models.CharField(
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoatividade",
            name="activity_as",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="tiposervidor",
            name="indicativo",
            field=models.CharField(
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
