# Generated by Django 2.2.24 on 2021-08-03 17:14
import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


def _null_function(apps, schema_editor):
    pass


def migrate_configs_administrative_unit(apps, schema_editor):

    if settings.ORGAN_IDENTIFIER == "mpto":
        modelo = apps.get_model("rh", "AdministrativeUnitConfig")
        modeloAdm = apps.get_model("rh", "UnidadeAdministrativa")
        modeloUser = apps.get_model("auth", "User")
        creator = modeloUser.objects.get(pk=1)
        ua = modeloAdm.objects.filter(pk=454).last()  # PGJ
        config, isnew = modelo.objects.get_or_create(
            administrative_unit=ua,
            cnae_preponderant=ua.cnae_preponderant,
            tax_classification=ua.tax_classification,
            start_validity=datetime.date(2021, 1, 1),
            created_by=creator,
            modified_by=creator,
        )
        print(
            "%s CRIEi uma configuração nova %s" % ("NÃO" if not isnew else "", config)
        )
        ua.configs.add(config)
    else:
        print(
            "É necessário criar configuração de Unidade Administrativa para o eSocial."
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0138_auto_20210505_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeUnitConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "cnae_preponderant",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tax_classification",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciáriasubstituída",
                            ),
                            (
                                2,
                                "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária nãosubstituída",
                            ),
                            (
                                3,
                                "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciáriasubstituída e não substituída",
                            ),
                            (4, "MEI - Micro Empreendedor Individual"),
                            (6, "Agroindústria"),
                            (8, "Consórcio Simplificado de Produtores Rurais"),
                            (9, "Órgão Gestor de Mão de Obra"),
                            (10, "Entidade Sindical a que se refere a Lei 12.023/2009"),
                            (
                                11,
                                "Associação Desportiva que mantém Clube de Futebol Profissional",
                            ),
                            (
                                13,
                                "Banco, caixa econômica, sociedade de crédito, financiamento e investimento e demais empresas relacionadas no parágrafo",
                            ),
                            (
                                14,
                                "Sindicatos em geral, exceto aquele classificado no código [10]",
                            ),
                            (21, "Pessoa Física, exceto Segurado Especial"),
                            (22, "Segurado Especial"),
                            (
                                60,
                                "Missão Diplomática ou Repartição Consular de carreira estrangeira",
                            ),
                            (70, "Empresa de que trata o Decreto 5.436/2005"),
                            (
                                80,
                                "Entidade Beneficente de Assistência Social isenta de contribuições sociais",
                            ),
                            (
                                85,
                                "Administração Direta da União, Estados, Distrito Federal e Municípíos; Autarquias e Fundações Públicas",
                            ),
                            (99, "Pessoas Jurídicas em Geral"),
                        ],
                        verbose_name="Classificação tributária",
                    ),
                ),
                (
                    "eletronic_reg_employees",
                    models.BooleanField(
                        default=True,
                        verbose_name="Opta por registro eletrônico de empregados",
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="rh.UnidadeAdministrativa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.RunPython(migrate_configs_administrative_unit, _null_function),
    ]
