# Generated by Django 2.2.21 on 2021-05-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0139_auto_20210511_1120"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationActivityRetiree",
            fields=[
                (
                    "movimentacaopessoal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPessoal",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Início")),
                (
                    "data_encerramento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Encerramento"
                    ),
                ),
                ("ativo", models.BooleanField(blank=True, default=True)),
                (
                    "activity_as",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "INDEFINIDO"),
                            ("E", "ESTAGIÁRIO"),
                            ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                            ("P", "MILITAR"),
                            ("S", "SERVIDOR"),
                            ("T", "TERCEIRIZADO"),
                            ("V", "VOLUNTÁRIO"),
                            ("A", "JOVEM CIDADÃO - APRENDIZ"),
                            ("X", "EXTERNO SEM VÍNCULO"),
                            ("O", "APOSENTADO"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("rule", models.IntegerField(verbose_name="Regra")),
                (
                    "lotacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Lotacao",
                        verbose_name="Local de trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaração de Atividade do Aposentado",
                "ordering": ("-data_inicio",),
            },
            bases=("rh.movimentacaopessoal",),
        ),
    ]
