# Generated by Django 2.2.24 on 2021-08-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0139_auto_20210803_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="order_weight",
            field=models.SmallIntegerField(
                blank=True, default=0, verbose_name="Peso ordenação"
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="organizational_classification",
            field=models.IntegerField(
                choices=[
                    (1, "Não informado"),
                    (2, "Primeira Entrância"),
                    (3, "Segunda Entrancia"),
                    (4, "Sede Terceira Entrancia"),
                    (5, "Terceira Entrancia"),
                    (6, "Sede  & Promotoria"),
                    (7, "Órgãos de Administração Superior e Execução"),
                    (8, "Órgãos de Administração Superior e Execução Nivel 2"),
                    (9, "Orgão Auxiliares - Diretoria Geral"),
                    (10, "Orgão Auxiliares - Diretoria Geral  Nivel 2"),
                    (11, "Primeira Entrância Nível 2"),
                    (12, "Segunda Entrancia Nível 2"),
                    (13, "Orgão Auxiliares - Diretoria Geral  Nivel 3"),
                    (14, "Orgão Auxiliares - Diretoria Geral  Nivel 4"),
                    (15, "Órgãos de Administração Superior e Execução Nivel 3"),
                    (16, "Órgãos de Administração Superior e Execução Nivel 2.1"),
                    (17, "Órgãos de Administração Superior e Execução Nivel 2.2"),
                ],
                default=1,
                verbose_name="Classificação do Organograma",
            ),
        ),
    ]
