# Generated by Django 2.2.23 on 2021-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0140_declarationactivityretiree"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="declarationactivityretiree",
            options={
                "ordering": ("-data_inicio",),
                "verbose_name": "Declaração de Atividade",
            },
        ),
        migrations.AlterField(
            model_name="declarationactivityretiree",
            name="rule",
            field=models.IntegerField(
                choices=[
                    (1, "Art. 3º, da EC nº 47/05"),
                    (2, "Art. 40º, § 1º, III, b, da Constituição Federal"),
                    (3, "Art. 10º, § 1º, I, da  EC nº 103/19"),
                    (4, "Art. 4º da EC nº 103/19"),
                    (5, "Regra Geral: Fundamento Art. 40, § 1°, III, a, da CF."),
                    (
                        6,
                        "Art. 8, I e III, a e b, da EC nº 20/98 (vigente até 31/12/2003)",
                    ),
                    (
                        7,
                        "Art. 8º, § 1º, I, a e b, da EC nº 20/98 (Vigente até 31.12.03)",
                    ),
                    (8, "Art. 2º, I a III, a e b, da EC nº 41/03"),
                    (9, "Art. 6º, da EC nº 41/03"),
                    (10, "Art. 20 da  EC nº 103/19"),
                ],
                verbose_name="Regra",
            ),
        ),
        migrations.AlterField(
            model_name="retiree",
            name="type_retirement",
            field=models.IntegerField(default=1, verbose_name="Tipo de Aposentadoria"),
        ),
    ]
