# Generated by Django 2.2.24 on 2021-08-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models
import datetime


def _null_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0140_auto_20210813_1754"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativeunitconfig",
            name="cnae_preponderant",
        ),
        migrations.AddField(
            model_name="administrativeunitconfig",
            name="federative_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.PessoaJuridica",
                verbose_name="Ente federativo",
            ),
        ),
        migrations.AddField(
            model_name="administrativeunitconfig",
            name="legal_nature",
            field=models.IntegerField(
                choices=[
                    (1015, "Órgão Público do Poder Executivo Federal"),
                    (
                        1023,
                        "Órgão Público do Poder Executivo Estadual ou do Distrito Federal",
                    ),
                    (1031, "Órgão Público do Poder Executivo Municipal"),
                    (1040, "Órgão Público do Poder Legislativo Federal"),
                    (
                        1058,
                        "Órgão Público do Poder Legislativo Estadual ou do Distrito Federal",
                    ),
                    (1066, "Órgão Público do Poder Legislativo Municipal"),
                    (1074, "Órgão Público do Poder Judiciário Federal"),
                    (1082, "Órgão Público do Poder Judiciário Estadual"),
                    (1104, "Autarquia Federal"),
                    (1112, "Autarquia Estadual ou do Distrito Federal"),
                    (1120, "Autarquia Municipal"),
                    (1139, "Fundação Pública de Direito Público Federal"),
                    (
                        1147,
                        "Fundação Pública de Direito Público Estadual ou do Distrito Federal",
                    ),
                    (1155, "Fundação Pública de Direito Público Municipal"),
                    (1163, "Órgão Público Autônomo Federal"),
                    (1171, "Órgão Público Autônomo Estadual ou do Distrito Federal"),
                    (1180, "Órgão Público Autônomo Municipal"),
                    (1198, "Comissão Polinacional"),
                    (1201, "Fundo Público"),
                    (1210, "Consórcio Público de Direito Público (Associação Pública)"),
                    (1228, "Consórcio Público de Direito Privado"),
                    (1236, "Estado ou Distrito Federal"),
                    (1244, "Município"),
                    (1252, "Fundação Pública de Direito Privado Federal"),
                    (
                        1260,
                        "Fundação Pública de Direito Privado Estadual ou do Distrito Federal",
                    ),
                    (1279, "Fundação Pública de Direito Privado Municipal"),
                ],
                default=1082,
                verbose_name="Natureza jurídica",
            ),
        ),
        migrations.AddField(
            model_name="processsuspension",
            name="fap_modified",
            field=models.BooleanField(default=False, verbose_name="FAP mudou?"),
        ),
        migrations.AddField(
            model_name="processsuspension",
            name="rat_modified",
            field=models.BooleanField(default=False, verbose_name="RAT mudou?"),
        ),
        migrations.CreateModel(
            name="TaxAllocationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "fpas",
                    models.PositiveIntegerField(
                        default=582, verbose_name="Código FPAS"
                    ),
                ),
                (
                    "terc_code",
                    models.CharField(
                        default="0000", max_length=4, verbose_name="Código de Terceiros"
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_allocation_configs",
                        to="rh.UnidadeAdministrativa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="EstablishmentConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "cnae_preponderant",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "rat_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Fator RAT"
                    ),
                ),
                (
                    "fap_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Fator FAP"
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establishment_configs",
                        to="rh.UnidadeAdministrativa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
