# Generated by Django 2.2.24 on 2021-08-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models
import datetime


def _null_function(apps, schema_editor):
    pass


def migrate_configs_administrative_unit(apps, schema_editor):
    if settings.ORGAN_IDENTIFIER == "mpto":
        modelo = apps.get_model("rh", "EstablishmentConfig")
        modelot = apps.get_model("rh", "TaxAllocationConfig")
        modeloAdm = apps.get_model("rh", "UnidadeAdministrativa")
        modeloRat = apps.get_model("gfp", "FatorRat")
        modeloFap = apps.get_model("gfp", "FatorFap")
        modeloUser = apps.get_model("auth", "User")
        creator = modeloUser.objects.get(pk=1)
        ua = modeloAdm.objects.filter(pk=454).last()  # PGJ
        confige, isnew = modelo.objects.get_or_create(
            administrative_unit=ua,
            cnae_preponderant=ua.cnae_preponderant,
            rat_value=modeloRat.objects.last().valor,
            fap_value=modeloFap.objects.last().valor,
            start_validity=datetime.date(2021, 1, 1),
            created_by=creator,
            modified_by=creator,
        )
        print(
            "%s CRIEi uma configuração de ESTABLISHMENT nova %s"
            % ("NÃO" if not isnew else "", confige)
        )
        ua.establishment_configs.add(confige)
        configt, isnew = modelot.objects.get_or_create(
            administrative_unit=ua,
            created_by=creator,
            modified_by=creator,
            start_validity=datetime.date(2021, 1, 1),
        )
        print(
            "%s CRIEi uma configuração de TAX nova %s"
            % ("NÃO" if not isnew else "", configt)
        )
        ua.tax_allocation_configs.add(configt)

        modelo = apps.get_model("rh", "AdministrativeUnitConfig")
        modelo.objects.filter(administrative_unit=ua).update(
            federative_body=apps.get_model("rh", "PessoaJuridica")
            .objects.filter(pk=5275)
            .last()
        )
    else:
        print(
            "É necessário criar configuração de Unidade Administrativa para o eSocial."
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0141_auto_20210816_1658"),
    ]

    operations = [
        migrations.RunPython(migrate_configs_administrative_unit, _null_function),
    ]
