# Generated by Django 2.2.23 on 2021-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0142_auto_20210525_1155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retiree",
            name="type",
        ),
        migrations.AddField(
            model_name="retiree",
            name="previous_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                ],
                default="",
                max_length=1,
            ),
        ),
    ]
