# Generated by Django 2.2.24 on 2021-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0143_auto_20210525_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="comarca",
            name="difficult_provision",
            field=models.BooleanField(default=False, verbose_name="Difícil Provimento"),
        ),
        migrations.AlterField(
            model_name="retiree",
            name="type_retirement",
            field=models.IntegerField(
                choices=[
                    (1, "COMPULSÓRIA"),
                    (2, "ESPECIAL"),
                    (3, "IMPLEMENTO DE IDADE"),
                    (4, "INVALIDEZ"),
                    (5, "TEMPO DE CONTRIBUIÇÃO"),
                    (6, "VOLUNTÁRIA"),
                ],
                default=1,
                verbose_name="Tipo de Aposentadoria",
            ),
        ),
    ]
