# Generated by Django 2.2.24 on 2021-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0143_unidadeadministrativa_veiculo_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="legal_nature",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1015, "Órgão Público do Poder Executivo Federal"),
                    (
                        1023,
                        "Órgão Público do Poder Executivo Estadual ou do Distrito Federal",
                    ),
                    (1031, "Órgão Público do Poder Executivo Municipal"),
                    (1040, "Órgão Público do Poder Legislativo Federal"),
                    (
                        1058,
                        "Órgão Público do Poder Legislativo Estadual ou do Distrito Federal",
                    ),
                    (1066, "Órgão Público do Poder Legislativo Municipal"),
                    (1074, "Órgão Público do Poder Judiciário Federal"),
                    (1082, "Órgão Público do Poder Judiciário Estadual"),
                    (1104, "Autarquia Federal"),
                    (1112, "Autarquia Estadual ou do Distrito Federal"),
                    (1120, "Autarquia Municipal"),
                    (1139, "Fundação Pública de Direito Público Federal"),
                    (
                        1147,
                        "Fundação Pública de Direito Público Estadual ou do Distrito Federal",
                    ),
                    (1155, "Fundação Pública de Direito Público Municipal"),
                    (1163, "Órgão Público Autônomo Federal"),
                    (1171, "Órgão Público Autônomo Estadual ou do Distrito Federal"),
                    (1180, "Órgão Público Autônomo Municipal"),
                    (1198, "Comissão Polinacional"),
                    (1201, "Fundo Público"),
                    (1210, "Consórcio Público de Direito Público (Associação Pública)"),
                    (1228, "Consórcio Público de Direito Privado"),
                    (1236, "Estado ou Distrito Federal"),
                    (1244, "Município"),
                    (1252, "Fundação Pública de Direito Privado Federal"),
                    (
                        1260,
                        "Fundação Pública de Direito Privado Estadual ou do Distrito Federal",
                    ),
                    (1279, "Fundação Pública de Direito Privado Municipal"),
                ],
                null=True,
                verbose_name="Natureza jurídica",
            ),
        ),
        migrations.AlterField(
            model_name="unidadeadministrativa",
            name="tax_classification",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (
                        1,
                        "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciáriasubstituída",
                    ),
                    (
                        2,
                        "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária nãosubstituída",
                    ),
                    (
                        3,
                        "Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciáriasubstituída e não substituída",
                    ),
                    (4, "MEI - Micro Empreendedor Individual"),
                    (6, "Agroindústria"),
                    (8, "Consórcio Simplificado de Produtores Rurais"),
                    (9, "Órgão Gestor de Mão de Obra"),
                    (10, "Entidade Sindical a que se refere a Lei 12.023/2009"),
                    (
                        11,
                        "Associação Desportiva que mantém Clube de Futebol Profissional",
                    ),
                    (
                        13,
                        "Banco, caixa econômica, sociedade de crédito, financiamento e investimento e demais empresas relacionadas no parágrafo",
                    ),
                    (
                        14,
                        "Sindicatos em geral, exceto aquele classificado no código [10]",
                    ),
                    (21, "Pessoa Física, exceto Segurado Especial"),
                    (22, "Segurado Especial"),
                    (
                        60,
                        "Missão Diplomática ou Repartição Consular de carreira estrangeira",
                    ),
                    (70, "Empresa de que trata o Decreto 5.436/2005"),
                    (
                        80,
                        "Entidade Beneficente de Assistência Social isenta de contribuições sociais",
                    ),
                    (
                        85,
                        "Administração Direta da União, Estados, Distrito Federal e Municípíos; Autarquias e Fundações Públicas",
                    ),
                    (99, "Pessoas Jurídicas em Geral"),
                ],
                null=True,
                verbose_name="Classificação tributária",
            ),
        ),
    ]
