# Generated by Django 2.2.24 on 2021-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0144_auto_20210608_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="sub_atual_10_a87",
            field=models.BooleanField(
                default=False, verbose_name="A87 - Grat. Adicional -10%"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_atual_10_b94",
            field=models.BooleanField(
                default=False, verbose_name="B94 - Dif. Desig. AMD. Superior"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_atual_10_d24",
            field=models.BooleanField(
                default=False, verbose_name="D24 - Grat. Função Orgãos Auxiliares"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_atual_10_d25",
            field=models.BooleanField(
                default=False,
                verbose_name="D25 - Grat. Função de Coordenadores - Sobre o Cargo Atual",
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_atual_10_e64",
            field=models.BooleanField(
                default=False,
                verbose_name="E64 - Grat. Membro Conselho Superior Ministério Público",
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_ini_10_coll_bonus",
            field=models.BooleanField(
                default=True, verbose_name="Gratificação de Acervo"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_ini_10_d25",
            field=models.BooleanField(
                default=False, verbose_name="D25 - Grat. Função de Coordenadores"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_mem_20_b87",
            field=models.BooleanField(
                default=False,
                verbose_name="B87 - Verba de representação Art.82 L.C. 27/93",
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_mem_20_d26",
            field=models.BooleanField(
                default=False,
                verbose_name="D26 - Representação (Art.147 L.C. 516/2010)",
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="sub_mem_20_e08",
            field=models.BooleanField(
                default=False, verbose_name="E08 - Representação (Ato 358/2011)"
            ),
        ),
    ]
