# Generated by Django 2.2.24 on 2021-06-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0145_auto_20210614_1055"),
        ("rh", "0138_auto_20210505_1644"),
    ]

    operations = []
