# Generated by Django 2.2.20 on 2021-09-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0145_cargo_code_tce"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicconcurrence",
            name="job_positions",
            field=models.ManyToManyField(
                blank=True,
                related_name="public_concurrence",
                to="rh.Cargo",
                verbose_name="Cargos",
            ),
        ),
        migrations.AddField(
            model_name="publicconcurrence",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.Publicacao",
            ),
        ),
        migrations.AddField(
            model_name="publicconcurrence",
            name="type_concurrence",
            field=models.IntegerField(blank=True, null=True, verbose_name="Tipo"),
        ),
    ]
