# Generated by Django 2.2.24 on 2021-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0145_auto_20210614_1055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comarca",
            name="difficult_provision",
        ),
    ]
