# Generated by Django 2.2.24 on 2021-06-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0145_auto_20210614_1055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_atual_10_a87",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_atual_10_b94",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_atual_10_d24",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_atual_10_d25",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_atual_10_e64",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_ini_10_coll_bonus",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_ini_10_d25",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_mem_20_b87",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_mem_20_d26",
        ),
        migrations.RemoveField(
            model_name="lotacao",
            name="sub_mem_20_e08",
        ),
    ]
