# Generated by Django 2.2.24 on 2021-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0146_auto_20210929_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="exercise_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Exercício"
            ),
        ),
        migrations.AddField(
            model_name="servidor",
            name="termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Desligamento"
            ),
        ),
    ]
