# Generated by Django 2.2.24 on 2021-06-25 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gfp", "0074_auto_20210625_1230"),
        ("rh", "0147_merge_20210625_1229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declarationactivityretiree",
            name="rule",
            field=models.IntegerField(verbose_name="Regra"),
        ),
        migrations.AlterField(
            model_name="retiree",
            name="type_retirement",
            field=models.IntegerField(default=1, verbose_name="Tipo de Aposentadoria"),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGIÁRIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNTÁRIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM VÍNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                    ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                    ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                    ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                    ("MEC2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO"),
                    ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                    ("APO", "SERVIDOR APOSENTADO"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="StockingFunds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_stockingfunds",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplace_stockingfunds",
                        to="rh.Lotacao",
                        verbose_name="Lotação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verbas de Lotação",
                "ordering": ["start_validity"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
