# Generated by Django 2.2.24 on 2021-10-21 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0147_auto_20210902_1008"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialsecurityconfig",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="socialsecurityconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="socialsecurityconfig",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="socialsecurityconfig",
            name="modified_by",
        ),
        migrations.AlterField(
            model_name="servidor",
            name="social_security",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_social_security",
                to="rh.SocialSecurityConfig",
            ),
        ),
        migrations.CreateModel(
            name="SocialSecurityEmployee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.Servidor"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "social_security_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.SocialSecurityConfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AddField(
            model_name="servidor",
            name="social_securities",
            field=models.ManyToManyField(
                through="rh.SocialSecurityEmployee", to="rh.SocialSecurityConfig"
            ),
        ),
    ]
