# Generated by Django 2.2.24 on 2021-07-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0148_auto_20210625_1230"),
        ("rh", "0146_merge_20210628_0900"),
    ]

    operations = []
