# Generated by Django 2.2.24 on 2021-07-12 14:30

from django.db import migrations
from django.conf import settings
from datetime import date


def add_stockingfunds_in_lotacao(apps, schema_editor):
    Lotacao = apps.get_model("rh", "Lotacao")
    StockingFunds = apps.get_model("rh", "StockingFunds")
    Evento = apps.get_model("gfp", "Evento")
    User = apps.get_model("auth", "User")
    events_id = [
        1582,  # 005-00 GRATIFICAÇÃO ACERVO
        1602,  # 808-00 EXERCÍCIO CUMULATIVO
        1603,  # 809-00 EXERCÍCIO CUMULATIVO DE FUNÇÕES
    ]
    user_default = User.objects.get(username="athenas")

    for lotacao in Lotacao.objects.all():
        for event_id in events_id:
            StockingFunds.objects.create(
                workplace=lotacao,
                event=Evento.objects.get(pk=event_id),
                active=True,
                start_validity=date(2021, 1, 15),
                created_by=user_default,
                modified_by=user_default,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0149_merge_20210712_1428"),
    ]

    operations = [
        migrations.RunPython(add_stockingfunds_in_lotacao),
    ]
