# Generated by Django 2.2.24 on 2021-07-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0151_auto_20210712_1742"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="portal_approver",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Aprovador Portal"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaopromocao",
            name="criterio",
            field=models.IntegerField(
                choices=[
                    (1, "ANTIGUIDADE"),
                    (2, "MERECIMENTO"),
                    (3, "PERMUTA"),
                    (4, "VITALICIAMENTO"),
                ],
                default=1,
            ),
        ),
    ]
