# Generated by Django 2.2.24 on 2021-09-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0154_merge_20210827_1333"),
        ("rh", "0144_auto_20210910_1427"),
    ]

    operations = []
