# Generated by Django 2.2.24 on 2021-09-15 12:10

from django.db import migrations, models
from datetime import timedelta


def _null_function(apps, schema_editor):
    pass


def update_financial_dates(apps, schema_editor):
    MovimentacaoPosse = apps.get_model("rh", "MovimentacaoPosse")
    ups = MovimentacaoPosse.objects.filter(
        financial_effect_date_end__isnull=True
    ).update(
        financial_effect_date_end=models.F("data_desligamento") - timedelta(days=1)
    )
    print(f"> Atualizando datas de efeito financeiro:  {ups}")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0155_merge_20210915_1209"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movimentacaoposse",
            old_name="financial_effect_date",
            new_name="financial_effect_date_start",
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="financial_effect_date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Efeito Financeiro"
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="organizational_classification",
            field=models.IntegerField(
                choices=[
                    (1, "Não informado"),
                    (2, "Primeira Entrância"),
                    (3, "Segunda Entrancia"),
                    (4, "Sede Terceira Entrancia"),
                    (5, "Terceira Entrancia"),
                    (6, "Sede  & Promotoria"),
                    (7, "Órgãos de Administração Superior e Execução"),
                    (8, "Órgãos de Administração Superior e Execução Nivel 2"),
                    (9, "Orgão Auxiliares - Diretoria Geral"),
                    (10, "Orgão Auxiliares - Diretoria Geral  Nivel 2"),
                    (11, "Primeira Entrância Nível 2"),
                    (12, "Segunda Entrancia Nível 2"),
                    (13, "Orgão Auxiliares - Diretoria Geral  Nivel 3"),
                    (14, "Orgão Auxiliares - Diretoria Geral  Nivel 4"),
                ],
                default=1,
                verbose_name="Classificação do Organograma",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaopromocao",
            name="criterio",
            field=models.IntegerField(
                choices=[
                    (1, "ANTIGUIDADE"),
                    (2, "MERECIMENTO"),
                    (3, "PERMUTA"),
                    (4, "VITALICIAMENTO"),
                ],
                default=1,
            ),
        ),
        migrations.RunPython(update_financial_dates, _null_function),
    ]
