# Generated by Django 2.2.24 on 2021-09-17 16:24

from django.db import migrations, models
import django.db.models.deletion


def _null_function(apps, schema_editor):
    pass


def migrate(apps, schema_editor):
    from rh.scripts import migrate_retiree

    migrate_retiree.migrate_retiree()


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0078_merge_20210915_1209"),
        ("esocial", "0006_auto_20210816_1700"),
        ("rh", "0156_auto_20210915_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="founder_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiaries",
                to="rh.Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="tipo_movcarreira",
            field=models.CharField(
                choices=[
                    ("NOMEACAO", "Nomeação"),
                    ("APROVEITAMENTO", "Aproveitamento"),
                    ("READAPTACAO", "Readaptação"),
                    ("RECONDUCAO", "Recondução"),
                    ("REINTEGRACAO", "Reintegração"),
                    ("REVERSAO", "Reversão"),
                    ("TITULARIZACAO", "Titularização"),
                    ("PROGRESSAO", "Progressão"),
                    ("ENQUADRAMENTO", "Enquadramento"),
                    ("REMOCAO", "Remoção"),
                    ("PROMOCAO", "Promoção"),
                    ("BENEFICIO", "Benefício Previdenciário"),
                ],
                default="NOMEACAO",
                max_length=30,
                verbose_name="Provimento",
            ),
        ),
        migrations.CreateModel(
            name="BenefitMovement",
            fields=[
                (
                    "movimentacaoposse_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPosse",
                    ),
                ),
                (
                    "type_legal_representative",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (4, "Representação por Procuração"),
                            (2, "Representação por Cautela"),
                            (1, "Representação por Tutela"),
                            (3, "Sem Representante"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="Tipo de representante",
                    ),
                ),
                (
                    "quota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=100,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "benefit_base_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "benefit_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "benefit_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="esocial.ItemTable",
                        verbose_name="Regra do benefício",
                    ),
                ),
                (
                    "legal_representative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.PessoaFisica",
                    ),
                ),
                (
                    "reference_parity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gfp.ReferenciaNiveis2D",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Benefício",
                "ordering": ("-data_exercicio",),
            },
            bases=("rh.movimentacaoposse",),
        ),
        migrations.RunPython(migrate, _null_function),
    ]
