# Generated by Django 2.2.24 on 2021-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0158_auto_20210922_1325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[("DPROV", "DIFICIL PROVIMENTO"), ("ACRV", "ACERVO")],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
