# Generated by Django 2.2.24 on 2021-10-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0160_merge_20211008_1542"),
        ("rh", "0149_auto_20211025_1004"),
    ]

    operations = []
