# Generated by Django 2.2.27 on 2022-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0164_auto_20220304_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="telefone",
            name="kinship",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                verbose_name="Grau de Parentesco (Emergência)",
            ),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="action",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, ""), (1, "Coadjuvando"), (2, "Colaborando")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="prejudice",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, ""), (1, "Com prejuízo"), (2, "Sem prejuízo")],
                default=0,
                null=True,
            ),
        ),
    ]
