# Generated by Django 2.2.28 on 2022-04-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0166_auto_20220412_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="BKP_MovimentacaoPosse",
            fields=[
                (
                    "movimentacaoposse_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPosse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rh.movimentacaoposse",),
        ),
        migrations.AlterField(
            model_name="movimentacaodesligamento",
            name="tipo_desligamento",
            field=models.IntegerField(
                choices=[
                    (1, "EXONERAÇÃO EFETIVO"),
                    (2, "EXONERAÇÃO COMISSIONADO"),
                    (3, "EXONERAÇÃO ESTABILIZADO"),
                    (4, "APOSENTADORIA POR INVALIDEZ"),
                    (5, "APOSENTADORIA VOLUNTÁRIA"),
                    (6, "POSSE EM OUTRO CARGO"),
                    (7, "FALECIMENTO"),
                    (8, "RESCISÃO"),
                    (9, "DEMISSÃO"),
                    (10, "RESERVA REFORMA"),
                    (11, "DISPONIBILIDADE"),
                    (12, "PROMOÇÃO/REMOÇÃO"),
                    (13, "FIM REQUISIÇÃO/ACORDO COOPERAÇÃO"),
                    (14, "APOSENTADORIA COMPULSÓRIA"),
                    (15, "APOSENTADORIA ESPECIAL"),
                    (16, "APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO"),
                    (17, "APOSENTADORIA POR IDADE"),
                    (18, "REDISTRIBUIÇÃO"),
                    (19, "REVERSÃO DE REINTEGRAÇÃO"),
                    (20, "FIM DE MANDATO"),
                    (21, "FIM TSVE"),
                ],
                default=1,
                verbose_name="Tipo de Desligamento",
            ),
        ),
    ]
