# Generated by Django 2.2.28 on 2022-04-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0084_auto_20220412_1430"),
        ("socialsecurity", "0008_auto_20220420_1122"),
        ("cif", "0017_auto_20181127_1822"),
        ("afastamento", "0018_auto_20220412_1444"),
        ("pvf", "0007_auto_20220412_1430"),
        ("estagio", "0008_auto_20220412_1430"),
        ("apd", "0009_auto_20220412_1430"),
        ("rh", "0167_auto_20220419_1827"),
    ]

    operations = [
        migrations.CreateModel(
            name="BKP_MovimentacaoPosseReq",
            fields=[
                (
                    "movimentacaopessoal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPessoal",
                    ),
                ),
                (
                    "data_posse",
                    models.DateField(blank=True, null=True, verbose_name="Data Posse"),
                ),
                (
                    "data_exercicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Exercício"
                    ),
                ),
                (
                    "data_desligamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Desligamento"
                    ),
                ),
                ("ativo", models.BooleanField(blank=True, default=True)),
                (
                    "tipo_movcarreira",
                    models.CharField(
                        choices=[
                            ("NOMEACAO", "Nomeação"),
                            ("APROVEITAMENTO", "Aproveitamento"),
                            ("READAPTACAO", "Readaptação"),
                            ("RECONDUCAO", "Recondução"),
                            ("REINTEGRACAO", "Reintegração"),
                            ("REVERSAO", "Reversão"),
                            ("TITULARIZACAO", "Titularização"),
                            ("PROGRESSAO", "Progressão"),
                            ("ENQUADRAMENTO", "Enquadramento"),
                            ("REMOCAO", "Remoção"),
                            ("PROMOCAO", "Promoção"),
                            ("BENEFICIO", "Benefício Previdenciário"),
                            ("REQUISICAO", "Requisição"),
                            ("POSSE_ESTAGIARIO", "Posse Estagiário"),
                            ("POSSE_COLABORADOR", "Posse Colaborador"),
                        ],
                        default="NOMEACAO",
                        max_length=30,
                        verbose_name="Provimento",
                    ),
                ),
                (
                    "bond",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Gerar vínculo"
                    ),
                ),
                (
                    "judicial_decision",
                    models.BooleanField(
                        default=False, verbose_name="Decorrente de decisão judicial"
                    ),
                ),
                (
                    "out_off_distribution_list",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Fora da lista de distribuição",
                    ),
                ),
                (
                    "number_process",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número do Processo Judicial",
                    ),
                ),
                (
                    "judicial_deposit",
                    models.BooleanField(
                        default=False, verbose_name="Pagamento realizado em juízo"
                    ),
                ),
                (
                    "legal_amnesty_process",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        verbose_name="Número e Ano Lei Anistia",
                    ),
                ),
                (
                    "financial_effect_date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Efeito Financeiro"
                    ),
                ),
                (
                    "financial_effect_date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Efeito Financeiro"
                    ),
                ),
                (
                    "anotacao_geral_exercicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bkp_anotgeral_exercicio",
                        to="rh.AnotacaoGeral",
                    ),
                ),
                (
                    "anotacao_geral_nomeacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bkp_anotgeral_nomeacao",
                        to="rh.AnotacaoGeral",
                    ),
                ),
                (
                    "public_concurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bkp_employees",
                        to="rh.PublicConcurrence",
                        verbose_name="Concurso",
                    ),
                ),
                (
                    "publication_exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bkp_possessions_publication_exercise",
                        to="rh.Publicacao",
                        verbose_name="Publicação de Exercício",
                    ),
                ),
                (
                    "publication_possession",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bkp_possessions_publication_possession",
                        to="rh.Publicacao",
                        verbose_name="Publicação de Posse",
                    ),
                ),
                (
                    "quadro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Quadro",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rh.movimentacaopessoal",),
        ),
        migrations.DeleteModel(
            name="BKP_MovimentacaoPosse",
        ),
    ]
