# Generated by Django 2.2.28 on 2022-04-25 11:02
import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0168_auto_20220420_1122"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processsuspension",
            name="date_suspension",
        ),
        migrations.AddField(
            model_name="cargoquadro",
            name="cbo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.Cbo",
            ),
        ),
        migrations.AddField(
            model_name="processsuspension",
            name="end_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Fim Suspensão"
            ),
        ),
        migrations.AddField(
            model_name="processsuspension",
            name="start_validity",
            field=models.DateField(
                default=datetime.datetime.now(), verbose_name="Data Início Suspensão"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestmove",
            name="cbo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rh.Cbo",
            ),
        ),
        migrations.AlterField(
            model_name="establishmentconfig",
            name="send_fap",
            field=models.BooleanField(
                default=False, verbose_name="Forçar envio FAP ao eSocial?"
            ),
        ),
        migrations.AlterField(
            model_name="socialsecurityemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socialsecurities",
                to="rh.Servidor",
            ),
        ),
    ]
