# Generated by Django 2.2.28 on 2022-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0172_auto_20220530_1510"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molestia",
            name="origem",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Administrativo"), (2, "Judicial")],
                null=True,
                verbose_name="Origem",
            ),
        ),
    ]
