# Generated by Django 2.2.28 on 2022-06-28 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0173_auto_20220609_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmove",
            name="job_position_origin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cargo na origem"
            ),
        ),
        migrations.AlterField(
            model_name="requestmove",
            name="organ_origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requestmove_organ_origin",
                to="rh.UnidadeAdministrativa",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="situacao_funcional_cache",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                    ("INATIVO_TSVE", "Fim de TSVE"),
                ],
                default="NOT_FOUND",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                    ("INATIVO_TSVE", "Fim de TSVE"),
                ],
                default="ATIVO",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="NaturalPersonHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("when", models.DateField(default=datetime.date.today)),
                (
                    "tipo_logradouro",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Endereço - Tipo do Logradouro",
                    ),
                ),
                (
                    "tipo_endereco",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Endereço - Tipo do Endereço",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Endereço - Logradouro",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Endereço - Bairro",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Endereço - Número",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Endereço - Complemento",
                    ),
                ),
                (
                    "outsider",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Endereço no exterior"
                    ),
                ),
                (
                    "outsider_citty",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Cidade no Exterior",
                    ),
                ),
                (
                    "phone_main",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone Principal",
                    ),
                ),
                (
                    "phone_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "RESIDENCIAL"),
                            (2, "COMERCIAL"),
                            (3, "CELULAR"),
                            (4, "FAX"),
                            (5, "INSTITUCIONAL"),
                            (6, "CONTATO EMERGÊNCIA"),
                        ],
                        null=True,
                        verbose_name="Tipo de Telefone",
                    ),
                ),
                (
                    "phone_public",
                    models.BooleanField(blank=True, null=True, verbose_name="Público"),
                ),
                (
                    "phone_description",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "phone_contact_emergency",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone de Emergência",
                    ),
                ),
                (
                    "contact_emergency_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Contato de Emergência",
                    ),
                ),
                (
                    "cnh",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CNH"
                    ),
                ),
                (
                    "cnh_categoria",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="CNH - Categoria",
                    ),
                ),
                (
                    "cnh_expedition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="CNH - Data da Expedição"
                    ),
                ),
                (
                    "cnh_first_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="CNH - Data da primeira habilitação",
                    ),
                ),
                (
                    "cnh_validity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="CNH - Data de Validade"
                    ),
                ),
                (
                    "professional_council",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Conselho Profissional",
                    ),
                ),
                (
                    "professional_council_expedition_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Conselho Profissional - Data da Expedição",
                    ),
                ),
                (
                    "professional_council_validity_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Conselho Profissional - Data de Validade",
                    ),
                ),
                (
                    "professional_council_issuer",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Conselho Profissional - Orgão de Expedição",
                    ),
                ),
                (
                    "nis",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="NIS"
                    ),
                ),
                (
                    "reservista",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Reservista"
                    ),
                ),
                (
                    "classe_reservista",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Reservista - Classe",
                    ),
                ),
                (
                    "ric",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="RIC"
                    ),
                ),
                (
                    "ric_expedition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="RIC - Data da Expedição"
                    ),
                ),
                (
                    "ric_issuer",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="RIC - Orgão Emissor",
                    ),
                ),
                (
                    "rne",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="RNE"
                    ),
                ),
                (
                    "rne_expedition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="RNE - Data da Expedição"
                    ),
                ),
                (
                    "rne_issuer",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="RNE - Orgão Emissor",
                    ),
                ),
                (
                    "titulo_eleitor",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Título Eleitor",
                    ),
                ),
                (
                    "secao_titulo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Título de Eleitor - Seção",
                    ),
                ),
                (
                    "zona_titulo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Título de Eleitor - Zona",
                    ),
                ),
                (
                    "ctps",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="CTPS"
                    ),
                ),
                (
                    "serie_ctps",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="CTPS - Série",
                    ),
                ),
                (
                    "pis_pasep",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="PIS/PASEP"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "data_obito",
                    models.DateField(blank=True, null=True, verbose_name="Data Óbito"),
                ),
                (
                    "doador",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Doador de órgãos"
                    ),
                ),
                (
                    "uniao_estavel",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="União Estável"
                    ),
                ),
                (
                    "email_pessoal",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="E-mail Pessoal",
                    ),
                ),
                (
                    "estado_civil",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "SOLTEIRO"),
                            (2, "CASADO"),
                            (3, "VIUVO"),
                            (4, "SEPARADO JUDICIALMENTE"),
                            (5, "DIVORCIADO"),
                            (6, "UNIAO ESTAVEL"),
                            (7, "NÃO FOI DEFINIDO NO CADASTRO - SERA EXCLUIDO"),
                        ],
                        null=True,
                        verbose_name="Estado civíl",
                    ),
                ),
                (
                    "fator_rh",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "-"), (2, "+"), (3, "NAO INFORMADO")],
                        null=True,
                        verbose_name="Fator RH",
                    ),
                ),
                (
                    "grau_instrucao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "ANALFABETO"),
                            (2, "ALFABETIZADO SEM CURSOS REGULARES"),
                            (3, "SERA EXCLUIDO 4"),
                            (4, "FUNDAMENTAL COMPLETO"),
                            (5, "MÉDIO INCOMPLETO"),
                            (6, "MEDIO COMPLETO OU EQUIVALENTE LEGAL"),
                            (7, "SUPERIOR INCOMPLETO"),
                            (8, "SUPERIOR COMPLETO OU EQUIVALENTE LEGAL"),
                            (9, "ESPECIALIZAÇÃO/PÓS"),
                            (10, "MESTRADO"),
                            (11, "DOUTORADO"),
                            (12, "SERA EXCLUIDO"),
                            (13, "SERA EXCLUIDO 1"),
                            (14, "SERA EXCLUIDO 2"),
                            (15, "ATÉ O 5o ANO INCOMPLETO DO ENSINO FUNDAMENTAL"),
                            (16, "5o ANO COMPLETO DO ENSINO FUNDAMENTAL"),
                            (17, "DO 6o AO 9o ANO DO ENSINO FUNDAMENTAL INCOMPLETO"),
                            (18, "NÃO INFORMADO"),
                        ],
                        null=True,
                        verbose_name="Grau de Instrução",
                    ),
                ),
                (
                    "immigrant_residence_time",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "NÃO É IMIGRANTE"),
                            (1, "PRAZO INDETERMINADO"),
                            (2, "PRAZO DETERMINADO"),
                        ],
                        null=True,
                        verbose_name="Tempo de residência do imigrante",
                    ),
                ),
                (
                    "immigrant_entry_condition",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (10, "NÃO É IMIGRANTE"),
                            (1, "Refugiado"),
                            (2, "Solicitante de refúgio"),
                            (3, "Permanência no Brasil em razão de reunião familiar"),
                            (4, "Beneficiado pelo acordo entre países do Mercosul"),
                            (
                                5,
                                "Dependente de agente diplomático/consular de países que mantêm acordo de reciprocidade p/ exercício atividade remunerada",
                            ),
                            (
                                6,
                                "Beneficiado pelo Tratado de Amizade, Cooperação e Consulta entre a República Federativa do Brasil e República Portuguesa",
                            ),
                            (7, "Outra condição"),
                        ],
                        null=True,
                        verbose_name="Condição de ingresso do imigrante",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "nome_conjuge",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Nome Cônjuge",
                    ),
                ),
                (
                    "nome_mae",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Nome Mãe"
                    ),
                ),
                (
                    "phonetic_father_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "nome_pai",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Nome Pai"
                    ),
                ),
                (
                    "phonetic_mother_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gênero"
                    ),
                ),
                (
                    "raca_cor",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "PARDA"),
                            (2, "AMARELA"),
                            (3, "NEGRA"),
                            (4, "INDÍGENA"),
                            (5, "NÃO INFORMADO"),
                            (6, "BRANCA"),
                        ],
                        null=True,
                        verbose_name="Raça/Cor",
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="RG"
                    ),
                ),
                (
                    "rg_data_expedicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="RG - Data da Expedição"
                    ),
                ),
                (
                    "rg_orgao",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="RG - Orgão"
                    ),
                ),
                (
                    "sangue",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "B"),
                            (2, "AB"),
                            (3, "O"),
                            (4, "A"),
                            (5, "NAO INFORMADO"),
                        ],
                        null=True,
                        verbose_name="Tipo Sanguíneo",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "MASCULINO"), ("F", "FEMININO")],
                        max_length=1,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "sexual_orientation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "HETEROSSEXUAL"),
                            (2, "HOMOSSEXUAL"),
                            (3, "BISSEXUAL"),
                            (4, "ASSEXUAL"),
                            (5, "NÃO INFORMADA"),
                        ],
                        null=True,
                        verbose_name="Orientação Sexual",
                    ),
                ),
                (
                    "social_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome Social",
                    ),
                ),
                (
                    "necessidade_especial",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Necessidade Especial"
                    ),
                ),
                (
                    "profissao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Profissão"
                    ),
                ),
                (
                    "renda_familiar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Renda Familiar",
                    ),
                ),
                (
                    "has_serious_diseases",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Doença Grave"
                    ),
                ),
                (
                    "retired",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Aposentado"
                    ),
                ),
                (
                    "is_lawyer",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Advogado"
                    ),
                ),
                (
                    "oab",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="OAB"
                    ),
                ),
                (
                    "name_cache",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cache Name"
                    ),
                ),
                (
                    "phonetic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, verbose_name="Slug"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "enable_protocol",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Habilitar protocolo"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "rate_fill",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "cnh_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="CNH - Estado",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="NaturalPersonHistory_address_country",
                        to="rh.Pais",
                        verbose_name="País(Residentes no Exterior)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ctps_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="CTPS - Estado",
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ged.Arquivo",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Localidade",
                        verbose_name="Endereço - Cidade",
                    ),
                ),
                (
                    "municipio_naturalidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Localidade",
                        verbose_name="Naturalidade",
                    ),
                ),
                (
                    "municipio_titulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Localidade",
                        verbose_name="Título de Eleitor - Municipio",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rh.Pais",
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "nationality_birth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="NaturalPersonHistory_nationality_birth",
                        to="rh.Pais",
                        verbose_name="País de nascimento",
                    ),
                ),
                (
                    "natural_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="rh.PessoaFisica",
                    ),
                ),
                (
                    "professional_council_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="Conselho Profissional - Estado",
                    ),
                ),
                (
                    "rg_uf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rh.Estado",
                        verbose_name="RG - UF",
                    ),
                ),
                (
                    "ric_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="RIC - Estado",
                    ),
                ),
                (
                    "rne_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rh.Estado",
                        verbose_name="RNE - Estado",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
