# Generated by Django 2.2.28 on 2022-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0174_auto_20220628_1910"),
    ]

    operations = [
        migrations.AddField(
            model_name="molestia",
            name="cid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CID"
            ),
        ),
    ]
