# Generated by Django 2.2.28 on 2022-06-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0175_molestia_cid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoDiligencia",
            fields=[
                (
                    "movimentacaopessoal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPessoal",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                (
                    "comarca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Comarca",
                        verbose_name="Comarca",
                    ),
                ),
                (
                    "publicacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diligencias",
                        to="rh.Publicacao",
                        verbose_name="Publicação",
                    ),
                ),
                (
                    "substituto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diligencias",
                        to="rh.Servidor",
                        verbose_name="Substituto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Verba de Diligência",
                "db_table": "rh_movdiligencias",
            },
            bases=("rh.movimentacaopessoal",),
        ),
    ]
