# Generated by Django 2.2.28 on 2022-07-13 15:54
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import os


FIXTURES = (
    "fixtures/benefit_situation.json",
    "fixtures/type_fired_benefit.json",
    "fixtures/type_pension_death.json",
)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("esocial", "0012_auto_20220713_1550"),
        ("rh", "0176_movimentacaodiligencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminationBenefitMovement",
            fields=[
                (
                    "movimentacaodesligamento_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoDesligamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rh.movimentacaodesligamento",),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="after_organ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benefit_movements_after_organs",
                to="rh.UnidadeAdministrativa",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="benefit_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número do Benefício"
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="founder_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_beneficiaries",
                to="rh.Servidor",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="previous_benefit_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Número do Benefício Anterior",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="previous_organ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benefit_movements_previous_organs",
                to="rh.UnidadeAdministrativa",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="reactivated_benefit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reactivations",
                to="rh.BenefitMovement",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="situation",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Situação do Benefício"
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="termination_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="benefit_movements_reasons",
                to="esocial.ItemTable",
                verbose_name="Motivo da cessação do benefício.",
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="transfer_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Transferência"
            ),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="type_pension_death",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Tipo de Pensão por Morte"
            ),
        ),
        migrations.AlterField(
            model_name="benefitmovement",
            name="benefit_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="benefit_movements_types",
                to="esocial.ItemTable",
                verbose_name="Regra do benefício",
            ),
        ),
        migrations.AlterField(
            model_name="bkp_movimentacaopossereq",
            name="tipo_movcarreira",
            field=models.CharField(
                choices=[
                    ("NOMEACAO", "Nomeação"),
                    ("APROVEITAMENTO", "Aproveitamento"),
                    ("READAPTACAO", "Readaptação"),
                    ("RECONDUCAO", "Recondução"),
                    ("REINTEGRACAO", "Reintegração"),
                    ("REVERSAO", "Reversão"),
                    ("TITULARIZACAO", "Titularização"),
                    ("PROGRESSAO", "Progressão"),
                    ("ENQUADRAMENTO", "Enquadramento"),
                    ("REMOCAO", "Remoção"),
                    ("PROMOCAO", "Promoção"),
                    ("REQUISICAO", "Requisição"),
                    ("POSSE_ESTAGIARIO", "Posse Estagiário"),
                    ("POSSE_COLABORADOR", "Posse Colaborador"),
                    ("BENEFICIO", "Benefício Previdenciário"),
                ],
                default="NOMEACAO",
                max_length=30,
                verbose_name="Provimento",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoposse",
            name="tipo_movcarreira",
            field=models.CharField(
                choices=[
                    ("NOMEACAO", "Nomeação"),
                    ("APROVEITAMENTO", "Aproveitamento"),
                    ("READAPTACAO", "Readaptação"),
                    ("RECONDUCAO", "Recondução"),
                    ("REINTEGRACAO", "Reintegração"),
                    ("REVERSAO", "Reversão"),
                    ("TITULARIZACAO", "Titularização"),
                    ("PROGRESSAO", "Progressão"),
                    ("ENQUADRAMENTO", "Enquadramento"),
                    ("REMOCAO", "Remoção"),
                    ("PROMOCAO", "Promoção"),
                    ("REQUISICAO", "Requisição"),
                    ("POSSE_ESTAGIARIO", "Posse Estagiário"),
                    ("POSSE_COLABORADOR", "Posse Colaborador"),
                    ("BENEFICIO", "Benefício Previdenciário"),
                ],
                default="NOMEACAO",
                max_length=30,
                verbose_name="Provimento",
            ),
        ),
        migrations.CreateModel(
            name="SuspensionBenefit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_validity", models.DateField(verbose_name="Início vigência")),
                (
                    "end_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim vigência"
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("01", "Suspensão por não recadastramento"),
                            ("99", "Outros motivos de suspensão"),
                        ],
                        max_length=2,
                        verbose_name="Motivo da Suspensão",
                    ),
                ),
                (
                    "reason_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descrição do motivo da suspensão",
                    ),
                ),
                (
                    "benefit_movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_suspensions",
                        to="rh.BenefitMovement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(up, down),
    ]
