# Generated by Django 2.2.28 on 2022-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0178_lotacao_nucleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="possessioncollaborator",
            name="number_gedoc",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Número GEDOC"
            ),
        ),
        migrations.AddField(
            model_name="possessioncollaborator",
            name="number_insurance",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Número de Seguro"
            ),
        ),
    ]
