# Generated by Django 2.2.28 on 2022-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0179_auto_20220715_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitmovement",
            name="situation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Benefício concedido pelo próprio órgão declarante"),
                    (2, "Benefício transferido de outro órgão"),
                    (3, "Mudança de CPF do beneficiário"),
                ],
                default=1,
                null=True,
                verbose_name="Situação do Benefício",
            ),
        ),
        migrations.AlterField(
            model_name="benefitmovement",
            name="type_pension_death",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Vitalícia"), (2, "Temporária")],
                null=True,
                verbose_name="Tipo de Pensão por Morte",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaodesligamento",
            name="tipo_desligamento",
            field=models.IntegerField(
                choices=[
                    (1, "EXONERAÇÃO EFETIVO"),
                    (2, "EXONERAÇÃO COMISSIONADO"),
                    (3, "EXONERAÇÃO ESTABILIZADO"),
                    (4, "APOSENTADORIA POR INVALIDEZ"),
                    (5, "APOSENTADORIA VOLUNTÁRIA"),
                    (6, "POSSE EM OUTRO CARGO"),
                    (7, "FALECIMENTO"),
                    (8, "RESCISÃO"),
                    (9, "DEMISSÃO"),
                    (10, "RESERVA REFORMA"),
                    (11, "DISPONIBILIDADE"),
                    (12, "PROMOÇÃO/REMOÇÃO"),
                    (13, "FIM REQUISIÇÃO/ACORDO COOPERAÇÃO"),
                    (14, "APOSENTADORIA COMPULSÓRIA"),
                    (15, "APOSENTADORIA ESPECIAL"),
                    (16, "APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO"),
                    (17, "APOSENTADORIA POR IDADE"),
                    (18, "REDISTRIBUIÇÃO"),
                    (19, "REVERSÃO DE REINTEGRAÇÃO"),
                    (20, "FIM DE MANDATO"),
                    (21, "FIM TSVE"),
                    (22, "FIM DE CONTRATO"),
                    (24, "FIM BENEFÍCIO"),
                ],
                default=1,
                verbose_name="Tipo de Desligamento",
            ),
        ),
        migrations.CreateModel(
            name="MovimentacaoAuxiliarCoordenacao",
            fields=[
                (
                    "movimentacaopessoal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPessoal",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                ("gedoc", models.CharField(max_length=128, verbose_name="GEDOC")),
                (
                    "nucleo",
                    models.IntegerField(
                        choices=[
                            (1, "Núcleo de Atuação Judicial Cível"),
                            (2, "Núcleo de Defesa da Cidadania"),
                            (
                                3,
                                "Núcleo de Defesa do Patrimõnio Público e da Probidade",
                            ),
                            (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                            (5, "Núcleo de Defesa da Criança e do Adolescente"),
                            (6, "Núcleo de Atuação Judicial Criminal"),
                            (7, "Núcleo de Execução Penal"),
                            (8, "Núcleo de Defesa da Vida"),
                            (
                                9,
                                "Núcleo de Defesa da Administração Pública e Ordem Tributária",
                            ),
                            (10, "Promotorias de Justiça do Juizado Eleitoral"),
                        ]
                    ),
                ),
                (
                    "comarca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Comarca",
                        verbose_name="Comarca",
                    ),
                ),
                (
                    "publicacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auxiliar_coordenacao",
                        to="rh.Publicacao",
                        verbose_name="Publicação",
                    ),
                ),
                (
                    "substituto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auxiliar_coordenacao",
                        to="rh.Servidor",
                        verbose_name="Substituto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Designação para Auxiliar de Coordenação",
                "db_table": "rh_mov_auxiliar_coordenacao",
            },
            bases=("rh.movimentacaopessoal",),
        ),
    ]
