# Generated by Django 2.2.28 on 2022-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0181_load_fixture_gestor_beneficios"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="able_to_pay",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Apto a Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="gedoc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="paid_out",
            field=models.BooleanField(blank=True, default=False, verbose_name="Pago"),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="pay_month",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "JANEIRO"),
                    (2, "FEVEREIRO"),
                    (3, "MARÇO"),
                    (4, "ABRIL"),
                    (5, "MAIO"),
                    (6, "JUNHO"),
                    (7, "JULHO"),
                    (8, "AGOSTO"),
                    (9, "SETEMBRO"),
                    (10, "OUTUBRO"),
                    (11, "NOVEMBRO"),
                    (12, "DEZEMBRO"),
                    (13, "13º SALÁRIO"),
                ],
                null=True,
                verbose_name="Mês de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="pay_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ano de Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="payment_installments",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parcelas de Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaodesligamento",
            name="tipo_desligamento",
            field=models.IntegerField(
                choices=[
                    (1, "EXONERAÇÃO EFETIVO"),
                    (2, "EXONERAÇÃO COMISSIONADO"),
                    (3, "EXONERAÇÃO ESTABILIZADO"),
                    (4, "APOSENTADORIA POR INVALIDEZ"),
                    (5, "APOSENTADORIA VOLUNTÁRIA"),
                    (6, "POSSE EM OUTRO CARGO"),
                    (7, "FALECIMENTO"),
                    (8, "RESCISÃO"),
                    (9, "DEMISSÃO"),
                    (10, "RESERVA REFORMA"),
                    (11, "DISPONIBILIDADE"),
                    (12, "PROMOÇÃO/REMOÇÃO"),
                    (13, "FIM REQUISIÇÃO/ACORDO COOPERAÇÃO"),
                    (14, "APOSENTADORIA COMPULSÓRIA"),
                    (15, "APOSENTADORIA ESPECIAL"),
                    (16, "APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO"),
                    (17, "APOSENTADORIA POR IDADE"),
                    (18, "REDISTRIBUIÇÃO"),
                    (19, "REVERSÃO DE REINTEGRAÇÃO"),
                    (20, "FIM DE MANDATO"),
                    (21, "FIM TSVE"),
                    (22, "FIM DE CONTRATO"),
                    (23, "REVISÃO DE BENEFÍCIO"),
                    (24, "FIM BENEFÍCIO"),
                ],
                default=1,
                verbose_name="Tipo de Desligamento",
            ),
        ),
    ]
