# Generated by Django 2.2.28 on 2022-08-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0181_load_fixture_gestor_beneficios"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="publication_change",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication_change",
                to="rh.Publicacao",
            ),
        ),
    ]
