# Generated by Django 2.2.28 on 2022-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0183_merge_20220802_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmove",
            name="regime_contract",
            field=models.IntegerField(
                blank=True, default=2, verbose_name="Regime de contrato"
            ),
        ),
        migrations.AddField(
            model_name="servidor",
            name="event_esocial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="nucleo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="naturalpersonhistory",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "MASCULINO"), ("F", "FEMININO"), ("N", "NÃO INFORMADO")],
                max_length=1,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="pessoafisica",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "MASCULINO"), ("F", "FEMININO"), ("N", "NÃO INFORMADO")],
                max_length=1,
                null=True,
            ),
        ),
    ]
