# Generated by Django 2.2.28 on 2022-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0183_merge_20220802_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="prioridade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Prioridade (Lotacionograma)"
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("041", "GRAT. SUB PROCURADOR JUR"),
                    ("042", "GRAT. SUB PROCURADOR  ADM"),
                    ("087", "GRAT OUVIDOR"),
                    ("114", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("098", "GRAT GAECO"),
                    ("110", "GRAT CEAF"),
                    ("111", "GRAT NARE"),
                    ("112", "GRAT  CAO"),
                    ("113", "GRAT CONSELHO SUPERIOR"),
                    ("005", "GRAT. ACERVO"),
                    ("115", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("116", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("117", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("118", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("030", "DIFICIL PROVIMENTO MEMBRO"),
                    ("067", "AUXILIO ALIMENTACAO"),
                    ("066", "AUXILIO CRECHE"),
                    ("076", "VERBA DILIGENCIA"),
                    ("120", "AUXILIO TRANSPORTE"),
                    ("097", "GRAT NACO"),
                    ("089", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("031", "DIFICIL PROVIMENTO SERVIDOR"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
