# Generated by Django 2.2.28 on 2022-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0185_merge_20220809_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="financial_effect_date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Efeito Financeiro Fim"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="financial_effect_date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Efeito Financeiro Início"
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaorequisicao",
            name="category",
            field=models.IntegerField(
                choices=[
                    (305, "Servidor indicado para conselho ou órgão deliberativo"),
                    (101, "Empregado - CLT"),
                    (301, "Servidor Público Titular de Cargo Efetivo"),
                    (307, "Militar"),
                ],
                default=301,
                verbose_name="Categoria eSocial origem",
            ),
        ),
        migrations.AlterField(
            model_name="requestmove",
            name="category",
            field=models.IntegerField(
                choices=[
                    (305, "Servidor indicado para conselho ou órgão deliberativo"),
                    (101, "Empregado - CLT"),
                    (301, "Servidor Público Titular de Cargo Efetivo"),
                    (307, "Militar"),
                ],
                default=301,
                verbose_name="Categoria eSocial origem",
            ),
        ),
        migrations.AlterField(
            model_name="requestmove",
            name="regime_contract",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "CLT"), (2, "ESTATUTÁRIO")],
                default=2,
                verbose_name="Regime de contrato",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("19", "GRAT OUVIDOR"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("11", "GRAT GAECO"),
                    ("13", "GRAT NACO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("6", "GRAT. ACERVO"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("1", "DIFICIL PROVIMENTO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
