# Generated by Django 2.2.28 on 2022-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0186_auto_20220817_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoposse",
            name="aid_moving_house_gedoc",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="GEDOC do Auxílio Mudança",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoposse",
            name="aid_moving_house_paymente_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data Autorização Pagamentos do Auxílio Mudança",
            ),
        ),
    ]
