# Generated by Django 2.2.28 on 2022-08-26 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0187_auto_20220824_0925"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="consolidated",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Consolidado"
            ),
        ),
        migrations.CreateModel(
            name="MovesSubstitutionsConsolidated",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "days_consolidated",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total Dias Consolidado"
                    ),
                ),
                (
                    "paid_out",
                    models.BooleanField(blank=True, default=False, verbose_name="Pago"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substitutions",
                    models.ManyToManyField(
                        related_name="substitutions_consolidated",
                        to="rh.MovimentacaoSubstituicao",
                        verbose_name="Substituições Consolidado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Substituição - Consolidado",
                "db_table": "rh_movsubstituicaoconsolidado",
                "ordering": ["employee"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
