# Generated by Django 2.2.28 on 2022-08-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0188_auto_20220829_1649"),
        ("rh", "0188_auto_20220826_0038"),
    ]

    operations = []
