# Generated by Django 2.2.28 on 2022-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0192_auto_20220907_0346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="gedoc",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="GEDOC"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                ],
                null=True,
            ),
        ),
    ]
