# Generated by Django 2.2.28 on 2022-09-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0100_auto_20220908_1200"),
        ("rh", "0193_auto_20220908_0910"),
    ]

    operations = [
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="base_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Base",
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="contribution_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Base Previdenciária",
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="employer_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Patronal",
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="installments",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Prazo"
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="installments_paid",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Parcela"
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="paycheck_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paycheck_applied_consolidated",
                to="gfp.ContraCheque",
                verbose_name="Contra Cheque Aplicado",
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="pct",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="qtd_max",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="anotacaogeral",
            name="tipo_documento",
            field=models.IntegerField(
                choices=[
                    (3, "PORTARIA"),
                    (1, "ATO"),
                    (2, "DECRETO"),
                    (4, "OFÍCIO"),
                    (5, "DESPACHO"),
                    (6, "TERMO"),
                    (7, "MEMORANDO"),
                    (8, "REQUERIMENTO"),
                    (9, "CONCESSÃO"),
                    (10, "ACORDO COOPERAÇÃO TÉCNICA"),
                    (11, "LEI"),
                    (12, "APOSTILA"),
                    (14, "DECRETO LEGISLATIVO"),
                    (15, "RESOLUÇÃO"),
                    (16, "CIRCULAR"),
                    (17, "PROCESSO"),
                    (18, "DECISÃO"),
                    (95, "DECLARAÇÃO DE ENTRADA EM ATIVIDADE"),
                    (96, "TERMO LOTAÇÃO"),
                    (97, "TERMO EXERCÍCIO"),
                    (98, "TERMO POSSE"),
                    (99, "OUTROS"),
                    (100, "DOCUMENTO DIGITAL"),
                    (101, "PORTARIA DE INSTAURAÇÃO"),
                    (102, "CONTRATO"),
                    (103, "TERMO DECOMPROMISSO DE ESTAGIO"),
                    (104, "TERMO DE RECISÃO DE ESTAGIÁRIO"),
                    (105, "ATO ADMINISTRATIVO"),
                    (1000, "GEDOC"),
                ],
                verbose_name="Tipo Documento",
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="tipo",
            field=models.IntegerField(
                choices=[
                    (3, "PORTARIA"),
                    (1, "ATO"),
                    (2, "DECRETO"),
                    (4, "OFÍCIO"),
                    (5, "DESPACHO"),
                    (6, "TERMO"),
                    (7, "MEMORANDO"),
                    (8, "REQUERIMENTO"),
                    (9, "CONCESSÃO"),
                    (10, "ACORDO COOPERAÇÃO TÉCNICA"),
                    (11, "LEI"),
                    (12, "APOSTILA"),
                    (14, "DECRETO LEGISLATIVO"),
                    (15, "RESOLUÇÃO"),
                    (16, "CIRCULAR"),
                    (17, "PROCESSO"),
                    (18, "DECISÃO"),
                    (95, "DECLARAÇÃO DE ENTRADA EM ATIVIDADE"),
                    (96, "TERMO LOTAÇÃO"),
                    (97, "TERMO EXERCÍCIO"),
                    (98, "TERMO POSSE"),
                    (99, "OUTROS"),
                    (100, "DOCUMENTO DIGITAL"),
                    (101, "PORTARIA DE INSTAURAÇÃO"),
                    (102, "CONTRATO"),
                    (103, "TERMO DECOMPROMISSO DE ESTAGIO"),
                    (104, "TERMO DE RECISÃO DE ESTAGIÁRIO"),
                    (105, "ATO ADMINISTRATIVO"),
                    (1000, "GEDOC"),
                ],
                verbose_name="Tipo de Publicação",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("19", "GRAT OUVIDOR"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("11", "GRAT GAECO"),
                    ("13", "GRAT NACO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("6", "GRAT. ACERVO"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("1", "DIFICIL PROVIMENTO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
