# Generated by Django 2.2.28 on 2022-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0194_auto_20220908_1314"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacaoauxiliarcoordenacao",
            options={
                "ordering": ["comarca"],
                "verbose_name": "Designação para Auxiliar de Coordenação",
            },
        ),
        migrations.AlterModelOptions(
            name="movimentacaodiligencia",
            options={
                "ordering": ["comarca"],
                "verbose_name": "Movimentação de Verba de Diligência",
            },
        ),
        migrations.AlterField(
            model_name="servidor",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGIÁRIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNTÁRIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM VÍNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                    ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                    ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                    ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                    ("MEC2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO"),
                    ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                    ("APO", "SERVIDOR APOSENTADO"),
                    ("BFP", "BENEFICIARIO DE PENSÃO"),
                    ("REX", "SERVIDOR REQUISITADO EXTERNO"),
                    ("COE", "COLABORADOR EVENTUAL"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo do Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("6", "GRAT. ACERVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
