# Generated by Django 2.2.28 on 2022-09-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0194_auto_20220908_1314"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoTeletrabalho",
            fields=[
                (
                    "movimentacaopessoal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.MovimentacaoPessoal",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                ("presencial", models.IntegerField(verbose_name="Presencial")),
                (
                    "gedoc",
                    models.TextField(blank=True, null=True, verbose_name="GEDOC"),
                ),
                (
                    "tipo_ato",
                    models.IntegerField(
                        choices=[(862, "ATO 862"), (1058, "ATO 1058")],
                        verbose_name="Tipo Ato",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("rh.movimentacaopessoal",),
        ),
        migrations.CreateModel(
            name="MetaTeletrabalho",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                ("descrição", models.TextField(verbose_name="Descrição")),
                ("meta", models.IntegerField(verbose_name="Meta")),
                (
                    "mov_teletrabalho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mov_teletrabalho",
                        to="rh.MovimentacaoTeletrabalho",
                        verbose_name="Movimentação Teletrabalho",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
