# Generated by Django 2.2.28 on 2022-09-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0195_auto_20220921_1505"),
    ]

    operations = [
        migrations.RenameField(
            model_name="metateletrabalho",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
