# Generated by Django 2.2.28 on 2022-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0197_merge_20220929_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="tipo_ato",
            field=models.IntegerField(verbose_name="Tipo Ato"),
        ),
    ]
