# Generated by Django 2.2.28 on 2022-10-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0201_auto_20221013_1421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacaoauxiliarcoordenacao",
            options={
                "ordering": ["designacao"],
                "verbose_name": "Designação para Auxiliar de Coordenação",
            },
        ),
        migrations.RemoveField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="comarca",
        ),
    ]
