# Generated by Django 2.2.28 on 2022-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0202_auto_20221014_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (59, "COMPROVANTE DE VOTAÇÂO - ELEIÇÕES MUNICIPAIS 2020"),
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                    (60, "CURRÍCULO"),
                ],
                default=57,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaorequisicao",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "1 - NÃO INFORMADO"),
                    (
                        101,
                        "101 - Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT",
                    ),
                    (
                        102,
                        "102 - Empregado - Trabalhador rural por pequeno prazo da Lei 11.718/2008",
                    ),
                    (103, "103 - Empregado - Aprendiz"),
                    (104, "104 - Empregado - Doméstico"),
                    (
                        105,
                        "105 - Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998",
                    ),
                    (
                        106,
                        "106 - Trabalhador temporário - Contrato nos termos da Lei 6.019/1974",
                    ),
                    (
                        107,
                        "107 - Empregado - Contrato de trabalho Verde e Amarelo - sem acordo para antecipação mensal da multa",
                    ),
                    (
                        108,
                        "108 - Empregado - Contrato de trabalho Verde e Amarelo - com acordo para antecipação mensal da multa rescisória do FGTS",
                    ),
                    (111, "111 - Empregado - Contrato de trabalho intermitente"),
                    (201, "201 - Trabalhador avulso portuário"),
                    (202, "202 - Trabalhador avulso não portuário"),
                    (
                        301,
                        "301 - Servidor público titular de cargo efetivo, magistrado, ministro de Tribunal de Contas, conselheiro de",
                    ),
                    (
                        302,
                        "302 - Servidor público ocupante de cargo exclusivo em comissão",
                    ),
                    (303, "303 - Exercente de mandato eletivo"),
                    (
                        304,
                        "304 - Servidor público exercente de mandato eletivo, inclusive com exercício de cargo em comissão",
                    ),
                    (
                        305,
                        "305 - Servidor público indicado para conselho ou órgão deliberativo, na condição de representante do governo",
                    ),
                    (
                        306,
                        "306 - Servidor público contratado por tempo determinado, sujeito a regime administrativo especial definido",
                    ),
                    (307, "307 - Militar"),
                    (308, "308 - Conscrito"),
                    (309, "309 - Agente público - Outros"),
                    (310, "310 - Servidor público eventual"),
                    (
                        311,
                        "311 - Ministros, juízes, procuradores, promotores ou oficiais de justiça à disposição da Justiça Eleitoral",
                    ),
                    (312, "312 - Auxiliar local"),
                    (
                        313,
                        "313 - Servidor público exercente de atividade de instrutoria, capacitação, treinamento, curso ou concurso",
                    ),
                    (
                        401,
                        "401 - Dirigente sindical - Informação prestada pelo sindicato",
                    ),
                    (
                        410,
                        "410 - Trabalhador cedido/exercício em outro órgão/juiz auxiliar - Informação prestada pelo cessionário/destino",
                    ),
                    (501, "501 - Dirigente sindical - Segurado especial"),
                    (
                        701,
                        "701 - Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias",
                    ),
                    (
                        711,
                        "711 - Contribuinte individual - Transportador autônomo de passageiros",
                    ),
                    (
                        712,
                        "712 - Contribuinte individual - Transportador autônomo de carga",
                    ),
                    (
                        721,
                        "721 - Contribuinte individual - Diretor não empregado, com FGTS",
                    ),
                    (
                        722,
                        "722 - Contribuinte individual - Diretor não empregado, sem FGTS",
                    ),
                    (
                        723,
                        "723 - Contribuinte individual - Empresário, sócio e membro de conselho de administração ou fiscal",
                    ),
                    (
                        731,
                        "731 - Contribuinte individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho",
                    ),
                    (
                        734,
                        "734 - Contribuinte individual - Transportador cooperado que presta serviços por intermédio de",
                    ),
                    (
                        738,
                        "738 - Contribuinte individual - Cooperado filiado a cooperativa de produção",
                    ),
                    (
                        741,
                        "741 - Contribuinte individual - Microempreendedor individual",
                    ),
                    (
                        751,
                        "751 - Contribuinte individual - Magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral",
                    ),
                    (
                        761,
                        "761 - Contribuinte individual - Associado eleito para direção de cooperativa, associação ou entidade de classe",
                    ),
                    (
                        771,
                        "771 - Contribuinte individual - Membro de conselho tutelar, nos termos da Lei 8.069/1990",
                    ),
                    (
                        781,
                        "781 - Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa",
                    ),
                    (901, "901 - Estagiário"),
                    (
                        902,
                        "902 - Médico residente ou residente em área profissional de saúde",
                    ),
                    (903, "903 - Bolsista"),
                    (
                        904,
                        "904 - Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário",
                    ),
                    (
                        906,
                        "906 - Beneficiário do Programa Nacional de Prestação de Serviço Civil Voluntário",
                    ),
                ],
                default=301,
                verbose_name="Categoria eSocial origem",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="tipo_ato",
            field=models.IntegerField(
                choices=[(862, "862"), (1058, "1058")], verbose_name="Tipo Ato"
            ),
        ),
        migrations.AlterField(
            model_name="requestmove",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "1 - NÃO INFORMADO"),
                    (
                        101,
                        "101 - Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT",
                    ),
                    (
                        102,
                        "102 - Empregado - Trabalhador rural por pequeno prazo da Lei 11.718/2008",
                    ),
                    (103, "103 - Empregado - Aprendiz"),
                    (104, "104 - Empregado - Doméstico"),
                    (
                        105,
                        "105 - Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998",
                    ),
                    (
                        106,
                        "106 - Trabalhador temporário - Contrato nos termos da Lei 6.019/1974",
                    ),
                    (
                        107,
                        "107 - Empregado - Contrato de trabalho Verde e Amarelo - sem acordo para antecipação mensal da multa",
                    ),
                    (
                        108,
                        "108 - Empregado - Contrato de trabalho Verde e Amarelo - com acordo para antecipação mensal da multa rescisória do FGTS",
                    ),
                    (111, "111 - Empregado - Contrato de trabalho intermitente"),
                    (201, "201 - Trabalhador avulso portuário"),
                    (202, "202 - Trabalhador avulso não portuário"),
                    (
                        301,
                        "301 - Servidor público titular de cargo efetivo, magistrado, ministro de Tribunal de Contas, conselheiro de",
                    ),
                    (
                        302,
                        "302 - Servidor público ocupante de cargo exclusivo em comissão",
                    ),
                    (303, "303 - Exercente de mandato eletivo"),
                    (
                        304,
                        "304 - Servidor público exercente de mandato eletivo, inclusive com exercício de cargo em comissão",
                    ),
                    (
                        305,
                        "305 - Servidor público indicado para conselho ou órgão deliberativo, na condição de representante do governo",
                    ),
                    (
                        306,
                        "306 - Servidor público contratado por tempo determinado, sujeito a regime administrativo especial definido",
                    ),
                    (307, "307 - Militar"),
                    (308, "308 - Conscrito"),
                    (309, "309 - Agente público - Outros"),
                    (310, "310 - Servidor público eventual"),
                    (
                        311,
                        "311 - Ministros, juízes, procuradores, promotores ou oficiais de justiça à disposição da Justiça Eleitoral",
                    ),
                    (312, "312 - Auxiliar local"),
                    (
                        313,
                        "313 - Servidor público exercente de atividade de instrutoria, capacitação, treinamento, curso ou concurso",
                    ),
                    (
                        401,
                        "401 - Dirigente sindical - Informação prestada pelo sindicato",
                    ),
                    (
                        410,
                        "410 - Trabalhador cedido/exercício em outro órgão/juiz auxiliar - Informação prestada pelo cessionário/destino",
                    ),
                    (501, "501 - Dirigente sindical - Segurado especial"),
                    (
                        701,
                        "701 - Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias",
                    ),
                    (
                        711,
                        "711 - Contribuinte individual - Transportador autônomo de passageiros",
                    ),
                    (
                        712,
                        "712 - Contribuinte individual - Transportador autônomo de carga",
                    ),
                    (
                        721,
                        "721 - Contribuinte individual - Diretor não empregado, com FGTS",
                    ),
                    (
                        722,
                        "722 - Contribuinte individual - Diretor não empregado, sem FGTS",
                    ),
                    (
                        723,
                        "723 - Contribuinte individual - Empresário, sócio e membro de conselho de administração ou fiscal",
                    ),
                    (
                        731,
                        "731 - Contribuinte individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho",
                    ),
                    (
                        734,
                        "734 - Contribuinte individual - Transportador cooperado que presta serviços por intermédio de",
                    ),
                    (
                        738,
                        "738 - Contribuinte individual - Cooperado filiado a cooperativa de produção",
                    ),
                    (
                        741,
                        "741 - Contribuinte individual - Microempreendedor individual",
                    ),
                    (
                        751,
                        "751 - Contribuinte individual - Magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral",
                    ),
                    (
                        761,
                        "761 - Contribuinte individual - Associado eleito para direção de cooperativa, associação ou entidade de classe",
                    ),
                    (
                        771,
                        "771 - Contribuinte individual - Membro de conselho tutelar, nos termos da Lei 8.069/1990",
                    ),
                    (
                        781,
                        "781 - Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa",
                    ),
                    (901, "901 - Estagiário"),
                    (
                        902,
                        "902 - Médico residente ou residente em área profissional de saúde",
                    ),
                    (903, "903 - Bolsista"),
                    (
                        904,
                        "904 - Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário",
                    ),
                    (
                        906,
                        "906 - Beneficiário do Programa Nacional de Prestação de Serviço Civil Voluntário",
                    ),
                ],
                default=301,
                verbose_name="Categoria eSocial origem",
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="category_esocial",
            field=models.IntegerField(
                choices=[
                    (1, "1 - NÃO INFORMADO"),
                    (
                        101,
                        "101 - Empregado - Geral, inclusive o empregado público da administração direta ou indireta contratado pela CLT",
                    ),
                    (
                        102,
                        "102 - Empregado - Trabalhador rural por pequeno prazo da Lei 11.718/2008",
                    ),
                    (103, "103 - Empregado - Aprendiz"),
                    (104, "104 - Empregado - Doméstico"),
                    (
                        105,
                        "105 - Empregado - Contrato a termo firmado nos termos da Lei 9.601/1998",
                    ),
                    (
                        106,
                        "106 - Trabalhador temporário - Contrato nos termos da Lei 6.019/1974",
                    ),
                    (
                        107,
                        "107 - Empregado - Contrato de trabalho Verde e Amarelo - sem acordo para antecipação mensal da multa",
                    ),
                    (
                        108,
                        "108 - Empregado - Contrato de trabalho Verde e Amarelo - com acordo para antecipação mensal da multa rescisória do FGTS",
                    ),
                    (111, "111 - Empregado - Contrato de trabalho intermitente"),
                    (201, "201 - Trabalhador avulso portuário"),
                    (202, "202 - Trabalhador avulso não portuário"),
                    (
                        301,
                        "301 - Servidor público titular de cargo efetivo, magistrado, ministro de Tribunal de Contas, conselheiro de",
                    ),
                    (
                        302,
                        "302 - Servidor público ocupante de cargo exclusivo em comissão",
                    ),
                    (303, "303 - Exercente de mandato eletivo"),
                    (
                        304,
                        "304 - Servidor público exercente de mandato eletivo, inclusive com exercício de cargo em comissão",
                    ),
                    (
                        305,
                        "305 - Servidor público indicado para conselho ou órgão deliberativo, na condição de representante do governo",
                    ),
                    (
                        306,
                        "306 - Servidor público contratado por tempo determinado, sujeito a regime administrativo especial definido",
                    ),
                    (307, "307 - Militar"),
                    (308, "308 - Conscrito"),
                    (309, "309 - Agente público - Outros"),
                    (310, "310 - Servidor público eventual"),
                    (
                        311,
                        "311 - Ministros, juízes, procuradores, promotores ou oficiais de justiça à disposição da Justiça Eleitoral",
                    ),
                    (312, "312 - Auxiliar local"),
                    (
                        313,
                        "313 - Servidor público exercente de atividade de instrutoria, capacitação, treinamento, curso ou concurso",
                    ),
                    (
                        401,
                        "401 - Dirigente sindical - Informação prestada pelo sindicato",
                    ),
                    (
                        410,
                        "410 - Trabalhador cedido/exercício em outro órgão/juiz auxiliar - Informação prestada pelo cessionário/destino",
                    ),
                    (501, "501 - Dirigente sindical - Segurado especial"),
                    (
                        701,
                        "701 - Contribuinte individual - Autônomo em geral, exceto se enquadrado em uma das demais categorias",
                    ),
                    (
                        711,
                        "711 - Contribuinte individual - Transportador autônomo de passageiros",
                    ),
                    (
                        712,
                        "712 - Contribuinte individual - Transportador autônomo de carga",
                    ),
                    (
                        721,
                        "721 - Contribuinte individual - Diretor não empregado, com FGTS",
                    ),
                    (
                        722,
                        "722 - Contribuinte individual - Diretor não empregado, sem FGTS",
                    ),
                    (
                        723,
                        "723 - Contribuinte individual - Empresário, sócio e membro de conselho de administração ou fiscal",
                    ),
                    (
                        731,
                        "731 - Contribuinte individual - Cooperado que presta serviços por intermédio de cooperativa de trabalho",
                    ),
                    (
                        734,
                        "734 - Contribuinte individual - Transportador cooperado que presta serviços por intermédio de",
                    ),
                    (
                        738,
                        "738 - Contribuinte individual - Cooperado filiado a cooperativa de produção",
                    ),
                    (
                        741,
                        "741 - Contribuinte individual - Microempreendedor individual",
                    ),
                    (
                        751,
                        "751 - Contribuinte individual - Magistrado classista temporário da Justiça do Trabalho ou da Justiça Eleitoral",
                    ),
                    (
                        761,
                        "761 - Contribuinte individual - Associado eleito para direção de cooperativa, associação ou entidade de classe",
                    ),
                    (
                        771,
                        "771 - Contribuinte individual - Membro de conselho tutelar, nos termos da Lei 8.069/1990",
                    ),
                    (
                        781,
                        "781 - Ministro de confissão religiosa ou membro de vida consagrada, de congregação ou de ordem religiosa",
                    ),
                    (901, "901 - Estagiário"),
                    (
                        902,
                        "902 - Médico residente ou residente em área profissional de saúde",
                    ),
                    (903, "903 - Bolsista"),
                    (
                        904,
                        "904 - Participante de curso de formação, como etapa de concurso público, sem vínculo de emprego/estatutário",
                    ),
                    (
                        906,
                        "906 - Beneficiário do Programa Nacional de Prestação de Serviço Civil Voluntário",
                    ),
                ],
                default=1,
                verbose_name="Categoria eSocial",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("30", "EXERCÍCIO CUMULATIVO"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("6", "GRAT. ACERVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
