# Generated by Django 2.2.28 on 2022-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0204_auto_20221019_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="gestor_plantao_dti",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Gestor plantão DTI"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="gestor_plantao_eleitoral",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Gestor plantão eleitoral"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="gestor_plantao_final_semana",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Gestor plantão final de Semana"
            ),
        ),
        migrations.AddField(
            model_name="lotacao",
            name="gestor_plantao_recesso",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Gestor plantão recesso"
            ),
        ),
    ]
