# Generated by Django 2.2.28 on 2022-11-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0205_auto_20221019_1650"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimentacaoauxiliarcoordenacao",
            options={
                "ordering": ["servidor_designacao"],
                "verbose_name": "Designação para Auxiliar de Coordenação",
            },
        ),
        migrations.RemoveField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="designacao",
        ),
        migrations.AddField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="servidor_designacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.ServidorLotacao",
                verbose_name="Designação para gratificação",
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                    (13, "Zona Eleitoral"),
                    (14, "CAO"),
                    (15, "GAECO"),
                    (16, "Procuradoria Especializada da Capital"),
                    (17, "Procuradoria da Capital"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                    (13, "Zona Eleitoral"),
                    (14, "CAO"),
                    (15, "GAECO"),
                    (16, "Procuradoria Especializada da Capital"),
                    (17, "Procuradoria da Capital"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="tipo_ato",
            field=models.IntegerField(
                choices=[(862, "ATO 862/2019 "), (1058, "ATO 1058/2021")],
                verbose_name="Tipo Ato",
            ),
        ),
    ]
