# Generated by Django 2.2.28 on 2022-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0206_auto_20221104_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="lotacionograma",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
