# Generated by Django 2.2.28 on 2022-11-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0207_auto_20221110_1607"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCineBrasil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("label", models.CharField(max_length=150, verbose_name="Rótulo")),
            ],
        ),
        migrations.CreateModel(
            name="HigherEducationInstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "acronym",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sigla"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ArqDesignacaoExercicio",
        ),
        migrations.AlterModelOptions(
            name="movimentacaoauxiliarcoordenacao",
            options={
                "ordering": ["servidor_designacao__lotacao__comarca"],
                "verbose_name": "Designação para Auxiliar de Coordenação",
            },
        ),
        migrations.AddField(
            model_name="servidor",
            name="quota_system",
            field=models.IntegerField(default=1, verbose_name="Regime de Cotas"),
        ),
        migrations.AlterField(
            model_name="cargoquadro",
            name="nivel_escolaridade",
            field=models.IntegerField(
                choices=[
                    (1, "FUNDAMENTAL"),
                    (2, "MÉDIO"),
                    (3, "SUPERIOR"),
                    (4, "ELEMENTAR"),
                    (5, "POS GRADUAÇÃO"),
                ],
                null=True,
                verbose_name="Nível de Escolaridade",
            ),
        ),
        migrations.AlterField(
            model_name="configjobposition",
            name="educational_level",
            field=models.IntegerField(
                choices=[
                    (1, "FUNDAMENTAL"),
                    (2, "MÉDIO"),
                    (3, "SUPERIOR"),
                    (4, "ELEMENTAR"),
                    (5, "POS GRADUAÇÃO"),
                ],
                default=3,
                null=True,
                verbose_name="Nível de Escolaridade",
            ),
        ),
        migrations.AlterField(
            model_name="graduationcnmp",
            name="institution",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instituicao"
            ),
        ),
        migrations.AddField(
            model_name="graduationcnmp",
            name="course_cine_brasil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.CourseCineBrasil",
                verbose_name="Curso Cine Brasil",
            ),
        ),
        migrations.AddField(
            model_name="graduationcnmp",
            name="institution_inep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.HigherEducationInstitution",
                verbose_name="Instituição (INEP)",
            ),
        ),
        migrations.AddField(
            model_name="possessiontrainee",
            name="course_cine_brasil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.CourseCineBrasil",
                verbose_name="Curso (INEP)",
            ),
        ),
        migrations.AddField(
            model_name="possessiontrainee",
            name="institution_inep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.HigherEducationInstitution",
                verbose_name="Instituição (INEP)",
            ),
        ),
    ]
