# Generated by Django 2.2.28 on 2022-12-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0209_auto_20221212_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidorlotacao",
            name="electoral_refused",
            field=models.BooleanField(default=False, verbose_name="Declínio Eleitoral"),
        ),
    ]
