# Generated by Django 2.2.28 on 2022-12-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0209_auto_20221212_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="highereducationinstitution",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.Localidade",
            ),
        ),
    ]
