# Generated by Django 2.2.28 on 2022-12-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0210_highereducationinstitution_municipality"),
        ("rh", "0210_auto_20221215_1718"),
    ]

    operations = []
