# Generated by Django 2.2.28 on 2023-01-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0211_merge_20221215_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="tipo_lotacao",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, ""), (1, "Administração"), (2, "Execução")],
                default=0,
                null=True,
            ),
        ),
    ]
