# Generated by Django 2.2.28 on 2023-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0212_lotacao_tipo_lotacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidorlotacao",
            name="occup_area",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(2, "Área Meio"), (1, "Área Fim")],
                null=True,
                verbose_name="Área de Atuação",
            ),
        ),
    ]
