# Generated by Django 2.2.28 on 2023-01-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0213_servidorlotacao_occup_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="metateletrabalho",
            name="periodicity",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Diário"),
                    (2, "Semanal"),
                    (3, "Mensal"),
                    (4, "Bimestral"),
                    (5, "Trimestral"),
                    (6, "Quadrimestral"),
                    (7, "Semestral"),
                    (8, "Anual"),
                ],
                null=True,
            ),
        ),
    ]
