# Generated by Django 2.2.28 on 2023-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0214_auto_20230118_0932"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="deducao",
            field=models.IntegerField(blank=True, null=True, verbose_name="Dedução"),
        ),
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="tempo_bruto",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Tempo Bruto"
            ),
        ),
        migrations.AddField(
            model_name="anotacaotemposervico",
            name="tipo_regime",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR"), (4, "RPPE")],
                null=True,
                verbose_name="Tipo de Regime",
            ),
        ),
        migrations.AlterField(
            model_name="metateletrabalho",
            name="periodicity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="tipo_ato",
            field=models.IntegerField(
                choices=[
                    (862, "ATO 862/2019 "),
                    (1058, "ATO 1058/2021"),
                    (1149, "ATO 1.149/2022"),
                ],
                verbose_name="Tipo Ato",
            ),
        ),
    ]
