# Generated by Django 2.2.28 on 2023-02-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0215_auto_20230203_1029"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotacaoEleitoral",
            fields=[
                (
                    "anotacaogeral_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rh.AnotacaoGeral",
                    ),
                ),
                ("data_declinio", models.DateField(verbose_name="Data Declínio")),
                (
                    "lotacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Lotacao",
                        verbose_name="Lotacão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anotação Eleitoral",
                "db_table": "rh_anoteleitoral",
            },
            bases=("rh.anotacaogeral",),
        ),
    ]
