# Generated by Django 2.2.28 on 2023-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0216_auto_20230206_2021"),
    ]

    operations = [
        migrations.RenameField(
            model_name="naturalpersonhistory",
            old_name="email_pessoal",
            new_name="email_institucional",
        ),
        migrations.RenameField(
            model_name="pessoafisica",
            old_name="email_pessoal",
            new_name="email_institucional",
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                    (13, "Zona Eleitoral"),
                    (14, "CAO"),
                    (15, "GAECO"),
                    (16, "Procuradoria Especializada da Capital"),
                    (17, "Procuradoria da Capital"),
                    (18, "PGJ (Administração)"),
                    (19, "Núcleo de Diligências"),
                    (20, "Núcleo Diretoria Promotorias Capital"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metateletrabalho",
            name="periodicity",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Diário"),
                    (2, "Semanal"),
                    (3, "Mensal"),
                    (4, "Bimestral"),
                    (5, "Trimestral"),
                    (6, "Quadrimestral"),
                    (7, "Semestral"),
                    (8, "Anual"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="nucleo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Núcleo de Atuação Judicial Cível"),
                    (2, "Núcleo de Defesa da Cidadania"),
                    (3, "Núcleo de Defesa do Patrimônio Público e da Probidade"),
                    (4, "Núcleo de Defesa Ambiental e da Ordem Urbanística"),
                    (5, "Núcleo de Defesa da Criança e do Adolescente"),
                    (6, "Núcleo de Atuação Judicial Criminal"),
                    (7, "Núcleo de Execução Penal"),
                    (8, "Núcleo de Defesa da Vida"),
                    (9, "Núcleo de Defesa da Administração Pública e Ordem Tributária"),
                    (10, "Promotorias de Justiça do Juizado Eleitoral"),
                    (11, "Núcleo de Enfrent. à Violência Dom. e Fam. Contra a Mulher"),
                    (12, "Núcleo das Promotorias de Substituição"),
                    (13, "Zona Eleitoral"),
                    (14, "CAO"),
                    (15, "GAECO"),
                    (16, "Procuradoria Especializada da Capital"),
                    (17, "Procuradoria da Capital"),
                    (18, "PGJ (Administração)"),
                    (19, "Núcleo de Diligências"),
                    (20, "Núcleo Diretoria Promotorias Capital"),
                ],
                null=True,
            ),
        ),
    ]
