# Generated by Django 2.2.28 on 2023-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0217_auto_20230216_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naturalpersonhistory",
            name="email_institucional",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="E-mail Institucional",
            ),
        ),
    ]
