# Generated by Django 2.2.28 on 2023-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0218_auto_20230216_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalpersonhistory",
            name="email_pessoal",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="E-mail Pessoal"
            ),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="email_pessoal",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
