# Generated by Django 2.2.28 on 2023-02-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0219_auto_20230217_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotacao",
            name="responsible_substituted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsavel_substituido",
                to="rh.Servidor",
                verbose_name="Responsável substituído",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosubstituicao",
            name="designation_substitute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitution_substitute",
                to="rh.ServidorLotacao",
                verbose_name="Designação substituto",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosubstituicao",
            name="designation_substituted",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitution_substituted",
                to="rh.ServidorLotacao",
                verbose_name="Designação do substituído",
            ),
        ),
    ]
