# Generated by Django 2.2.28 on 2023-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0221_controlepagamentopessoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidorlotacao",
            name="coordinator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="action",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, ""),
                    (1, "Coadjuvando"),
                    (2, "Colaborando"),
                    (3, "Adjunto"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
