# Generated by Django 2.2.28 on 2023-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0222_auto_20230302_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadro",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
