# Generated by Django 2.2.28 on 2023-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0225_auto_20230316_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="metateletrabalho",
            name="active",
            field=models.BooleanField(blank=True, default=True, verbose_name="Ativo"),
        ),
    ]
