# Generated by Django 2.2.28 on 2023-03-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0226_metateletrabalho_active"),
        ("rh", "0226_experienciaprofissional"),
    ]

    operations = []
