# Generated by Django 2.2.28 on 2023-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0227_merge_20230320_1156"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaodesligamento",
            name="desligamento_automatico",
            field=models.BooleanField(
                default=False, verbose_name="Desligamento Automático"
            ),
        ),
    ]
