# Generated by Django 2.2.28 on 2023-03-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0228_movimentacaodesligamento_desligamento_automatico"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlepagamentopessoal",
            options={
                "ordering": [
                    "-periodo_ano",
                    "-periodo_mes",
                    "servidor",
                    "evento",
                    "status",
                ],
                "verbose_name": "Controle Pagamento de Pessoal",
            },
        ),
        migrations.AlterModelOptions(
            name="movimentacaoauxiliarcoordenacao",
            options={
                "ordering": ["servidor"],
                "verbose_name": "Designação para Auxiliar de Coordenação",
            },
        ),
        migrations.RenameField(
            model_name="controlepagamentopessoal",
            old_name="valor",
            new_name="valor_calculado",
        ),
        migrations.RemoveField(
            model_name="controlepagamentopessoal",
            name="pago",
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analise", "Em Análise"),
                    ("apto", "Apto para pgto"),
                    ("inapto", "Inapto para pgto"),
                    ("pago", "Pago"),
                ],
                default="analise",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="valor_confirmado",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="data_fim",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Data Fim"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoauxiliarcoordenacao",
            name="data_inicio",
            field=models.DateField(db_index=True, verbose_name="Data Início"),
        ),
    ]
