# Generated by Django 2.2.28 on 2023-03-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0229_auto_20230327_1044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlepagamentopessoal",
            name="qtd",
        ),
        migrations.RemoveField(
            model_name="controlepagamentopessoal",
            name="valor_confirmado",
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="info",
            field=models.TextField(blank=True, null=True, verbose_name="Informações"),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="parcela",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Parcela"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="pct",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="prazo",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Prazo"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="qtd_dias_calculado",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd Dias Calculado"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="qtd_dias_confirmado",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd Dias Confirmado"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="qtd_dias_pgto",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd Dias para Pgto"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="qtd_max_dias",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Qtd Máxima de Dias Calculado",
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="valor_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Valor Base",
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="valor_base_prev",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Base Previdenciária",
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="valor_patronal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=16,
                null=True,
                verbose_name="Patronal",
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="valor_pgto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor para Pgto",
            ),
        ),
        migrations.AlterField(
            model_name="controlepagamentopessoal",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pgtos_pessoal_evento",
                to="gfp.Evento",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="controlepagamentopessoal",
            name="valor_calculado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=16,
                null=True,
                verbose_name="Valor Calculado",
            ),
        ),
    ]
