# Generated by Django 2.2.28 on 2023-04-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0230_auto_20230328_2137"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="aprovador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aprovador_teletrabalho",
                to="rh.Servidor",
                verbose_name="Aprovador do Teletrabalho",
            ),
        ),
    ]
