# Generated by Django 2.2.28 on 2023-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0231_movimentacaoteletrabalho_aprovador"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeworkplacehistory",
            name="partial_responsible",
            field=models.BooleanField(
                default=False, verbose_name="Responsável parcial"
            ),
        ),
        migrations.AddField(
            model_name="servidorlotacao",
            name="partial_responsible",
            field=models.BooleanField(
                default=False, verbose_name="Responsável Parcial"
            ),
        ),
    ]
