# Generated by Django 2.2.28 on 2023-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0232_auto_20230403_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="ativo",
            field=models.BooleanField(blank=True, default=False, verbose_name="Ativo"),
        ),
    ]
