# Generated by Django 2.2.28 on 2023-05-03 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0233_movimentacaoteletrabalho_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="situacao_funcional_cache",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_PARC_ESTUDAR",
                        "Afastado Parcial - Estudar no País/Exterior",
                    ),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    (
                        "ATIVO_AFA_SINDICANCIA_ADM",
                        "Afastado - Sindicância Administrativa",
                    ),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                    ("INATIVO_TSVE", "Fim de TSVE"),
                    ("ATIVO_AFA_CANDIDATURA", "Afastado - Candidatura"),
                ],
                default="NOT_FOUND",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="situacaofuncional",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("NOT_FOUND", "Não encontrado"),
                    ("ATIVO", "Em atividade"),
                    ("ATIVO_LIC_SAUDE", "Licenciado - Tratamento de Saúde"),
                    ("ATIVO_LIC_DOENCA", "Licenciado - Doença em Pessoa da Família"),
                    ("ATIVO_LIC_MATERNIDADE", "Licenciado - Maternidade"),
                    ("ATIVO_LIC_ADOCAO", "Licenciado - Tutoria ou Adoção"),
                    (
                        "ATIVO_LIC_AFAST_CONJUGE",
                        "Licenciado - Afastamento do Conjuge/Companheiro",
                    ),
                    ("ATIVO_LIC_MILITAR", "Licenciado - Serviço Militar"),
                    ("ATIVO_LIC_POLITICA", "Licenciado - Atividade Política"),
                    (
                        "ATIVO_LIC_CAPACITACAO",
                        "Licenciado - Capacitação ou Especialização (3 meses por quinquênio)",
                    ),
                    (
                        "ATIVO_LIC_INTERESSE",
                        "Licenciado - Tratar de Interesse Particular",
                    ),
                    (
                        "ATIVO_LIC_CLASSISTA",
                        "Licenciado - Desempenho de Mandato Classista",
                    ),
                    ("ATIVO_LIC_PREMIO", "Licença Prêmio"),
                    ("ATIVO_AFA_DISPONIBILIDADE", "Afastado - Em disponibilidade"),
                    (
                        "ATIVO_AFA_OUT_ORG_ONUS_MP",
                        "Afastado - Servir a outro Órgão com ônus para o MP",
                    ),
                    (
                        "ATIVO_AFA_OUT_ORG_SEM_ONUS_MP",
                        "Afastado - Servir a outro Órgão sem ônus para o MP",
                    ),
                    ("ATIVO_AFA_SUSPENSAO", "Afastado - Suspensão"),
                    ("ATIVO_AFA_COMPJUIZO", "Afastado - Comparecer a juízo"),
                    ("ATIVO_AFA_ELETIVO", "Afastado - Exercício de Mandato Eletivo"),
                    ("ATIVO_AFA_ESTUDAR", "Afastado - Estudar no País/Exterior"),
                    (
                        "ATIVO_AFA_PARC_ESTUDAR",
                        "Afastado Parcial - Estudar no País/Exterior",
                    ),
                    ("ATIVO_AFA_MISSAO", "Afastado - Missão Oficial no Exterior"),
                    (
                        "ATIVO_AFA_ELEITORAL",
                        "Afastado - Convocação da Justiça Eleitoral",
                    ),
                    ("ATIVO_AFA_JURI", "Afastado - Servir no Tribunal do Juri"),
                    (
                        "ATIVO_AFA_TREINAMENTO",
                        "Afastado - Treinamento (Palestras/Congressos/Seminários/Outros)",
                    ),
                    (
                        "ATIVO_AFA_DESLOCAMENTO",
                        "Afastado - Deslocamento até a nova sede",
                    ),
                    (
                        "ATIVO_AFA_COMPETICAO",
                        "Afastado - Competição desportiva ou representação cultural",
                    ),
                    (
                        "ATIVO_AFA_CURSO_CONCURSO",
                        "Afastado - Curso de formação de etapa de concurso público",
                    ),
                    ("ATIVO_AFA_PRISAO", "Afastado - Prisão"),
                    (
                        "ATIVO_AFA_SINDICANCIA_ADM",
                        "Afastado - Sindicância Administrativa",
                    ),
                    ("ATIVO_AUS_SANGUE", "Ausente - Doação de sangue"),
                    ("ATIVO_AUS_ELEITOR", "Ausente - Alistamento como eleitor"),
                    ("ATIVO_AUS_CASAMENTO", "Ausente - Casamento"),
                    ("ATIVO_AUS_NASCIMENTO", "Ausente - Nascimento/adoção de filho"),
                    ("ATIVO_AUS_FALECIMENTO", "Ausente - Falecimento"),
                    (
                        "ATIVO_AUS_CONCLUSAO",
                        "Ausente - Finalização de trabalho de conclusão de curso",
                    ),
                    ("ATIVO_FERIAS", "Fruindo Férias"),
                    ("ATIVO_VIAGEM", "Viagem a Serviço"),
                    ("ATIVO_RECESSO", "Fruindo Recesso"),
                    ("ATIVO_FOLGA_ANIVERSARIO", "Fruindo Folga Aniversário"),
                    ("ATIVO_FOLGA_ELEITORAL", "Fruindo Folga Eleitoral"),
                    ("ATIVO_FOLGA_COMPENSACAO", "Fruindo Folga Compensação"),
                    ("ATIVO_USU_BANCO_DE_HORAS", "Fruindo Folga Banco de Horas"),
                    ("ATIVO_USU_PREVENCAOSAUDE", "Fruindo Folga Prevenção Saúde"),
                    ("ATIVO_ATUACAO_GRUPO_TRAB", "Atuação em Grupo de Trabalho"),
                    ("ATIVO_DESEMPENHO_FUNCAO", "Desempenho de Função"),
                    ("ATIVO_PLANTAO", "Fruindo Plantão de Feriado"),
                    (
                        "ATIVO_DISPONIBILIDADE",
                        "Em disponibilidade(com onus para origem ou para requisitante?)",
                    ),
                    ("INATIVO_APO_INVALIDEZ", "Aposentado - Por invalidez"),
                    ("INATIVO_APO_COMPULSORIO", "Aposentado - Compulsório"),
                    ("INATIVO_APO_VOLUNTARIO", "Aposentado - Voluntário"),
                    ("INATIVO_APO_ESPECIAL", "Aposentado - Especial"),
                    (
                        "INATIVO_APO_TEMPO_CONTRIBUICAO",
                        "Aposentado - Por tempo de contribuição",
                    ),
                    ("INATIVO_APO_IDADE", "Aposentado - Por idade"),
                    ("INATIVO_FALECIDO", "Falecido"),
                    ("INATIVO_EXONERADO_PEDIDO", "Exonerado - A pedido"),
                    ("INATIVO_EXONERADO_OFICIO", "Exonerado - De ofício"),
                    ("INATIVO_DEMITIDO", "Demitido"),
                    ("INATIVO_DEVOLVIDO", "Devolvido ao Órgão de Origem"),
                    ("INATIVO_OUTRO_CARGO", "Posse em outro cargo inacumulável"),
                    ("INATIVO_TSVE", "Fim de TSVE"),
                    ("ATIVO_AFA_CANDIDATURA", "Afastado - Candidatura"),
                ],
                default="ATIVO",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("6", "GRAT. ACERVO"),
                    ("30", "EXERCÍCIO CUMULATIVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="PeriodoExercCumulPermanente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "mes",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-ano", "-mes"),
                "unique_together": {("mes", "ano")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="ExercCumulPermanente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "qtd_dias_afastamento",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qtd Dias Afastamento"
                    ),
                ),
                (
                    "qtd_dias_consolidado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qtd Dias Consolidado"
                    ),
                ),
                (
                    "qtd_dias_deferido",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qtd Dias - Calculado"
                    ),
                ),
                (
                    "pct_consolidado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "pct_deferido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAL", "Avaliar"),
                            ("DEFER", "Deferido"),
                            ("INDEFER", "Indeferido"),
                        ],
                        default="AVAL",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercs_cumul_perm",
                        to="rh.PeriodoExercCumulPermanente",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exerc_cumul_perm",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
            options={
                "ordering": ("-periodo", "servidor", "-created_at"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="DesigsExercCumulPermanente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("substituicao", models.BooleanField(default=False)),
                ("base_calculo", models.BooleanField(default=False)),
                (
                    "data_vigencia_inicio",
                    models.DateField(null=True, verbose_name="Data Vigência Início"),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Vigência Fim"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exerc_cumul_perm_desigs",
                        to="rh.Lotacao",
                        verbose_name="Designação",
                    ),
                ),
                (
                    "exerc_cumul_perm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designacoes",
                        to="rh.ExercCumulPermanente",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-data_vigencia_inicio", "-created_at"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
