# Generated by Django 2.2.28 on 2023-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0234_auto_20230503_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Vida Funcional"),
                    (2, "Tela de designações"),
                    (3, "Afastamento"),
                ],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
        migrations.AddField(
            model_name="servidorlotacao",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Vida Funcional"),
                    (2, "Tela de designações"),
                    (3, "Afastamento"),
                ],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
    ]
