# Generated by Django 2.2.28 on 2023-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0234_auto_20230503_2119"),
    ]

    operations = [
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="pct",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
