# Generated by Django 2.2.28 on 2023-05-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0235_desigsexerccumulpermanente_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="acao",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, ""),
                    (1, "Coadjuvando"),
                    (2, "Colaborando"),
                    (3, "Adjunto"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="com_prejuizo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="coordenador",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="responsavel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="titular",
            field=models.BooleanField(default=False),
        ),
    ]
