# Generated by Django 2.2.28 on 2023-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0236_auto_20230511_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="defer",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Deferido"
            ),
        ),
    ]
