# Generated by Django 2.2.28 on 2023-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0237_movessubstitutionsconsolidated_defer"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="defer",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Deferido"
            ),
        ),
    ]
