# Generated by Django 2.2.28 on 2023-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0238_movimentacaosubstituicao_defer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desigsexerccumulpermanente",
            name="com_prejuizo",
        ),
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="prejuizo",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, ""), (1, "Com prejuízo"), (2, "Sem prejuízo")],
                default=0,
                null=True,
            ),
        ),
    ]
