# Generated by Django 2.2.28 on 2023-05-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0235_auto_20230511_1137"),
        ("rh", "0239_auto_20230515_1535"),
    ]

    operations = []
