# Generated by Django 2.2.28 on 2023-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0240_merge_20230517_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaosubstituicao",
            name="origin_register",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Origem do registro"
            ),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="origin_register",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Origem do registro"
            ),
        ),
    ]
