# Generated by Django 2.2.28 on 2023-06-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0241_auto_20230530_1350"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembersTelecommuting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                (
                    "telecommuting_reasons",
                    models.IntegerField(default=1, verbose_name="Tipo Ato"),
                ),
                (
                    "status",
                    models.BooleanField(blank=True, default=True, verbose_name="Ativo"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_teleworks",
                        to="rh.Servidor",
                        verbose_name="Membro em trabalho remoto",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telework_member_file",
                        to="ged.Arquivo",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
