# Generated by Django 2.2.28 on 2023-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0241_auto_20230530_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidorlotacao",
            name="empenho_gaeco",
            field=models.BooleanField(default=False),
        )
    ]
