# Generated by Django 2.2.28 on 2023-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0244_merge_20230616_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="indicativo",
            field=models.CharField(
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                    ("R", "RESIDENTE"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="tipo_lei_cargo",
            field=models.CharField(
                choices=[
                    ("EF", "EFETIVO"),
                    ("CM", "COMISSÃO"),
                    ("FC", "FUNÇÃO DE CONFIANÇA"),
                    ("AC", "ACORDO DE COOPERAÇÃO TÉCNICA"),
                    ("ES", "ESTAGIÁRIO"),
                    ("EL", "ELETIVO"),
                    ("TE", "TERCEIRIZADO"),
                    ("VL", "VOLUNTÁRIO"),
                    ("JC", "JOVEM CIDADÃO - APRENDIZ"),
                    ("EX", "EXTERNO - SEM VÍNCULO"),
                    ("AP", "APOSENTADO"),
                    ("RS", "RESIDENTE"),
                ],
                default="EF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoatividade",
            name="activity_as",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                    ("R", "RESIDENTE"),
                ],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                    ("R", "RESIDENTE"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="tiposervidor",
            name="indicativo",
            field=models.CharField(
                choices=[
                    ("I", "INDEFINIDO"),
                    ("E", "ESTAGIÁRIO"),
                    ("M", "MEMBRO DO MINISTÉRIO PÚBLICO"),
                    ("P", "MILITAR"),
                    ("S", "SERVIDOR"),
                    ("T", "TERCEIRIZADO"),
                    ("V", "VOLUNTÁRIO"),
                    ("A", "JOVEM CIDADÃO - APRENDIZ"),
                    ("X", "EXTERNO SEM VÍNCULO"),
                    ("O", "APOSENTADO"),
                    ("R", "RESIDENTE"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
