# Generated by Django 2.2.28 on 2023-06-20 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0117_auto_20230620_1628"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0245_auto_20230620_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="modulo_origem",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Módulo de origem"
            ),
        ),
        migrations.AlterField(
            model_name="exerccumulpermanente",
            name="qtd_dias_deferido",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd Dias - Deferido"
            ),
        ),
        migrations.AlterField(
            model_name="memberstelecommuting",
            name="telecommuting_reasons",
            field=models.IntegerField(
                default=1, verbose_name="Razão do Trabalho Remoto"
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("6", "GRAT. ACERVO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("30", "EXERCÍCIO CUMULATIVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="PeriodoGratMembros",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "mes",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-ano", "-mes"),
                "unique_together": {("mes", "ano")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="GratMembros",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designacoes",
                    models.ManyToManyField(
                        related_name="designacoes_grat_membro", to="rh.ServidorLotacao"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="rh.PeriodoGratMembros",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gratificacoes_membros",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
            options={
                "ordering": ("-periodo", "servidor", "-created_at"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Gratificacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "qtd_dias_consolidado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qtd Dias - Consolidado"
                    ),
                ),
                (
                    "qtd_dias_deferido",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qtd Dias - Deferido"
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(blank=True, null=True, verbose_name="Ordem"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAL", "Avaliar"),
                            ("DEFER", "Deferido"),
                            ("INDEFER", "Indeferido"),
                        ],
                        default="AVAL",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "cumulativa",
                    models.BooleanField(default=False, verbose_name="Cumulativa"),
                ),
                (
                    "principal",
                    models.BooleanField(default=False, verbose_name="Principal"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gratificacoes_membro",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "grat_membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gratificacoes",
                        to="rh.GratMembros",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("ordem", "evento"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="GratAuxiliarCoordenacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "qtd_dias_consolidado_titular",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Consolidado - Titular",
                    ),
                ),
                (
                    "qtd_dias_deferido_titular",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Deferido - Titular",
                    ),
                ),
                (
                    "qtd_dias_consolidado_substituto",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Consolidado - Substituto",
                    ),
                ),
                (
                    "qtd_dias_deferido_substituto",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Deferido - Substituto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAL", "Avaliar"),
                            ("DEFER", "Deferido"),
                            ("INDEFER", "Indeferido"),
                        ],
                        default="AVAL",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "mes",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grat_aux_coord",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mov_aux_coord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grat_aux_coord",
                        to="rh.MovimentacaoAuxiliarCoordenacao",
                    ),
                ),
            ],
            options={
                "ordering": ("-ano", "-mes"),
                "unique_together": {("mov_aux_coord", "ano", "mes")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
