# Generated by Django 2.2.28 on 2023-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0246_auto_20230620_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturalpersonhistory",
            name="send_esocial",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Enviar para eSocial?"
            ),
        ),
        migrations.AlterField(
            model_name="naturalpersonhistory",
            name="tipo_endereco",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Residencial"),
                    (2, "Comercial"),
                    (3, "Institucional"),
                    (4, "Profissional"),
                    (5, "Via pública"),
                    (6, "Não informado"),
                ],
                null=True,
                verbose_name="Endereço - Tipo do Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="naturalpersonhistory",
            name="tipo_logradouro",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "AVENIDA"),
                    (2, "PRAÇA"),
                    (3, "VIELA"),
                    (4, "PONTO - SERA EXCLUIDO"),
                    (5, "VIADUTO"),
                    (7, "OUTROS - SERA EXCLUIDO"),
                    (8, "RUA"),
                    (9, "QUADRA"),
                    (100, "EXTERIOR"),
                ],
                null=True,
                verbose_name="Endereço - Tipo do Logradouro",
            ),
        ),
    ]
