# Generated by Django 2.2.28 on 2023-06-23 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0117_auto_20230620_1628"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0247_auto_20230623_1009"),
    ]

    operations = [
        migrations.CreateModel(
            name="GratDiligencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "qtd_dias_consolidado_titular",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Consolidado - Titular",
                    ),
                ),
                (
                    "qtd_dias_deferido_titular",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Deferido - Titular",
                    ),
                ),
                (
                    "qtd_dias_consolidado_substituto",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Consolidado - Substituto",
                    ),
                ),
                (
                    "qtd_dias_deferido_substituto",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Qtd Dias - Deferido - Substituto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVAL", "Avaliar"),
                            ("DEFER", "Deferido"),
                            ("INDEFER", "Indeferido"),
                        ],
                        default="AVAL",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "mes",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "JANEIRO"),
                            (2, "FEVEREIRO"),
                            (3, "MARÇO"),
                            (4, "ABRIL"),
                            (5, "MAIO"),
                            (6, "JUNHO"),
                            (7, "JULHO"),
                            (8, "AGOSTO"),
                            (9, "SETEMBRO"),
                            (10, "OUTUBRO"),
                            (11, "NOVEMBRO"),
                            (12, "DEZEMBRO"),
                            (13, "13º SALÁRIO"),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "data_ultimo_calculo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Último Cálculo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grat_diligencia",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mov_diligencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grat_diligencia",
                        to="rh.MovimentacaoDiligencia",
                    ),
                ),
            ],
            options={
                "ordering": ("-ano", "-mes"),
                "unique_together": {("mov_diligencia", "ano", "mes")},
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
