# Generated by Django 2.2.28 on 2023-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0249_auto_20230626_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="desigsexerccumulpermanente",
            name="cumulativa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servidorlotacao",
            name="cumulativa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="memberstelecommuting",
            name="telecommuting_reasons",
            field=models.IntegerField(
                default=1, verbose_name="Razão do Trabalho Remoto"
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="type_by_possession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFE", "SERVIDOR EFETIVO"),
                    ("ECM", "SERVIDOR EFETIVO E COMISSIONADO"),
                    ("MBR", "MEMBRO"),
                    ("MEL", "MEMBRO COM CARGO ELETIVO"),
                    ("MCM", "MEMBRO COM CARGO COMISSIONADO"),
                    ("MEC", "MEMBRO COM CARGO ELETIVO E COMISSIONADO"),
                    ("CMS", "SERVIDOR COMISSIONADO"),
                    ("REQ", "SERVIDOR REQUISITADO"),
                    ("RCM", "SERVIDOR REQUISITADO COMISSIONADO"),
                    ("EST", "ESTAGIÁRIO"),
                    ("TCR", "TERCEIRIZADO"),
                    ("VOL", "VOLUNTÁRIO"),
                    ("CTR", "SERVIDOR CONTRATADO"),
                    ("EXT", "EXTERNO SEM VÍNCULO"),
                    ("SAP", "SERVIDOR EFETIVO APOSENTADO"),
                    ("MAP", "MEMBRO APOSENTADO"),
                    ("RFC", "SERVIDOR REQUISITADO COM FUNÇÃO"),
                    ("EFC", "SERVIDOR EFETIVO COM FUNÇÃO"),
                    ("JCA", "JOVEM CIDADÃO - APRENDIZ"),
                    ("XXX", "DESCONHECIDO"),
                    ("MBR2", "MEMBRO DE 2ª ENTRÂNCIA"),
                    ("MEL2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO"),
                    ("MCM2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO COMISSIONADO"),
                    ("MEC2", "MEMBRO DE 2ª ENTRÂNCIA COM CARGO ELETIVO E COMISSIONADO"),
                    ("MAP2", "MEMBRO DE 2ª ENTRANCIA APOSENTADO"),
                    ("APO", "SERVIDOR APOSENTADO"),
                    ("BFP", "BENEFICIARIO DE PENSÃO"),
                    ("REX", "SERVIDOR REQUISITADO EXTERNO"),
                    ("COE", "COLABORADOR EVENTUAL"),
                ],
                default="EFE",
                max_length=5,
                verbose_name="Tipo do Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("6", "GRAT. ACERVO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("30", "EXERCÍCIO CUMULATIVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
