# Generated by Django 2.2.28 on 2023-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0251_auto_20230705_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialsecurityemployee",
            name="ignore_others_ssc",
            field=models.BooleanField(
                default=False, verbose_name="Ignorar Outras Configs. Previdenciárias"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosubstituicao",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "VDF"), (2, "DSG"), (3, "AFT"), (4, "GAD")],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
        migrations.AlterField(
            model_name="servidorlotacao",
            name="origin_register",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "VDF"), (2, "DSG"), (3, "AFT"), (4, "GAD")],
                default=None,
                null=True,
                verbose_name="Origem do registro",
            ),
        ),
    ]
