# Generated by Django 2.2.28 on 2023-08-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0252_auto_20230721_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="old_social_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome Social - BKP"
            ),
        ),
    ]
