# Generated by Django 2.2.28 on 2023-08-17 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0254_remove_pessoafisica_old_social_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigPeriodoCumulativoSubstituicao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=250, verbose_name="Título")),
                (
                    "data_inicio_periodo",
                    models.DateField(verbose_name="Data Início de Venda"),
                ),
                (
                    "data_fim_periodo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim de Venda"
                    ),
                ),
                (
                    "data_inicio_abrangencia",
                    models.DateField(verbose_name="Data Início da Abrangência"),
                ),
                (
                    "data_fim_abrangencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim da Abrangência"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("titulo", "data_inicio_periodo", "data_inicio_abrangencia")
                },
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
