# Generated by Django 2.2.28 on 2023-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0255_configperiodocumulativosubstituicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="posicao_concurso",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Posição no Concurso"
            ),
        ),
    ]
