# Generated by Django 2.2.28 on 2023-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0256_servidor_posicao_concurso"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoposse",
            name="data_inicio_instancia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Início na Instância"
            ),
        )
    ]
