# Generated by Django 2.2.28 on 2023-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0259_auto_20230830_1726"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listaantiguidademembros",
            name="tempo_afastamento",
        ),
        migrations.RemoveField(
            model_name="listaantiguidademembros",
            name="tempo_efetivo_exercicio",
        ),
        migrations.RemoveField(
            model_name="listaantiguidademembros",
            name="tempo_total_carreira",
        ),
        migrations.RemoveField(
            model_name="listaantiguidademembros",
            name="tempo_total_instancia",
        ),
    ]
