# Generated by Django 2.2.28 on 2023-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0260_auto_20230901_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="data_inicio_instancia",
            field=models.DateField(null=True, verbose_name="Data Início na Instância"),
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="origem",
            field=models.CharField(
                blank=True,
                choices=[("Manual", "MANUAL"), ("Job", "JOB")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="tempo_afastamento",
            field=models.IntegerField(null=True, verbose_name="Tempo de Afastamento"),
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="tempo_efetivo_exercicio",
            field=models.IntegerField(
                null=True, verbose_name="Tempo de Efetivo Exercício"
            ),
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="tempo_total_carreira",
            field=models.IntegerField(
                null=True, verbose_name="Tempo Total de Carreira"
            ),
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="tempo_total_instancia",
            field=models.IntegerField(
                null=True, verbose_name="Tempo Total na Instância"
            ),
        ),
    ]
