# Generated by Django 2.2.28 on 2023-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0261_auto_20230901_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="dimensionamento",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Dimensionamento BI"
            ),
        )
    ]
