# Generated by Django 2.2.28 on 2023-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0263_auto_20230904_1213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listaantiguidademembros",
            options={"ordering": ["tipo_cargo", "ordem_antiguidade"]},
        ),
        migrations.AddField(
            model_name="listaantiguidademembros",
            name="tipo_cargo",
            field=models.IntegerField(
                choices=[
                    (1, "PROCURADOR"),
                    (2, "PROMOTOR"),
                    (3, "PROMOTOR SUBSTITUTO"),
                ],
                null=True,
                verbose_name="Cargo",
            ),
        ),
        migrations.AlterField(
            model_name="listaantiguidademembros",
            name="ordem_antiguidade",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Ordem de Antiguidade"
            ),
        ),
    ]
