# Generated by Django 2.2.28 on 2023-09-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0264_auto_20230905_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("6", "GRAT. ACERVO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("30", "EXERCÍCIO CUMULATIVO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
        migrations.DeleteModel(
            name="ListaAntiguidadeMembros",
        ),
    ]
