# Generated by Django 2.2.28 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0265_auto_20230906_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="verificado_mastiff",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Verificado no Mastiff"
            ),
        ),
    ]
