# Generated by Django 2.2.28 on 2023-09-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0267_auto_20230914_1311"),
        ("rh", "0267_auto_20230914_0842"),
    ]

    operations = []
