# Generated by Django 2.2.28 on 2023-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0268_merge_20230921_1911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberstelecommuting",
            name="status",
        ),
    ]
