# Generated by Django 2.2.28 on 2023-09-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0268_merge_20230921_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="lotacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_teletrabalho",
                to="rh.ServidorLotacao",
                verbose_name="lotacao",
            ),
        ),
    ]
