# Generated by Django 2.2.28 on 2023-10-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0269_auto_20230927_1345"),
        ("rh", "0270_atualizar_movimentacaoposse_lotacao"),
    ]

    operations = []
