# Generated by Django 2.2.28 on 2023-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0271_merge_20231002_1913"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotacao",
            name="classificacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Promotoria"),
                    (2, "Procuradoria"),
                    (3, "Coordenadoria"),
                    (999, "Outros"),
                ],
                null=True,
                verbose_name="Classificação",
            ),
        ),
    ]
