# Generated by Django 2.2.28 on 2023-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0272_lotacao_classificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoursworkcontract",
            name="duracao_intervalo",
            field=models.CharField(
                blank=True,
                default="0200",
                max_length=4,
                verbose_name="Duração do Intervalo",
            ),
        ),
    ]
