# Generated by Django 2.2.28 on 2023-10-03 12:11

from django.db import migrations
from rh.models import Lotacao
from django.db.models import Q
from contrib.utils import getLogger

log = getLogger(__name__)


def classificar_lotacoes(apps, schema_editor):
    """
    Preenche o campo Classificação da Lotação com: Promotoria, Procuradoria, Coordenadoria ou Outros,
    de acordo com o nome da Lotação.
    """
    Lotacao.objects.filter(nome__icontains="PROMOTORIA").update(classificacao=1)
    Lotacao.objects.filter(nome__icontains="PROCURADORIA").update(classificacao=2)
    Lotacao.objects.filter(nome__icontains="COORDENA").update(classificacao=3)
    Lotacao.objects.exclude(
        Q(nome__icontains="PROMOTORIA")
        | Q(nome__icontains="PROCURADORIA")
        | Q(nome__icontains="COORDENA")
    ).update(classificacao=9999)


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0272_lotacao_classificacao"),
    ]

    operations = [
        migrations.RunPython(classificar_lotacoes),
    ]
