# Generated by Django 2.2.28 on 2023-10-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0273_hoursworkcontract_duracao_intervalo"),
        ("rh", "0273_classificar_lotacoes"),
    ]

    operations = []
