# Generated by Django 2.2.28 on 2023-10-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0277_auto_20231010_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="retroativo",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Retroativo"
            ),
        ),
    ]
