# Generated by Django 2.2.28 on 2023-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0278_auto_20231011_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberstelecommuting",
            name="status",
            field=models.IntegerField(
                choices=[(1, "ATIVO"), (2, "INATIVO"), (3, "AGENDADO")],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
