# Generated by Django 2.2.28 on 2023-10-09 11:11

from django.db import migrations
from datetime import date

from rh.models import MembersTelecommuting


def forward(*args, **kwargs):
    hoje = date.today()

    q_membros_agendado = MembersTelecommuting.objects.filter(data_inicio__gt=hoje)
    if q_membros_agendado.exists():
        q_membros_agendado.update(status=3)

    q_membros_inativos = MembersTelecommuting.objects.filter(
        status=1, data_fim__lt=hoje
    )
    if q_membros_inativos.exists():
        q_membros_inativos.update(status=2)

    q_membros_ativos = MembersTelecommuting.objects.filter(status=3, data_inicio=hoje)
    if q_membros_ativos.exists():
        q_membros_ativos.update(status=1)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0279_memberstelecommuting_status"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
