# Generated by Django 2.2.28 on 2023-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0280_atualizar_status_membros_teletrabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="indeferido",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Indeferido"
            ),
        ),
    ]
