# Generated by Django 2.2.28 on 2023-10-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0282_auto_20231024_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotacao",
            name="classificacao",
            field=models.IntegerField(
                blank=True,
                choices=[(4, "Eleitoral"), (999, "Outros")],
                null=True,
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="tipo",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (3, "PORTARIA"),
                    (1, "ATO"),
                    (2, "DECRETO"),
                    (4, "OFÍCIO"),
                    (5, "DESPACHO"),
                    (6, "TERMO"),
                    (7, "MEMORANDO"),
                    (8, "REQUERIMENTO"),
                    (9, "CONCESSÃO"),
                    (10, "ACORDO COOPERAÇÃO TÉCNICA"),
                    (11, "LEI"),
                    (12, "APOSTILA"),
                    (14, "DECRETO LEGISLATIVO"),
                    (15, "RESOLUÇÃO"),
                    (16, "CIRCULAR"),
                    (17, "PROCESSO"),
                    (18, "DECISÃO"),
                    (95, "DECLARAÇÃO DE ENTRADA EM ATIVIDADE"),
                    (96, "TERMO LOTAÇÃO"),
                    (97, "TERMO EXERCÍCIO"),
                    (98, "TERMO POSSE"),
                    (99, "OUTROS"),
                    (100, "DOCUMENTO DIGITAL"),
                    (101, "PORTARIA DE INSTAURAÇÃO"),
                    (102, "CONTRATO"),
                    (103, "TERMO DECOMPROMISSO DE ESTAGIO"),
                    (104, "TERMO DE RECISÃO DE ESTAGIÁRIO"),
                    (105, "ATO ADMINISTRATIVO"),
                    (106, "Portaria PGJ"),
                    (107, "Portaria DG"),
                    (108, "Portaria SGA"),
                    (109, "Portaria PRE MT"),
                    (1000, "GEDOC"),
                ],
                null=True,
                verbose_name="Tipo de Publicação",
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("6", "GRAT. ACERVO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("30", "EXERCÍCIO CUMULATIVO SUBSTITUIÇÃO COORDENAÇÃO"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
