# Generated by Django 2.2.28 on 2023-10-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0283_auto_20231025_2308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="ano",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Ano"
            ),
        ),
    ]
