# Generated by Django 2.2.28 on 2023-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0285_load_fixture_representante_legal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benefitmovement",
            name="type_legal_representative",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "PAI"),
                    (2, "MÂE"),
                    (3, "TUROR"),
                    (4, "CURADOR"),
                    (5, "RESPONSAVEL POR GUARDA"),
                    (6, "GUARDA DE MENOR DE 18 ANOS"),
                ],
                default=1,
                null=True,
                verbose_name="Tipo de representante",
            ),
        )
    ]
