# Generated by Django 2.2.28 on 2023-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0286_auto_20231113_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metateletrabalho",
            name="periodicity",
            field=models.IntegerField(
                choices=[
                    (1, "Diário"),
                    (2, "Semanal"),
                    (3, "Mensal"),
                    (4, "Bimestral"),
                    (5, "Trimestral"),
                    (6, "Quadrimestral"),
                    (7, "Semestral"),
                    (8, "Anual"),
                ],
                null=True,
            ),
        ),
    ]
