# Generated by Django 2.2.28 on 2023-11-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0288_atualizar_periodicidade_meta_teletrabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="movessubstitutionsconsolidated",
            name="gcpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="move_subs_consolidated",
                to="rh.ControlePagamentoPessoal",
                verbose_name="GCPP",
            ),
        ),
        migrations.AlterField(
            model_name="benefitmovement",
            name="type_legal_representative",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "PAI"),
                    (2, "MÂE"),
                    (3, "TUTOR"),
                    (4, "CURADOR"),
                    (5, "RESPONSAVEL POR GUARDA"),
                    (6, "GUARDA DE MENOR DE 18 ANOS"),
                ],
                default=1,
                null=True,
                verbose_name="Tipo de representante",
            ),
        ),
        migrations.AlterField(
            model_name="lotacao",
            name="classificacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Promotoria"),
                    (2, "Procuradoria"),
                    (3, "Coordenadoria"),
                    (4, "Eleitoral"),
                    (999, "Outros"),
                ],
                null=True,
                verbose_name="Classificação",
            ),
        ),
    ]
