# Generated by Django 2.2.28 on 2023-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0289_auto_20231122_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="codigo_email",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Código de verificação do e-mail",
            ),
        ),
        migrations.AddField(
            model_name="pessoafisica",
            name="email_pessoal_verificado",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="E-mail secundário verificado?",
            ),
        ),
    ]
