# Generated by Django 2.2.28 on 2024-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0290_auto_20231207_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoursworkcontract",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, null=True, unique=True, verbose_name="Código"
            ),
        ),
    ]
