# Generated by Django 2.2.28 on 2024-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0291_auto_20240126_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargahoraria",
            name="quantidade",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
