# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
from django.core.management import call_command

import os

FIXTURES = ("fixtures/controller_gestor_batidas.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        try:
            call_command("loaddata", filepath)
        except Exception as err:
            print(err)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0293_lotacao_gestor_plantao_pgj"),
    ]

    operations = [
        migrations.RunPython(up, down),
    ]
