# Generated by Django 2.2.28 on 2024-02-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0296_auto_20240226_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialsecurityemployee",
            name="participante_migrado",
            field=models.BooleanField(
                default=False, verbose_name="Participante migrado?"
            ),
        ),
    ]
