# Generated by Django 2.2.28 on 2024-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0298_load_fixture_gestor_envio_ponto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlepagamentopessoal",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analise", "Em Análise"),
                    ("calculado", "Calculado"),
                    ("apto", "Apto para pgto"),
                    ("inapto", "Inapto para pgto"),
                    ("pago", "Pago"),
                ],
                default="analise",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
