# Generated by Django 2.2.28 on 2024-03-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0299_auto_20240311_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaosubstituicao",
            name="periodo_cumul_subs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periodo_cumul_subs",
                to="rh.ConfigPeriodoCumulativoSubstituicao",
            ),
        ),
    ]
