# Generated by Django 2.2.28 on 2024-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0301_atualizar_periodo_janela_exerc_cumul"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configperiodocumulativosubstituicao",
            options={"ordering": ("-data_inicio_periodo", "-data_fim_periodo")},
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="beneficio_integral",
            field=models.BooleanField(default=False, verbose_name="Beneficio Integral"),
        ),
        migrations.AddField(
            model_name="benefitmovement",
            name="paridade_salarial",
            field=models.BooleanField(default=False, verbose_name="Paridade Salarial"),
        ),
    ]
