# Generated by Django 2.2.28 on 2024-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0302_auto_20240423_1515"),
        ("rh", "0302_auto_20240424_1136"),
    ]

    operations = []
