# Generated by Django 2.2.28 on 2024-06-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("rh", "0305_atualizar_localidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="graduationcnmp",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anexo_graduationcnmp",
                to="ged.Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="improvementandgraduatecnmp",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anexo_improvementandgraduatecnmp",
                to="ged.Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="publishedworkscnmp",
            name="anexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anexo_publishedworkscnmp",
                to="ged.Arquivo",
            ),
        ),
    ]
