# Generated by Django 2.2.28 on 2024-07-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0307_atualizar_ibges_localidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="dependencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pag_pessoal_dependencia",
                to="rh.Dependencia",
                verbose_name="Dependencia",
            ),
        ),
        migrations.AlterField(
            model_name="memberstelecommuting",
            name="telecommuting_reasons",
            field=models.IntegerField(
                choices=[
                    (1, "Razao 1"),
                    (2, "Razao 2"),
                    (6, "Razao 6"),
                    (3, "Razao 3"),
                    (4, "Razao 4"),
                    (5, "Razao 5"),
                ],
                default=1,
                verbose_name="Razão do Trabalho Remoto",
            ),
        ),
    ]
