# Generated by Django 2.2.28 on 2024-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0309_incluir_localidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="data_alteracao_esocial",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de alteração esocial"
            ),
        ),
    ]
