# Generated by Django 2.2.28 on 2024-07-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0310_pessoafisica_data_alteracao_esocial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoafisica",
            name="data_codigo_email",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data código email"
            ),
        )
    ]
