# Generated by Django 2.2.28 on 2024-07-25 11:02

from django.db import migrations, models
from django.core.management import call_command
from django.conf import settings
import os


FIXTURES = ("fixtures/new_job_atualizar_id_usuario.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0311_auto_20240722_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="id_usuario_mastiff",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="id do usuário mastiff"
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
