# Generated by Django 2.2.28 on 2024-08-08 17:09

from django.db import migrations
from contrib.middleware import set_current_user
from rh.models import MovimentacaoTeletrabalho


def forward(*args, **kwargs):
    set_current_user("athenas")
    servidores = []
    for mov_tele in MovimentacaoTeletrabalho.objects.order_by(
        "servidor", "data_inicio"
    ):
        # Usa update para não travar nas validações
        if not mov_tele.servidor.pk in servidores:
            MovimentacaoTeletrabalho.objects.filter(pk=mov_tele.pk).update(
                tipo_pedido=1
            )  # Adesão
            servidores.append(mov_tele.servidor.pk)
        else:
            MovimentacaoTeletrabalho.objects.filter(pk=mov_tele.pk).update(
                tipo_pedido=2
            )  # Prorrogação


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0313_auto_20240801_1042"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
