# Generated by Django 2.2.28 on 2024-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0314_atribui_tipo_pedido_teletrabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadobancario",
            name="agencia_dv",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="DV da agência"
            ),
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="agencia_numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número da agência"
            ),
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="conta_dv",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="DV da conta"
            ),
        ),
        migrations.AddField(
            model_name="dadobancario",
            name="conta_numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número da conta"
            ),
        ),
        migrations.AlterField(
            model_name="workplaceconfigtag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("31", "INDENIZ COMP ART4º-E- 358/2011"),
                    ("25", "GRAT. AUXILIAR ADM. SUPERIOR"),
                    ("21", "GRAT. SUB PROCURADOR JUR"),
                    ("20", "GRAT. SUB PROCURADOR  ADM"),
                    ("24", "GRAT. SUB. PROCURADOR PLAN"),
                    ("19", "GRAT OUVIDOR"),
                    ("27", "GRAT. OUVIDOR ADJUNTO"),
                    ("26", "GRAT. FUNÇÃO ORGÃOS AUXILIARES"),
                    ("23", "GRAT FUNÇÃO AUX GAB PGJ"),
                    ("22", "GRAT. FUNÇÃO. AUX. GAB COGER"),
                    ("13", "GRAT NACO"),
                    ("11", "GRAT GAECO"),
                    ("10", "GRAT CEAF"),
                    ("9", "GRAT NARE"),
                    ("8", "GRAT  CAO"),
                    ("12", "GRAT FUNÇÃO COORDENADOR  10%"),
                    ("14", "GRAT FUNÇÃO COORDENAÇÃO 30%"),
                    ("1", "DIFICIL PROVIMENTO"),
                    ("2", "GRAT FUNÇÃO COORDENADOR 5%"),
                    ("3", "GRAT FUNÇÃO COORDENADOR 6%"),
                    ("4", "GRAT FUNÇÃO COORDENADOR 7%"),
                    ("5", "GRAT FUNÇÃO COORDENADOR 8%"),
                    ("6", "GRAT. ACERVO"),
                    ("7", "GRAT CONSELHO SUPERIOR"),
                    ("30", "EXERCÍCIO CUMULATIVO SUBSTITUIÇÃO COORDENAÇÃO"),
                    ("32", "EXERCICIO CUMULATIVO - PERMANENTE"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
    ]
