# Generated by Django 2.2.28 on 2024-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0315_auto_20240924_2128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadobancario",
            name="agencia_dv",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="DV da agência"
            ),
        ),
        migrations.AlterField(
            model_name="dadobancario",
            name="agencia_numero",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número da agência"
            ),
        ),
        migrations.AlterField(
            model_name="dadobancario",
            name="conta_dv",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="DV da conta"
            ),
        ),
        migrations.AlterField(
            model_name="dadobancario",
            name="conta_numero",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número da conta"
            ),
        ),
    ]
