# Generated by Django 2.2.28 on 2024-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0316_auto_20240926_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="banco",
            name="chave_pix",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Chave Pix"
            ),
        ),
    ]
