# Generated by Django 2.2.28 on 2024-10-08 19:51
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0317_banco_chave_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banco",
            name="numero",
            field=models.CharField(default="", max_length=3, verbose_name="Número"),
        ),
    ]
