# Generated by Django 2.2.28 on 2024-10-17 09:59
from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command
import os

FIXTURES = ("fixtures/status_teletrabalho_choices.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0318_auto_20241008_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="qtd_bloqueios",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd bloqueios"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="qtd_meses_impedido",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd meses impedido"
            ),
        ),
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Regular"),
                    (2, "Desbloqueado"),
                    (3, "Bloqueado"),
                    (4, "Revogado"),
                ],
                default=1,
                verbose_name="Status do teletrabalho",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
