# Generated by Django 2.2.28 on 2024-11-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("rh", "0320_historicomovteletrabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicomovteletrabalho",
            name="anexos",
            field=models.ManyToManyField(
                related_name="historico_movteletrabalhos",
                to="ged.Arquivo",
                verbose_name="Anexos",
            ),
        ),
        migrations.AlterField(
            model_name="historicomovteletrabalho",
            name="acao",
            field=models.CharField(
                choices=[
                    ("BLOQUEAR", "Bloquear"),
                    ("DESBLOQUEAR", "Desbloquear"),
                    ("REVOGAR", "Revogar"),
                    ("IGNORAR", "Ignorar"),
                    ("CONCLUIR", "concluir"),
                    ("REGULARIZAR", "regularizar"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Regular"),
                    (2, "Desbloqueado"),
                    (3, "Bloqueado"),
                    (4, "Revogado"),
                    (5, "Ignorado"),
                    (6, "Finalizado"),
                ],
                default=1,
                verbose_name="Status do teletrabalho",
            ),
        ),
    ]
