# Generated by Django 2.2.28 on 2024-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0321_auto_20241104_1751"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicomovteletrabalho",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="dependencia",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Início"
            ),
        ),
    ]
