# Generated by Django 2.2.28 on 2024-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0322_auto_20241108_0756"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependencia",
            name="origem",
            field=models.CharField(
                choices=[("vdf", "VDF"), ("manual", "MANUAL")],
                default="manual",
                max_length=50,
                verbose_name="Origem",
            ),
        ),
    ]
