# Generated by Django 2.2.28 on 2024-12-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0324_load_fixtures_status_teletrabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="contracheque_removido",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Contracheque removido?"
            ),
        ),
        migrations.AddField(
            model_name="controlepagamentopessoal",
            name="contracheque_removido_texto",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Texto do contracheque removido",
            ),
        ),
        migrations.AlterField(
            model_name="historicomovteletrabalho",
            name="acao",
            field=models.CharField(
                choices=[
                    ("BLOQUEAR", "Bloquear"),
                    ("DESBLOQUEAR", "Desbloquear"),
                    ("REVOGAR", "Revogar"),
                    ("IGNORAR", "Ignorar"),
                    ("CONCLUIR", "Concluir"),
                    ("REGULARIZAR", "Regularizar"),
                    ("PENDENTE", "Pendente"),
                    ("ZERAR", "Zerar saldo devedor"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoteletrabalho",
            name="situacao",
            field=models.IntegerField(
                choices=[
                    (1, "Regular"),
                    (2, "Desbloqueado"),
                    (3, "Bloqueado"),
                    (4, "Revogado"),
                    (5, "Ignorado"),
                    (6, "Concluído"),
                    (7, "Pendente"),
                ],
                default=1,
                verbose_name="Status do teletrabalho",
            ),
        ),
    ]
