# Generated by Django 2.2.28 on 2024-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0325_auto_20241211_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaoteletrabalho",
            name="possui_saldo_devedor",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Possui saldo devedor"
            ),
        ),
    ]
