# Generated by Django 2.2.28 on 2025-02-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diarias', '0099_load_fixtures_email_fluxo_cancelamento_diarias_dg'),
        ('rh', '0328_atualizar_data_fim_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='cargo_eventual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_eventual', to='diarias.CargoDiarias', verbose_name='Cargo Colaborador Eventual'),
        ),
    ]
