# Generated by Django 4.2 on 2025-02-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0329_alter_administrativeunitconfig_id_and_more"),
        ("rh", "0329_servidor_cargo_eventual"),
    ]

    operations = []
