from datetime import datetime, time

parser = {
    "AutoField": None,
    "BigIntegerField": int(),
    "BooleanField": bool(),
    "CharField": str(),
    "CommaSeparatedIntegerField": None,
    "DateField": datetime.now().date(),
    "DateTimeField": datetime.now(),
    "DecimalField": float(),
    "DictWrapper": None,
    "EmailField": str(),
    "Field": None,
    "FieldDoesNotExist": None,
    "FilePathField": str(),
    "FloatField": float(),
    "GenericIPAddressField": str(),
    "IPAddressField": str(),
    "IntegerField": int(),
    "NOT_PROVIDED": None,
    # 'NullBooleanField': bool(),
    "PositiveIntegerField": int(),
    "PositiveSmallIntegerField": int(),
    "QueryWrapper": None,
    "SlugField": str(),
    "SmallIntegerField": int(),
    "TextField": str(),
    "TimeField": time,
    "URLField": str(),
}
