# -*- coding: utf-8 -*-

CONSIGFACIL = {
    "header": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "tipo_de_registro",
            "value": 1,
            "size": 1,
            "type": "N",
            "fill": False,
        },
        2: {
            "label": "data_de_geracao",
            "value": 0,
            "size": 8,
            "type": "N",
            "fill": False,
        },
        3: {
            "label": "nome_do_arquivo",
            "value": "",
            "size": 20,
            "type": "A",
            "fill": False,
        },
    },
    "employees": {
        "cfg": {
            "label": "SERVIDOR",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "folha", "value": 0, "size": 10, "type": "N", "fill": False},
        2: {"label": "matricula", "value": 0, "size": 10, "type": "N", "fill": False},
        3: {"label": "cpf", "value": 0, "size": 11, "type": "N", "fill": 0},
        4: {"label": "nome", "value": "", "size": 100, "type": "A", "fill": False},
        5: {
            "label": "codigo_regime",
            "value": "",
            "size": 10,
            "type": "A",
            "fill": False,
        },
        6: {"label": "regime", "value": "", "size": 100, "type": "A", "fill": False},
        7: {
            "label": "cargo_estavel",
            "value": 0,
            "size": 1,
            "type": "N",
            "fill": False,
        },
        8: {"label": "data_admissao", "value": 0, "size": 8, "type": "N", "fill": 0},
        9: {"label": "codigo_orgao", "value": 0, "size": 4, "type": "N", "fill": False},
        10: {
            "label": "descricao_orgao",
            "value": "",
            "size": 100,
            "type": "A",
            "fill": False,
        },
        11: {
            "label": "codigo_cargo",
            "value": "",
            "size": 10,
            "type": "A",
            "fill": False,
        },
        12: {
            "label": "descricao_cargo",
            "value": "",
            "size": 100,
            "type": "A",
            "fill": False,
        },
        13: {
            "label": "carteira_trabalho",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        14: {"label": "pis", "value": "", "size": 1, "type": "A", "fill": False},
        15: {
            "label": "estado_civil",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        16: {
            "label": "nome_conjuge",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        17: {"label": "sexo", "value": "", "size": 1, "type": "A", "fill": False},
        18: {"label": "nome_pai", "value": "", "size": 1, "type": "A", "fill": False},
        19: {"label": "nome_mae", "value": "", "size": 1, "type": "A", "fill": False},
        20: {
            "label": "nacionalidade",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        21: {
            "label": "data_nascimento",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        22: {"label": "rg_numero", "value": "", "size": 1, "type": "A", "fill": False},
        23: {"label": "rg_orgao", "value": "", "size": 1, "type": "A", "fill": False},
        24: {"label": "rg_uf", "value": "", "size": 1, "type": "A", "fill": False},
        25: {
            "label": "escolaridade",
            "value": "",
            "size": 1,
            "type": "A",
            "fill": False,
        },
        26: {"label": "email", "value": "", "size": 100, "type": "A", "fill": False},
        27: {"label": "celular", "value": "", "size": 20, "type": "A", "fill": False},
        28: {"label": "telefone", "value": "", "size": 20, "type": "A", "fill": False},
        29: {
            "label": "endereco_rua_avenida",
            "value": "",
            "size": 100,
            "type": "A",
            "fill": False,
        },
        30: {"label": "numero", "value": "", "size": 10, "type": "A", "fill": False},
        31: {
            "label": "complemento",
            "value": "",
            "size": 20,
            "type": "A",
            "fill": False,
        },
        32: {"label": "bairro", "value": "", "size": 50, "type": "A", "fill": False},
        33: {"label": "cidade", "value": "", "size": 50, "type": "A", "fill": False},
        34: {"label": "uf", "value": "", "size": 2, "type": "A", "fill": False},
        35: {"label": "cep", "value": 0, "size": 8, "type": "N", "fill": False},
        36: {
            "label": "codigo_banco",
            "value": 0,
            "size": 3,
            "type": "N",
            "fill": False,
        },
        37: {
            "label": "codigo_agencia",
            "value": 0,
            "size": 6,
            "type": "N",
            "fill": False,
        },
        38: {"label": "conta", "value": 0, "size": 25, "type": "N", "fill": False},
        39: {
            "label": "margem_geral",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        40: {
            "label": "margem_cartao",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        41: {
            "label": "salario_base",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        42: {
            "label": "salario_minimo",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        43: {
            "label": "salario_bruto",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        44: {
            "label": "salario_liquido",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
        45: {
            "label": "total_descontos_obrigatórios",
            "value": 0,
            "size": 10,
            "type": "A",
            "fill": False,
        },
    },
    "payroll": {
        "cfg": {
            "label": "FOLHA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "folha", "value": 0, "size": 10, "type": "N", "fill": False},
        2: {"label": "matricula", "value": 0, "size": 10, "type": "N", "fill": False},
        3: {
            "label": "codigo_verba",
            "value": 0,
            "size": 10,
            "type": "N",
            "fill": False,
        },
        4: {
            "label": "descricao_verba",
            "value": "",
            "size": 100,
            "type": "A",
            "fill": False,
        },
        5: {"label": "tipo", "value": "", "size": 1, "type": "A", "fill": False},
        6: {"label": "valor", "value": 0, "size": 10, "type": "A", "fill": False},
        7: {
            "label": "parcelas_restantes",
            "value": 0,
            "size": 10,
            "type": "N",
            "fill": False,
        },
        8: {
            "label": "parcela_inicial",
            "value": 0,
            "size": 10,
            "type": "N",
            "fill": False,
        },
        9: {
            "label": "parcela_atual",
            "value": 0,
            "size": 10,
            "type": "N",
            "fill": False,
        },
        10: {
            "label": "prazo_total",
            "value": 0,
            "size": 10,
            "type": "N",
            "fill": False,
        },
        11: {
            "label": "motivo_nao_desconto",
            "value": "",
            "size": 50,
            "type": "A",
            "fill": False,
        },
    },
}
