# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planoconta", "0007_auto_20180921_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoconta",
            name="regime_previdenciario",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR"), (4, "RPPE")],
                default=1,
                verbose_name="Regime previdenciário",
            ),
        ),
        migrations.AlterField(
            model_name="provision",
            name="manual_balance_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Balanço patronal",
            ),
        ),
        migrations.AlterField(
            model_name="provision",
            name="manual_balance_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Balanço valor",
            ),
        ),
        migrations.AlterField(
            model_name="provisionmanager",
            name="pension_system",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RGPS"), (2, "RPPS"), (3, "MILITAR"), (4, "RPPE")],
                default=1,
                verbose_name="Regime previdenciário",
            ),
        ),
        migrations.AlterField(
            model_name="provisionplan",
            name="auto_balance_at_end_period",
            field=models.BooleanField(default=False, verbose_name="Zerar balanço?"),
        ),
    ]
