
location /media/images {
    alias /app/var/www/media/images/;
    autoindex on;
}

location /athenas/static/js/ext/ {
    alias /app/var/www/ext-3.4.0/;
    autoindex on;
}

location /athenas/static/js/ckeditor/ {
    alias /app/var/www/ckeditor/;
    autoindex on;
}

location /athenas/static/js/codemirror/ {
    alias /app/var/www/CodeMirror/;
    autoindex on;
}

location /athenas/static/ {
    autoindex on;
    alias /app/var/www/static/;
}

location /media/ {
    autoindex on;
    alias /app/var/www/media/;
}
