# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0165_auto_20220315_0915"),
        ("protocolo", "0029_auto_20211026_1459"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmbudsmanAnonymous",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OmbudsmanLegalPerson",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OnlineCertificateCitizen",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OnlineCertificateLegalPerson",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OnlineProtocolLegalPerson",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("subject_detail", models.CharField(max_length=255)),
                ("document_number", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OnlineProtocolCitizen",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("subject_detail", models.CharField(max_length=255)),
                ("document_number", models.CharField(max_length=100)),
                ("live_in_referenced_city", models.BooleanField(default=True)),
                (
                    "referenced_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onlineprotocolcitizen_manifestations",
                        to="rh.Localidade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
        migrations.CreateModel(
            name="OmbudsmanCitizen",
            fields=[
                (
                    "protocolo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.Protocolo",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("live_in_referenced_city", models.BooleanField(default=True)),
                (
                    "referenced_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ombudsmancitizen_manifestations",
                        to="rh.Localidade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("protocolo.protocolo",),
        ),
    ]
