# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("internal_security", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentreport",
            options={
                "ordering": ("-reported_at", "-received_at", "-closed_at"),
                "permissions": (
                    ("can_admin_incident", "Pode administrar os incidentes"),
                    (
                        "can_reginal_admin_incident",
                        "Pode administrar os incidentes regionais",
                    ),
                    ("can_view_panic_button", "Pode visualizar o botao do panico"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="emotionalstate",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emotional_state_reports",
                to="rh.Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="emotionalstate",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emotional_state_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentplace",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="places",
                to="internal_security.IncidentReport",
            ),
        ),
        migrations.AlterField(
            model_name="incidentplace",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="in_incident_places",
                to="rh.Lotacao",
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_closer_security_incidentes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_receiver_security_incidentes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_reporter_security_incidentes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="type_finish",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Atendido"), (100, "Chamado inválido")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportlog",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportlog",
            name="incident_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="internal_security.IncidentReport",
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportlog",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportlog",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
