version: "3.7"

services:
  web:
    image: ${IMGHUB_REPO}/nginx
    command: configure start
    stop_signal: SIGINT
    deploy:
      mode: replicated 
      replicas: 4
      restart_policy:
        condition: any
        delay: 15s
      update_config:
        parallelism: 2
        delay: 15s
        order: stop-first
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    ports:
      - target: 8000
        published: ${HTTP_PORT}
        protocol: tcp
      - target: 8443
        published: ${HTTPS_PORT}
        protocol: tcp
    volumes:
      - ${PWD}/volumes/etc:/app/etc
      - ${PWD}/volumes/cache:/app/var/cache
      - ${PWD}/volumes/htdocs:/app/var/www
      - ${PWD}/volumes/logs:/app/var/log
  worker:
    stop_signal: SIGINT
    image: ${IMGHUB_REPO}/athenas:${BRANCH}
    command: register start
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      PYTHONPATH: /app/root
      ATHENAS_CONFIG_FILE: /etc/athenas.conf
      PYTHONUNBUFFERED: 0
      DCVS_BRANCH: port-py37
      ENV_PY_VERSION: 3.9
      RELOAD: 0
      APP_USER_ID: $USER_ID
      APP_GROUP_ID: $USER_ID
      DATABASE_DEFAULT: /run/secrets/bd_athenas
      CROWD_USERNAME: /run/secrets/crowd_username
      CROWD_PASSWORD: /run/secrets/crowd_password
      CROWD_TOKEN: /run/secrets/crowd_token
      LDAP_ADMIN_USER_DN: /run/secrets/ldap_admin_user_dn
      LDAP_ADMIN_PASSWD: /run/secrets/ldap_admin_passwd
      JASPER_SERVER_USERNAME: /run/secrets/jasper_server_username
      JASPER_SERVER_PASSWORD: /run/secrets/jasper_server_password
      DATABASE_PLANTOES_USER: /run/secrets/database_plantoes_user
      DATABASE_PLANTOES_PASSWORD: /run/secrets/database_plantoes_password
      DATABASE_SISDIAS_USER: /run/secrets/database_sisdias_user
      DATABASE_SISDIAS_PASSWORD: /run/secrets/database_sisdias_password
      DATABASE_FOLHAPONTO_USER: /run/secrets/database_folhaponto_user
      DATABASE_FOLHAPONTO_PASSWORD: /run/secrets/database_folhaponto_password
      DATABASE_SIAP_USER: /run/secrets/database_siap_user
      DATABASE_SIAP_PASSWORD: /run/secrets/database_siap_password
      HERMES_TOKEN: /run/secrets/hermes_token
      HERMES_TOKEN_RELATORIOS: /run/secrets/hermes_token_relatorios
      HERMES_TOKEN_EMAIL_PESSOAL: /run/secrets/hermes_token_email_pessoal
      HERMES_TOKEN_PROCESSAMENTOS: /run/secrets/hermes_token_processamentos
      CROWD_APP_PASSWD: /run/secrets/crowd_app_passwd
      TOKEN_API_NOMEACAO_RESIDENTES: /run/secrets/token_api_nomeacao_residentes
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      TOKEN_API_DAA_TRANSP_DIST: /run/secrets/token_api_daa_transp_dist
      TOKEN_API_PLANTOES: /run/secrets/token_api_plantoes
      TOKEN_API_SISDIAS: /run/secrets/token_api_sisdias

    volumes:
      - ${PWD}/config.d/branched.json:/etc/athenas.conf:ro
      - ${PWD}/volumes/etc:/app/etc
      - ${PWD}/volumes/storage:/app/var/storage
      - ${PWD}/volumes/htdocs:/app/var/www
      - ${PWD}/volumes/logs:/app/var/log
      - ${PWD}/volumes/cache:/app/var/cache
    secrets:
      - bd_athenas
      - crowd_username
      - crowd_password
      - crowd_token
      - ldap_admin_user_dn
      - ldap_admin_passwd
      - jasper_server_username
      - jasper_server_password
      - database_plantoes_user
      - database_plantoes_password
      - database_sisdias_user
      - database_sisdias_password
      - database_folhaponto_user
      - database_folhaponto_password
      - database_siap_user
      - database_siap_password
      - hermes_token
      - hermes_token_relatorios
      - hermes_token_email_pessoal
      - hermes_token_processamentos
      - crowd_app_passwd
      - token_api_nomeacao_residentes
      - jwt_secret_key
      - token_api_daa_transp_dist
      - token_api_plantoes
      - token_api_sisdias
  manager:
    stop_signal: SIGINT
    image: ${IMGHUB_REPO}/athenas:${BRANCH}
    command: configure collectstatic jsbuild migrate register start
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.name == node0
      replicas: 1
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      PYTHONPATH: /app/root
      ATHENAS_CONFIG_FILE: /etc/athenas.conf
      PYTHONUNBUFFERED: 0
      DCVS_BRANCH: port-py37
      ENV_PY_VERSION: 3.9
      RELOAD: 0
      APP_USER_ID: $USER_ID
      APP_GROUP_ID: $USER_ID
      DATABASE_DEFAULT: /run/secrets/bd_athenas
      CROWD_USERNAME: /run/secrets/crowd_username
      CROWD_PASSWORD: /run/secrets/crowd_password
      CROWD_TOKEN: /run/secrets/crowd_token
      LDAP_ADMIN_USER_DN: /run/secrets/ldap_admin_user_dn
      LDAP_ADMIN_PASSWD: /run/secrets/ldap_admin_passwd
      JASPER_SERVER_USERNAME: /run/secrets/jasper_server_username
      JASPER_SERVER_PASSWORD: /run/secrets/jasper_server_password
      DATABASE_PLANTOES_USER: /run/secrets/database_plantoes_user
      DATABASE_PLANTOES_PASSWORD: /run/secrets/database_plantoes_password
      DATABASE_SISDIAS_USER: /run/secrets/database_sisdias_user
      DATABASE_SISDIAS_PASSWORD: /run/secrets/database_sisdias_password
      DATABASE_FOLHAPONTO_USER: /run/secrets/database_folhaponto_user
      DATABASE_FOLHAPONTO_PASSWORD: /run/secrets/database_folhaponto_password
      DATABASE_SIAP_USER: /run/secrets/database_siap_user
      DATABASE_SIAP_PASSWORD: /run/secrets/database_siap_password
      HERMES_TOKEN: /run/secrets/hermes_token
      HERMES_TOKEN_RELATORIOS: /run/secrets/hermes_token_relatorios
      HERMES_TOKEN_EMAIL_PESSOAL: /run/secrets/hermes_token_email_pessoal
      HERMES_TOKEN_PROCESSAMENTOS: /run/secrets/hermes_token_processamentos
      CROWD_APP_PASSWD: /run/secrets/crowd_app_passwd
      TOKEN_API_NOMEACAO_RESIDENTES: /run/secrets/token_api_nomeacao_residentes
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      TOKEN_API_DAA_TRANSP_DIST: /run/secrets/token_api_daa_transp_dist
      TOKEN_API_PLANTOES: /run/secrets/token_api_plantoes
      TOKEN_API_SISDIAS: /run/secrets/token_api_sisdias

    volumes:
      - ${PWD}/config.d/branched.json:/etc/athenas.conf:ro
      - ${PWD}/volumes/etc:/app/etc
      - ${PWD}/volumes/storage:/app/var/storage
      - ${PWD}/volumes/htdocs:/app/var/www
      - ${PWD}/volumes/logs:/app/var/log
      - ${PWD}/volumes/cache:/app/var/cache
    secrets:
      - bd_athenas
      - crowd_username
      - crowd_password
      - crowd_token
      - ldap_admin_user_dn
      - ldap_admin_passwd
      - jasper_server_username
      - jasper_server_password
      - database_plantoes_user
      - database_plantoes_password
      - database_sisdias_user
      - database_sisdias_password
      - database_folhaponto_user
      - database_folhaponto_password
      - database_siap_user
      - database_siap_password
      - hermes_token
      - hermes_token_relatorios
      - hermes_token_email_pessoal
      - hermes_token_processamentos
      - crowd_app_passwd
      - token_api_nomeacao_residentes
      - jwt_secret_key
      - token_api_daa_transp_dist
      - token_api_plantoes
      - token_api_sisdias
  daphne:
    stop_signal: SIGINT
    image: ${IMGHUB_REPO}/athenas:${BRANCH}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    command: daphne
    volumes:
      - ${PWD}/config.d/branched.json:/etc/athenas.conf:ro
      - ${PWD}/volumes/storage:/app/var/storage
      - ${PWD}/volumes/cache:/app/var/cache
      - ${PWD}/volumes/logs:/app/var/log
    environment:
      DEV_MODE: 1
      PYTHONPATH: /app/root
      ATHENAS_CONFIG_FILE: /etc/athenas.conf
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 0
      ENV_PY_VERSION: 3.9
      APP_USER_ID: $USER_ID
      APP_GROUP_ID: $USER_ID
      DATABASE_DEFAULT: /run/secrets/bd_athenas
      CROWD_USERNAME: /run/secrets/crowd_username
      CROWD_PASSWORD: /run/secrets/crowd_password
      CROWD_TOKEN: /run/secrets/crowd_token
      LDAP_ADMIN_USER_DN: /run/secrets/ldap_admin_user_dn
      LDAP_ADMIN_PASSWD: /run/secrets/ldap_admin_passwd
      JASPER_SERVER_USERNAME: /run/secrets/jasper_server_username
      JASPER_SERVER_PASSWORD: /run/secrets/jasper_server_password
      DATABASE_PLANTOES_USER: /run/secrets/database_plantoes_user
      DATABASE_PLANTOES_PASSWORD: /run/secrets/database_plantoes_password
      DATABASE_SISDIAS_USER: /run/secrets/database_sisdias_user
      DATABASE_SISDIAS_PASSWORD: /run/secrets/database_sisdias_password
      DATABASE_FOLHAPONTO_USER: /run/secrets/database_folhaponto_user
      DATABASE_FOLHAPONTO_PASSWORD: /run/secrets/database_folhaponto_password
      DATABASE_SIAP_USER: /run/secrets/database_siap_user
      DATABASE_SIAP_PASSWORD: /run/secrets/database_siap_password
      HERMES_TOKEN: /run/secrets/hermes_token
      HERMES_TOKEN_RELATORIOS: /run/secrets/hermes_token_relatorios
      HERMES_TOKEN_EMAIL_PESSOAL: /run/secrets/hermes_token_email_pessoal
      HERMES_TOKEN_PROCESSAMENTOS: /run/secrets/hermes_token_processamentos
      CROWD_APP_PASSWD: /run/secrets/crowd_app_passwd
      TOKEN_API_NOMEACAO_RESIDENTES: /run/secrets/token_api_nomeacao_residentes
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      TOKEN_API_DAA_TRANSP_DIST: /run/secrets/token_api_daa_transp_dist
      TOKEN_API_PLANTOES: /run/secrets/token_api_plantoes
      TOKEN_API_SISDIAS: /run/secrets/token_api_sisdias

    secrets:
      - bd_athenas
      - crowd_username
      - crowd_password
      - crowd_token
      - ldap_admin_user_dn
      - ldap_admin_passwd
      - jasper_server_username
      - jasper_server_password
      - database_plantoes_user
      - database_plantoes_password
      - database_sisdias_user
      - database_sisdias_password
      - database_folhaponto_user
      - database_folhaponto_password
      - database_siap_user
      - database_siap_password
      - hermes_token
      - hermes_token_relatorios
      - hermes_token_email_pessoal
      - hermes_token_processamentos
      - crowd_app_passwd
      - token_api_nomeacao_residentes
      - jwt_secret_key
      - token_api_daa_transp_dist
      - token_api_plantoes
      - token_api_sisdias
  celery:
    stop_signal: SIGINT
    image: ${IMGHUB_REPO}/athenas:${BRANCH}
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M
    command: celery
    environment:
      PYTHONPATH: /app/root
      ATHENAS_CONFIG_FILE: /etc/athenas.conf
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 0
      ENV_PY_VERSION: 3.9
      APP_USER_ID: $USER_ID
      APP_GROUP_ID: $USER_ID
      DATABASE_DEFAULT: /run/secrets/bd_athenas
      CROWD_USERNAME: /run/secrets/crowd_username
      CROWD_PASSWORD: /run/secrets/crowd_password
      CROWD_TOKEN: /run/secrets/crowd_token
      LDAP_ADMIN_USER_DN: /run/secrets/ldap_admin_user_dn
      LDAP_ADMIN_PASSWD: /run/secrets/ldap_admin_passwd
      JASPER_SERVER_USERNAME: /run/secrets/jasper_server_username
      JASPER_SERVER_PASSWORD: /run/secrets/jasper_server_password
      DATABASE_PLANTOES_USER: /run/secrets/database_plantoes_user
      DATABASE_PLANTOES_PASSWORD: /run/secrets/database_plantoes_password
      DATABASE_SISDIAS_USER: /run/secrets/database_sisdias_user
      DATABASE_SISDIAS_PASSWORD: /run/secrets/database_sisdias_password
      DATABASE_FOLHAPONTO_USER: /run/secrets/database_folhaponto_user
      DATABASE_FOLHAPONTO_PASSWORD: /run/secrets/database_folhaponto_password
      DATABASE_SIAP_USER: /run/secrets/database_siap_user
      DATABASE_SIAP_PASSWORD: /run/secrets/database_siap_password
      HERMES_TOKEN: /run/secrets/hermes_token
      HERMES_TOKEN_RELATORIOS: /run/secrets/hermes_token_relatorios
      HERMES_TOKEN_EMAIL_PESSOAL: /run/secrets/hermes_token_email_pessoal
      HERMES_TOKEN_PROCESSAMENTOS: /run/secrets/hermes_token_processamentos
      CROWD_APP_PASSWD: /run/secrets/crowd_app_passwd
      TOKEN_API_NOMEACAO_RESIDENTES: /run/secrets/token_api_nomeacao_residentes
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      TOKEN_API_DAA_TRANSP_DIST: /run/secrets/token_api_daa_transp_dist
      TOKEN_API_PLANTOES: /run/secrets/token_api_plantoes
      TOKEN_API_SISDIAS: /run/secrets/token_api_sisdias
    volumes:
      - ${PWD}/config.d/branched.json:/etc/athenas.conf:ro
      - ${PWD}/volumes/etc:/app/etc
      - ${PWD}/volumes/storage:/app/var/storage
      - ${PWD}/volumes/htdocs:/app/var/www
      - ${PWD}/volumes/logs:/app/var/log
      - ${PWD}/volumes/cache:/app/var/cache
    secrets:
      - bd_athenas
      - crowd_username
      - crowd_password
      - crowd_token
      - ldap_admin_user_dn
      - ldap_admin_passwd
      - jasper_server_username
      - jasper_server_password
      - database_plantoes_user
      - database_plantoes_password
      - database_sisdias_user
      - database_sisdias_password
      - database_folhaponto_user
      - database_folhaponto_password
      - database_siap_user
      - database_siap_password
      - hermes_token
      - hermes_token_relatorios
      - hermes_token_email_pessoal
      - hermes_token_processamentos
      - crowd_app_passwd
      - token_api_nomeacao_residentes
      - jwt_secret_key
      - token_api_daa_transp_dist
      - token_api_plantoes
      - token_api_sisdias
  flower:
    stop_signal: SIGINT
    image: ${IMGHUB_REPO}/athenas:${BRANCH}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      resources:
        limits:
          memory: 512M
    command: flower
    ports:
      - ${FLOWER_PORT}:8001
    environment:
      PYTHONPATH: /app/root
      ATHENAS_CONFIG_FILE: /etc/athenas.conf
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 0
      ENV_PY_VERSION: 3.9
      APP_USER_ID: $USER_ID
      APP_GROUP_ID: $USER_ID
      DATABASE_DEFAULT: /run/secrets/bd_athenas
      CROWD_USERNAME: /run/secrets/crowd_username
      CROWD_PASSWORD: /run/secrets/crowd_password
      CROWD_TOKEN: /run/secrets/crowd_token
      LDAP_ADMIN_USER_DN: /run/secrets/ldap_admin_user_dn
      LDAP_ADMIN_PASSWD: /run/secrets/ldap_admin_passwd
      JASPER_SERVER_USERNAME: /run/secrets/jasper_server_username
      JASPER_SERVER_PASSWORD: /run/secrets/jasper_server_password
      DATABASE_PLANTOES_USER: /run/secrets/database_plantoes_user
      DATABASE_PLANTOES_PASSWORD: /run/secrets/database_plantoes_password
      DATABASE_SISDIAS_USER: /run/secrets/database_sisdias_user
      DATABASE_SISDIAS_PASSWORD: /run/secrets/database_sisdias_password
      DATABASE_FOLHAPONTO_USER: /run/secrets/database_folhaponto_user
      DATABASE_FOLHAPONTO_PASSWORD: /run/secrets/database_folhaponto_password
      DATABASE_SIAP_USER: /run/secrets/database_siap_user
      DATABASE_SIAP_PASSWORD: /run/secrets/database_siap_password
      HERMES_TOKEN: /run/secrets/hermes_token
      HERMES_TOKEN_RELATORIOS: /run/secrets/hermes_token_relatorios
      HERMES_TOKEN_EMAIL_PESSOAL: /run/secrets/hermes_token_email_pessoal
      HERMES_TOKEN_PROCESSAMENTOS: /run/secrets/hermes_token_processamentos
      CROWD_APP_PASSWD: /run/secrets/crowd_app_passwd
      TOKEN_API_NOMEACAO_RESIDENTES: /run/secrets/token_api_nomeacao_residentes
      JWT_SECRET_KEY: /run/secrets/jwt_secret_key
      TOKEN_API_DAA_TRANSP_DIST: /run/secrets/token_api_daa_transp_dist
      TOKEN_API_PLANTOES: /run/secrets/token_api_plantoes
      TOKEN_API_SISDIAS: /run/secrets/token_api_sisdias
    volumes:
      - ${PWD}/config.d/branched.json:/etc/athenas.conf:ro
      - ${PWD}/volumes/logs:/app/var/log
      - ${PWD}/volumes/storage:/app/var/storage
      - ${PWD}/volumes/cache:/app/var/cache
    secrets:
      - bd_athenas
      - crowd_username
      - crowd_password
      - crowd_token
      - ldap_admin_user_dn
      - ldap_admin_passwd
      - jasper_server_username
      - jasper_server_password
      - database_plantoes_user
      - database_plantoes_password
      - database_sisdias_user
      - database_sisdias_password
      - database_folhaponto_user
      - database_folhaponto_password
      - database_siap_user
      - database_siap_password
      - hermes_token
      - hermes_token_relatorios
      - hermes_token_email_pessoal
      - hermes_token_processamentos
      - crowd_app_passwd
      - token_api_nomeacao_residentes
      - jwt_secret_key
      - token_api_daa_transp_dist
      - token_api_plantoes
      - token_api_sisdias
  mongo:
    image: registry.mpmt.mp.br/mongo:5.0.9
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - ${PWD}/volumes/mongo:/data/db
  rabbitmq:
    image: registry.mpmt.mp.br/rabbitmq:3-management
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
          - ${PWD}/volumes/etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  redis:
    image: registry.mpmt.mp.br/redis:5-alpine
    command: redis-server /conf/redis.conf
    deploy:
      resources:
        limits:
          memory: 1024M
    sysctls:
      net.core.somaxconn: 1024
    configs:
      - source: athenas_redis
        target: /conf/redis.conf
        uid: '999'
        mode: 0600
    volumes:
      - ${PWD}/volumes/redis:/data

configs:
  athenas_redis:
    file: ${PWD}/redis.conf

secrets:
  bd_athenas:
    external: true
  crowd_username:
    external: true
  crowd_password:
    external: true
  crowd_token:
    external: true
  ldap_admin_user_dn:
    external: true
  ldap_admin_passwd:
    external: true
  jasper_server_username:
    external: true
  jasper_server_password:
    external: true
  database_plantoes_user:
    external: true
  database_plantoes_password:
    external: true
  database_sisdias_user:
    external: true
  database_sisdias_password:
    external: true
  database_folhaponto_user:
    external: true
  database_folhaponto_password:
    external: true
  database_siap_user:
    external: true
  database_siap_password:
    external: true
  hermes_token:
    external: true
  hermes_token_relatorios:
    external: true
  hermes_token_email_pessoal:
    external: true
  hermes_token_processamentos:
    external: true
  crowd_app_passwd:
    external: true
  token_api_nomeacao_residentes:
    external: true
  jwt_secret_key:
    external: true
  token_api_daa_transp_dist:
    external: true
  token_api_plantoes:
    external: true
  token_api_sisdias:
    external: true