# Generated by Django 2.2.28 on 2023-08-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomeacao", "0002_auto_20230803_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoconvidado",
            name="rg_orgao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="RG - Orgão"
            ),
        ),
    ]
