# Generated by Django 2.2.28 on 2023-08-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomeacao", "0003_auto_20230803_1803"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnexoConvidado",
        ),
    ]
