# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0004_auto_20190206_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="falta",
            name="carga_horaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faltas",
                to="rh.CargaHoraria",
            ),
        ),
    ]
