# Generated by Django 2.2.28 on 2023-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0007_auto_20230725_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="falta",
            name="competencia_desconto",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="Competência de Desconto",
            ),
        ),
    ]
