# Generated by Django 2.2.28 on 2023-08-29 16:50

from django.db import migrations

from datetime import datetime
from contrib.middleware import set_current_user
from contrib.utils import getLogger
from django.contrib.auth.models import User


log = getLogger(__name__)


def set_user_to_job(username: str) -> None:
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist as e:
        log.error(f'Não foi localizado o usuário "{username}" - {e}')
        set_current_user(User.objects.get(username="athenas"))
    else:
        set_current_user(user)


def popular_justificativas(apps, schema_editor):
    """
    Esta função popula o campo origem da Justificativa do Folha Ponto com Vida Funcional ou
    Gestor de Faltas com base no relacionamento da Justificativa com o Vida Funcional
    """
    set_user_to_job("job_popular_justificativas")

    PointJustification = apps.get_model("pvf", "PointJustification")
    print(
        f'>>> {datetime.now().strftime("%d/%m/%Y %H:%M")} - Iniciando preenchimento do campo Origem da Justificativa <<<'
    )

    # Origem 1: Justificativas com origem no Vida Funcional
    PointJustification.objects.filter(request__isnull=False).update(origem=1)

    # Origem 2: Justificativas com origem no Gestor de Faltas
    PointJustification.objects.filter(request__isnull=True).update(origem=2)

    print(
        f'>>> {datetime.now().strftime("%d/%m/%Y %H:%M")} - Finalizando preenchimento do campo Origem da Justificativa <<<'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0009_auto_20230818_1731"),
    ]

    operations = [
        migrations.RunPython(popular_justificativas),
    ]
