# Generated by Django 2.2.28 on 2023-09-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0263_auto_20230904_1213"),
        ("gfp", "0119_folha_update_ available_pvf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ponto", "0010_popular_origem_justificativa"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaltaContraCheque",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "contra_cheque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falta_contracheque",
                        to="gfp.ContraCheque",
                        verbose_name="Contracheque",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falta_contracheque",
                        to="gfp.Evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "faltas",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="falta_contracheque",
                        to="ponto.Falta",
                        verbose_name="Faltas",
                    ),
                ),
                (
                    "gcpp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falta_contracheque",
                        to="rh.ControlePagamentoPessoal",
                        verbose_name="GCPP",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falta_contracheque",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
