# Generated by Django 2.2.28 on 2023-09-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0011_faltacontracheque"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaltaContraCheque",
        ),
    ]
