# Generated by Django 2.2.28 on 2023-09-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0012_delete_faltacontracheque"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feriado",
        ),
    ]
