# Generated by Django 2.2.28 on 2023-11-22 11:52

from django.db import migrations
from datetime import datetime

from contrib.daterange import NewDateRange
from contrib.utils import getLogger

from django.db.models import Q
from common.usefulday.models import NonWorkingDay
from rh.ponto.models import Falta

log = getLogger(__name__)


def popular_dias_uteis(apps, schema_editor):
    """
    Esta função popula o campo dias_uteis das Faltas.
    """
    print(
        f'>>> {datetime.now().strftime("%d/%m/%Y %H:%M")} - Iniciando preenchimento do campo dias_uteis da Falta <<<'
    )
    faltas = Falta.objects.filter(dias_uteis__isnull=True)

    for falta in faltas:
        falta.save()

    print(
        f'>>> {datetime.now().strftime("%d/%m/%Y %H:%M")} - Finalizando preenchimento do campo dias_uteis da Falta <<<'
    )


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("ponto", "0014_falta_dias_uteis"),
    ]

    operations = [
        migrations.RunPython(popular_dias_uteis, down),
    ]
