# -*- coding: utf-8 -*-

FPSPLAN = {
    "header": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "plan", "value": "PLANSAUDE", "size": 0, "type": "A"},
        2: {"label": "organ", "value": "MINISTERIO PUBLICO", "size": 0, "type": "A"},
        3: {"label": "file_name", "value": "", "size": 0, "type": "A"},
        4: {"label": "reference", "value": "0", "size": 6, "type": "A"},
        5: {"label": "date", "value": "", "size": 0, "type": "A"},
    },
    "consignables": {
        "cfg": {
            "label": "RETORNO_CONSIGNAÇÕES",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "organ", "value": 103, "size": 0, "type": "N"},
        2: {"label": "registration", "value": 0, "size": 0, "type": "A"},
        3: {"label": "bond", "value": "", "size": 0, "type": "A"},
        4: {"label": "pension", "value": "", "size": 0, "type": "A"},
        5: {"label": "cpf", "value": "", "size": 0, "type": "A"},
        6: {"label": "month", "value": "01", "size": 0, "type": "A"},
        7: {"label": "year", "value": "2016", "size": 0, "type": "A"},
        8: {"label": "value", "value": "", "size": 0, "type": "A"},
        9: {"label": "type_of", "value": "CP", "size": 0, "type": "A"},
        10: {"label": "refused_flag", "value": 0, "size": 0, "type": "N"},
        11: {"label": "refused_reason", "value": "", "size": 0, "type": "A"},
        12: {"label": "percent", "value": "", "size": 0, "type": "A"},
        13: {"label": "installments", "value": "F", "size": 0, "type": "A"},
    },
    "bases": {
        "cfg": {
            "label": "BASE_SALARIAL",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "organ", "value": 103, "size": 0, "type": "N"},
        2: {"label": "registration", "value": 0, "size": 0, "type": "A"},
        3: {"label": "bond", "value": "", "size": 0, "type": "A"},
        4: {"label": "pension", "value": "", "size": 0, "type": "A"},
        5: {"label": "cpf", "value": "", "size": 0, "type": "A"},
        6: {"label": "month", "value": "01", "size": 0, "type": "A"},
        7: {"label": "year", "value": "2016", "size": 0, "type": "A"},
        8: {"label": "base_value", "value": "", "size": 0, "type": "A"},
    },
    "departures": {
        "cfg": {
            "label": "AFASTAMENTOS",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "organ", "value": 103, "size": 0, "type": "N"},
        2: {"label": "registration", "value": 0, "size": 0, "type": "A"},
        3: {"label": "bond", "value": "", "size": 0, "type": "A"},
        4: {"label": "pension", "value": "", "size": 0, "type": "A"},
        5: {"label": "cpf", "value": "", "size": 0, "type": "A"},
        6: {"label": "departure_reason", "value": 2, "size": 0, "type": "N"},
    },
    "returns": {
        "cfg": {
            "label": "DEVOLUÇÕES",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "organ", "value": 103, "size": 0, "type": "N"},
        2: {"label": "registration", "value": 0, "size": 0, "type": "A"},
        3: {"label": "bond", "value": "", "size": 0, "type": "A"},
        4: {"label": "pension", "value": "", "size": 0, "type": "A"},
        5: {"label": "cpf", "value": "", "size": 0, "type": "A"},
        6: {"label": "month", "value": "01", "size": 0, "type": "A"},
        7: {"label": "year", "value": "2016", "size": 0, "type": "A"},
        8: {
            "label": "return_value",
            "value": "",
            "size": 0,
            "decimals": 2,
            "type": "N",
        },
        9: {"label": "type_of", "value": "CP", "size": 0, "type": "A"},
        10: {"label": "refused_flag", "value": 0, "size": 0, "type": "N"},
        11: {"label": "refused_reason", "value": "", "size": 0, "type": "A"},
    },
}
