# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("council", "0004_auto_20180316_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="councillor",
            name="councillor_type",
            field=models.SmallIntegerField(
                choices=[
                    (None, "Nenhum"),
                    (1, "Presidente"),
                    (2, "Corregedor"),
                    (3, "Membro"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="rapporteurdocument",
            name="from_distribution",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rapporteur_document",
                to="council.DistributionRapporteur",
            ),
        ),
        migrations.AlterField(
            model_name="rapporteurdocument",
            name="rapporteur",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="council.Rapporteur",
            ),
        ),
        migrations.AlterField(
            model_name="rapporteurdocument",
            name="rapporteur_vote_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Procedente o pedido"),
                    (2, "Improcedente o pedido"),
                    (201, "Declarar Impedimento"),
                    (202, "Declarar Suspeição"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Procedente"),
                    (2, "Improcedente"),
                    (3, "Abstenção"),
                    (4, "Homologado parcialmente"),
                ],
                null=True,
            ),
        ),
    ]
