# Generated by Django 2.2.20 on 2021-09-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("pvf", "0003_auto_20210908_0910"),
        ("rh", "0153_auto_20210723_1552"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateInterestAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Interesse Particular",
                "db_table": "pvf_afastamento_private",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="TrainingAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "curse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_trainingabsences",
                        to="rh.Curso",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_trainingabsences",
                        to="rh.UnidadeAdministrativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Capacitação",
                "db_table": "pvf_absence_training",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="PoliticalActivityAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "elective_office",
                    models.IntegerField(
                        choices=[
                            (1, "Prefeito/Vice"),
                            (2, "Vereador"),
                            (3, "Deputado Estadual"),
                            (4, "Deputado Federal"),
                            (5, "Governador/Vice"),
                            (6, "Senador/Presidente República/Vice"),
                        ],
                        default=1,
                        verbose_name="Cargo Eletivo",
                    ),
                ),
                (
                    "political_party",
                    models.CharField(
                        default="", max_length=100, verbose_name="Partido Político"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvf_politicalactivityabsences",
                        to="rh.Localidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Atividade Política",
                "db_table": "pvf_absence_politicalactivity",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="PaternityAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "is_childcare_assistence",
                    models.BooleanField(
                        default=False, verbose_name="Dependente do Auxílio Creche"
                    ),
                ),
                (
                    "is_incoming_tax",
                    models.BooleanField(default=False, verbose_name="Dependente do IR"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        choices=[(1, "VÁLIDO"), (2, "INVÁLIDO")], default=1, null=True
                    ),
                ),
                (
                    "incapacity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Incapacidade física/mental",
                    ),
                ),
                (
                    "birth_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_paternityabsences",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_paternityabsences",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Paternidade",
                "db_table": "pvf_absence_paternity",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="MourningAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "family_bond",
                    models.IntegerField(
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO"),
                            (3, "FILHO(A)"),
                            (4, "PAI/MÃE"),
                            (5, "IRMÃO"),
                            (6, "ENTEADO"),
                            (7, "MENOR TUTELADO"),
                            (8, "EX-CÔNJUGE"),
                            (9, "NETOS"),
                            (10, "OUTROS"),
                            (11, "OUTROS - DEPENDÊNCIA ECONÔMICA"),
                        ],
                        default=10,
                        verbose_name="Tipo de Vínculo",
                    ),
                ),
                (
                    "death_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_deathmourningabsences",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvf_mourningabsences",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Luto",
                "db_table": "pvf_absence_mourning",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="MaternityAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "is_childcare_assistence",
                    models.BooleanField(
                        default=False, verbose_name="Dependente do Auxílio Creche"
                    ),
                ),
                (
                    "is_incoming_tax",
                    models.BooleanField(default=False, verbose_name="Dependente do IR"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        choices=[(1, "VÁLIDO"), (2, "INVÁLIDO")], default=1, null=True
                    ),
                ),
                (
                    "incapacity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Incapacidade física/mental",
                    ),
                ),
                (
                    "birth_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_maternityabsences",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_maternityabsences",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Maternidade",
                "db_table": "pvf_absence_maternity",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="MarriageAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "marriage_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_marriageabsences",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvf_marriageabsences",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença para Casamento",
                "db_table": "pvf_absence_marriage",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="HealthTreatmentAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "medical_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_healthtreatmentabsences",
                        to="ged.Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Saúde",
                "db_table": "pvf_absence_healthtreatment",
            },
            bases=("pvf.portalrequestabsence",),
        ),
        migrations.CreateModel(
            name="FamilyHealthTreatmentAbsence",
            fields=[
                (
                    "portalrequestabsence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pvf.PortalRequestAbsence",
                    ),
                ),
                (
                    "degree_kinship",
                    models.IntegerField(
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO"),
                            (3, "FILHO(A)"),
                            (4, "PAI/MÃE"),
                            (5, "IRMÃO"),
                            (6, "ENTEADO"),
                            (7, "MENOR TUTELADO"),
                            (8, "EX-CÔNJUGE"),
                            (9, "NETOS"),
                            (10, "OUTROS"),
                            (11, "OUTROS - DEPENDÊNCIA ECONÔMICA"),
                        ],
                        default=10,
                        verbose_name="Tipo de Vínculo",
                    ),
                ),
                (
                    "medical_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pvf_familyhealthtreatmentabsences",
                        to="ged.Arquivo",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvf_familyhealthtreatmentabsences",
                        to="rh.PessoaFisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licença Saúde (Pessoa da Família)",
                "db_table": "pvf_absence_familyhealthtreatment",
            },
            bases=("pvf.portalrequestabsence",),
        ),
    ]
