# Generated by Django 2.2.28 on 2022-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maternityabsence",
            name="dependent_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "CÔNJUGE"),
                    (2, "COMPANHEIRO(A) - UNIÃO ESTÁVEL"),
                    (3, "FILHO(A) NÃO EMANCIPADO MENOR DE 21 ANOS"),
                    (4, "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (5, "PAI(MÃE) COM DEPENDÊNCIA ECONÔMICA"),
                    (
                        6,
                        "IRMÃO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (7, "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (8, "ENTEADO NÃO EMANCIPADO MENOR DE 21"),
                    (9, "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (
                        10,
                        "MENOR TUTELADO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA OU GUARDA JUDICIAL",
                    ),
                    (11, "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (12, "AVÓS COM DEPENDENCIA ECONOMICA"),
                    (13, "BISAVÓS COM DEPENDENCIA ECONOMICA"),
                    (
                        14,
                        "NETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (
                        15,
                        "BISNETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (16, " EX-CÔNJUGE"),
                    (
                        17,
                        "FILHO(A) OU ENTEADO(A) UNIVERSITÁRIO(A) OU CURSANDO ESCOLA TÉCNICA DE 2ºGRAU, ATÉ 24 ANOS",
                    ),
                    (18, "AGREGADO/OUTROS"),
                ],
                null=True,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="paternityabsence",
            name="dependent_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "CÔNJUGE"),
                    (2, "COMPANHEIRO(A) - UNIÃO ESTÁVEL"),
                    (3, "FILHO(A) NÃO EMANCIPADO MENOR DE 21 ANOS"),
                    (4, "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (5, "PAI(MÃE) COM DEPENDÊNCIA ECONÔMICA"),
                    (
                        6,
                        "IRMÃO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (7, "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (8, "ENTEADO NÃO EMANCIPADO MENOR DE 21"),
                    (9, "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (
                        10,
                        "MENOR TUTELADO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA OU GUARDA JUDICIAL",
                    ),
                    (11, "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR"),
                    (12, "AVÓS COM DEPENDENCIA ECONOMICA"),
                    (13, "BISAVÓS COM DEPENDENCIA ECONOMICA"),
                    (
                        14,
                        "NETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (
                        15,
                        "BISNETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                    ),
                    (16, " EX-CÔNJUGE"),
                    (
                        17,
                        "FILHO(A) OU ENTEADO(A) UNIVERSITÁRIO(A) OU CURSANDO ESCOLA TÉCNICA DE 2ºGRAU, ATÉ 24 ANOS",
                    ),
                    (18, "AGREGADO/OUTROS"),
                ],
                null=True,
                verbose_name="Tipo",
            ),
        ),
    ]
