# Generated by Django 2.2.28 on 2023-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0003_blooddonationabsence"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthtreatmentabsence",
            name="hours",
            field=models.IntegerField(null=True, verbose_name="Afastamento em horas"),
        ),
    ]
