# Generated by Django 2.2.28 on 2023-07-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("afastamento", "0029_licencasaude_cid"),
        ("absence", "0004_healthtreatmentabsence_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthtreatmentabsence",
            name="CID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pvf_requests",
                to="afastamento.CID",
            ),
        ),
    ]
