# Generated by Django 2.2.28 on 2023-07-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0005_healthtreatmentabsence_cid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthtreatmentabsence",
            old_name="CID",
            new_name="cid",
        ),
    ]
