# Generated by Django 2.2.28 on 2024-09-19 14:23
from django.db import migrations, models
from django.conf import settings
from django.core.management import call_command
import os

FIXTURES = ("fixtures/classificacao_licenca.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", "pvf", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0007_familyhealthtreatmentabsence_cid"),
    ]

    operations = [
        migrations.AddField(
            model_name="maternityabsence",
            name="classificacao",
            field=models.IntegerField(
                choices=[(1, "Normal"), (2, "Antecipação")], default=1, null=True
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
