# Generated by Django 2.2.28 on 2024-09-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("absence", "0008_maternityabsence_classificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maternityabsence",
            name="dependent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pvf_maternityabsences",
                to="rh.PessoaFisica",
            ),
        ),
    ]
