# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 17:57
from __future__ import unicode_literals

import sys
from django.db import migrations, models

from corregedoria.cirdir.models import Address, Property, Debits, Health, Teaching


def log(message, end="\n", *args, **kwargs):
    output = message % args
    output = output % kwargs

    sys.stdout.write(output)
    sys.stdout.write(end)
    sys.stdout.flush()


def up_apply_updated_at_in_address(*args, **kwargs):
    log(" Iniciando update_at em endereco")
    for obj in Address.objects.filter():
        at = obj.modified_at if obj.modified_at else obj.created_at
        Address.objects.filter(pk=obj.pk).update(updated_at=at)
        log(".", end="")
    log(" Endereco pronto\n")


def up_apply_updated_at_in_health(*args, **kwargs):
    log(" Iniciando update_at em Saude")
    for obj in Health.objects.filter():
        at = obj.modified_at if obj.modified_at else obj.created_at
        Health.objects.filter(pk=obj.pk).update(updated_at=at)
        log(".", end="")
    log(" Saude pronto\n")


def up_apply_updated_at_in_property(*args, **kwargs):
    log(" Iniciando update_at em Bens")
    for obj in Property.objects.filter():
        at = obj.modified_at if obj.modified_at else obj.created_at
        Property.objects.filter(pk=obj.pk).update(updated_at=at)
        log(".", end="")
    log(" Bens pronto\n")


def up_apply_updated_at_in_debits(*args, **kwargs):
    log(" Iniciando update_at em Debitos")
    for obj in Debits.objects.filter():
        at = obj.modified_at if obj.modified_at else obj.created_at
        Debits.objects.filter(pk=obj.pk).update(updated_at=at)
        log(".", end="")
    log(" Debitos pronto\n")


def up_apply_updated_at_in_teaching(*args, **kwargs):
    log(" Iniciando update_at em Docencia")
    for obj in Teaching.objects.filter():
        at = obj.modified_at if obj.modified_at else obj.created_at
        Teaching.objects.filter(pk=obj.pk).update(updated_at=at)
        log(".", end="")
    log(" Docencia pronto\n")


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cirdir", "0010_auto_20191210_1141"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Cadastro de endere\xe7os de resid\xeancia"},
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debits",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="health",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teaching",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(up_apply_updated_at_in_address, down_fake),
        migrations.RunPython(up_apply_updated_at_in_property, down_fake),
        migrations.RunPython(up_apply_updated_at_in_health, down_fake),
        migrations.RunPython(up_apply_updated_at_in_debits, down_fake),
        migrations.RunPython(up_apply_updated_at_in_teaching, down_fake),
    ]
