# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cirdir", "0011_auto_20191216_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlinformation",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
