# -*- coding: utf-8 -*-

SICAP = {
    "header": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "tipo_de_registro", "value": 1, "size": 1, "type": "N"},
        2: {"label": "data_de_geracao", "value": 0, "size": 8, "type": "N"},
        3: {"label": "nome_do_arquivo", "value": "", "size": 20, "type": "A"},
    },
    "dispatch": {
        "cfg": {
            "label": "ATO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "idUnidadeGestora",
            "value": "",
            "size": 14,
            "type": "N",
            "required": True,
        },
        2: {
            "label": "exercicio",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        3: {
            "label": "remessa",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "data",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "act": {
        "cfg": {
            "label": "ATO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        2: {
            "label": "cnpjUgPublicacao",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        3: {
            "label": "veiculoPublicacao",
            "value": "",
            "size": 50,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "dataPublicacao",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
    },
    "law": {
        "cfg": {
            "label": "LEI",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "numeroLei",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        2: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": False,
        },
        3: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "dataPublicacao",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "veiculoPublicacao",
            "value": "",
            "size": 50,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "ementa",
            "value": "",
            "size": 50,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "job_position": {
        "cfg": {
            "label": "CARGO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "codigoCargo",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {"label": "numeroLei", "value": "", "size": 10, "type": "N", "fixed": True},
        3: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": False,
        },
        4: {
            "label": "nomeCargo",
            "value": "",
            "size": 80,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "atribuicaoCargo",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "idCargoNome",
            "value": "",
            "size": 5,
            "type": "N",
            "fixed": False,
            "required": True,
            "verbose": "Codigo TCE",
        },
        7: {
            "label": "regimeJuridico",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        8: {
            "label": "vinculoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        9: {
            "label": "jornadaSemanal",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        10: {
            "label": "descricaoJornadaSemanal",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
        },
        11: {
            "label": "quantidadeVagas",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        12: {
            "label": "natureza",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        13: {
            "label": "vencimentoInicial",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        14: {
            "label": "vencimentoFinal",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        15: {
            "label": "escolaridade",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        16: {
            "label": "classe",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
            "required": True,
        },
    },
    "administrative_unit": {
        "cfg": {
            "label": "UNIDADE_ADMINISTRATIVA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "codigoUnidadeAdministrativa",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        2: {"label": "sigla", "value": "", "size": 20, "type": "A", "fixed": False},
        3: {"label": "nome", "value": "", "size": 100, "type": "A", "fixed": False},
        4: {"label": "cnpj", "value": "", "size": 14, "type": "A", "fixed": False},
    },
    "workplace": {
        "cfg": {
            "label": "LOTACAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "codigoLotacao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "codigoUnidadeAdministrativa",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        3: {
            "label": "sigla",
            "value": "",
            "size": 20,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "nome",
            "value": "",
            "size": 100,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "employee": {
        "cfg": {
            "label": "SERVIDOR",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "cpfServidor",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "nome",
            "value": "",
            "size": 100,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        3: {
            "label": "rg",
            "value": "",
            "size": 20,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "pcd",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "rgExpedidor",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "rgExpedicao",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "carteiraTrabalho",
            "value": "",
            "size": 20,
            "type": "N",
            "fixed": False,
        },
        8: {
            "label": "numeroPisPasep",
            "value": "",
            "size": 11,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        9: {
            "label": "carteiraTrabalhoSerie",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        10: {
            "label": "tituloEleitor",
            "value": "",
            "size": 20,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        11: {
            "label": "tituloEleitorZona",
            "value": "",
            "size": 6,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        12: {
            "label": "tituloEleitorSecao",
            "value": "",
            "size": 6,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        13: {
            "label": "tituloEleitorUf",
            "value": "",
            "size": 2,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        14: {"label": "cnh", "value": "", "size": 15, "type": "N", "fixed": True},
        15: {
            "label": "dataNascimento",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        16: {
            "label": "siglaPais",
            "value": "",
            "size": 2,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        17: {
            "label": "siglaEstado",
            "value": "",
            "size": 2,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        18: {
            "label": "codigoMunicipio",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        19: {
            "label": "escolaridade",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        20: {
            "label": "sexo",
            "value": "",
            "size": 1,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        21: {
            "label": "estadoCivil",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        22: {
            "label": "cpfConjuge",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
        },
        23: {
            "label": "dataNascimentoConjuge",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
        },
        24: {"label": "cpfMae", "value": "", "size": 11, "type": "A", "fixed": False},
        25: {"label": "nomeMae", "value": "", "size": 100, "type": "A", "fixed": False},
        26: {
            "label": "dataNascimentoMae",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
        },
    },
    "admission": {
        "cfg": {
            "label": "ADMISSAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "codigoLotacao",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        3: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        4: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "cpfServidor",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "tipoAdmissao",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "numeroEdital",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
        },
        8: {
            "label": "numeroInscricao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        9: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
        },
        10: {
            "label": "prorrogacaoContrato",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
        },
        11: {
            "label": "contratoSuspenso",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
        },
        12: {
            "label": "dataPosse",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        13: {
            "label": "dataExercicio",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        14: {
            "label": "dataInicio",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        15: {"label": "dataFim", "value": "", "size": 10, "type": "A", "fixed": False},
        16: {
            "label": "contratoValor",
            "value": "",
            "size": 10,
            "type": "I",
            "fixed": False,
        },
        17: {
            "label": "contratoMotivo",
            "value": "",
            "size": 50,
            "type": "A",
            "fixed": False,
        },
        18: {
            "label": "cnpjOrgaoOrigemCedido",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
        },
        19: {
            "label": "cessaoCnpjOrgaoRemuneracao",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
        },
        20: {
            "label": "efetivoEmpregoPublico",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
        },
        21: {
            "label": "formaEmpregoPublico",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
        },
        22: {
            "label": "previdenciaRequisitado",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
        },
        23: {
            "label": "cnpjRppsRequisitado",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
        },
        24: {
            "label": "observacao",
            "value": "",
            "size": 200,
            "type": "A",
            "fixed": False,
        },
    },
    "dismissal": {
        "cfg": {
            "label": "DESLIGAMENTO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        4: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        7: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        8: {
            "label": "tipoDesligamento",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        9: {
            "label": "dataDesligamento",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "readaptation": {
        "cfg": {
            "label": "READAPTACAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        8: {
            "label": "dataInicio",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "reappointment": {
        "cfg": {
            "label": "RECONDUCAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        8: {
            "label": "dataExercicio",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "reintegration": {
        "cfg": {
            "label": "REINTEGRACAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        8: {
            "label": "dataExercicio",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "retirement": {
        "cfg": {
            "label": "APOSENTADORIA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        5: {
            "label": "cpfServidor",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "cnpjUnidadeGestoraOrigem",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        8: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        9: {
            "label": "dataAposentadoria",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        10: {
            "label": "tipoAposentadoria",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        11: {
            "label": "reversao",
            "value": "",
            "size": 1,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        12: {
            "label": "numeroAtoReversao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
        },
        13: {
            "label": "tipoAtoReversao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
        },
        14: {
            "label": "dataReversao",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        15: {
            "label": "revisao",
            "value": "",
            "size": 1,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        16: {
            "label": "compensassaoPrevidenciaria",
            "value": "",
            "size": 1,
            "type": "A",
            "fixed": False,
            "required": True,
        },
    },
    "pension": {
        "cfg": {
            "label": "PENSAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
        },
        5: {
            "label": "cpfServidor",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "cnpjUnidadeGestoraOrigem",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        8: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        9: {
            "label": "tipoPensao",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
        },
        10: {
            "label": "dataObito",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
        },
        11: {"label": "revisao", "value": "", "size": 1, "type": "N", "required": True},
        12: {
            "label": "compensassaoPrevidenciaria",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
        },
    },
    "pensioner": {
        "cfg": {
            "label": "PENSIONISTA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
        },
        5: {
            "label": "cpfServidor",
            "value": "",
            "size": 11,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        6: {
            "label": "cnpjUnidadeGestoraOrigem",
            "value": "",
            "size": 14,
            "type": "A",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        8: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        9: {
            "label": "cpfPensionista",
            "value": "",
            "size": 14,
            "type": "A",
            "required": True,
        },
        10: {"label": "nome", "value": "", "size": 100, "type": "A", "required": True},
        11: {
            "label": "dataNascimento",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
        },
        12: {
            "label": "grauParentesco",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
        },
        13: {
            "label": "tipoBeneficio",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
        },
        14: {
            "label": "inicioBeneficio",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
        },
        15: {
            "label": "fimBeneficio",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
        },
        16: {
            "label": "percentual",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
        },
        17: {
            "label": "responsavelBeneficio",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
        },
        18: {"label": "revisao", "value": "", "size": 1, "type": "N", "required": True},
    },
    "license": {
        "cfg": {
            "label": "LICENCA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "licencaMotivo",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        8: {
            "label": "dataInicio",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        9: {
            "label": "dataFim",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        10: {
            "label": "remunerado",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
    },
    "function": {
        "cfg": {
            "label": "FUNCAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        8: {
            "label": "dataInicio",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        9: {
            "label": "recebeComissao",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
    },
    "assignment": {
        "cfg": {
            "label": "CESSAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "cnpjOrgaoDestino",
            "value": "",
            "size": 14,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        8: {
            "label": "dataInicio",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        9: {
            "label": "dataFim",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
    },
    "availability": {
        "cfg": {
            "label": "DISPONIBILIDADE",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "dataDisponibilidade",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
    },
    "utilization": {
        "cfg": {
            "label": "APROVEITAMENTO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAtoAdmissao",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAtoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargoAdmissao",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        6: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        7: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        8: {
            "label": "dataAproveitamento",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
    },
    "sheet_item": {
        "cfg": {
            "label": "FOLHA_ITEM",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "codigoFolhaItemESocial",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "motivoFolhaSemRemuneracao",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        3: {
            "label": "codigoFolhaItem",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        4: {
            "label": "descricao",
            "value": "",
            "size": 150,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "incidePrevidenciaGeral",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        6: {
            "label": "incidePrevidenciaRPPS",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        7: {
            "label": "incideIRRF",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
    },
    "sheet": {
        "cfg": {
            "label": "FOLHA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "matriculaServidor",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "numeroAto",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        3: {
            "label": "tipoAto",
            "value": "",
            "size": 4,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        4: {
            "label": "codigoCargo",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "codigoFolhaItem",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        6: {
            "label": "tipoFolha",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        7: {
            "label": "competencia",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        8: {
            "label": "valor",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        9: {
            "label": "complemento",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        10: {
            "label": "aliquotaDesconto",
            "value": "",
            "size": 6,
            "type": "A",
            "fixed": False,
        },
        11: {
            "label": "aliquotaDescontoPrevidenciario",
            "value": "",
            "size": 6,
            "type": "A",
            "fixed": False,
        },
        12: {
            "label": "baseDescontoPrevidenciario",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
        },
        13: {
            "label": "baseDescontoIr",
            "value": "",
            "size": 10,
            "type": "A",
            "fixed": False,
        },
        14: {
            "label": "regimePrevidenciario",
            "value": "",
            "size": 1,
            "type": "N",
            "fixed": False,
            "required": True,
        },
        15: {
            "label": "referenciaSalarial",
            "value": "",
            "size": 30,
            "type": "A",
            "fixed": False,
        },
        16: {
            "label": "observacao",
            "value": "",
            "size": 200,
            "type": "A",
            "fixed": False,
        },
        17: {
            "label": "jornadaSemanal",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        18: {
            "label": "descricaoJornadaSemanal",
            "value": "",
            "size": 2,
            "type": "N",
            "fixed": False,
        },
    },
    "socialsecurity_gathering": {
        "cfg": {
            "label": "RECOLHIMENTO_PREVIDENCIARIO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "cnpjOrgaoDestino",
            "value": "",
            "size": 14,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        2: {
            "label": "anoCompetencia",
            "value": "",
            "size": 4,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        3: {
            "label": "mesCompetencia",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        4: {
            "label": "dataPagamento",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        5: {
            "label": "numeroPagamento",
            "value": "",
            "size": 13,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        6: {
            "label": "regimePrevidenciario",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        7: {
            "label": "servidorPatronal",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        8: {
            "label": "servidorSegurado",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        9: {
            "label": "quantidadeServidores",
            "value": "",
            "size": 7,
            "type": "N",
            "fixed": False,
        },
        10: {
            "label": "contribuitesIndividuaisPatronal",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        11: {
            "label": "contribuitesIndividuaisSegurado",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        12: {
            "label": "quantidadeContribuintesIndividuais",
            "value": "",
            "size": 6,
            "type": "N",
            "fixed": False,
        },
        13: {
            "label": "outrasEntidades",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        14: {
            "label": "salarioFamilia",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        15: {
            "label": "salarioMaternidade",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        16: {"label": "deducoes", "value": "", "size": 10, "type": "N", "fixed": False},
        17: {
            "label": "acrescimos",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        18: {
            "label": "valorPago",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        19: {
            "label": "houvePagamento",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
    },
    "socialsecurity_demonstrative": {
        "cfg": {
            "label": "DEMONSTRATIVO_PREVIDENCIARIO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "cnpj",
            "value": "",
            "size": 14,
            "type": "A",
            "required": True,
            "fixed": True,
        },
        2: {
            "label": "periodoReferencia",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
            "fixed": False,
        },
        3: {
            "label": "regimePrevidencia",
            "value": "",
            "size": 1,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        4: {
            "label": "cnpjRppsRequisitado",
            "value": "",
            "size": 14,
            "type": "N",
            "required": True,
            "fixed": True,
        },
        5: {
            "label": "baseCalculo",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        6: {
            "label": "aliquotaPatronal",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
        7: {
            "label": "aliquotaRatFap",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": False,
        },
        8: {
            "label": "contribuicaoPatronal",
            "value": "",
            "size": 10,
            "type": "N",
            "required": True,
            "fixed": False,
        },
    },
    "public_concurrence": {
        "cfg": {
            "label": "EDITAL",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {
            "label": "tipoEdital",
            "value": "",
            "size": 2,
            "type": "N",
            "required": True,
        },
        2: {
            "label": "numeroEdital",
            "value": "",
            "size": 10,
            "type": "N",
            "fixed": True,
            "required": True,
        },
        3: {"label": "veiculoPublicacao", "value": "", "size": 50, "type": "A"},
        4: {
            "label": "dataPublicacao",
            "value": "",
            "size": 10,
            "type": "A",
            "required": True,
        },
        5: {"label": "dataInicioInscricoes", "value": "", "size": 10, "type": "A"},
        6: {"label": "dataFimInscricoes", "value": "", "size": 10, "type": "A"},
        7: {"label": "prazoValidade", "value": "", "size": 4, "type": "N"},
        8: {"label": "cnpjEmpresaOrganizadora", "value": "", "size": 14, "type": "A"},
    },
    "organizing_company": {
        "cfg": {
            "label": "EMPRESA_ORGANIZADORA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "cnpjEmpresaOrganizadora", "value": "", "size": 14, "type": "A"},
        2: {"label": "nome", "value": "", "size": 100, "type": "A"},
        3: {"label": "valor", "value": "", "size": 10, "type": "N"},
        4: {"label": "modalidadeLicitacao", "value": "", "size": 2, "type": "N"},
        5: {"label": "numeroAdministrativo", "value": "", "size": 25, "type": "A"},
        6: {"label": "anoAdministrativo", "value": "", "size": 4, "type": "N"},
        7: {"label": "numeroLicitatorio", "value": "", "size": 10, "type": "N"},
        8: {"label": "anoLicitatorio", "value": "", "size": 4, "type": "N"},
        9: {"label": "situacaoContratacao", "value": "", "size": 2, "type": "N"},
    },
    "notice_approval": {
        "cfg": {
            "label": "EDITAL_HOMOLOGACAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "numeroEdital", "value": "", "size": 10, "type": "N"},
        2: {"label": "numeroAto", "value": "", "size": 10, "type": "N", "fixed": True},
        3: {"label": "dataHomologacao", "value": "", "size": 10, "type": "A"},
        4: {"label": "veiculoPublicacao", "value": "", "size": 50, "type": "A"},
        5: {"label": "dataPublicacao", "value": "", "size": 10, "type": "A"},
    },
    "vacant": {
        "cfg": {
            "label": "VAGA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "numeroEdital", "value": "", "size": 10, "type": "N"},
        2: {
            "label": "codigoUnidadeAdministrativa",
            "value": "",
            "size": 20,
            "type": "A",
        },
        3: {"label": "codigoCargo", "value": "", "size": 10, "type": "N"},
        4: {"label": "codigoVaga", "value": "", "size": 6, "type": "N"},
        5: {"label": "tipoConcorrencia", "value": "", "size": 2, "type": "N"},
        6: {"label": "quantidade", "value": "", "size": 6, "type": "N"},
        7: {"label": "especialidadeVaga", "value": "", "size": 50, "type": "A"},
    },
    "approved": {
        "cfg": {
            "label": "APROVADO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "numeroEdital", "value": "", "size": 10, "type": "N"},
        2: {"label": "codigoVaga", "value": "", "size": 6, "type": "N"},
        3: {"label": "cpf", "value": "", "size": 11, "type": "A"},
        4: {"label": "nome", "value": "", "size": 100, "type": "A"},
        5: {"label": "numeroInscricao", "value": "", "size": 10, "type": "N"},
        6: {"label": "classificacao", "value": "", "size": 6, "type": "N"},
    },
}
