# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0002_auto_20150810_1114"),
        ("protocolo", "0001_initial"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="interessado",
            field=models.ForeignKey(
                related_name="prot_interessado",
                to="rh.Pessoa",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="lotacao_criacao",
            field=models.ForeignKey(
                related_name="prot_lotacao_criacao",
                verbose_name="Lota\xe7\xe3o de Cria\xe7\xe3o",
                blank=True,
                to="rh.OrgaoGeral",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="orgao_geral_destino",
            field=models.ForeignKey(
                related_name="prot_orgao_destino",
                verbose_name="Destino",
                blank=True,
                to="rh.OrgaoGeral",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="orgao_geral_origem",
            field=models.ForeignKey(
                related_name="prot_orgao_origem",
                verbose_name="Origem",
                to="rh.OrgaoGeral",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="referencias",
            field=models.ManyToManyField(
                related_name="prot_referencias",
                null=True,
                verbose_name="Refer\xeancias",
                to="protocolo.Referencia",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="servidor_origem",
            field=models.ForeignKey(
                related_name="prot_servidor_origem",
                to="rh.Servidor",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="protocolo",
            name="tipo_documento",
            field=models.ForeignKey(
                related_name="prot_tipo_documento",
                to="protocolo.TipoDocumento",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="permissaoedoc",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="permissaoedoc",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="anexos",
            field=models.ManyToManyField(
                related_name="movimentacao", null=True, to="protocolo.Anexo", blank=True
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="child_of",
            field=models.ForeignKey(
                related_name="derivative_for",
                to="protocolo.Movimentacao",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="destinatario",
            field=models.ForeignKey(
                related_name="mov_destinatario",
                blank=True,
                to="rh.Pessoa",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="lotacao_criacao",
            field=models.ForeignKey(
                related_name="mov_lotacao_criacao",
                verbose_name="Lota\xc3\xa7\xc3\xa3o de Cria\xc3\xa7\xc3\xa3o",
                blank=True,
                to="rh.OrgaoGeral",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="lotacao_destino",
            field=models.ForeignKey(
                related_name="mov_lotacao_destino",
                blank=True,
                to="rh.OrgaoGeral",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="lotacao_origem",
            field=models.ForeignKey(
                related_name="mov_lotacao_origem",
                to="rh.OrgaoGeral",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="protocolo",
            field=models.ForeignKey(
                related_name="movimentacoes",
                to="protocolo.Protocolo",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="servidor_destino",
            field=models.ForeignKey(
                related_name="mov_servidor_destino",
                blank=True,
                to="rh.Servidor",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="servidor_origem",
            field=models.ForeignKey(
                related_name="mov_servidor_origem",
                to="rh.Servidor",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="impressora",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="impressora",
            name="lotacao",
            field=models.ForeignKey(
                to="rh.Lotacao", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="impressora",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="etiqueta",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="etiqueta",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="etiqueta",
            name="protocolo",
            field=models.ForeignKey(
                to="protocolo.Protocolo", unique=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="lotacao",
            field=models.ManyToManyField(
                related_name="lotacao_comp_prot",
                null=True,
                to="rh.OrgaoGeral",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="permissao",
            field=models.ManyToManyField(to="protocolo.PermissaoEdoc", null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="pessoa_fisica",
            field=models.ManyToManyField(
                related_name="pessoa_comp_prot",
                null=True,
                to="rh.PessoaFisica",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharprotocolo",
            name="protocolo",
            field=models.ForeignKey(
                related_name="protocolo_comp_prot",
                blank=True,
                to="protocolo.Protocolo",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharcaixa",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharcaixa",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharcaixa",
            name="permissao",
            field=models.ManyToManyField(to="protocolo.PermissaoEdoc"),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharcaixa",
            name="pessoa_fisica",
            field=models.ManyToManyField(
                related_name="pessoa_compartilhada",
                null=True,
                to="rh.PessoaFisica",
                blank=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="compartilharcaixa",
            name="pessoa_fisica_dono",
            field=models.ForeignKey(
                to="rh.PessoaFisica", unique=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="attachment",
            name="attach",
            field=models.ForeignKey(
                related_name="+", to="ged.Arquivo", on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="attachment",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="attachment",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="attachment",
            name="moviment",
            field=models.ForeignKey(
                related_name="attachments",
                to="protocolo.Movimentacao",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="attachment",
            name="protocol",
            field=models.ForeignKey(
                related_name="attachments",
                to="protocolo.Protocolo",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anexo",
            name="arquivo",
            field=models.ForeignKey(
                blank=True, to="ged.Arquivo", null=True, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anexo",
            name="created_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="anexo",
            name="modified_by",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                blank=True,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
    ]
