# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
from django.core.management import call_command

import os


FIXTURES = ("fixtures/tipodocumento_vacation.json",)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "edocs/protocolo", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        try:
            call_command("loaddata", filepath)
        except Exception as err:
            print(err)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0020_auto_20190920_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="special_type",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.RunPython(up, down),
    ]
