# Generated by Django 2.2.11 on 2020-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0021_add_special_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocolo",
            name="encaminhado",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="grupo",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="habilitado",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
