# Generated by Django 2.2.13 on 2020-06-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0118_auto_20200513_1820"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protocolo", "0022_auto_20200327_1611"),
    ]

    operations = [
        migrations.CreateModel(
            name="Envelop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("references", models.TextField()),
                ("attachments", models.TextField()),
                ("advice", models.TextField()),
                ("urgency", models.BooleanField(default=False)),
                ("opinion", models.BooleanField(default=False)),
                ("close", models.BooleanField(default=False)),
                ("reopen", models.BooleanField(default=False)),
                ("physical", models.BooleanField(default=False)),
                ("with_workflow", models.BooleanField(default=False)),
                ("confidential", models.BooleanField(default=None)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.Servidor"
                    ),
                ),
                (
                    "location_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotacao_origem",
                        to="rh.OrgaoGeral",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moviment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelop",
                        to="protocolo.Movimentacao",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="CommomDestination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, db_index=True, max_length=60)),
                (
                    "envelop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="protocolo.Envelop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonDestination",
            fields=[
                (
                    "commomdestination_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.CommomDestination",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.Pessoa"
                    ),
                ),
            ],
            bases=("protocolo.commomdestination",),
        ),
        migrations.CreateModel(
            name="LocationDestination",
            fields=[
                (
                    "commomdestination_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="protocolo.CommomDestination",
                    ),
                ),
                (
                    "general_organ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.OrgaoGeral"
                    ),
                ),
            ],
            bases=("protocolo.commomdestination",),
        ),
    ]
