# Generated by Django 2.2.13 on 2020-06-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0024_auto_20200622_1440"),
    ]

    operations = [
        migrations.RenameField(
            model_name="envelop",
            old_name="moviment",
            new_name="movement",
        ),
    ]
