# Generated by Django 2.2.13 on 2020-06-28 14:50

from django.db import migrations, models
import django.db.models.deletion


def up(apps, schema_editor):
    Envelop = apps.get_model("protocolo.Envelop")

    Envelop.objects.filter(
        pk__in=Envelop.objects.filter(destinations__created_movement=None).values("pk")
    ).update(delivery_state=1)

    Envelop.objects.exclude(
        pk__in=Envelop.objects.filter(destinations__created_movement=None).values("pk")
    ).update(delivery_state=3)


def down(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0025_auto_20200622_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelop",
            name="delivery_state",
            field=models.SmallIntegerField(
                choices=[(1, "pendent"), (2, "in-delivery"), (3, "finished")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="envelop",
            name="movement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envelops",
                to="protocolo.Movimentacao",
            ),
        ),
        migrations.RunPython(up, down),
    ]
