# Generated by Django 2.2.17 on 2021-01-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protocolo", "0026_envelop_undo_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="commomdestination",
            name="movement_undone_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Movimentação desfeita em"
            ),
        ),
        migrations.AddField(
            model_name="commomdestination",
            name="movement_undone_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Movimentação desfeita por",
            ),
        ),
        migrations.AlterField(
            model_name="commomdestination",
            name="created_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destinations",
                to="protocolo.Movimentacao",
            ),
        ),
        migrations.AlterField(
            model_name="envelop",
            name="delivery_state",
            field=models.SmallIntegerField(
                choices=[
                    (1, "pendent"),
                    (2, "in-delivery"),
                    (3, "finished"),
                    (4, "empty"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="destinatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_destinatario",
                to="rh.Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="lotacao_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_lotacao_destino",
                to="rh.OrgaoGeral",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="lotacao_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_lotacao_origem",
                to="rh.OrgaoGeral",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="protocolo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentacoes",
                to="protocolo.Protocolo",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="servidor_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_servidor_destino",
                to="rh.Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="servidor_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mov_servidor_origem",
                to="rh.Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="interessado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_interessado",
                to="rh.Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="lotacao_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_lotacao_criacao",
                to="rh.OrgaoGeral",
                verbose_name="Lotação de Criação",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="orgao_geral_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_orgao_destino",
                to="rh.OrgaoGeral",
                verbose_name="Destino",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="orgao_geral_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_orgao_origem",
                to="rh.OrgaoGeral",
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="servidor_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_servidor_origem",
                to="rh.Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prot_tipo_documento",
                to="protocolo.TipoDocumento",
            ),
        ),
    ]
