# Generated by Django 2.2.24 on 2021-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0028_alter_commondestination_to_use_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupperson",
            name="all_attorneys",
            field=models.BooleanField(default=False, verbose_name="Procuradores"),
        ),
        migrations.AddField(
            model_name="groupperson",
            name="all_prosecutors",
            field=models.BooleanField(default=False, verbose_name="Promotores"),
        ),
    ]
