# Generated by Django 2.2.28 on 2022-08-11 20:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocolo", "0030_auto_20220804_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolo",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="protocolo",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="protocolo",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="protocolo_p_search__794f3c_gin"
            ),
        ),
    ]
