# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mq", "0004_auto_20171121_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="visualized",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Visualized"
            ),
        ),
        migrations.AlterField(
            model_name="taskmessages",
            name="type_of",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "INFO"), (2, "WARN"), (3, "ERROR"), (4, "FILE")],
                db_index=True,
                default=1,
                verbose_name="Type",
            ),
        ),
    ]
