# Generated by Django 2.2.28 on 2024-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mq", "0005_auto_20230112_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notificar_hermes",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Notificar hermes"
            ),
        ),
    ]
