# Generated by Django 2.2.28 on 2024-07-15 16:13
from django.db import migrations, models
from django.core.management import call_command
from django.conf import settings
import os


FIXTURES = ("fixtures/tipos_processametos_choices.json",)


def forward(*args, **kwargs):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "engine", "mq", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def backward(*args, **kwargs):
    print("Running backward...")


class Migration(migrations.Migration):

    dependencies = [
        ("mq", "0006_task_notificar_hermes"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tipo_processamento",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Padrão"), (2, "Relatórios"), (3, "Email pessoal")],
                null=True,
                verbose_name="Tipo de processamento",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
