# Generated by Django 4.2 on 2025-02-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0014_alter_historicoservico_id_alter_scheduledservices_id_and_more",
        ),
        ("mq", "0008_load_fixture_tp_processamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task",
                to="services.scheduledservices",
                verbose_name="Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tipo_processamento",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Padrão"),
                    (2, "Relatórios"),
                    (3, "Email pessoal"),
                    (4, "Esocial"),
                ],
                null=True,
                verbose_name="Tipo de processamento",
            ),
        ),
        migrations.AlterField(
            model_name="taskmessages",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
