# Generated by Django 2.2.28 on 2022-12-12 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0209_auto_20221212_1119"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisProcedure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=800, verbose_name="Descrição"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento Diagnóstico",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("exam_date", models.DateTimeField(verbose_name="Data do exame")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=999, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=99, verbose_name="Ordem"),
                ),
                (
                    "result",
                    models.PositiveSmallIntegerField(
                        default=99, verbose_name="Resultado"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis_procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam",
                        to="health.DiagnosisProcedure",
                        verbose_name="Procedimento diagnóstico",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame",
                "ordering": ("exam_date",),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
