# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_load_fixtures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="order",
            field=models.PositiveSmallIntegerField(
                choices=[(99, "Não informado"), (1, "Inicial"), (2, "Sequencial")],
                default=99,
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="result",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (99, "Não informado"),
                    (1, "Normal"),
                    (2, "Alterado"),
                    (3, "Estável"),
                    (4, "Agravamento"),
                ],
                default=99,
                verbose_name="Resultado",
            ),
        ),
    ]
