# Generated by Django 2.2.28 on 2023-10-03 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0271_merge_20231002_1913"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotacaoPessoal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "texto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto Anotação"
                    ),
                ),
                (
                    "estado_anotacao",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Em Aberto"),
                            (2, "Públicação Solicitada"),
                            (3, "Públicação Realizada"),
                            (4, "Públicação Cancelada"),
                            (5, "Publicação Solicitada ao Expediente"),
                        ],
                        null=True,
                        verbose_name="Estado da Anotação",
                    ),
                ),
                (
                    "tipo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tipo de Anotação"
                    ),
                ),
                (
                    "documento_numero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número Documento",
                    ),
                ),
                (
                    "documento_ano",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano Documento"
                    ),
                ),
                (
                    "documento_tipo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (3, "PORTARIA"),
                            (1, "ATO"),
                            (2, "DECRETO"),
                            (4, "OFÍCIO"),
                            (5, "DESPACHO"),
                            (6, "TERMO"),
                            (7, "MEMORANDO"),
                            (8, "REQUERIMENTO"),
                            (9, "CONCESSÃO"),
                            (10, "ACORDO COOPERAÇÃO TÉCNICA"),
                            (11, "LEI"),
                            (12, "APOSTILA"),
                            (14, "DECRETO LEGISLATIVO"),
                            (15, "RESOLUÇÃO"),
                            (16, "CIRCULAR"),
                            (17, "PROCESSO"),
                            (18, "DECISÃO"),
                            (95, "DECLARAÇÃO DE ENTRADA EM ATIVIDADE"),
                            (96, "TERMO LOTAÇÃO"),
                            (97, "TERMO EXERCÍCIO"),
                            (98, "TERMO POSSE"),
                            (99, "OUTROS"),
                            (100, "DOCUMENTO DIGITAL"),
                            (101, "PORTARIA DE INSTAURAÇÃO"),
                            (102, "CONTRATO"),
                            (103, "TERMO DECOMPROMISSO DE ESTAGIO"),
                            (104, "TERMO DE RECISÃO DE ESTAGIÁRIO"),
                            (105, "ATO ADMINISTRATIVO"),
                            (1000, "GEDOC"),
                        ],
                        null=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "documento_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Documento"
                    ),
                ),
                (
                    "data_efeito_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efeito Início"
                    ),
                ),
                (
                    "data_efeito_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Efeito Fim"
                    ),
                ),
                (
                    "gedoc_numero",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número GEDOC",
                    ),
                ),
                (
                    "login_resp_import",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Login Responsável - SIAP Importação",
                    ),
                ),
                (
                    "nome_resp_import",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome Responsável - SIAP Importação",
                    ),
                ),
                (
                    "dt_ultima_alteracao",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data Última Alteração - SIAP Importação",
                    ),
                ),
                (
                    "status_import",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Status - SIAP Importação"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rh.Servidor",
                        verbose_name="anotacao_pessoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anotação Pessoal",
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
