# Generated by Django 2.2.28 on 2023-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anotacao_pessoal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anotacaopessoal",
            old_name="dt_ultima_alteracao",
            new_name="data_ultima_alteracao",
        ),
        migrations.RemoveField(
            model_name="anotacaopessoal",
            name="modified_at",
        ),
    ]
