# Generated by Django 2.2.28 on 2023-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anotacao_pessoal", "0003_auto_20231010_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacaopessoal",
            name="exibir",
            field=models.BooleanField(default=True, verbose_name="Exibir"),
        ),
    ]
