# Generated by Django 2.2.28 on 2023-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anotacao_pessoal", "0004_anotacaopessoal_exibir"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacaopessoal",
            name="codigo_siap_import",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Código - SIAP Importação",
            ),
        ),
    ]
