FROM IMGHUB_REPO

WORKDIR /app

COPY . /app/root
COPY docker/busybox.py /bin/
COPY docker/policy.xml /etc/ImageMagick-6/policy.xml

RUN mkdir -p /app/var/www

RUN chmod +x /bin/busybox.py
RUN python3 /bin/busybox.py configure

RUN wget https://tools.mpmt.mp.br/files/athenas/js-vol-current.tar.gz && \
    tar xf js-vol-current.tar.gz --strip-components=1 -C /app/var/www && \
    rm js-vol-current.tar.gz && \
    rm -fr /app/.cache/pip

ENTRYPOINT ["python","/bin/busybox.py"]

# CMD ["register",  "start"]