# -*- coding:utf-8 -*-

"""
No escopo de módulo NÃO DEVE HAVER import do settings ou qualquer outro módulo ou aplicativo que tenha
importação do settings do Django.

Solução: Criar modulos separados e fazer import via importlib
a partir do escopo do método ready do AppConfig
"""

import importlib
from django.apps import AppConfig


class GFPConfig(
    AppConfig
):  # Substituir "Sample" pelo nome que preferir dar ao AppConfig
    name = "rh.gfp"  # Caminho completo para o app. Ex: rh.gfp.dirf
    default_auto_field = "django.db.models.BigAutoField"

    controllers = [
        # Aqui devem ser listados os caminhos dos controllers do app. Ex: web.api.cms.metadata
        "rh.gfp.views",
        "rh.gfp.reports",
        "rh.gfp.filebuild",
        "rh.gfp.rais.views",
        "rh.gfp.api.evento",
        "rh.gfp.api.estrutura_salarial",
        "rh.gfp.api.payroll",
        "rh.gfp.api.classcode",
        "rh.gfp.api.parameters",
        # 'rh.gfp.api.socialsecurity',
        "rh.gfp.api.extrapayment",
        "rh.gfp.api.paycheckdifference",
        "rh.gfp.api.progression",
        "rh.gfp.api.paycheck",
        "rh.gfp.api.conference",
        "rh.gfp.api.report",
        "rh.gfp.api.irrf",
        "rh.gfp.api.transparencychoice",
        "rh.gfp.generators.pasep.reports",
        "rh.gfp.generators.plansaude.reports",
        "rh.gfp.generators.viabillize.reports",
        "rh.gfp.generators.neoconsig.reports",
        "rh.gfp.generators.consigfacil.reports",
        "rh.gfp.api.remunerationbase",
        "rh.gfp.api.extern",
        "rh.gfp.api.familysalary",
        "rh.gfp.api.sicap",
        "rh.gfp.api.importpayroll",
        "rh.gfp.api.remunerationrelationship",
        "rh.gfp.api.gcpp",
        "rh.gfp.api.vacation",
    ]

    def ready(self):
        """
        O carregamento de partes necessárias ao app.
        """
        register_statics()
        connect_signals()
        loaders()
        # carregar qualquer outra coisa necessária ao app


def connect_signals():
    """Seus sinais devem ser carregados aqui.

    importlib.import_module('nome.canonico.do.modulo.de.sinais')
    """
    importlib.import_module("rh.gfp.signals")
    # importlib.import_module('rh.gfp.signals.event')
    importlib.import_module("rh.gfp.signals.differences")
    importlib.import_module("rh.gfp.signals.paychecks")
    importlib.import_module("rh.gfp.plugins.rh_models")
    importlib.import_module("rh.gfp.signals.remuneration_base")
    importlib.import_module("rh.gfp.signals.progression_departure")


def loaders():
    pass


def register_statics():
    """O registro dos arquivos estáticos do app deve ser feito aqui.

    Ex:

        Application = importlib.import_module('default.views').Application
        '/%(context)s/static/web/js/shortcuts.js',

        Application.register_stylesheet('/%(context)s/static/web/css/styles.css')
    """

    Application = importlib.import_module("default.views").Application

    js_paths = (
        # ORGANIZED LOADERS ----------------------------------------------------------------------------
        "/%(context)s/static/rh/js/gfp.js",
        "/%(context)s/static/rh/js/gfp.pensao.js",
        "/%(context)s/static/rh/js/controlador.js",
        "/%(context)s/static/rh/js/gfp.filebuild.js",
        "/%(context)s/static/rh/gfp/lancador/DependentesGrid.js",
        "/%(context)s/static/rh/gfp/evento/EventoGrid.js",
        "/%(context)s/static/rh/gfp/evento/EventoRestful.js",
        "/%(context)s/static/rh/gfp/evento/EventoWindow.js",
        "/%(context)s/static/rh/gfp/evento/EventoManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/EstruturaSalarialRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/EstruturaSalarialManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/EstruturaSalarialGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/EstruturaSalarialWindow.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ModeloTabelaSalarialRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ModeloTabelaSalarialManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ModeloTabelaSalarialGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ModeloTabelaSalarialWindow.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/TabelaSalarialRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/TabelaSalarialManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/TabelaSalarialGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/TabelaSalarialWindow.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaNiveis2DRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaNiveis2DManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaNiveis2DGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaNiveis2DWindow.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/CargosEstruturaRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/CargosEstruturaManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/CargosEstruturaGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/CargosEstruturaWindow.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaSalarioRestful.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaSalarioManage.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaSalarioGrid.js",
        "/%(context)s/static/rh/gfp/estrutura_salarial/ReferenciaSalarioWindow.js",
        # '/%(context)s/static/rh/gfp/lancador/ChangePaychecks.js',
        "/%(context)s/static/rh/gfp/lancador/Pendencies.js",
        # '/%(context)s/static/rh/gfp/lancador/Lancador.js',
        "/%(context)s/static/rh/gfp/extern/Viabillize.js",
        "/%(context)s/static/rh/gfp/extern/NeoConsig.js",
        "/%(context)s/static/rh/gfp/extern/ConsigFacil.js",
        "/%(context)s/static/rh/gfp/payroll/ModelPayrollGrid.js",
        "/%(context)s/static/rh/gfp/payroll/ModelPayrollRestful.js",
        "/%(context)s/static/rh/gfp/payroll/ModelPayrollWindow.js",
        "/%(context)s/static/rh/gfp/payroll/ModelPayrollManage.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollWindow.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollManage.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodWindow.js",
        "/%(context)s/static/rh/gfp/classcode/LoaderGrid.js",
        "/%(context)s/static/rh/gfp/classcode/LoaderRestful.js",
        "/%(context)s/static/rh/gfp/classcode/LoaderWindow.js",
        "/%(context)s/static/rh/gfp/classcode/CalculationGrid.js",
        "/%(context)s/static/rh/gfp/classcode/CalculationRestful.js",
        "/%(context)s/static/rh/gfp/classcode/CalculationWindow.js",
        "/%(context)s/static/rh/gfp/parameters/FapFactorGrid.js",
        "/%(context)s/static/rh/gfp/parameters/FapFactorRestful.js",
        "/%(context)s/static/rh/gfp/parameters/FapFactorWindow.js",
        "/%(context)s/static/rh/gfp/parameters/FapFactorManage.js",
        "/%(context)s/static/rh/gfp/parameters/RatFactorGrid.js",
        "/%(context)s/static/rh/gfp/parameters/RatFactorRestful.js",
        "/%(context)s/static/rh/gfp/parameters/RatFactorWindow.js",
        "/%(context)s/static/rh/gfp/parameters/RatFactorManage.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeePayrollTypeGrid.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeePayrollTypeRestful.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeePayrollTypeWindow.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeePayrollTypeManage.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollTypeGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollTypeRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollTypeWindow.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollTypeManage.js",
        "/%(context)s/static/rh/gfp/payroll/BankingDataPersonPayrollGrid.js",
        "/%(context)s/static/rh/gfp/payroll/BankingDataPersonPayrollRestful.js",
        "/%(context)s/static/rh/gfp/payroll/BankingDataPersonPayrollWindow.js",
        "/%(context)s/static/rh/gfp/payroll/BankingDataPersonPayrollManage.js",
        "/%(context)s/static/rh/gfp/payroll/BankingConvenantGrid.js",
        "/%(context)s/static/rh/gfp/payroll/BankingConvenantRestful.js",
        "/%(context)s/static/rh/gfp/payroll/BankingConvenantWindow.js",
        "/%(context)s/static/rh/gfp/payroll/BankingConvenantManage.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodWindow.js",
        "/%(context)s/static/rh/gfp/payroll/PeriodManage.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollMessageGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollMessageRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PayrollMessageWindow.js",
        "/%(context)s/static/rh/gfp/parameters/CNJRaisGrid.js",
        "/%(context)s/static/rh/gfp/parameters/CNJRaisRestful.js",
        "/%(context)s/static/rh/gfp/parameters/CNJRaisWindow.js",
        "/%(context)s/static/rh/gfp/parameters/CNJRaisManage.js",
        "/%(context)s/static/rh/gfp/parameters/CNAERestful.js",
        "/%(context)s/static/rh/gfp/parameters/CNAEWindow.js",
        "/%(context)s/static/rh/gfp/parameters/CNAEGrid.js",
        "/%(context)s/static/rh/gfp/parameters/CNAEManage.js",
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityRestful.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityWindow.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityGrid.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityManage.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityRangeRestful.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityRangeWindow.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityRangeGrid.js',
        # '/%(context)s/static/rh/gfp/socialsecurity/SocialSecurityRangeManage.js',
        "/%(context)s/static/rh/gfp/payroll/GenreEventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventManage.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/EventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/BancoConsignacaoRestful.js",
        "/%(context)s/static/rh/gfp/payroll/BancoConsignacaoGrid.js",
        "/%(context)s/static/rh/gfp/payroll/EventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/EventWindow.js",
        "/%(context)s/static/rh/gfp/parameters/RRARestful.js",
        "/%(context)s/static/rh/gfp/parameters/RRAManage.js",
        "/%(context)s/static/rh/gfp/parameters/RRAGrid.js",
        "/%(context)s/static/rh/gfp/parameters/RRAWindow.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeeRestful.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeeWindow.js",
        "/%(context)s/static/rh/gfp/parameters/RRAEmployeeGrid.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentRestful.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentWindow.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentGrid.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentManage.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentPeriodManage.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentPeriodRestful.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentPeriodWindow.js",
        "/%(context)s/static/rh/gfp/extrapayment/ExtraPaymentPeriodGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryManage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryWindow.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceManage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceWindow.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryShowRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/EntryDifferenceShowGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceItemRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceItemGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceItemWindow.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceConfigRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceConfigGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/PayCheckDifferenceConfigWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/MarginConsignableRestful.js",
        "/%(context)s/static/rh/gfp/paycheck/MarginConsignableManage.js",
        "/%(context)s/static/rh/gfp/paycheck/MarginConsignableGrid.js",
        "/%(context)s/static/rh/gfp/paycheck/MarginConsignableWindow.js",
        # '/%(context)s/static/rh/gfp/paycheckdifference/EntriesDifferenceRestful.js',
        "/%(context)s/static/rh/gfp/paycheckdifference/EntriesDifferenceGrid.js",
        # '/%(context)s/static/rh/gfp/paycheckdifference/EntriesDifferenceWindow.js',
        "/%(context)s/static/rh/gfp/payroll/PayCheckAltRestful.js",
        "/%(context)s/static/rh/gfp/payroll/PayCheckAltManage.js",
        "/%(context)s/static/rh/gfp/payroll/PayCheckAltGrid.js",
        "/%(context)s/static/rh/gfp/payroll/PayCheckAltWindow.js",
        "/%(context)s/static/rh/gfp/payroll/EntriesRestful.js",
        "/%(context)s/static/rh/gfp/payroll/EntriesGrid.js",
        "/%(context)s/static/rh/gfp/payroll/EntriesWindow.js",
        "/%(context)s/static/rh/gfp/payroll/EntriesManage.js",
        "/%(context)s/static/rh/gfp/progression/SalaryProgressionRestful.js",
        "/%(context)s/static/rh/gfp/progression/SalaryProgressionGrid.js",
        "/%(context)s/static/rh/gfp/progression/SalaryProgressionWindow.js",
        "/%(context)s/static/rh/gfp/progression/SalaryProgressionManage.js",
        "/%(context)s/static/rh/gfp/progression/ProgressionMonthReportWindow.js",
        "/%(context)s/static/rh/gfp/progression/RelatorioProrrogacoesWindow.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_solicitation/Restful.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_solicitation/Grid.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_solicitation/Window.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_solicitation/Manage.js",
        "/%(context)s/static/rh/gfp/progression/document/Restful.js",
        "/%(context)s/static/rh/gfp/progression/document/Grid.js",
        "/%(context)s/static/rh/gfp/progression/document/Window.js",
        "/%(context)s/static/rh/gfp/progression/document/Manage.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_config/Restful.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_config/Grid.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_config/Window.js",
        "/%(context)s/static/rh/gfp/progression/horizontal_config/Manage.js",
        "/%(context)s/static/rh/gfp/reports/DemonstrativoIgeprevWindow.js",
        "/%(context)s/static/rh/gfp/reports/PayCheckManage.js",
        "/%(context)s/static/rh/gfp/reports/ProofOfIncome.js",
        "/%(context)s/static/rh/gfp/reports/EmployeeByEventType.js",
        "/%(context)s/static/rh/gfp/reports/FinancialStatementManage.js",
        "/%(context)s/static/rh/gfp/reports/Billet.js",
        "/%(context)s/static/rh/gfp/reports/Cubo.js",
        "/%(context)s/static/rh/gfp/reports/Lista.js",
        "/%(context)s/static/rh/gfp/reports/PassInstallment.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFWindow.js",
        "/%(context)s/static/rh/gfp/reports/CommitmentReportManage.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/BaseForm.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/PayCheck.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/PayCheckMPMT.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/FinancialStatement.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/EmployeeRecord.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/ComprovanteRendimentos.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/Documents.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/StaticDocuments.js",
        "/%(context)s/static/rh/gfp/reports/employee/forms/TimeSheet.js",
        "/%(context)s/static/rh/gfp/reports/employee/Manager.js",
        "/%(context)s/static/rh/gfp/reports/Manager.js",
        "/%(context)s/static/rh/gfp/reports/CedulaCAdminReport.js",
        "/%(context)s/static/rh/gfp/reports/CedulaCReport.js",
        "/%(context)s/static/rh/gfp/irrf/cedulaC/CedulaCGrid.js",
        "/%(context)s/static/rh/gfp/irrf/cedulaC/CedulaCManage.js",
        "/%(context)s/static/rh/gfp/irrf/cedulaC/CedulaCRestful.js",
        "/%(context)s/static/rh/gfp/irrf/cedulaC/CedulaCWindow.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFGrid.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFRestful.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFManage.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFFaixaWindow.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFFaixaGrid.js",
        "/%(context)s/static/rh/gfp/irrf/IRRFFaixaRestful.js",
        "/%(context)s/static/rh/gfp/transparencychoice/Restful.js",
        "/%(context)s/static/rh/gfp/transparencychoice/Manage.js",
        "/%(context)s/static/rh/gfp/transparencychoice/Grid.js",
        "/%(context)s/static/rh/gfp/transparencychoice/Window.js",
        "/%(context)s/static/rh/gfp/transparencychoice/GroupEventsRestful.js",
        "/%(context)s/static/rh/gfp/transparencychoice/GroupEventsManage.js",
        "/%(context)s/static/rh/gfp/transparencychoice/GroupEventsGrid.js",
        "/%(context)s/static/rh/gfp/transparencychoice/GroupEventsWindow.js",
        "/%(context)s/static/rh/gfp/transparencychoice/reports/Payroll.js",
        "/%(context)s/static/rh/gfp/transparencychoice/reports/Support.js",
        "/%(context)s/static/rh/gfp/transparencychoice/genreevent/TransparencyManage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/CorrectionFactorLoaderWindow.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/CorrectionFactorWindow.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/CorrectionFactorGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/CorrectionFactorRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/CorrectionFactorManage.js",
        "/%(context)s/static/rh/gfp/payroll/BankingEmployeeTypePayrollGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/Manage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/Grid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/Restful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/Window.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/Manage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/Grid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/Restful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/PayrollManage.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/PayrollRestful.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/PayrollGrid.js",
        "/%(context)s/static/rh/gfp/paycheckdifference/difference_payroll/difference/PayrollWindow.js",
        "/%(context)s/static/rh/gfp/payroll/BankingEmployeeTypePayrollRestful.js",
        "/%(context)s/static/rh/gfp/payroll/BankingEmployeeTypePayrollWindow.js",
        "/%(context)s/static/rh/gfp/payroll/BankingEmployeeTypePayrollManage.js",
        "/%(context)s/static/rh/gfp/parameters/NatureEventRestful.js",
        "/%(context)s/static/rh/gfp/parameters/NatureEventManage.js",
        "/%(context)s/static/rh/gfp/parameters/NatureEventGrid.js",
        "/%(context)s/static/rh/gfp/parameters/NatureEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/EventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/EventManage.js",
        "/%(context)s/static/rh/gfp/payroll/EventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/EventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/ConfigEventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/ConfigEventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/ConfigEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/SpecieEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/FocusesOnEventsRestful.js",
        "/%(context)s/static/rh/gfp/payroll/FocusesOnEventsGrid.js",
        "/%(context)s/static/rh/gfp/payroll/FocusesOnEventsWindow.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventRestful.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventManage.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventGrid.js",
        "/%(context)s/static/rh/gfp/payroll/GenreEventWindow.js",
        "/%(context)s/static/rh/gfp/payroll/ImportPayroll.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationBaseRestful.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationBaseManage.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationBaseGrid.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationBaseWindow.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationPeriodRestful.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationPeriodManage.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationPeriodGrid.js",
        "/%(context)s/static/rh/gfp/remunerationbase/RemunerationPeriodWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckRestful.js",
        "/%(context)s/static/rh/gfp/conference/liquidvalue/Manage.js",
        "/%(context)s/static/rh/gfp/conference/liquidvalue/Grid.js",
        "/%(context)s/static/rh/gfp/conference/liquidvalue/Restful.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/Manage.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/Grid.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/Restful.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/folhaevento/Manage.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/folhaevento/Grid.js",
        "/%(context)s/static/rh/gfp/conference/massmanagementfunds/folhaevento/Restful.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckManage.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckManageNew.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckGrid.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckGridNew.js",
        "/%(context)s/static/rh/gfp/paycheck/PayCheckWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesRestful.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesSimpleRestful.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesGrid.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesSimpleGrid.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesMemoryWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/EntriesSimpleWindow.js",
        "/%(context)s/static/rh/gfp/paycheck/reports/PayCheck.js",
        "/%(context)s/static/rh/gfp/paycheck/socialsecurity/WindowFileGenerator.js",
        "/%(context)s/static/rh/gfp/familysalary/Manage.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryGrid.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryWindow.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryRestful.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryRangeGrid.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryRangeWindow.js",
        "/%(context)s/static/rh/gfp/familysalary/FamilySalaryRangeRestful.js",
        "/%(context)s/static/rh/gfp/conference/payroll/Manage.js",
        "/%(context)s/static/rh/gfp/conference/payroll/PaycheckGrid.js",
        "/%(context)s/static/rh/gfp/conference/payroll/PaycheckRestful.js",
        "/%(context)s/static/rh/gfp/conference/payroll/EntriesManage.js",
        "/%(context)s/static/rh/gfp/conference/payroll/EntriesGrid.js",
        "/%(context)s/static/rh/gfp/conference/payroll/EntriesRestful.js",
        "/%(context)s/static/rh/gfp/conference/payroll/EntriesWindow.js",
        "/%(context)s/static/rh/gfp/conference/payroll/ConferenceManage.js",
        "/%(context)s/static/rh/gfp/conference/payroll/ConferenceGrid.js",
        "/%(context)s/static/rh/gfp/conference/payroll/ConferenceRestful.js",
        "/%(context)s/static/rh/gfp/conference/payroll/ConferenceWindow.js",
        "/%(context)s/static/rh/gfp/remunerationrelationship/Manage.js",
        "/%(context)s/static/rh/gfp/remunerationrelationship/Grid.js",
        "/%(context)s/static/rh/gfp/remunerationrelationship/Window.js",
        "/%(context)s/static/rh/gfp/remunerationrelationship/Restful.js",
        "/%(context)s/static/rh/gfp/gcpp/Manage.js",
        "/%(context)s/static/rh/gfp/gcpp/Grid.js",
        "/%(context)s/static/rh/gfp/gcpp/Restful.js",
        "/%(context)s/static/rh/gfp/gcpp/Window.js",
        "/%(context)s/static/rh/gfp/gcpp_est_res/Manage.js",
        "/%(context)s/static/rh/gfp/gcpp_est_res/Grid.js",
        "/%(context)s/static/rh/gfp/gcpp_est_res/Restful.js",
        "/%(context)s/static/rh/gfp/gcpp_est_res/Window.js",
        "/%(context)s/static/rh/gfp/gcpp/payroll/Manage.js",
        "/%(context)s/static/rh/gfp/gcpp/payroll/Grid.js",
        "/%(context)s/static/rh/gfp/gcpp/payroll/Restful.js",
        "/%(context)s/static/rh/gfp/gcpp/payroll/Window.js",
        "/%(context)s/static/rh/gfp/vacation/Manage.js",
        "/%(context)s/static/rh/gfp/vacation/Grid.js",
        "/%(context)s/static/rh/gfp/vacation/Restful.js",
        "/%(context)s/static/rh/gfp/vacation/Window.js",
    )

    for path in js_paths:
        Application.register_javascript(path, scope="rh")

    # 'Registro dos Stylesheet's para este aplicativo'
    Application.register_stylesheet("/%(context)s/static/rh/images/fopag/fopag.css")
    Application.register_stylesheet("/%(context)s/static/rh/images/fopag/style.css")
    Application.register_stylesheet(
        "/%(context)s/static/rh/images/progressoes/sprite-progressoes.css"
    )
