from rh.sisdias.models import Sdia01OrdemServico
from datetime import datetime


def montar_sisdias_model(data):
    model = Sdia01OrdemServico()

    # Converter campos de data
    def parse_datetime(date_str):
        return datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S") if date_str else None

    model.numero = data.get("numero")
    model.data = parse_datetime(data.get("data"))
    model.local = data.get("local")
    model.chapa_servidor = data.get("chapa_servidor")
    model.nome_servidor = data.get("nome_servidor")
    model.cargo_servidor = data.get("cargo_servidor")
    model.carteira_identidade = data.get("carteira_identidade")
    model.finalidade = data.get("finalidade")
    model.chapa_designante = data.get("chapa_designante")
    model.num_diaria_estado = data.get("num_diaria_estado")
    model.valor_unit_estado = data.get("valor_unit_estado")
    model.num_diaria_pais = data.get("num_diaria_pais")
    model.valor_unit_pais = data.get("valor_unit_pais")
    model.num_diaria_exterior = data.get("num_diaria_exterior")
    model.valor_unit_exterior = data.get("valor_unit_exterior")
    model.chapa_ordenador = data.get("chapa_ordenador")
    model.valor_importancia = data.get("valor_importancia")
    model.data_setor_pessoal = parse_datetime(data.get("data_setor_pessoal"))
    model.chapa_resp_pessoal = data.get("chapa_resp_pessoal")
    model.num_empenho = data.get("num_empenho")
    model.data_empenho = parse_datetime(data.get("data_empenho"))
    model.num_cheque = data.get("num_cheque")
    model.data_cheque = parse_datetime(data.get("data_cheque"))
    model.chapa_resp_financeiro = data.get("chapa_resp_financeiro")
    # model.situacao = data.get("situacao")
    model.sdia07_cdgmotivo_cancel = data.get("sdia07_cdgmotivo_cancel")
    # model.sdia02_cdglocalidade_origem = data.get("sdia02_cdglocalidade_origem")
    model.valor_total_estado_old = data.get("valor_total_estado_old")
    model.valor_total_pais_old = data.get("valor_total_pais_old")
    model.valor_total_exterior_old = data.get("valor_total_exterior_old")
    model.valor_dolar = data.get("valor_dolar")
    # model.sdia12_cdgtipo_finalidade = data.get("sdia12_cdgtipo_finalidade")
    model.sacs01_usuario_cadastro = data.get("sacs01_usuario_cadastro")
    # model.sdia08_cdgpessoa_externa = data.get("sdia08_cdgpessoa_externa")
    # model.sdia13_cdgconvenio = data.get("sdia13_cdgconvenio")
    model.data_setor_financeiro = parse_datetime(data.get("data_setor_financeiro"))
    model.sacs01_usuario_empenho = data.get("sacs01_usuario_empenho")
    model.sacs01_usuario_cancelamento = data.get("sacs01_usuario_cancelamento")
    model.data_cancelamento = parse_datetime(data.get("data_cancelamento"))
    model.banco = data.get("banco")
    model.agencia = data.get("agencia")
    model.conta = data.get("conta")
    model.data_protocolo_banco = parse_datetime(data.get("data_protocolo_banco"))
    model.relatorio_entregue = data.get("relatorio_entregue")
    model.meio = data.get("meio")
    model.km = data.get("km")
    model.num_bilhete = data.get("num_bilhete")
    model.empresa_transporte = data.get("empresa_transporte")
    model.placa_veiculo_mp = data.get("placa_veiculo_mp")
    model.descricao_resultado = data.get("descricao_resultado")
    model.observacoes = data.get("observacoes")
    model.data_relatorio = parse_datetime(data.get("data_relatorio"))
    model.protocolo = data.get("protocolo")
    model.meiadiaria = data.get("meiadiaria")
    model.tipo = data.get("tipo")
    model.relatorioonline = data.get("relatorioonline")
    model.emissaobilhete = data.get("emissaobilhete")
    model.viagemefetivada = data.get("viagemefetivada")
    model.data_recebido = parse_datetime(data.get("data_recebido"))
    model.informacoes_adicionais = data.get("informacoes_adicionais")
    model.valor_pass = data.get("valor_pass")
    model.autoridade_sol = data.get("autoridade_sol")
    model.autoridade_con = data.get("autoridade_con")
    model.pass_custeada = data.get("pass_custeada")
    model.pass_custeada_outros = data.get("pass_custeada_outros")
    model.locomocao_outros = data.get("locomocao_outros")
    model.auxilios_devolvidos = data.get("auxilios_devolvidos")
    model.valor_devolucao = data.get("valor_devolucao")
    model.tipo_origem = data.get("tipo_origem")
    model.email = data.get("email")
    model.transportes_devolvidos = data.get("transportes_devolvidos")
    model.valor_transportes = data.get("valor_transportes")
    model.numerounicocnmp = data.get("numerounicocnmp")
    model.totaldescontos = data.get("totaldescontos")
    model.totalareceber = data.get("totalareceber")
    model.valor_total_estado = data.get("valor_total_estado")
    model.valor_total_pais = data.get("valor_total_pais")
    model.valor_total_exterior = data.get("valor_total_exterior")
    model.email_enviado = data.get("email_enviado")
    model.qtd_auxilios = data.get("qtd_auxilios")
    model.qtd_transportes = data.get("qtd_transportes")
    model.valor_total_bruto = data.get("valor_total_bruto")
    model.valor_total_liquido = data.get("valor_total_liquido")
    model.valor_uni_auxilios = data.get("valor_uni_auxilios")
    model.valor_uni_transportes = data.get("valor_uni_transportes")
    model.comprovante_arquivo = data.get("comprovante_arquivo")
    model.relatorio_viagem_arquivo = data.get("relatorio_viagem_arquivo")
    model.data_pagamento = parse_datetime(data.get("data_pagamento"))
    model.empenho = data.get("empenho")
    model.data_valor_devolvido = parse_datetime(data.get("data_valor_devolvido"))
    model.valor_devolvido = data.get("valor_devolvido")

    return model
