# Generated by Django 2.2.28 on 2024-01-09 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigPeriodoEnvioRelatoriosSemestrais",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=250, verbose_name="Título")),
                (
                    "data_inicio_periodo_envio",
                    models.DateField(verbose_name="Data Início de Envio"),
                ),
                (
                    "data_fim_periodo_envio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Fim de Envio"
                    ),
                ),
                (
                    "data_inicio_periodo_analisado",
                    models.DateField(verbose_name="Data Início de periodo analisado"),
                ),
                (
                    "data_fim_periodo_analisado",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data Fim de periodo analisado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "titulo",
                        "data_inicio_periodo_envio",
                        "data_inicio_periodo_analisado",
                    )
                },
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
