# Generated by Django 2.2.28 on 2024-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teletrabalho", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configperiodoenviorelatoriossemestrais",
            name="data_fim_periodo_analisado",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Data Fim de periodo analisado",
            ),
        ),
        migrations.AlterField(
            model_name="configperiodoenviorelatoriossemestrais",
            name="data_inicio_periodo_analisado",
            field=models.CharField(
                max_length=10, verbose_name="Data Início de periodo analisado"
            ),
        ),
    ]
