# -*- coding:utf-8 -*-
from contrib.config import config

ACCOUNT_INTEGRATION_ENDPOINT = config("ACCOUNT_INTEGRATION_ENDPOINT", default=None)
ACCOUNT_INTEGRATION_CHANGE_PASSWORD = config(
    "ACCOUNT_INTEGRATION_CHANGE_PASSWORD", default=None
)
ACCOUNT_INTEGRATION_TOKEN = config("ACCOUNT_INTEGRATION_TOKEN", default="secret")

CLASSCODE_AUTO_REGISTRATION_NUMBER_SLUG = config(
    "CLASSCODE_AUTO_REGISTRATION_NUMBER_SLUG", default="mpmt-registration"
)
MATRICULA_FIELD_BLOCKED = config("MATRICULA_FIELD_BLOCKED", default=True)
MANY_EMPLOYEE_ACTIVE_SAME_PERSON = config(
    "MANY_EMPLOYEE_ACTIVE_SAME_PERSON", default=True
)

UPDATE_WORK_ASSIGNMENT_FROM_DEPARTURE = config(
    "UPDATE_WORK_ASSIGNMENT_FROM_DEPARTURE", default=False
)
