TURNOS = (
    ("MANHA", "Manhã"),
    ("TARDE", "Tarde"),
    ("NOITE", "Noite"),
)


FLUXOS_CANCELADOS = [21, 32]

FLUXO_PAGO = 16  # id do fluxo - DEFIN - Gerência financeira - Pago

FLUXO_AGUARDADO_PRESTACAO_CONTAS = 17
FLUXO_PRESTACAO_CONTAS_ENTREGUE = 18

FLUXO_FINALIZADO = 19
FLUXO_CANCELADO = 32


FLUXOS_PAGAMENTO = [14, 15]
FLUXOS_PRESTACAO_CONTAS = [17, 18]
