# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0008_auto_20190429_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="data_publicacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o per\xedodo aquisitivo foi publicado.",
                null=True,
                verbose_name="Data de Publica\xe7\xe3o",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="mes_fruicao",
            field=models.SmallIntegerField(
                choices=[
                    (1, "JANEIRO"),
                    (2, "FEVEREIRO"),
                    (3, "MAR\xc7O"),
                    (4, "ABRIL"),
                    (5, "MAIO"),
                    (6, "JUNHO"),
                    (7, "JULHO"),
                    (8, "AGOSTO"),
                    (9, "SETEMBRO"),
                    (10, "OUTUBRO"),
                    (11, "NOVEMBRO"),
                    (12, "DEZEMBRO"),
                    (14, "-------------"),
                ],
                default=14,
                help_text="M\xc3\xaas para frui\xc3\xa7\xc3\xa3o coletiva, caso haja",
                verbose_name="M\xeas de frui\xe7\xe3o",
            ),
        ),
    ]
