# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ferias", "0009_auto_20190617_1812"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodoaquisitivoservidor",
            options={"ordering": ("servidor", "periodo_aquisitivo")},
        ),
        migrations.AlterField(
            model_name="alteracaopasu",
            name="anotacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Anotação de Alteração.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alteracoes_ferias",
                to="rh.AnotacaoFerias",
                verbose_name="Anotação",
            ),
        ),
        migrations.AlterField(
            model_name="alteracaopasu",
            name="autorizado",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Se a autorizacao foi deferida ou indeferida.",
                verbose_name="Autorizado",
            ),
        ),
        migrations.AlterField(
            model_name="alteracaopasu",
            name="autorizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="O servidor (Chefe) que autorizaou essa parcela",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="autorizacoes_ferias",
                to="rh.Servidor",
                verbose_name="Autorizado por",
            ),
        ),
        migrations.AlterField(
            model_name="alteracaopasu",
            name="justificativa",
            field=models.TextField(
                help_text="Justificativa para a alteração da parcela de ususfruto.",
                verbose_name="Justificativa",
            ),
        ),
        migrations.AlterField(
            model_name="alteracaopasu",
            name="pas",
            field=models.ForeignKey(
                blank=True,
                help_text="Alteração de parcelas de um servidor em um determinado período aquisitivo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alteracoes",
                to="ferias.PeriodoAquisitivoServidor",
                verbose_name="Alteração",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="bloquear_conflitos",
            field=models.BooleanField(
                default=False,
                help_text="Bloquear para marcações conflitantes com todos os substitutos",
                verbose_name="Bloquer conflitos",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="dias_antecedencia_fruicao",
            field=models.SmallIntegerField(
                blank=True,
                default=15,
                help_text="Dias de antecedência entre a marcação/alteração e a fruição",
                verbose_name="Antecedência fruição (dias)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="dias_por_periodo",
            field=models.SmallIntegerField(
                default="30",
                help_text="Quantidade de dias máxima que pode ser usufruído em um período.",
                verbose_name="Dias por período",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="exigir_autorizacao_chefia_mediata",
            field=models.BooleanField(
                default=False,
                help_text="Se é necessário que a chefia mediata autorize após a chefia imediata",
                verbose_name="Autorizacao chefia mediata",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="max_divisoes",
            field=models.SmallIntegerField(
                default=2,
                help_text="Quantidade máxima de divisões que um período de férias pode ser usufruído.",
                verbose_name="Máximo de divisões",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="meses_exercicio",
            field=models.SmallIntegerField(
                blank=True,
                default=12,
                help_text="Tempo de exercício, em meses, para adquirir direito a fruição de um periodo de férias",
                verbose_name="Tempo de exercício (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="meses_max_fruicao",
            field=models.SmallIntegerField(
                default=12,
                help_text="Tempo máximo (em meses) para o gozo dos dias de férias. OBS.: XX meses - 1 dia",
                verbose_name="Máximo fruição (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="meses_prescricao",
            field=models.SmallIntegerField(
                default=24,
                help_text="Tempo máximo (em meses) para o gozo dos dias de férias, antes de prescreverem.",
                verbose_name="Prescrição (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="min_dias_por_divisao",
            field=models.SmallIntegerField(
                default="10",
                help_text="Quantidade mínima de dias que pode ser dividida o período de usufruto.",
                verbose_name="Quantidade mínimo de dias por divisão",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="modo",
            field=models.CharField(
                choices=[("CONTINUO", "Contínuo"), ("ANUAL", "Anual")],
                default="CONTINUO",
                help_text="Modo de avaliação do período aquisitivo. ANUAL: perído por ano.\n            CONTINUO: período de acordo com a data de exercício do servidor.",
                max_length=30,
                verbose_name="Modo de aquisição",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="nome",
            field=models.CharField(
                help_text="Identificação da configuração",
                max_length=100,
                unique=1,
                verbose_name="Nome",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="quantidade_periodos",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Único"),
                    (2, "Semestre"),
                    (3, "Quadrimestre"),
                    (4, "Trimestre"),
                ],
                default=1,
                help_text="Quantidade de períodos em um ano (12 meses).Ex.: Servidor = 1 periodo por ano (12 meses), Membro= 2 períodos por ano",
                verbose_name="Períodos",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="tipo_servidor",
            field=models.CharField(
                choices=[("S", "Servidor"), ("M", "Membro")],
                default="SERVIDOR",
                help_text="Para qual tipo de servidor será aplicada essa configuração de férias.",
                max_length=30,
                verbose_name="Tipo de servidor",
            ),
        ),
        migrations.AlterField(
            model_name="pasualteracao",
            name="justificativa",
            field=models.TextField(
                help_text="Justificativa para a alteração da parcela de ususfruto.",
                verbose_name="Justificativa",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="bloqueado",
            field=models.BooleanField(
                default=False,
                help_text="Os servidores não poderão utilizar esse período. Ex.: Criação de período anteriores.",
                verbose_name="Bloqueado",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="configuracao",
            field=models.ForeignKey(
                help_text="A configuração de férias utilizado para esse período aquisitivo.",
                on_delete=django.db.models.deletion.PROTECT,
                to="ferias.Configuracao",
                verbose_name="Configuração de férias",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="data_fim_prev",
            field=models.DateField(
                blank=True,
                help_text="Data para finalização das marcações de férias.",
                null=True,
                verbose_name="Final de Previsão",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="data_homologacao_prev",
            field=models.DateField(
                blank=True,
                help_text="Data prevista para homologação do período aquisitivo.",
                null=True,
                verbose_name="Data de Homologação",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="data_inicio_prev",
            field=models.DateField(
                help_text="Data para início das marcações de férias.",
                verbose_name="Início de Previsão",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="mes_fruicao",
            field=models.SmallIntegerField(
                choices=[
                    (1, "JANEIRO"),
                    (2, "FEVEREIRO"),
                    (3, "MARÇO"),
                    (4, "ABRIL"),
                    (5, "MAIO"),
                    (6, "JUNHO"),
                    (7, "JULHO"),
                    (8, "AGOSTO"),
                    (9, "SETEMBRO"),
                    (10, "OUTUBRO"),
                    (11, "NOVEMBRO"),
                    (12, "DEZEMBRO"),
                    (14, "-------------"),
                ],
                default=14,
                help_text="Mês para fruição coletiva, caso haja",
                verbose_name="Mês de fruição",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="periodo",
            field=models.SmallIntegerField(
                default=1,
                help_text="Período (único/semestre/quadrimestre) do ano que gerou esse período aquisitivo quando as férias são anuais.\n            Ex.: 2 -> para férias anuais com período aquisitivo no segundo semestre do ano.",
                verbose_name="Período",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivo",
            name="periodo_anterior",
            field=models.BooleanField(
                default=False,
                help_text="Informa se o período é anterior à data atual. Deve ser usado para períodos anteriores à utilização do sistema",
                verbose_name="Antigo",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidor",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidor",
            name="data_referencia",
            field=models.DateField(
                blank=True,
                help_text="Data de referencia para o calculo do período aquisitivo .",
                verbose_name="Data de referência",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidor",
            name="estado",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Aguardando Liberação p/ Marcação"),
                    (2, "Em Andamento"),
                    (4, "Concluída"),
                    (8, "Indenizado Total ou Parcialmente"),
                ],
                default=1,
                help_text="Situação atual desse período aquisitivo",
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidor",
            name="periodo_aquisitivo",
            field=models.ForeignKey(
                help_text="O período aquisitivo refente a que o servidor tem direito.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paservidores",
                to="ferias.PeriodoAquisitivo",
                verbose_name="Período aquisitivo",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidor",
            name="servidor",
            field=models.ForeignKey(
                help_text="O servidor que pode marcar férias para o período aquisitivo solicitado.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos_aquisitivos",
                to="rh.Servidor",
                verbose_name="Servidor",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="autorizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="O servidor (Chefe) que autorizou essa parcela",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ferias_autorizadas",
                to="rh.Servidor",
                verbose_name="Autorizado por",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="data_fim_cache",
            field=models.DateField(
                blank=True,
                help_text="Data fim da fruição desse período de férias.",
                null=True,
                verbose_name="Data Fim Cache",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="data_inicio",
            field=models.DateField(
                help_text="Início da fruição desse período de férias.",
                verbose_name="Início",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="data_prevista_fim",
            field=models.DateField(
                blank=True,
                help_text="Data prevista de fim da fruição desse período de férias.",
                null=True,
                verbose_name="Prevista de Fim",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="estado",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Inclusão solicitada"),
                    (2, "Autorizado"),
                    (4, "Homologado"),
                    (16, "Alterado"),
                    (8, "Alteração solicitada"),
                    (32, "Interrompido"),
                    (64, "Suspenso"),
                    (128, "Em fruição"),
                    (256, "Usufruído"),
                    (512, "Não autorizado"),
                    (1024, "Substituto"),
                ],
                default=1,
                help_text="Situação atual",
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="periodo_aquisitivo_servidor",
            field=models.ForeignKey(
                help_text="O período aquisitivo refente a que o servidor tem direito.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usufrutos",
                to="ferias.PeriodoAquisitivoServidor",
                verbose_name="Período aquisitivo",
            ),
        ),
        migrations.AlterField(
            model_name="periodoaquisitivoservidorusufruto",
            name="suspenso_por",
            field=models.ForeignKey(
                blank=True,
                help_text="O servidor que suspenendeu essa parcela",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ferias_suspensas",
                to="rh.Servidor",
                verbose_name="Suspenso por",
            ),
        ),
    ]
