# Generated by Django 2.2.28 on 2023-09-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0265_auto_20230906_1621"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaAntiguidadeMembros",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ordem_antiguidade",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Ordem de Antiguidade"
                    ),
                ),
                (
                    "data_inicio_carreira",
                    models.DateField(null=True, verbose_name="Início na Carreira"),
                ),
                (
                    "data_inicio_instancia",
                    models.DateField(
                        null=True, verbose_name="Data Início na Instância"
                    ),
                ),
                (
                    "tempo_afastamento",
                    models.IntegerField(null=True, verbose_name="Tempo de Afastamento"),
                ),
                (
                    "tempo_total_instancia",
                    models.IntegerField(
                        null=True, verbose_name="Tempo Total na Instância"
                    ),
                ),
                (
                    "tempo_efetivo_exercicio",
                    models.IntegerField(
                        null=True, verbose_name="Tempo de Efetivo Exercício"
                    ),
                ),
                (
                    "tempo_total_carreira",
                    models.IntegerField(
                        null=True, verbose_name="Tempo Total de Carreira"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        blank=True,
                        choices=[("Manual", "MANUAL"), ("Job", "JOB")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tipo_cargo",
                    models.IntegerField(
                        choices=[
                            (1, "PROCURADOR"),
                            (2, "PROMOTOR"),
                            (3, "PROMOTOR SUBSTITUTO"),
                        ],
                        null=True,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antiguidade",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo_cargo", "ordem_antiguidade"],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
