# -*- coding: utf-8 -*-


__PREFIXO = "MP"

Config = {
    # Registro do Tipo 0
    "reg-00": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "versao": "2011",
            "lenght": 551,
        },
        1: {"label": "sequencial", "value": 0, "size": 6, "type": "N"},
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {"label": "prefixo", "value": __PREFIXO, "size": 2, "type": "A"},
        4: {"label": "tipo_registro", "value": 0, "size": 1, "type": "N"},
        5: {"label": "const1", "value": 1, "size": 1, "type": "N"},
        6: {"label": "resp_cpf", "value": 0, "size": 14, "type": "N"},
        7: {"label": "resp_tipo", "value": 4, "size": 1, "type": "N"},
        8: {"label": "resp_razao", "value": "", "size": 40, "type": "A"},
        9: {"label": "resp_logradouro", "value": "", "size": 40, "type": "A"},
        10: {"label": "resp_numero", "value": 0, "size": 6, "type": "N"},
        11: {"label": "resp_complemento", "value": "", "size": 21, "type": "A"},
        12: {"label": "resp_bairro", "value": "", "size": 19, "type": "A"},
        13: {"label": "resp_cep", "value": "", "size": 8, "type": "A"},
        14: {"label": "resp_cod_municipio", "value": 0, "size": 7, "type": "N"},
        15: {"label": "resp_municipio", "value": "", "size": 30, "type": "A"},
        16: {"label": "resp_uf", "value": "", "size": 2, "type": "A"},
        17: {"label": "resp_fone_ddd", "value": 63, "size": 2, "type": "N"},
        18: {"label": "resp_fone", "value": 32167600, "size": 9, "type": "N"},
        19: {"label": "indicador_retificadora", "value": 2, "size": 1, "type": "N"},
        20: {"label": "data_retificadora", "value": 0, "size": 8, "type": "N"},
        21: {"label": "data_geracao", "value": 0, "size": 8, "type": "N"},
        22: {"label": "resp_email", "value": "", "size": 45, "type": "A"},
        23: {"label": "resp_nome", "value": "", "size": 52, "type": "A"},
        24: {"label": "filer1", "value": "", "size": 24, "type": "A"},
        25: {"label": "resp_cpf", "value": 0, "size": 11, "type": "N"},
        26: {"label": "resp_crea", "value": 0, "size": 12, "type": "N"},
        27: {"label": "resp_nascimento", "value": 0, "size": 8, "type": "N"},
        28: {"label": "filer2", "value": "", "size": 159, "type": "A"},
    },
    # Registro do Tipo 1
    "reg-01": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "versao": "2011",
            "lenght": 551,
        },
        1: {"label": "sequencial", "value": 0, "size": 6, "type": "N"},
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {"label": "prefixo", "value": __PREFIXO, "size": 2, "type": "A"},
        4: {"label": "tipo_registro", "value": 1, "size": 1, "type": "N"},
        5: {"label": "razao", "value": "", "size": 52, "type": "A"},
        6: {"label": "logradouro", "value": "", "size": 40, "type": "A"},
        7: {"label": "numero", "value": 0, "size": 6, "type": "N"},
        8: {"label": "complemento", "value": "", "size": 21, "type": "A"},
        9: {"label": "bairro", "value": "", "size": 19, "type": "A"},
        10: {"label": "cep", "value": "", "size": 8, "type": "A"},
        11: {"label": "cod_municipio", "value": 0, "size": 7, "type": "N"},
        12: {"label": "municipio", "value": "", "size": 30, "type": "A"},
        13: {"label": "uf", "value": "", "size": 2, "type": "A"},
        14: {"label": "fone_ddd", "value": 63, "size": 2, "type": "N"},
        15: {"label": "fone", "value": 32167600, "size": 9, "type": "N"},
        16: {"label": "email", "value": "drtfolha@mpto.mp.br", "size": 45, "type": "A"},
        17: {"label": "cnae", "value": 8424800, "size": 7, "type": "N"},
        18: {"label": "naturezajuridica", "value": 1082, "size": 4, "type": "N"},
        19: {"label": "num_proprietario", "value": 0, "size": 4, "type": "N"},
        20: {"label": "data_base", "value": 5, "size": 2, "type": "N"},
        21: {"label": "tipo_inscricao", "value": 1, "size": 1, "type": "N"},
        22: {"label": "tipo_rais", "value": 0, "size": 1, "type": "N"},
        23: {"label": "filer1", "value": 0, "size": 2, "type": "N"},
        24: {"label": "cei_vinculado", "value": 0, "size": 12, "type": "N"},
        25: {"label": "ano_base", "value": 0, "size": 4, "type": "N"},
        26: {"label": "porte", "value": 3, "size": 1, "type": "N"},
        27: {"label": "optante_simples", "value": 2, "size": 1, "type": "N"},
        28: {"label": "pat", "value": 2, "size": 1, "type": "N"},
        29: {"label": "pat_lte_5min", "value": 0, "size": 6, "type": "N"},
        30: {"label": "pat_gt_5min", "value": 0, "size": 6, "type": "N"},
        31: {"label": "pct_servico", "value": 0, "size": 3, "type": "N"},
        32: {"label": "pct_cozinha", "value": 0, "size": 3, "type": "N"},
        33: {"label": "pct_refeicao", "value": 0, "size": 3, "type": "N"},
        34: {"label": "pct_refeicao_transportada", "value": 0, "size": 3, "type": "N"},
        35: {"label": "pct_cesta_alimento", "value": 0, "size": 3, "type": "N"},
        36: {"label": "pct_alimento_convenio", "value": 0, "size": 3, "type": "N"},
        37: {"label": "indica_encerramento", "value": 2, "size": 1, "type": "N"},
        38: {"label": "data_encerramento", "value": 0, "size": 8, "type": "N"},
        39: {"label": "patronal_associativo_cnpj", "value": 0, "size": 14, "type": "N"},
        40: {
            "label": "patronal_associativo_valor",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        41: {"label": "patronal_tributo_cnpj", "value": 0, "size": 14, "type": "N"},
        42: {
            "label": "patronal_tributo_valor",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        43: {
            "label": "patronal_assistencial_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        44: {
            "label": "patronal_assistencial_valor",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        45: {
            "label": "patronal_confederativo_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        46: {
            "label": "patronal_confederativo_valor",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        47: {"label": "em_atividade_anobase", "value": 1, "size": 1, "type": "N"},
        48: {
            "label": "centraliza_contribuicao_sindical",
            "value": 2,
            "size": 1,
            "type": "N",
        },
        49: {
            "label": "contribuicao_sindical_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        50: {"label": "filiado_sindicato", "value": 2, "size": 1, "type": "N"},
        51: {"label": "sistema_ponto", "value": 6, "size": 2, "type": "N"},
        52: {"label": "filer2", "value": "", "size": 85, "type": "A"},
        53: {"label": "filer3", "value": "", "size": 12, "type": "A"},
    },
    # Registro do Tipo 1
    "reg-02": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "versao": "2011",
            "lenght": 551,
        },
        1: {"label": "sequencial", "value": 0, "size": 6, "type": "N"},
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {"label": "prefixo", "value": __PREFIXO, "size": 2, "type": "A"},
        4: {"label": "tipo_registro", "value": 2, "size": 1, "type": "N"},
        5: {"label": "pasep", "value": 0, "size": 11, "type": "N"},
        6: {"label": "nome", "value": "", "size": 52, "type": "A"},
        7: {"label": "data_nascimento", "value": 0, "size": 8, "type": "N"},
        8: {"label": "nacionalidade", "value": 0, "size": 2, "type": "N"},
        9: {"label": "ano_chegada_pais", "value": 0, "size": 4, "type": "N"},
        10: {"label": "grau_instrucao", "value": 0, "size": 2, "type": "N"},
        11: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        12: {"label": "ctps_numero", "value": 0, "size": 8, "type": "N"},
        13: {"label": "ctps_serie", "value": "", "size": 5, "type": "A"},
        14: {"label": "data_admissao", "value": 0, "size": 8, "type": "N"},
        15: {"label": "tipo_admissao", "value": 0, "size": 2, "type": "N"},
        16: {
            "label": "salario_contratual",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        17: {"label": "tipo_salario_contratual", "value": 1, "size": 1, "type": "N"},
        18: {"label": "horas_semanais", "value": 0, "size": 2, "type": "N"},
        19: {"label": "cbo", "value": 0, "size": 6, "type": "N"},
        20: {"label": "vinculo_empregaticio", "value": 0, "size": 2, "type": "N"},
        21: {"label": "codigo_desligamento", "value": 0, "size": 2, "type": "N"},
        22: {"label": "data_desligamento", "value": 0, "size": 4, "type": "N"},
        23: {
            "label": "remuneracao_01",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        24: {
            "label": "remuneracao_02",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        25: {
            "label": "remuneracao_03",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        26: {
            "label": "remuneracao_04",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        27: {
            "label": "remuneracao_05",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        28: {
            "label": "remuneracao_06",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        29: {
            "label": "remuneracao_07",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        30: {
            "label": "remuneracao_08",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        31: {
            "label": "remuneracao_09",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        32: {
            "label": "remuneracao_10",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        33: {
            "label": "remuneracao_11",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        34: {
            "label": "remuneracao_12",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        35: {
            "label": "adiantamento_13",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        36: {"label": "mes_adiantamento_13", "value": 0, "size": 2, "type": "N"},
        37: {
            "label": "remuneracao_13",
            "value": 0,
            "size": 9,
            "type": "N",
            "decimal": 2,
        },
        38: {"label": "mes_13", "value": 0, "size": 2, "type": "N"},
        39: {"label": "raca_cor", "value": 0, "size": 1, "type": "N"},
        40: {"label": "indicador_deficiencia", "value": 0, "size": 1, "type": "N"},
        41: {"label": "tipo_deficiencia", "value": 0, "size": 1, "type": "N"},
        42: {"label": "indicador_alvara", "value": 2, "size": 1, "type": "N"},
        43: {"label": "aviso_previo", "value": 0, "size": 9, "type": "N", "decimal": 2},
        44: {"label": "sexo", "value": 0, "size": 1, "type": "N"},
        45: {"label": "afastamento_1_motivo", "value": 0, "size": 2, "type": "N"},
        46: {"label": "afastamento_1_inicio", "value": 0, "size": 4, "type": "N"},
        47: {"label": "afastamento_1_fim", "value": 0, "size": 4, "type": "N"},
        48: {"label": "afastamento_2_motivo", "value": 0, "size": 2, "type": "N"},
        49: {"label": "afastamento_2_inicio", "value": 0, "size": 4, "type": "N"},
        50: {"label": "afastamento_2_fim", "value": 0, "size": 4, "type": "N"},
        51: {"label": "afastamento_3_motivo", "value": 0, "size": 2, "type": "N"},
        52: {"label": "afastamento_3_inicio", "value": 0, "size": 4, "type": "N"},
        53: {"label": "afastamento_3_fim", "value": 0, "size": 4, "type": "N"},
        54: {
            "label": "afastamento_quantidade_dias",
            "value": 0,
            "size": 3,
            "type": "N",
        },
        55: {
            "label": "ferias_indenizado",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        56: {
            "label": "banco_de_horas_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        57: {"label": "banco_de_horas_qnt_meses", "value": 0, "size": 2, "type": "N"},
        58: {
            "label": "dicidio_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        59: {"label": "dicidio_qnt_meses", "value": 0, "size": 2, "type": "N"},
        60: {"label": "gratificacao_valor", "value": 0, "size": 8, "type": "N"},
        61: {"label": "gratificacao_meses", "value": 0, "size": 2, "type": "N"},
        62: {
            "label": "valor_recisao",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        63: {
            "label": "contribuicao_associativo_1_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        64: {
            "label": "contribuicao_associativo_1_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        65: {
            "label": "contribuicao_associativo_2_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        66: {
            "label": "contribuicao_associativo_2_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        67: {"label": "contribuicao_tributo_cnpj", "value": 0, "size": 14, "type": "N"},
        68: {
            "label": "contribuicao_tributo_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        69: {
            "label": "contribuicao_assistencial_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        70: {
            "label": "contribuicao_assistencial_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        71: {
            "label": "contribuicao_confederativo_cnpj",
            "value": 0,
            "size": 14,
            "type": "N",
        },
        72: {
            "label": "contribuicao_confederativo_valor",
            "value": 0,
            "size": 8,
            "type": "N",
            "decimal": 2,
        },
        73: {"label": "municipio_trabalho", "value": 0, "size": 7, "type": "N"},
        74: {"label": "hora_extra_01", "value": 0, "size": 3, "type": "N"},
        75: {"label": "hora_extra_02", "value": 0, "size": 3, "type": "N"},
        76: {"label": "hora_extra_03", "value": 0, "size": 3, "type": "N"},
        77: {"label": "hora_extra_04", "value": 0, "size": 3, "type": "N"},
        78: {"label": "hora_extra_05", "value": 0, "size": 3, "type": "N"},
        79: {"label": "hora_extra_06", "value": 0, "size": 3, "type": "N"},
        80: {"label": "hora_extra_07", "value": 0, "size": 3, "type": "N"},
        81: {"label": "hora_extra_08", "value": 0, "size": 3, "type": "N"},
        82: {"label": "hora_extra_09", "value": 0, "size": 3, "type": "N"},
        83: {"label": "hora_extra_10", "value": 0, "size": 3, "type": "N"},
        84: {"label": "hora_extra_11", "value": 0, "size": 3, "type": "N"},
        85: {"label": "hora_extra_12", "value": 0, "size": 3, "type": "N"},
        86: {"label": "filiado_sindicato", "value": 2, "size": 1, "type": "N"},
        87: {"label": "aprendiz_gravida", "value": 2, "size": 1, "type": "N"},
        88: {"label": "trabalho_parcial", "value": 2, "size": 1, "type": "N"},
        89: {"label": "teletrabalho", "value": 2, "size": 1, "type": "N"},
        90: {"label": "trabalho_intermitente", "value": 2, "size": 1, "type": "N"},
        91: {"label": "filer1", "value": "", "size": 8, "type": "A"},
    },
    # Registro do Tipo 9
    "reg-09": {
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "versao": "2011",
            "lenght": 551,
        },
        1: {"label": "sequencial", "value": 0, "size": 6, "type": "N"},
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {"label": "prefixo", "value": __PREFIXO, "size": 2, "type": "A"},
        4: {"label": "tipo_registro", "value": 9, "size": 1, "type": "N"},
        5: {"label": "count_tipo_1", "value": 0, "size": 6, "type": "N"},
        6: {"label": "count_tipo_2", "value": 0, "size": 6, "type": "N"},
        7: {"label": "filer1", "value": "", "size": 516, "type": "A"},
    },
}
