# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gfp", "0106_auto_20230112_1053"),
        ("pensao", "0004_auto_20161111_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="pensao",
            name="event_employee_13",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pensions_as_event_employee_13",
                to="gfp.Evento",
                verbose_name="Evento no servidor",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="event_employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pensions_as_event_employee",
                to="gfp.Evento",
                verbose_name="Evento no servidor",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="event_pensioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pensions_as_event_pensioner",
                to="gfp.Evento",
                verbose_name="Evento no pensionista",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="pensionista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pensao_pensionista",
                to="rh.PessoaFisica",
                verbose_name="Pensionista",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="publicacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pensao_publicacao",
                to="rh.Publicacao",
                verbose_name="Publicação",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="representante_legal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pensao_representante_legal",
                to="rh.PessoaFisica",
            ),
        ),
        migrations.AlterField(
            model_name="pensao",
            name="servidor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pensao_pagador",
                to="rh.Servidor",
                verbose_name="Servidor",
            ),
        ),
    ]
