# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, b"Descartavel"),
                            (2, b"Permanente"),
                            (100, b"Invalidada"),
                        ]
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="have_jwt_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="jwt.Voucher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisposableVoucher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("jwt.voucher",),
        ),
    ]
