# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_type",
            field=models.SmallIntegerField(
                choices=[(1, "Descartavel"), (2, "Permanente"), (100, "Invalidada")]
            ),
        ),
    ]
