# Generated by Django 2.2.28 on 2022-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsecurity", "0008_auto_20220420_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentbond",
            name="function_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Função"
            ),
        ),
    ]
