# Generated by Django 2.2.28 on 2022-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsecurity", "0009_employmentbond_function_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentbond",
            name="purpose",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Previdenciário e Antiguidade"),
                    (2, "Previdenciário"),
                    (3, "Antiguidade"),
                ],
                null=True,
                verbose_name="Para Fins",
            ),
        ),
    ]
