# Generated by Django 2.2.28 on 2023-03-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialsecurity", "0011_auto_20230315_1202"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmentbond",
            name="transparency_portal",
        ),
    ]
