# Generated by Django 2.2.28 on 2023-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialsecurity", "0012_remove_employmentbond_transparency_portal"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentbond",
            name="raw_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Tempo Bruto"
            ),
        ),
    ]
