# -*- coding: utf-8 -*-
import re
import os
import json
import codecs
import importlib


# try:
#     import cStringIO as io
# except ImportError:
#     import StringIO as io

from django.core.management.base import BaseCommand
from contrib.utils import getLogger
from django.contrib.contenttypes.models import ContentType
from django.db import models
from default.management.commands import extractors

log = getLogger(__name__)


TEMPLATES = {
    "case-rest-autocompletefield": """
if '%(name)s' in params:
    if params.get('%(name)s') != '':
        field = getattr(self.Model, '%(name)s')

        # mater compatibilidade com django-1.4.x
        get_queryset = field.get_queryset
        query = get_queryset()

        try:
            params.update(
                %(name)s=query.get(pk=params.get('%(name)s'))
            )
        except Exception as e:
            log.exception(e)
            raise e
    else:
        params.update(%(name)s=None)""",
    "case-checkboxfield": """if '%(name)s' in params:
    params.update(%(name)s=params.get('%(name)s', 'off').lower() == 'on')""",
    "case-datefield": """
if '%(name)s' in params:
    if params.get('%(name)s') != '':
        params.update(%(name)s=DateUtils.str_to_date(params.get('%(name)s')))
    else:
        params.update(%(name)s=None)""",
    "case-datetimefield": """
if '%(name)s' in params:
    if params.get('%(name)s') != '':
        params.update(%(name)s=DateUtils.str_to_datetime(params.get('%(name)s')))
    else:
        params.update(%(name)s=None)""",
    "controller-dry": """# -*- coding: utf-8 -*-
from contrib.newrest import RestfulDRY
from contrib.utils import getLogger
from %(namespace)s.models import %(classname)s


log = getLogger(__name__)


class %(prefix)s%(classname)s(RestfulDRY):

    _model = %(classname)s

    # Tupla com atributos de Model e seus respectivos argumentos de pesquisa utilizados para indexar as buscas.
    # full_text_index = ()

    # Força o tratamento de todos os dados vindos do browser em uppercase.
    # force_upper = True

    # Em caso de delete ou update multi row força utilizar o ORM para realizar as ações.
    # force_orm_single = False

    # primary_key = 'pk'

    # Fields que não serão rastreados pelo model_to_dict e pelo get_params
    # exclude_fields = ['modified_by', 'created_by', 'created_at', 'modified_at']

    # Persistirá como False os booleans listados aqui que não estão presentes no @querydict de get_param(self, querydict, check_case).
    # Normalmente acontece com checkboxes e radiobutton não checkados no formulário
    # force_persist_boolean_fields = []

    # Persistirá como vazios os m2m listados que não vierem no request. Este é o caso de "selects" vazios comitados
    # force_persist_clear_m2m = []

    def json(self, args=[]):
        self.response['content-type'] = 'text/javascript'
        self.response.write('Ext._create("%(namespace)s.%(classname)sManage")')

""",
    "controller": """# -*- coding: utf-8 -*-
from contrib.newrest import Restful
from contrib.utils import getLogger
from %(namespace)s.models import %(classname)s
%(imports)s


log = getLogger(__name__)


class %(prefix)s%(classname)s(Restful):

    _model = %(classname)s

    def get_params(self, *args, **kargs):
        params = Restful.get_params(self, *args, **kargs)
        %(cases)s

        return params

    def model_to_dict(self, instance):
        rst = Restful.model_to_dict(self, instance)

        rst.update(
%(fields)s
        )

        return rst
""",
    "rest": """/** autogenerated **/
/**
 *
 **/
Ext._define('%(namespace)s.%(classname)sRestful', {
    extend: 'core.Restful',

    resource: '%(prefix)s%(classname)s',

    getFields: function(cfg) {
        if(!this._fields)
            this._fields = %(namespace)s.%(classname)sRestful.superclass.getFields.call(this, cfg).concat(%(fields)s);

        return this._fields;
    }
});
""",
    "window": """/** autogenerated **/
/**
 *
 **/
Ext._define('%(namespace)s.%(classname)sWindow', {
    extend: 'core.RestfulWindow',

    rest: '%(namespace)s.%(classname)sRestful',

    getFormPanel: function(cfg) {
        if(!this._formPanel)
            this._formPanel = Ext._create('Ext.form.FormPanel', {
                border: false,
                frame: true,
                items: %(fields)s
            });

        return this._formPanel;
    }
});

""",
    "grid": """/** autogenerated **/
/**
 *
 **/
Ext._define('%(namespace)s.%(classname)sGrid', {
    extend: 'core.RestfulGrid',

    restWindow: '%(namespace)s.%(classname)sWindow',

    getColumnModel: function() {
        if(!this._columnModel)
            this._columnModel = Ext._create(
                'Ext.grid.ColumnModel',
                [
                    Ext._create('Ext.grid.RowNumberer'),
                    {header: 'Cod', dataIndex: 'pk', width: 50, hidden: true},
                    {header: 'Descricao', dataIndex: 'unicode', id: 'autoExpandColumn'},
                    %(column)s
                ]
            );

        return this._columnModel;
    }
});

core.RestfulGrid.register(
    '%(namespace)s.%(classname)sRestful',
    '%(namespace)s.%(classname)sGrid'
);

""",
    "panel": """/** autogenerated **/
""",
    "m1": """/** autogenerated **/
Ext._define('%(namespace)s.%(classname)sManage', {
    extend: 'toolkit.widget.TabPanel',

    get%(classname)sGrid: function() {
        if(!this._grid) {
            this._grid = Ext._create('%(namespace)s.%(classname)sGrid', {
                region: 'center',
                gridAutoLoad: false
            });
        }

        return this._grid;
    },

    constructor: function(cfg) {
        cfg = core.nullValue(cfg, {});

        Ext.applyIf(
            cfg,
            {
                title: '%(classname)s'
            }
        );

        Ext.apply(
            cfg,
            {
                layout: 'border',
                items: [
                    this.get%(classname)sGrid(),
                ]
            }
        );

        %(namespace)s.%(classname)sManage.superclass.constructor.call(this, cfg);
    }
});

""",
}


class Command(BaseCommand):

    can_import_settings = True

    def add_arguments(self, parser):
        parser.add_argument(
            "-m",
            "--model",
            dest="model",
            default="",
            help="App name and model name with identify the model.",
        )

        parser.add_argument(
            "-p", "--prefix", dest="prefix", help="Prefix name of the controller."
        )

        parser.add_argument(
            "--with-package",
            dest="with_package",
            action="store_true",
            help="Use package instead module.",
        )

        parser.add_argument(
            "--without-rest",
            dest="without_rest",
            action="store_true",
            default=False,
            help="Doesn't create Restful JS and RestfulController.",
        )

        parser.add_argument(
            "--without-window",
            dest="without_window",
            action="store_true",
            default=False,
            help="Doesn't create window of restful",
        )

        parser.add_argument(
            "--without-grid",
            dest="without_grid",
            action="store_true",
            default=False,
            help="Doesn't create Grid for restful.",
        )

        parser.add_argument(
            "--with-manager",
            dest="with_manager",
            action="store_true",
            help="Create manage panel for restful.",
        )

        parser.add_argument(
            "-d",
            "--destination",
            dest="destination",
            default=None,
            help="Use package in place of module.",
        )

        parser.add_argument(
            "-n",
            "--namespace",
            dest="namespace",
            default=None,
            help="Namespace for Javascript files.",
        )

        parser.add_argument(
            "--without-dry",
            dest="nodry",
            default=False,
            action="store_true",
            help="Not using RestfulDRY for the controller template.",
        )

        parser.add_argument(
            "--overwrite",
            dest="overwrite",
            default=False,
            action="store_true",
            help="Force overwrite if file exist.",
        )

    re_app = re.compile(
        r"^(?P<app_label>([a-z]|_)+)\.(?P<model>([a-zA-Z]{1}[a-zA-Z0-9|_]+))$"
    )

    table = {}

    def create_module(self, path):
        self.create_directory(path)
        initfile = os.path.join(path, "__init__.py")
        os.path.exists(initfile) or open(initfile, "w")

    def create_directory(self, path):
        parts = path.split(os.path.sep)
        parent_dir = os.path.sep.join(parts[:-1])
        dirname = parts[-1]

        if os.path.isdir(parent_dir) is False:
            self.create_directory(parent_dir)

        if os.path.isdir(path) is False:
            os.mkdir(path)
            return True
        else:
            return False

    @classmethod
    def register(klass, field, extract):
        klass.table.update({field: extract})

    def get_namespace(self, Model, namespace=None, **kargs):
        if namespace is None:
            namespace = ".".join(Model.__module__.split(".")[:-1])
        return namespace

    def get_destination_path(self, destination, namespace):
        current_dir = os.getcwd()

        tmp = destination.replace(os.path.sep, ".")
        if namespace.startswith(tmp):
            namespace = namespace[len(tmp) + 1 :]

        return os.path.sep.join(
            [current_dir, destination, "static", namespace.replace(".", os.path.sep)]
        )

    def translate(self, Field):
        fn = self.table.get(Field.__class__, None)

        if fn is None:
            log.warn("Not found type for %s with type %s", Field.name, Field.__class__)
        else:
            log.debug([Field.__class__, fn])

        return fn if fn is not None else extractors.defaultfield

    def extract_field_config(self, Field):
        fn = self.translate(Field)

        return fn(Field)

    def extract_field(self, Model):
        rst = {}

        for field in [
            field
            for field in Model._meta.fields
            if not isinstance(field, models.AutoField)
        ]:
            rst.update(**{field.name: self.extract_field_config(field)})

        return rst

    def indent(self, text, number, indent=4, skip_indent_first_line=True):
        lines = text.split("\n")

        indented_lines = []
        for line in lines:
            if skip_indent_first_line and line == lines[0]:
                indented_lines.append(line)
            else:
                indented_lines.append("".join([(" " * (4 * number)), line]))

        return "\n".join(indented_lines)

    def rest_config(self, conf, clear_key=False):
        fields = []

        for name, value in list(conf.get("rest", {}).get("fields", {}).items()):
            fields += value.get("field", [])

        if clear_key:
            fields_ = re.sub(
                r"\"(?P<key>\w+)\"\:",
                r"\1:",
                self.indent(json.dumps(fields, indent=4), 3),
            )
        else:
            fields_ = self.indent(json.dumps(fields, indent=4), 3)

        rst = {
            "api_path": conf.get("api_path"),
            "namespace": conf.get("rest", {}).get("namespace"),
            "classname": conf.get("rest", {}).get("className"),
            "prefix": conf.get("rest", {}).get("prefix", ""),
            "fields": fields_,
        }

        return rst

    def rest_py_config(self, conf):
        rst = self.rest_config(conf)

        fields = []
        imports = []
        cases = []

        for name, field in list(conf.get("rest", {}).get("fields", {}).items()):
            form_field = field.get("form", {})
            if form_field.get("xtype", "") == "datefield":
                fields.append(
                    "%s%s=nil_date(instance.%s, None)" % ((" " * 4) * 3, name, name)
                )
                imports.append("from contrib.nil import nil_date")
                imports.append("from contrib.utils import DateUtils")
                cases.append(TEMPLATES.get("case-datefield") % {"name": name})
            elif form_field.get("xtype", "") == "rest-autocompletefield":
                fields.append(
                    "%s%s=nil_pk(instance.%s, None)" % ((" " * 4) * 3, name, name)
                )
                fields.append(
                    "%s%s_unicode=nil_unicode(instance.%s, None)"
                    % ((" " * 4) * 3, name, name)
                )
                imports.append("from contrib.nil import nil_pk, nil_unicode")
                cases.append(
                    TEMPLATES.get("case-rest-autocompletefield") % {"name": name}
                )
            elif form_field.get("xtype", "") == "checkbox":
                fields.append("%s%s=instance.%s" % ((" " * 4) * 3, name, name))
                cases.append(TEMPLATES.get("case-checkboxfield") % {"name": name})
            elif form_field.get("xtype", "") == "numberfield" and form_field.get(
                "allowDecimals", False
            ):
                fields.append(
                    "%s%s=float(instance.%s or 0)" % ((" " * 4) * 3, name, name)
                )

            elif form_field.get("xtype", "") == "numberfield" and not form_field.get(
                "allowDecimals", False
            ):
                fields.append(
                    "%s%s=int(instance.%s or 0)" % ((" " * 4) * 3, name, name)
                )
            elif form_field.get("xtype", "") == "tk-datetimefield":
                fields.append(
                    "%s%s=nil_datetime(instance.%s, None)" % ((" " * 4) * 3, name, name)
                )
                imports.append("from contrib.nil import nil_datetime")
                imports.append("from contrib.utils import DateUtils")
                cases.append(TEMPLATES.get("case-datetimefield") % {"name": name})
            elif form_field.get("xtype", "") == "combo":
                fields.append("%s%s=instance.%s" % ((" " * 4) * 3, name, name))
                fields.append(
                    "%s%s_display=nil_display(instance, '%s', None)"
                    % ((" " * 4) * 3, name, name)
                )
                imports.append("from contrib.nil import nil_display")
            else:
                fields.append("%s%s=instance.%s" % ((" " * 4) * 3, name, name))

        rst.update(
            fields=",\n".join(fields),
            imports="\n".join(set(imports)),
            cases=self.indent("\n".join(cases), 2),
        )

        return rst

    def window_config(self, conf):
        rst = self.rest_config(conf)

        rst.update(
            fields=re.sub(
                r"\"(?P<key>\w+)\"\:",
                r"\1:",
                self.indent(
                    json.dumps(
                        [
                            v.get("form", {})
                            for k, v in list(
                                conf.get("rest", {}).get("fields", {}).items()
                            )
                        ],
                        indent=4,
                    ),
                    3,
                ),
            )
        )

        return rst

    def grid_config(self, conf):
        rst = self.rest_config(conf)

        tpl = """{header: '%(fieldLabel)s', dataIndex: '%(name)s', width: 90}"""
        tpls = {
            "checkbox": """{header: '%(fieldLabel)s', dataIndex: '%(name)s_display', width: 90, renderer: function(value) { return (value ? 'SIM' : 'NÃO'); }}""",
            "combo": """{header: '%(fieldLabel)s', dataIndex: '%(name)s_display', width: 120}""",
            "rest-autocompletefield": """{header: '%(fieldLabel)s', dataIndex: '%(name)s_unicode', width: 120}""",
            "datefield": """{header: '%(fieldLabel)s', dataIndex: '%(name)s', width: 90, renderer: Ext.util.Format.dateRenderer('d/m/Y')}""",
            "tk-datetimefield": """{header: '%(fieldLabel)s', dataIndex: '%(name)s', width: 90, renderer: Ext.util.Format.dateRenderer('d/m/Y H:i')}""",
        }

        rst.update(
            column=self.indent(
                ",\n".join(
                    [
                        tpls.get(v.get("form", {}).get("xtype"), tpl)
                        % v.get("form", {})
                        for k, v in list(conf.get("rest", {}).get("fields", {}).items())
                    ]
                ),
                5,
            )
        )

        return rst

    def manage_config(self, conf):
        rst = self.rest_config(conf)

        return rst

    def get_base_filename(self, conf):
        return os.path.sep.join(
            [
                conf.get("destination"),
                conf.get("rest", {}).get("className", "Undefined"),
            ]
        )

    def builder_js_grid(self, conf, overwrite):
        filename = "%sGrid.js" % self.get_base_filename(conf)
        base_filename = None

        print("Creating JavaScript for Grid file in %s" % filename)

        if os.path.exists(filename) and not overwrite:
            base_filename = filename
            filename = "".join([base_filename, ".1"])

        with codecs.open(filename, "w", "utf-8") as filebuffer:
            tpl = TEMPLATES.get("grid")
            filebuffer.write(tpl % self.grid_config(conf))

        if base_filename:
            self.diff(base_filename, filename, base_filename)
            os.unlink(filename)

    def diff(self, base_path, new_path, out_path):
        from django.conf import settings

        diff_options = getattr(settings, "DIFF_OPTIONS", "--qall")
        diff_tool = getattr(settings, "DIFF_TOOL", "kdiff3")

        os.system(
            "%(diff_tool)s %(diff_options)s -o %(out_path)s %(base_path)s %(new_path)s"
            % vars()
        )

    def builder_js_window(self, conf, overwrite):
        filename = "%sWindow.js" % self.get_base_filename(conf)
        base_filename = None

        print("Creating JavaScript for Window file in %s" % filename)

        if os.path.exists(filename) and not overwrite:
            base_filename = filename
            filename = "".join([base_filename, ".1"])

        with codecs.open(filename, "w", "utf-8") as filebuffer:
            tpl = TEMPLATES.get("window")
            filebuffer.write(tpl % self.window_config(conf))

        if base_filename:
            self.diff(base_filename, filename, base_filename)
            os.unlink(filename)

    def builder_js_manage(self, conf, overwrite, type_of_manage="m1"):
        filename = "%sManage.js" % self.get_base_filename(conf)
        base_filename = None

        print("Creating JavaScript for Window file in %s" % filename)

        if os.path.exists(filename) and not overwrite:
            base_filename = filename
            filename = "".join([base_filename, ".1"])

        with codecs.open(filename, "w", "utf-8") as filebuffer:
            tpl = TEMPLATES.get(type_of_manage)
            filebuffer.write(tpl % self.manage_config(conf))

        if base_filename:
            self.diff(base_filename, filename, base_filename)
            os.unlink(filename)

    def builder_js_restful(self, conf, overwrite=False):
        filename = "%sRestful.js" % self.get_base_filename(conf)
        base_filename = None

        print("Creating JavaScript for Restful file in %s" % filename)

        if os.path.exists(filename) and not overwrite:
            base_filename = filename
            filename = "".join([base_filename, ".1"])

        with codecs.open(filename, "w", "utf-8") as filebuffer:
            tpl = TEMPLATES.get("rest")
            filebuffer.write(tpl % self.rest_config(conf, True))

        if base_filename:
            self.diff(base_filename, filename, base_filename)
            os.unlink(filename)

    def builder_py_restful(self, conf, nodry=False, overwrite=False):
        self.create_module(conf.get("api_path"))
        cfg = self.rest_config(conf)
        base_filename = None

        filename = os.path.join(
            cfg.get("api_path"), "%s.py" % cfg.get("classname").lower()
        )

        print("Creating Python for Controller file in %s" % filename)

        if os.path.exists(filename) and not overwrite:
            base_filename = filename
            filename = "".join([base_filename, ".1"])

        with codecs.open(filename, "w", "utf-8") as filebuffer:
            tpl = TEMPLATES.get("controller" if nodry else "controller-dry")
            filebuffer.write(tpl % self.rest_py_config(conf))

        if base_filename:
            self.diff(base_filename, filename, base_filename)
            os.unlink(filename)

    def builder(
        self,
        conf,
        without_rest,
        without_window,
        without_grid,
        nodry,
        overwrite,
        with_manager,
        **kargs
    ):
        if without_rest is False:
            self.builder_js_restful(conf, overwrite)
            self.builder_py_restful(conf, nodry, overwrite)
        if without_window is False:
            self.builder_js_window(conf, overwrite)
        if without_window is False:
            self.builder_js_grid(conf, overwrite)
        if with_manager:
            self.builder_js_manage(conf, overwrite)

    def get_module_path(self, module):
        mod = importlib.import_module(module)
        return os.path.dirname(mod.__file__)

    def extract_from_model(self, Model, namespace, destination, prefix, **kargs):
        api_path = os.path.join(
            self.get_module_path(".".join(Model.__module__.split(".")[:-1])), "api"
        )

        rst = {
            "api_path": api_path,
            "destination": self.get_destination_path(destination, namespace),
            "rest": {
                "prefix": prefix,
                "className": Model.__name__,
                "namespace": namespace,
                "fields": self.extract_field(Model),
            },
        }

        return rst

    def handle(self, model, **kargs):
        rst = self.re_app.match(model)

        if rst is not None:
            params = rst.groupdict()
            for k in params:
                params[k] = params[k].lower()
            print(params)
            try:
                ctype = ContentType.objects.get(**params)
            except ContentType.DoesNotExist:
                print("The model content type not found.")
            else:
                Model = ctype.model_class()
                kargs.update(namespace=self.get_namespace(Model, **kargs))
                conf = self.extract_from_model(Model, **kargs)

                self.create_directory(conf.get("destination"))
                self.builder(conf, **kargs)
        else:
            print("The model identification not match with xxx.")


Command.register(models.DecimalField, extractors.numberfield)
Command.register(models.CharField, extractors.charfield)
Command.register(models.IntegerField, extractors.integerfield)
Command.register(models.SmallIntegerField, extractors.integerfield)
Command.register(models.BigIntegerField, extractors.integerfield)
Command.register(models.EmailField, extractors.charfield)
Command.register(models.BooleanField, extractors.booleanfield)
Command.register(models.DateField, extractors.datefield)
Command.register(models.DateTimeField, extractors.datetimefield)
Command.register(models.ForeignKey, extractors.foreignfield)
