# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_auto_20170327_1739"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "common_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.Common",
                    ),
                ),
            ],
            bases=("web.common",),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="post_child",
                serialize=False,
                to="web.Content",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="web.Category"),
        ),
    ]
