# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordchangerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
