# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_passwordchangerequest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Atualizando em"
            ),
        ),
    ]
