# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_content_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="path",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="web.Category",
            ),
        ),
        migrations.AlterField(
            model_name="common",
            name="slug",
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
