# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_auto_20190909_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="ref_month",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="M\xc3\xaas de refer\xc3\xaancia",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="ref_year",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Ano de refer\xc3\xaancia",
            ),
        ),
    ]
