# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_auto_20190918_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="position",
            field=models.IntegerField(
                blank=True, db_index=True, default=9999, verbose_name="Ordem"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="publication_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Fim da publica\xc3\xa7\xc3\xa3o",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="publication_start",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Inicio da publica\xc3\xa7\xc3\xa3o",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="published_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Data de publica\xc3\xa7\xc3\xa3o",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="views",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                default=0,
                verbose_name="Visualiza\xc3\xa7\xc3\xb5es",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="web.Category"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_ptr",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="post_child",
                serialize=False,
                to="web.Content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="web.Post",
                verbose_name="Subitens",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Texto"),
        ),
    ]
