# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_auto_20190923_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="sites", to="web.Category"
            ),
        ),
    ]
