# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_area_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.IntegerField(
                blank=True, db_index=True, default=9999, verbose_name=b"Ordem"
            ),
        ),
        migrations.AlterField(
            model_name="multimedia",
            name="url_embed",
            field=models.CharField(
                blank=True, db_index=True, default=b"#", max_length=400
            ),
        ),
    ]
