# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-23 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_auto_20191021_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="computed_position",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=b"",
                max_length=20,
                verbose_name=b"Ordem com subn\xc3\xadvel",
            ),
        ),
    ]
