# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_category_computed_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=b"",
                max_length=400,
                verbose_name=b"Url",
            ),
        ),
    ]
