# Generated by Django 2.2.17 on 2021-01-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_auto_20201111_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="items_no_searchable",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                verbose_name="Remover da pesquisa?",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="no_searchable",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                verbose_name="Remover da pesquisa?",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="fullname",
            field=models.CharField(max_length=500, verbose_name="Nome completo"),
        ),
    ]
