# Generated by Django 2.2.18 on 2021-03-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_auto_20210111_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="multimedia",
            name="public_access",
            field=models.BooleanField(default=True, verbose_name="Acesso público"),
        ),
        migrations.AlterField(
            model_name="multimedia",
            name="ged",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="web_media",
                to="ged.Arquivo",
                verbose_name="Arquivo",
            ),
        ),
    ]
