# Generated by Django 2.2.18 on 2021-05-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0022_auto_20210302_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="web_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(
                blank=True, db_index=True, default=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="person_email",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Email"
            ),
        ),
    ]
