# Generated by Django 2.2.22 on 2021-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_auto_20210507_1424"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "permissions": (
                    ("can_disable_comment", "Pode desativar um comentário."),
                )
            },
        ),
    ]
