# Generated by Django 2.2.28 on 2022-08-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("web", "0024_auto_20210514_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="icon_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ged.Arquivo",
            ),
        ),
    ]
