# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_jobprofile_for_activity_statement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobprofile",
            options={
                "permissions": (
                    (
                        "sync_grants_for_user",
                        "Pode sincronizar as permissões para um usuario",
                    ),
                    (
                        "sync_grants_for_user_all_profiles",
                        "Pode sincronizar as permissões de todos os profiles",
                    ),
                )
            },
        ),
    ]
