# Generated by Django 2.2.28 on 2022-10-31 12:25

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.core.management import call_command
import os

FIXTURES = (
    "modelreport/fixtures/initialdb_0001_applications.json",
    "modelreport/fixtures/initialdb_0002_controllers.json",
)


def up(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")
    print("Running forward...")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "rh", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down(apps, schema_editor):
    print("Running backward...")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPDF",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelpdf",
                        to="ged.Arquivo",
                        verbose_name="Modelo PDF",
                    ),
                ),
            ],
        ),
        migrations.RunPython(up, down),
    ]
