# Generated by Django 2.2.28 on 2023-01-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0005_reorganization_of_storage_directory"),
        ("modelreport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelODT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelodt",
                        to="ged.Arquivo",
                        verbose_name="Modelo ODT",
                    ),
                ),
            ],
        ),
    ]
