# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0067_delivery_cancel_delivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rejectionfact",
            old_name="ordinace",
            new_name="rejected_ordinace",
        ),
        migrations.RenameField(
            model_name="supplementordinace",
            old_name="ordinace",
            new_name="supplemented_ordinace",
        ),
    ]
