# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 12:28
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


FIXTURES = ("fixtures/0029-choices-deadline-type.json",)


def up_load_data(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "judicial", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judicial", "0070_sign_attempt_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="recomendation",
            name="deadline",
            field=models.IntegerField(null=True, verbose_name="Prazo"),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="deadline_type",
            field=models.SmallIntegerField(default=1, verbose_name="Tipo do Prazo"),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="finished_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_finisher_recommendation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recomendation",
            name="remaining_days",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deadlinelog",
            name="recomendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="judicial.Recomendation",
            ),
        ),
        migrations.RunPython(up_load_data, down_fake),
        migrations.AlterModelOptions(
            name="partlawsuit",
            options={
                "ordering": ("page_number", "created_at"),
                "permissions": (
                    ("can_sign", "Pode assinar qualquer documento"),
                    (
                        "can_sign_simples",
                        "Pode assinar qualquer documento classificado como simples",
                    ),
                    ("can_unfold_any_document", "Pode desentranhar qualquer documento"),
                ),
            },
        ),
    ]
