# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 14:28
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command


FIXTURES = ("fixtures/0030-tags-system.json",)


def up_load_data(apps, schema_editor):
    BASE_DIR = getattr(settings, "BASE_DIR", "")

    for fixture in FIXTURES:
        filepath = os.path.join(BASE_DIR, "judicial", fixture)
        print('\033[1mRunning loaddata in fixture "%s"\033[0m' % filepath)
        call_command("loaddata", filepath)


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0071_add_fields_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="priority",
            field=models.SmallIntegerField(
                blank=True, default=1, null=True, verbose_name="Prioridade"
            ),
        ),
        migrations.RunPython(up_load_data, down_fake),
    ]
