# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def forward(apps, schema_editor):
    print("\n  Iniciando migração de dados...\n")

    OutCourtLawsuitLog = apps.get_model("judicial", "OutCourtLawsuitLog")
    MovementLog = apps.get_model("judicial", "MovementLog")

    actual_log = None

    for log in OutCourtLawsuitLog.objects.values(
        "lawsuit",
        "part",
        "location",
        signed_by=F("part__signed_by"),
        signed_at=F("part__signed_at"),
    ).order_by("lawsuit__pk", "part__signed_at"):

        if actual_log and actual_log.get("lawsuit") != log.get("lawsuit"):
            actual_log = None

        actual_log = log if not actual_log else actual_log

        if actual_log.get("location") != log.get("location"):
            MovementLog.objects.get_or_create(
                out_court_lawsuit_id=actual_log.get("lawsuit"),
                from_location_id=actual_log.get("location"),
                sended_by_id=actual_log.get("signed_by"),
                sended_at=actual_log.get("signed_at"),
                to_location_id=log.get("location"),
                received_by_id=log.get("signed_by"),
                received_at=log.get("signed_at"),
            )

        actual_log = log

    print("\n  Concluída a migração de dados")


def backward(apps, schema_editor):
    print("\n  Excluindo todos os dados de Movimentação...")
    apps.get_model("judicial", "MovementLog").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0091_loadfixture"),
        ("judicial", "0072_add_priority_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sended_at", models.DateTimeField(verbose_name="Enviado em")),
                (
                    "received_at",
                    models.DateTimeField(null=True, verbose_name="Recebido em"),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="rh.OrgaoGeral",
                        verbose_name="Lota\xe7\xe3o origem",
                    ),
                ),
                (
                    "out_court_lawsuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="judicial.OutCourtLawsuit",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recebido por",
                    ),
                ),
                (
                    "sended_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="rh.OrgaoGeral",
                        verbose_name="Lota\xe7\xe3o destino",
                    ),
                ),
            ],
        ),
        migrations.RunPython(forward, backward),
    ]
