# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 19:01
from __future__ import unicode_literals
import datetime

from django.db import migrations

from dateutil.relativedelta import relativedelta


def up_change_deadline(apps, schema_editor):
    print("change deadline ...")
    count = 0
    JudicialDiligence = apps.get_model("judicial", "JudicialDiligence")
    for jd in JudicialDiligence.objects.filter(
        delivery_status__in=[5, 9], date_delivery__gt="2019-04-05"
    ):
        for manifestation in jd.has_manifestations.filter(signed_by=None):
            if not manifestation.deadline:
                query_attempt = manifestation.diligence.deliveryattempt_set.filter(
                    delivery_date__isnull=False
                )
                if query_attempt.exists():
                    delivery_attempt = query_attempt.get()
                    manifestation.deadline = (
                        delivery_attempt.delivery_date.date()
                        + relativedelta(days=jd.deadline)
                    )
                    remaining_days = (
                        manifestation.deadline - datetime.date.today()
                    ).days
                    if jd.deadline > 0 and remaining_days > 0:
                        manifestation.remaining_days = remaining_days
                    manifestation.save()
                    count += 1

    print("total de manifestações modificadas: {}".format(count))


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0073_movementlog_and_its_data_migration"),
    ]

    operations = [
        migrations.RunPython(up_change_deadline, down_fake),
    ]
