# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judicial", "0074_change_deadline_manifestation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movementlog",
            options={"ordering": ("out_court_lawsuit", "sended_at")},
        ),
        migrations.AlterField(
            model_name="suspenddeadline",
            name="remaining_days",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="movementlog",
            unique_together=set([("out_court_lawsuit", "sended_by", "sended_at")]),
        ),
    ]
