# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judicial", "0076_requestcollaboration"),
    ]

    operations = [
        migrations.AddField(
            model_name="personhasaccess",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Finalizado em"
            ),
        ),
        migrations.AddField(
            model_name="personhasaccess",
            name="finished_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Finalizado por",
            ),
        ),
        migrations.AddField(
            model_name="personhasaccess",
            name="grant_by_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personhasaccess",
            name="revoked_by_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="personhasaccess",
            options={"ordering": ("state", "-created_at")},
        ),
    ]
