# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0077_create_fields_personhasaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judicialdiligence",
            name="execution_organ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diligences",
                to="rh.Lotacao",
            ),
        ),
    ]
