# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 10:57
from __future__ import unicode_literals

import sys

from django.db.models import Count, Max
from django.db import migrations, models
from django.db import transaction
import django.db.models.deletion


def up_fix_codename_part(apps, schema_editor):
    from judicial.models import PartLawsuit

    tuple_types = (
        PartLawsuit.objects.filter(codename_part__isnull=True)
        .values_list("type_part")
        .order_by("type_part")
        .annotate(count_type=Count("type_part"))
        .filter(count_type__gt=0)
    )

    count = len(tuple_types)
    current = 0
    message = ""

    for item in tuple_types:

        current += 1
        sys.stdout.write("\b" * len(message))
        message = " [%d de %d (%0.1f%%)] " % (
            current,
            count,
            ((float(current) / float(count)) * 100.0),
        )
        sys.stdout.write(message)
        sys.stdout.flush()

        typepart, qtd = item
        part = PartLawsuit.objects.filter(type_part=typepart).first()
        PartLawsuit.objects.filter(type_part=typepart).update(
            codename_part=part.my_origin.codename
        )

    sys.stdout.write("Pronto!")


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0079_fix_manifestation_sign"),
    ]

    operations = [
        migrations.AddField(
            model_name="partlawsuit",
            name="codename_part",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(up_fix_codename_part, down_fake),
    ]
