# Generated by Django 2.2.11 on 2020-04-01 17:48

from django.db import migrations
import sys


def update_by_queryset(queryset, name_type):
    from judicial.models import OutCourtLawsuitLog

    count = len(queryset)
    current = 0
    message = ""

    for item in queryset:

        current += 1
        sys.stdout.write("\b" * len(message))
        message = " %s [%d de %d (%0.1f%%)] " % (
            name_type,
            current,
            count,
            ((float(current) / float(count)) * 100.0),
        )
        sys.stdout.write(message)
        sys.stdout.flush()

        logs = OutCourtLawsuitLog.objects.filter(part__pk=item.pk)
        if logs.exists():
            logs.update(initiator_at=item.signed_at)
        else:
            sys.stdout.write("Registrou %s" % item)
            OutCourtLawsuitLog.register(item.lawsuit, item.my_origin)

    sys.stdout.write("\n")


def up_fix_initiator_at_outcourtlawsuit_log(apps, schema_editor):
    from judicial.models import (
        AssessmentNoticeOffice,
        Denunciation,
        OrdinaceReformulated,
    )

    denunciations = Denunciation.objects.filter(
        in_log__initiator_at__isnull=True, signed_at__isnull=False
    )
    ordinaces = OrdinaceReformulated.objects.filter(
        in_log__initiator_at__isnull=True, signed_at__isnull=False
    )
    assessments = AssessmentNoticeOffice.objects.filter(
        in_log__initiator_at__isnull=True, signed_at__isnull=False
    )

    update_by_queryset(denunciations, "denunciations")
    update_by_queryset(ordinaces, "ordinaces")
    update_by_queryset(assessments, "assessments")

    sys.stdout.write("Pronto!")


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0080_add_codename_part"),
    ]

    operations = [
        migrations.RunPython(up_fix_initiator_at_outcourtlawsuit_log, down_fake),
    ]
