# Generated by Django 2.2.12 on 2020-04-15 15:02

import sys

from django.db import migrations
from django.conf import settings


def up_fix_lawsuitmoviment_log(apps, schema_editor):
    from judicial.models import OutCourtLawsuitLog, LawsuitChangeMovimentLog

    query = OutCourtLawsuitLog.objects.filter(
        part__type_part__in=(
            "remittanceinternal",
            "specialremittanceinternal",
            "remittanceitselforgan",
            "triage",
        )
    )

    if settings.DEBUG:
        query = query[:1000]

    count = len(query)
    current = 0
    message = ""

    for item in query:

        current += 1
        sys.stdout.write("\b" * len(message))
        message = " LawsuitLogs [%d de %d (%0.1f%%)] " % (
            current,
            count,
            ((float(current) / float(count)) * 100.0),
        )
        sys.stdout.write(message)
        sys.stdout.flush()

        if item.part.my_origin.change_location_to:
            if type(item.part.my_origin.change_location_to) is list:
                for location in item.part.my_origin.change_location_to:
                    LawsuitChangeMovimentLog.register(item, location)
            else:
                LawsuitChangeMovimentLog.register(
                    item, item.part.my_origin.change_location_to
                )

    print(" {pronto}\n")


def down_fake(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0082_crate_log_moviment_lawsuit"),
    ]

    operations = [
        migrations.RunPython(up_fix_lawsuitmoviment_log, down_fake),
    ]
