# Generated by Django 2.2.12 on 2020-05-11 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0083_migrate_lawsuitlog_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadlinelog",
            name="reverted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
