# Generated by Django 2.2.12 on 2020-05-12 10:07
import sys

from django.db import migrations, models
from judicial.models import OutCourtLawsuitLog, PartLawsuit


def up_remove_corrupted(apps, schema_editor):
    sys.stdout.write("\n    Removing corruped ... ")
    sys.stdout.flush()

    query = (
        OutCourtLawsuitLog.objects.order_by("part_id")
        .values("part_id")
        .annotate(count_part=models.Count("part_id"))
    )
    sys.stdout.write(" (%d) " % query.filter(count_part__gt=1).count())
    sys.stdout.flush()

    to_exclude = OutCourtLawsuitLog.objects.filter(
        part_id__in=query.filter(count_part__gt=1).values("part_id")
    )

    sys.stdout.write(" (%d) " % to_exclude.count())
    sys.stdout.flush()

    to_exclude.delete()

    sys.stdout.write("done")
    sys.stdout.flush()


def up_fix_not_registred(apps, schema_editor):
    sys.stdout.write("\n    Fix parts not registred in log ... ")
    sys.stdout.flush()

    query = PartLawsuit.objects.exclude(signed_by=None).filter(in_log=None)
    message = ""
    total = query.count()
    pos = 0

    sys.stdout.write(" (%d) " % query.count())
    sys.stdout.flush()

    for p in query:
        pos += 1
        sys.stdout.write("\b" * len(message))
        message = " %d de %d " % (pos, total)
        sys.stdout.write(message)
        sys.stdout.flush()

        OutCourtLawsuitLog.register(p.lawsuit, p.my_origin)

    sys.stdout.write("done\n")
    sys.stdout.flush()


def empty(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0084_add_reverted_at_in_deadlinelog"),
    ]

    operations = [
        migrations.RunPython(up_remove_corrupted, empty),
        migrations.RunPython(up_fix_not_registred, empty),
    ]
