# Generated by Django 2.2.14 on 2020-08-17 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0118_auto_20200513_1820"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judicial", "0085_fix_duplicated_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "reminder_state",
                    models.SmallIntegerField(
                        choices=[(1, "Urgente"), (2, "Rápido"), (3, "Normal")],
                        default=3,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                ("content", models.TextField()),
                (
                    "access_level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Para todo Ministério Público"),
                            (2, "Para o departamento"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closeds_reminder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workplaces_reminder",
                        to="rh.Lotacao",
                    ),
                ),
            ],
            options={
                "ordering": ("reminder_state", "-created_at"),
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AlterField(
            model_name="legalclassification",
            name="path_cache",
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="legalclassification",
            name="taxonomy_type",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="requestcollaboration",
            name="protocol_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requestcollaboration",
                to="protocolo.Movimentacao",
                verbose_name="Certidão de recebimento",
            ),
        ),
        migrations.AlterField(
            model_name="workerreminder",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Concluído em"
            ),
        ),
        migrations.AlterField(
            model_name="workerreminder",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Concluído por",
            ),
        ),
        migrations.CreateModel(
            name="StatisticMarker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(blank=True, db_index=True, max_length=240)),
                (
                    "acting_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exclusives_statistic_markers",
                        to="judicial.ActingZone",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.AddField(
            model_name="outcourtlawsuit",
            name="statistic_markers",
            field=models.ManyToManyField(
                related_name="lawsuits", to="judicial.StatisticMarker"
            ),
        ),
        migrations.CreateModel(
            name="PartLawsuitReminder",
            fields=[
                (
                    "reminder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="judicial.Reminder",
                    ),
                ),
                (
                    "part_lawsuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="judicial.PartLawsuit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("judicial.reminder",),
        ),
        migrations.CreateModel(
            name="LawsuitReminder",
            fields=[
                (
                    "reminder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="judicial.Reminder",
                    ),
                ),
                (
                    "lawsuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="judicial.OutCourtLawsuit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("judicial.reminder",),
        ),
    ]
