# Generated by Django 2.2.13 on 2020-08-13 11:15
import sys

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def up_fix_main_matter(apps, schema_editor):
    OutCourtLawsuit = apps.get_model("judicial", "OutCourtLawsuit")

    sys.stdout.write("\n    Update main OutCourtLawsuit ... ")
    sys.stdout.flush()

    query = OutCourtLawsuit.objects.filter(cache_number__isnull=False)

    message = ""
    total = query.count()
    pos = 0

    sys.stdout.write(" (%d) " % total)
    sys.stdout.flush()

    for lawsuit in query:
        pos += 1
        sys.stdout.write("\b" * len(message))
        message = " %d de %d " % (pos, total)
        sys.stdout.write(message)
        sys.stdout.flush()

        lawsuit_matter = lawsuit.in_lawsuit_matter.filter(principal=True).first()
        if lawsuit_matter:
            OutCourtLawsuit.objects.filter(pk=lawsuit.pk).update(
                main_matter=lawsuit_matter.matter
            )

    sys.stdout.write("done\n")
    sys.stdout.flush()


def empty(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0086_create_reminders_and_statatistical_markers"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcourtlawsuit",
            name="main_matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="judicial.LegalMatter",
            ),
        ),
        migrations.AddField(
            model_name="outcourtlawsuitlog",
            name="main_matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="judicial.LegalMatter",
            ),
        ),
        migrations.AddField(
            model_name="triagepart",
            name="acting_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_triage_part",
                to="judicial.ActingZone",
            ),
        ),
        migrations.RunPython(up_fix_main_matter, empty),
    ]
