# Generated by Django 2.2.17 on 2020-11-09 15:44
from django.db import migrations, models
from judicial.models import OutCourtLawsuit, PartLawsuit


def up_at_moment(apps, schema_editor):
    OutCourtLawsuitLog = apps.get_model("judicial", "OutCourtLawsuitLog")
    query = OutCourtLawsuitLog.objects.filter(at_moment=None)
    total = query.count()
    pos = 0
    message = ""
    for log in query:
        pos += 1
        print("\b" * len(message), end="")
        message = f" {pos} de {total} "
        print(message, end="")

        part = PartLawsuit.objects.get(pk=log.part_id)
        log.at_moment = part.my_origin.at_moment()
        log.save()


def down_at_moment(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0087_create_main_matter_outcourtlwsuit"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcourtlawsuitlog",
            name="at_moment",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(up_at_moment, down_at_moment),
    ]
