# Generated by Django 2.2.17 on 2020-12-09 10:58

from django.db import migrations, models
import django.db.models.deletion
import judicial.models


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0088_log_with_at_moment"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcourtlawsuit",
            name="external_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="LegacyImport",
            fields=[
                (
                    "partlawsuit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="judicial.PartLawsuit",
                    ),
                ),
                (
                    "type_lawsuit",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Notícia de Fato"),
                            (2, "Inquérito Civil Público"),
                            (3, "Procedimento Preparatório"),
                            (4, "Procedimento Investigatório Criminal"),
                            (5, "Notícia de Fato Criminal"),
                            (6, "Em instauração"),
                            (7, "Procedimento Administrativo"),
                            (8, "Carta Precatória"),
                            (1242, "PROCEDIMENTO PREPARATORIO ELEITORAL"),
                        ],
                        default=0,
                    ),
                ),
                ("external_code", models.CharField(max_length=100, null=True)),
                ("import_number", models.PositiveIntegerField(blank=True, null=True)),
                ("import_year", models.SmallIntegerField(blank=True, null=True)),
                ("import_code", models.CharField(blank=True, max_length=30, null=True)),
                ("legacy_title", models.TextField()),
                ("instauration_date", models.DateField()),
                ("remaining_days", models.IntegerField(default=0)),
                (
                    "blokers",
                    models.ManyToManyField(
                        related_name="as_blokers_in_legacy_import", to="rh.Pessoa"
                    ),
                ),
                (
                    "city_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Localidade",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="judicial.ExecutionOrgan",
                    ),
                ),
                (
                    "main_matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="judicial.LegalMatter",
                    ),
                ),
                (
                    "major_interested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rh.Pessoa",
                    ),
                ),
                (
                    "other_interesteds",
                    models.ManyToManyField(
                        related_name="as_other_interesteds_in_legacy_import",
                        to="rh.Pessoa",
                    ),
                ),
                (
                    "other_matters",
                    models.ManyToManyField(
                        related_name="in_legacy_import", to="judicial.LegalMatter"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(judicial.models.InitialPartlawsuit, "judicial.partlawsuit"),
        ),
    ]
