# Generated by Django 2.2.24 on 2021-10-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0147_auto_20210902_1008"),
        ("judicial", "0094_add_title_in_addiotionaldiligence_recomendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counties",
                to="rh.Endereco",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
