# Generated by Django 2.2.28 on 2022-07-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0176_movimentacaodiligencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("judicial", "0096_auto_20220412_1430"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outcourtlawsuit",
            options={
                "ordering": ("remaining_days", "cache_number"),
                "permissions": (
                    ("outcourtlawsuitadmin", "Pode administrar os OutCourtLawsuit"),
                    (
                        "can_view_outcourtlawsuit_secretary",
                        "Pode visualizar os procedimentos da Secretaria",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="archivementnoticeoffice",
            name="cause",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "O fato já encontra-se solucionado"),
                    (2, "Não houve recurso"),
                    (3, "Ciência de homologação"),
                    (4, "Fato já foi objeto de investigação/ação judicial"),
                    (5, "Fato já solucionado"),
                    (6, "Morte do agente"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="type_vehicle",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Veículo Oficial"),
                    (2, "Veículo Particular"),
                    (3, "Correios ou outro terceiro"),
                    (4, "Por meio eletrônico"),
                ],
                null=True,
                verbose_name="Tipo de veiculo usado para a rezalizacao da diligencia",
            ),
        ),
        migrations.AlterField(
            model_name="dilationperiod",
            name="type_lawsuit",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Notícia de Fato"),
                    (2, "Inquérito Civil Público"),
                    (3, "Procedimento Preparatório"),
                    (4, "Procedimento Investigatório Criminal"),
                    (5, "Notícia de Fato Criminal"),
                    (6, "Em instauração"),
                    (7, "Procedimento Administrativo"),
                    (8, "Carta Precatória"),
                    (9, "Procedimento Preparatório Eleitoral"),
                    (10, "Procedimento de Gestão Administrativa"),
                ],
                null=True,
                verbose_name="Tipo do Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="legacyimport",
            name="type_lawsuit",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Notícia de Fato"),
                    (2, "Inquérito Civil Público"),
                    (3, "Procedimento Preparatório"),
                    (4, "Procedimento Investigatório Criminal"),
                    (5, "Notícia de Fato Criminal"),
                    (6, "Em instauração"),
                    (7, "Procedimento Administrativo"),
                    (8, "Carta Precatória"),
                    (9, "Procedimento Preparatório Eleitoral"),
                    (10, "Procedimento de Gestão Administrativa"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="ordinace",
            name="type_ordinace",
            field=models.SmallIntegerField(
                choices=[
                    (2, "INQUÉRITO CIVIL PÚBLICO"),
                    (3, "PROCEDIMENTO PREPARATÓRIO"),
                    (4, "PROCEDIMENTO INVESTIGATORIO CRIMINAL"),
                    (7, "PROCEDIMENTO ADMINISTRATIVO"),
                    (9, "PROCEDIMENTO PREPARATORIO ELEITORAL"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ordinacereformulated",
            name="type_ordinace",
            field=models.SmallIntegerField(
                choices=[
                    (2, "INQUÉRITO CIVIL PÚBLICO"),
                    (3, "PROCEDIMENTO PREPARATÓRIO"),
                    (4, "PROCEDIMENTO INVESTIGATORIO CRIMINAL"),
                    (7, "PROCEDIMENTO ADMINISTRATIVO"),
                    (9, "PROCEDIMENTO PREPARATORIO ELEITORAL"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outcourtlawsuit",
            name="type_lawsuit",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Notícia de Fato"),
                    (2, "Inquérito Civil Público"),
                    (3, "Procedimento Preparatório"),
                    (4, "Procedimento Investigatório Criminal"),
                    (5, "Notícia de Fato Criminal"),
                    (6, "Em instauração"),
                    (7, "Procedimento Administrativo"),
                    (8, "Carta Precatória"),
                    (9, "Procedimento Preparatório Eleitoral"),
                    (10, "Procedimento de Gestão Administrativa"),
                ],
                default=1,
                verbose_name="Tipo do Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="outcourtlawsuitlog",
            name="type_lawsuit",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Notícia de Fato"),
                    (2, "Inquérito Civil Público"),
                    (3, "Procedimento Preparatório"),
                    (4, "Procedimento Investigatório Criminal"),
                    (5, "Notícia de Fato Criminal"),
                    (6, "Em instauração"),
                    (7, "Procedimento Administrativo"),
                    (8, "Carta Precatória"),
                    (9, "Procedimento Preparatório Eleitoral"),
                    (10, "Procedimento de Gestão Administrativa"),
                ],
                verbose_name="Tipo do Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="rejectionfact",
            name="rejection_fact_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Não presente a legitimidade do MP"),
                    (2, "O fato não constitui violação de direito e interesses difuso"),
                    (3, "O fato já se encontra solucionado"),
                    (4, "O fato já é objeto de investigação ou ACP"),
                    (5, "Não traz indícios mínimos para início de investigação"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rejectionfact",
            name="type_ordinace",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (2, "INQUÉRITO CIVIL PÚBLICO"),
                    (3, "PROCEDIMENTO PREPARATÓRIO"),
                    (4, "PROCEDIMENTO INVESTIGATORIO CRIMINAL"),
                    (7, "PROCEDIMENTO ADMINISTRATIVO"),
                    (9, "PROCEDIMENTO PREPARATORIO ELEITORAL"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Secretary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution_organs",
                    models.ManyToManyField(
                        related_name="as_secretaries", to="judicial.ExecutionOrgan"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seretary",
                        to="rh.Lotacao",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name="AuditDispatchSecretary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type_dispatch",
                    models.SmallIntegerField(
                        default=1, verbose_name="Tipo de despacho"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawsuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatches",
                        to="judicial.OutCourtLawsuit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="rh.Lotacao",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatches",
                        to="judicial.Secretary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
