# Generated by Django 2.2.28 on 2022-08-04 11:53

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0184_auto_20220804_1153"),
        ("judicial", "0097_auto_20220713_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="partlawsuit",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.CreateModel(
            name="NoticeConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ordinace",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "INQUERITO CIVÍL PÚBLICO"),
                            (3, "PROCEDIMENTO PREPARATÓRIO"),
                        ],
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "departament",
                    models.ManyToManyField(
                        related_name="departaments",
                        to="rh.Lotacao",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "legal_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="judicial.LegalClassification",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "unique_together": {("type_ordinace", "legal_classification")},
            },
        ),
    ]
