# Generated by Django 2.2.28 on 2022-12-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judicial", "0098_auto_20220804_1153"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pouch",
            options={"ordering": ("-pouch_year", "-pouch_number")},
        ),
    ]
