from app.settings import (
    HERMES_TOKEN,
    HERMES_TOKEN_EMAIL_PESSOAL,
    HERMES_TOKEN_PROCESSAMENTOS,
    HERMES_TOKEN_RELATORIOS,
)


TIPO_TASK_PROCESSAMENTO_PADRAO = 1
TIPO_TASK_PROCESSAMENTO_RELATORIO = 2
TIPO_TASK_PROCESSAMENTO_EMAIL_PESSOAL = 3
TIPO_TASK_PROCESSAMENTO_ESOCIAL = 4

TEMPLATE_NOTIFICACAO_RELATORIO = "NOTIFICACAO_HERMES"
TEMPLATE_NOTIFICACAO_PROCESSAMENTO = "NOTIFICACAO_PROCESSAMENTO_HERMES"

SISTEMA_HERMES_PADRAO = "ATHENAS"
SISTEMA_HERMES_RELATORIO = "ATHENAS RELATORIOS"
SISTEMA_HERMES_EMAIL_PESSOAL = "ATHENAS EMAIL PESSOAL"
SISTEMA_HERMES_PROCESSAMENTOS = "ATHENAS PROCESSAMENTOS"

SISTEMA_HERMES = {
    TIPO_TASK_PROCESSAMENTO_PADRAO: SISTEMA_HERMES_PADRAO,
    TIPO_TASK_PROCESSAMENTO_RELATORIO: SISTEMA_HERMES_RELATORIO,
    TIPO_TASK_PROCESSAMENTO_EMAIL_PESSOAL: SISTEMA_HERMES_EMAIL_PESSOAL,
    TIPO_TASK_PROCESSAMENTO_ESOCIAL: SISTEMA_HERMES_PROCESSAMENTOS,
}

TIPO_TOKEN_HERMES = {
    TIPO_TASK_PROCESSAMENTO_PADRAO: HERMES_TOKEN,
    TIPO_TASK_PROCESSAMENTO_RELATORIO: HERMES_TOKEN_RELATORIOS,
    TIPO_TASK_PROCESSAMENTO_EMAIL_PESSOAL: HERMES_TOKEN_EMAIL_PESSOAL,
    TIPO_TASK_PROCESSAMENTO_ESOCIAL: HERMES_TOKEN_PROCESSAMENTOS,
}


TEMPLATE_NOTIFICACAO_HERMES = {
    TIPO_TASK_PROCESSAMENTO_RELATORIO: TEMPLATE_NOTIFICACAO_RELATORIO,
    TIPO_TASK_PROCESSAMENTO_ESOCIAL: TEMPLATE_NOTIFICACAO_PROCESSAMENTO,
}

STATUS_NOTIFICACAO = {
    TIPO_TASK_PROCESSAMENTO_RELATORIO: ["ready"],
    TIPO_TASK_PROCESSAMENTO_ESOCIAL: ["ready", "failed"],
}
