# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grupos",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nome", models.TextField(blank=True, null=True)),
                ("local", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("telefone", models.TextField(blank=True, null=True)),
                (
                    "qtde_max_membros_por_grupo",
                    models.BigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "grupos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Plantoes",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("de", models.DateTimeField(blank=True, null=True)),
                ("ate", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("servidor_id", models.BigIntegerField(blank=True, null=True)),
                ("local", models.TextField(blank=True, null=True)),
                ("status", models.BigIntegerField(blank=True, null=True)),
                ("telefone", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "plantoes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Plantonistas",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("grupo_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("servidor_id", models.BigIntegerField(blank=True, null=True)),
                ("telefone", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "plantonistas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Responsaveis",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("grupo_id", models.BigIntegerField(blank=True, null=True)),
                ("matricula", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("servidor_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "responsaveis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Trocas",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("de", models.TextField(blank=True, null=True)),
                ("ate", models.TextField(blank=True, null=True)),
                ("substituido_id", models.BigIntegerField(blank=True, null=True)),
                ("substituto_id", models.BigIntegerField(blank=True, null=True)),
                ("grupo_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "trocas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SincronizacaoPlantoes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("de", models.DateTimeField(blank=True, null=True)),
                ("ate", models.DateTimeField(blank=True, null=True)),
                ("servidor_id", models.BigIntegerField(blank=True, null=True)),
                ("mensagem", models.TextField(blank=True, null=True)),
                ("status", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "sincronizacao_plantoes",
            },
        ),
    ]
