# -*- coding: utf-8 -*-

from rh.const import MOTIVO_INICIO_DEPENDENCIA, MOTIVO_FIM_DEPENDENCIA, TIPO_DEPENDENTE

TBL_1 = {  # _SITUACAO_PREVIDENCIARIA = {
    0: "SERVIDOR ATIVO",
    1: "SERVIDOR INATIVO",  # APOSENTADO NO IGEPREV
    2: "INSTITUIDOR DE PENSÃO",
    3: "PENSIONISTA",  # OPÇÃO UTILIZADA PARA SECAD
    4: "FALECIDO SEM PENSIONISTA",
    5: "EX-PENSIONISTA",  # CASO ELE TENHA PENSIONISTAS E DEPOIS TERMINE O PERÍODO DA PENSÃO
    6: "INSTITUIDOR DE AUXÍLIO RECLUSÃO",
    7: "SEM VINCULO",  # COMISSIONADOS, QUANDO AINDA ERAM ENVIADOS PARA IGEPREV
}

TBL_2 = {  # _SITUACAO_FUNCIONAL = {
    0: "EM EXERCICIO",
    1: "EXONERADO",
    2: "LICENCIADO SEM REMUNERAÇÃO",
    3: "LICENCIADO COM REMUNERAÇÃO",
    4: "CEDIDO COM ONUS",
    5: "CEDIDO SEM ONUS",
    6: "REQUISITADO COM ONUS",
    7: "REQUISITADO SEM ONUS",
    8: "DEMITIDO",
    9: "EM DISPONIBILIDADE",
    10: "SEM VINCULO",
}

TBL_3 = {  # _VINCULO_ENTE = {
    0: "SERVIDOR CARGO EFETIVO",
    1: "MILITAR",
    2: "INATIVO",
    3: "SEM VÍNCULO",
}

TBL_4 = {  # _PODERES = {
    1: "EXECUTIVO",
    2: "LEGISLATIVO",
    3: "JUDICIÁRIO",
    4: "MINISTÉRIO PÚBLICO",
    5: "DESCONHECIDO",
    6: "TRIBUNAL DE CONTAS",
}

TBL_5 = {  # _ESTADOS_CIVIS = {
    1: "SOLTEIRO",
    2: "CASADO",
    3: "VIÚVO",
    4: "SEPARADO JUDICIALMENTE",
    5: "DIVORCIADO",
    6: "UNIÃO ESTÁVEL",
    7: "DESCONHECIDO",
}

TBL_6 = {  # _GRAU_INSTRUCAO = {
    1: "ANALFABETO",
    2: "ALFABETIZADO SEM CURSOS REGULARES",
    3: "FUNDAMENTAL INCOMPLETO",
    4: "FUNDAMENTAL COMPLETO",
    5: "MÉDIO INCOMPLETO",
    6: "MÉDIO COMPLETO",
    7: "SUPERIOR INCOMPLETO",
    8: "SUPERIOR COMPLETO OU EQUIVALENTE LEGAL",
    9: "ESPECIALIZAÇÃO/PÓS-GRADUAÇÃO",
    10: "MESTRADO",
    11: "DOUTORADO",
    12: "DESCONHECIDO",
}

TBL_7 = {  # _TIPOS_LOGRADOURO = {
    0: "RUA",
    1: "AVENIDA",
    2: "PRAÇA",
    3: "VIELA",
    4: "PONTE",
    5: "VIADUTO",
    6: "ALAMEDA",
    7: "OUTROS",
}

TBL_8 = {  # _TIPOS_FOLHA = {
    0: "EXECUTIVO",
    1: "ASSEMBLÉIA",
    2: "TRIBUNAL DE JUSTIÇA",
    3: "MINISTÉRIO PÚBLICO",
    4: "TRIBUNAL DE CONTAS",
    5: "CARTORÁRIO",
    6: "FRUNPREV",
}

TBL_9 = {  # _BENEFICIOS = {
    0: "OUTROS",
    1: "APOSENTADORIA POR INVALIDEZ",
    2: "APOSENTADORIA VOLUNTÁRIA POR IMPLEMENTO DE IDADE",
    3: "APOSENTADORIA VOLUNTÁRIO POR TEMPO DE CONTRIBUIÇÃO",
    4: "APOSENTADORIA COMPULSÓRIA",
    5: "AUXÍLIO DOENÇA",
    6: "AUXÍLIO DOENÇA POR ACIDENTE DE TRABALHO",
    7: "AUXÍLIO ACIDENTE",
    8: "AUXÍLIO RECLUSÃO",
    9: "SALÁRIO FAMÍLIA",
    10: "SALÁRIO MATERNIDADE",
    11: "PENSÃO POR MORTE DE SEGURADO ATIVO",
    12: "PENSÃO POR MORTE DE APOSENTADO POR IDADE OU POR TEMPO DE CONTRIBUIÇÃO",
    13: "PENSÃO POR MORTE DE APOSENTADORIA POR INVALIDEZ",
    14: "RESERVA REMUNERADA",
    15: "REFORMA",
    16: "REFORMA POR INVALIDEZ",
    17: "PENSÃO CIVIL",
    18: "PENSÃO MILITAR",
}

TBL_11 = {  # _MOTIVO_BENEFICIO_MILITAR_RESERVA = {
    1: "MOTIVO RESERVA TRINTA ANOS CONTRIBUIÇÃO",
    2: "MOTIVO RESERVA TIPO IDADE OFICIAL",
    3: "MOTIVO RESERVA OFICIAL INABILITADO PROMOÇÃO",
    4: "MOTIVO RESERVA SAÚDE FAMÍLIA",
    5: "MOTIVO RESERVA AFASTAMENTO CARGO PÚBLICO TEMP",
    6: "MOTIVO RESERVA CARGO ELETIVO",
    7: "MOTIVO RESERVA NÃO FREQUENTAR CURSO ELEVAÇÃO PM",
    8: "MOTIVO RESERVA IDADE MÍNIMA 1",
    9: "MOTIVO RESERVA IDADE MÍNIMA 2",
}

TBL_12 = {  # _MOTIVO_BENEFICIO_MILITAR_REFORMA = {
    1: "MOTIVO REFORMA SUPERAR IDADE LIMITE",
    2: "MOTIVO REFORMA INCAPACIDADE DEFINITIVA",
    3: "MOTIVO REFORMA INCAPACIDADE TEMPORARIAMENTE",
    4: "MOTIVO REFORMA CONDENADO PENA",
    5: "MOTIVO REFORMA CONSIDERADO CULPADO DISCIPLINA",
}

# TBL_13 = {#_GRAU_PARENTESCO = {
#    0: 'OUTROS',
#    1: u'CÔNJUGE',
#    2: u'COMPANHEIRO(A)',
#    3: u'FILHO(A)',
#    5: u'PAI(MÃE)',
#    6: u'IRMÃO(Ã)',
#    8: u'ENTEADO(A)',
#    10: u'MENOR TUTELADO',
#    12: u'EX-CÔNJUGE',
# }
TBL_13 = {  # _GRAU_PARENTESCO = {
    0: "FILHO (A)",
    1: "NETO (A)",
    2: "CÔNJUGE",
    3: "COMPANHEIRO (A)",
    4: "ENTEADO (A)",
    5: "PAI (MÃE)",
    6: "MENOR  TUTELADO",
    7: "EX-CÔNJUGE",
    8: "IRMÃO (Ã)",
    9: "Outros",
}

TBL_14 = MOTIVO_INICIO_DEPENDENCIA

TBL_15 = MOTIVO_FIM_DEPENDENCIA

TBL_16 = TIPO_DEPENDENTE

# TABELA 13(IGEPREV) VIROU TABELA 18
TBL_17 = {  # _TIPO_AFASTAMENTO = {
    1: "A DISPOSIÇÃO COM ONUS PARA O REQUISITANTE",
    2: "A DISPOSIÇÃO COM ONUS PARA O ORIGEM",
    3: "LICENÇA PARA TRATAR DE INTERESSES PARTICULARES",
    4: "LICENÇA PARA ACOMPANHAMENTO DE CÔNJUGE",
    5: "MANDATO ELETIVO",
    6: "REPRESENTAÇÃO SINDICAL",
}

# TABELA 14(IGEPREV) VIROU TABELA 18
TBL_18 = {  # CARGO ACUMULÁVEL
    1: "NÃO",
    2: "PROFESSOR",
    3: "MAGISTRADO",
    4: "MEMBRO DO MINISTÉRIO PÚBLICO",
    5: "MEMBRO DO TRIBUNAL DE CONTAS",
    6: "APOSENTADORIA ESPECIAL (EC 47/2OUTROS",
    7: "OUTROS",
}

# TABELA 15(IGEPREV) VIROU TABELA 19
TBL_19 = {  # CARGO TÉCNICO CIENTÍFICO
    1: "NÃO",
    2: "PROFISSIONAL SAÚDE",
    3: "PROFESSOR",
    9: "OUTROS",
}
