# -*- coding: utf-8 -*-

from contrib.utils import getLogger
from rh.gfp import febrabam as fb

log = getLogger()

SEFIP = {
    "header-file-reg-00": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "valor": 0,
            "size": 0,
            "tipo": "",
            "versao": "08.4",
            "lenght": 360,
        },
        1: {"label": "tipo_registro", "valor": 0, "size": 2, "tipo": "num"},
        2: {"label": "filler1", "valor": " ", "size": 51, "tipo": "alfa"},
        3: {"label": "tipo_remessa", "valor": 1, "size": 1, "tipo": "num"},
        4: {
            "label": "tipo_inscricao_responsavel",
            "valor": 3,
            "size": 1,
            "tipo": "num",
        },
        5: {"label": "inscricao_responsavel", "valor": 0, "size": 14, "tipo": "num"},
        6: {"label": "nome_responsavel", "valor": "", "size": 30, "tipo": "alfa"},
        7: {"label": "nome_contato", "valor": "", "size": 20, "tipo": "alfa"},
        8: {"label": "logradouro", "valor": "", "size": 50, "tipo": "alfa"},
        9: {"label": "bairro", "valor": "", "size": 20, "tipo": "alfa"},
        10: {"label": "cep", "valor": 0, "size": 8, "tipo": "num"},
        11: {"label": "cidade", "valor": "", "size": 20, "tipo": "alfa"},
        12: {"label": "uf", "valor": "TO", "size": 2, "tipo": "alfa"},
        13: {"label": "fone_contato", "valor": 0, "size": 12, "tipo": "num"},
        14: {
            "label": "site",
            "valor": "drtfolha@mpto.mp.br",
            "size": 60,
            "tipo": "alfa",
        },
        15: {"label": "competencia", "valor": "0", "size": 6, "tipo": "alfa"},
        16: {"label": "cod_recolhimento", "valor": 115, "size": 3, "tipo": "num"},
        17: {
            "label": "indicador_recolhimento_fgts",
            "valor": "",
            "size": 1,
            "tipo": "alfa",
        },
        18: {"label": "modalidade_arquivo", "valor": 1, "size": 1, "tipo": "num"},
        19: {"label": "data_recolhimento_fgts", "valor": "", "size": 8, "tipo": "alfa"},
        20: {
            "label": "indicador_recolhimento_prev",
            "valor": 1,
            "size": 1,
            "tipo": "num",
        },
        21: {"label": "data_recolhimento_prev", "valor": "", "size": 8, "tipo": "alfa"},
        22: {
            "label": "indice_recolhimento_atraso_prev",
            "valor": "",
            "size": 7,
            "tipo": "alfa",
        },
        23: {
            "label": "tipo_inscricao_fornecedor",
            "valor": 1,
            "size": 1,
            "tipo": "num",
        },
        24: {"label": "inscricao_fornecedor", "valor": 0, "size": 14, "tipo": "alfa"},
        25: {"label": "filler2", "valor": "", "size": 18, "tipo": "alfa"},
        26: {"label": "fim_linha", "valor": "*", "size": 1, "tipo": "alfa"},
    },
    "header-empresa-reg-10": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "valor": 0,
            "size": 0,
            "tipo": "",
            "versao": "08.4",
            "lenght": 360,
        },
        1: {"label": "tipo_registro", "valor": 10, "size": 2, "tipo": "num"},
        2: {"label": "tipo_inscricao_empresa", "valor": 3, "size": 1, "tipo": "num"},
        3: {"label": "inscricao_empresa", "valor": 0, "size": 14, "tipo": "num"},
        4: {"label": "filler1", "valor": 0, "size": 36, "tipo": "num"},
        5: {"label": "nome_empresa", "valor": "", "size": 40, "tipo": "alfa"},
        6: {"label": "logradouro", "valor": "", "size": 50, "tipo": "alfa"},
        7: {"label": "bairro", "valor": "", "size": 20, "tipo": "alfa"},
        8: {"label": "cep", "valor": 0, "size": 8, "tipo": "num"},
        9: {"label": "cidade", "valor": "", "size": 20, "tipo": "alfa"},
        10: {"label": "uf", "valor": "TO", "size": 2, "tipo": "alfa"},
        11: {"label": "fone_contato", "valor": 0, "size": 12, "tipo": "num"},
        12: {"label": "alteracao_endereco", "valor": "N", "size": 1, "tipo": "alfa"},
        13: {"label": "cnae", "valor": 8424800, "size": 7, "tipo": "num"},
        14: {"label": "alteracao_cnae", "valor": "N", "size": 1, "tipo": "alfa"},
        15: {"label": "rat", "valor": 0, "size": 2, "tipo": "num", "decimais": 1},
        16: {"label": "cod_centralizacao", "valor": 0, "size": 1, "tipo": "num"},
        17: {"label": "simples", "valor": "1", "size": 1, "tipo": "alfa"},
        18: {"label": "fpas", "valor": 582, "size": 3, "tipo": "num"},
        19: {"label": "cod_outras_entidades", "valor": 0, "size": 4, "tipo": "num"},
        20: {"label": "cod_pagamento_gps", "valor": 2402, "size": 4, "tipo": "num"},
        21: {
            "label": "percent_isencao_filantropia",
            "valor": "",
            "size": 5,
            "tipo": "alfa",
        },
        22: {
            "label": "salario_familia",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        23: {
            "label": "salario_maternidade",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        24: {
            "label": "contrib_desc_empregado_comp_13",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        25: {
            "label": "indicador_negativo_positivo",
            "valor": 0,
            "size": 1,
            "tipo": "num",
        },
        26: {
            "label": "valor_devido_prev_comp_13",
            "valor": 0,
            "size": 14,
            "tipo": "num",
        },
        27: {"label": "banco", "valor": "", "size": 3, "tipo": "alfa"},
        28: {"label": "agencia", "valor": "", "size": 4, "tipo": "alfa"},
        29: {"label": "conta_com_dv", "valor": "", "size": 9, "tipo": "alfa"},
        30: {"label": "filler2", "valor": 0, "size": 45, "tipo": "num"},
        31: {"label": "filler3", "valor": "", "size": 4, "tipo": "alfa"},
        32: {"label": "fim_linha", "valor": "*", "size": 1, "tipo": "alfa"},
    },
    "trabalhador-reg-30": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "valor": 0,
            "size": 0,
            "tipo": "",
            "versao": "08.4",
            "lenght": 360,
        },
        1: {"label": "tipo_registro", "valor": 30, "size": 2, "tipo": "num"},
        2: {"label": "tipo_inscricao_empresa", "valor": 1, "size": 1, "tipo": "num"},
        3: {"label": "inscricao_empresa", "valor": 0, "size": 14, "tipo": "num"},
        4: {
            "label": "tipo_inscricao_const_civil",
            "valor": "",
            "size": 1,
            "tipo": "num",
            "branco": " ",
        },
        5: {
            "label": "inscricao_const_civil",
            "valor": "",
            "size": 14,
            "tipo": "num",
            "branco": " ",
        },
        6: {
            "label": "pis_pasep_ci",
            "valor": 0,
            "size": 11,
            "tipo": "num",
            "branco": "*",
        },
        7: {
            "label": "data_admissao",
            "valor": "",
            "size": 8,
            "tipo": "alfa",
            "branco": " ",
        },
        8: {"label": "categ_trabalhador", "valor": 20, "size": 2, "tipo": "num"},
        9: {"label": "nome_trabalhador", "valor": "", "size": 70, "tipo": "alfa"},
        10: {"label": "matricula_trabalhador", "valor": 0, "size": 11, "tipo": "num"},
        11: {"label": "numero_ctps", "valor": "", "size": 7, "tipo": "alfa"},
        12: {"label": "serie_ctps", "valor": "", "size": 5, "tipo": "alfa"},
        13: {"label": "data_opcao_fgts", "valor": "", "size": 8, "tipo": "alfa"},
        14: {
            "label": "data_nascimento",
            "valor": "",
            "size": 8,
            "tipo": "alfa",
            "branco": " ",
        },
        15: {"label": "cbo", "valor": "*", "size": 5, "tipo": "alfa", "branco": "*"},
        16: {
            "label": "remuneracao_sem_13",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        17: {
            "label": "remuneracao_13",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        18: {"label": "classe_contribuicao", "valor": "", "size": 2, "tipo": "alfa"},
        19: {"label": "ocorrencia", "valor": "", "size": 2, "tipo": "alfa"},
        20: {
            "label": "valor_descontado_segurado",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        21: {
            "label": "remuneracao_base",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        22: {
            "label": "base_calculo_13",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        23: {
            "label": "base_calculo_13_compe_12",
            "valor": 0,
            "size": 15,
            "tipo": "num",
            "decimais": 2,
        },
        24: {"label": "filler1", "valor": "", "size": 98, "tipo": "alfa"},
        25: {"label": "fim_linha", "valor": "*", "size": 1, "tipo": "alfa"},
    },
    "trabalhador-reg-32": {  # registro de movimentacao
        "cfg": {
            "label": "",
            "valor": 0,
            "size": 0,
            "tipo": "",
            "versao": "08.4",
            "lenght": 360,
        },
        1: {"label": "tipo_registro", "valor": 32, "size": 2, "tipo": "num"},
        2: {"label": "tipo_inscricao_empresa", "valor": 1, "size": 1, "tipo": "num"},
        3: {"label": "inscricao_empresa", "valor": 0, "size": 14, "tipo": "num"},
        4: {
            "label": "tipo_inscricao_const_civil",
            "valor": "",
            "size": 1,
            "tipo": "num",
            "branco": " ",
        },
        5: {
            "label": "inscricao_const_civil",
            "valor": "",
            "size": 14,
            "tipo": "num",
            "branco": " ",
        },
        6: {
            "label": "pis_pasep_ci",
            "valor": 0,
            "size": 11,
            "tipo": "num",
            "branco": "*",
        },
        7: {
            "label": "data_admissao",
            "valor": "",
            "size": 8,
            "tipo": "alfa",
            "branco": " ",
        },
        8: {"label": "categ_trabalhador", "valor": 20, "size": 2, "tipo": "num"},
        9: {"label": "nome_trabalhador", "valor": "", "size": 70, "tipo": "alfa"},
        10: {"label": "cod_movimentacao", "valor": "", "size": 2, "tipo": "alfa"},
        11: {
            "label": "data_movimentacao",
            "valor": "",
            "size": 8,
            "tipo": "alfa",
            "branco": " ",
        },
        12: {"label": "indicativo_fgts", "valor": " ", "size": 1, "tipo": "alfa"},
        13: {"label": "filler1", "valor": "", "size": 225, "tipo": "alfa"},
        14: {"label": "fim_linha", "valor": "*", "size": 1, "tipo": "alfa"},
    },
    "triller-arquivo-reg-90": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "valor": 0,
            "size": 0,
            "tipo": "",
            "versao": "08.4",
            "lenght": 360,
        },
        1: {"label": "tipo_registro", "valor": 90, "size": 2, "tipo": "num"},
        2: {
            "label": "marca_final",
            "valor": 9,
            "size": 51,
            "tipo": "num",
            "branco": "9",
        },
        24: {"label": "filler1", "valor": "", "size": 306, "tipo": "alfa"},
        25: {"label": "fim_linha", "valor": "*", "size": 1, "tipo": "alfa"},
    },
}


class RegistroSefip(fb.Registro):
    _protocolo = SEFIP
    _separador = ""
