# -*- coding: utf-8 -*-

SISPREV = {
    #    """
    #        x = 1* -> obrigatorio
    #        x* = 2* -> obrigatorio para todos ativos
    #        x'' = 3* -> obrigatorio para todos inativos
    #        x0/ = 4* -> obrigatorio para todos pensionistas
    #    """
    "Erro-header": {
        "cfg": {
            "label": "",
            "valor": "",
            "size": 0,
            "tipo": "",
            "nome_arquivo": "Erro-gieprev",
        },
        1: {"label": "data_geracao", "valor": "", "size": 10, "tipo": "alfa"},
        2: {"label": "nome_arquivo", "valor": "Erro", "size": 40, "tipo": "alfa"},
        3: {"label": "quantidade_colunas", "valor": 6, "size": 1, "tipo": "num"},
    },
    "Erro": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "arquivo",
            "valor": "",
            "size": 40,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        2: {
            "label": "linha",
            "valor": "",
            "size": 3,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        3: {
            "label": "campo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        4: {
            "label": "mensagem",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "valor_esperado",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
    },
    "PessoasSegurados": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "nome",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        4: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "sexo",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        6: {
            "label": "mae",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        7: {
            "label": "cep",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        8: {
            "label": "logradouro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        9: {
            "label": "complemento",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        10: {
            "label": "bairro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        11: {
            "label": "numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        12: {"label": "uf", "valor": "", "size": 2, "obrigatorio": "0", "tipo": "alfa"},
        13: {
            "label": "cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        14: {
            "label": "fone_residencial",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        15: {
            "label": "fone_celular",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        16: {
            "label": "fone_trabalho",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        17: {
            "label": "email_1",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        18: {
            "label": "email_2",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        19: {
            "label": "pai",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        20: {
            "label": "estado_civil",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        21: {
            "label": "escolaridade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        22: {
            "label": "doenca_incapacitante",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        23: {
            "label": "data_inicio_doenca_incapacitante",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        24: {
            "label": "data_fim_doenca_incapacitante",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        25: {
            "label": "portador_molestia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        26: {
            "label": "data_inicio_portador_molestia",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        27: {
            "label": "data_fim_portador_molestia",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        28: {
            "label": "nacionalidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        29: {
            "label": "naturalidade_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        30: {
            "label": "naturalidade_cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        31: {
            "label": "pis_pasep",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        32: {
            "label": "rg_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        33: {
            "label": "rg_orgao",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        34: {
            "label": "rg_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        35: {
            "label": "rg_data_expedicao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        36: {
            "label": "ctps_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        37: {
            "label": "ctps_serie",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        38: {
            "label": "ctps_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        39: {
            "label": "ctps_data_emissao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        40: {
            "label": "ctps_local_expedicao",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        41: {
            "label": "titulo_eleitoral_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        42: {
            "label": "titulo_eleitoral_zona",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        43: {
            "label": "titulo_eleitoral_secao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        44: {
            "label": "titulo_eleitoral_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        45: {
            "label": "identificador_segurado",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        46: {
            "label": "matricula",
            "valor": "",
            "size": 10,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        47: {
            "label": "categoria",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        48: {
            "label": "orgao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        49: {
            "label": "unidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        50: {
            "label": "lotacao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        51: {
            "label": "identificador_cargo",
            "valor": "",
            "size": 30,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        52: {
            "label": "nome_cargo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        53: {
            "label": "data_admissao",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        54: {
            "label": "identificador_fonte_pagadora",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        55: {
            "label": "nome_fonte_pagadora",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        56: {
            "label": "tipo_situacao_funcional",
            "valor": "",
            "size": 2,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        57: {
            "label": "data_situacao_funcional",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        58: {
            "label": "excluido_exonerado",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        59: {
            "label": "data_exclusao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        60: {
            "label": "motivo_exclusao",
            "valor": "",
            "size": 75,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        61: {
            "label": "fundo_previdenciario",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        62: {
            "label": "abono_permanencia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        63: {
            "label": "data_abono_permanencia",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        64: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "ExoneradosAfastados": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "nome",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        4: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "sexo",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        6: {
            "label": "mae",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        7: {
            "label": "cep",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        8: {
            "label": "logradouro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        9: {
            "label": "complemento",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        10: {
            "label": "bairro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        11: {
            "label": "numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        12: {"label": "uf", "valor": "", "size": 2, "obrigatorio": "0", "tipo": "alfa"},
        13: {
            "label": "cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        14: {
            "label": "fone_residencial",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        15: {
            "label": "fone_celular",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        16: {
            "label": "fone_trabalho",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        17: {
            "label": "email_1",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        18: {
            "label": "email_2",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        19: {
            "label": "pai",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        20: {
            "label": "estado_civil",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        21: {
            "label": "escolaridade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        22: {
            "label": "doenca_incapacitante",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        23: {
            "label": "portador_molestia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        24: {
            "label": "nacionalidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        25: {
            "label": "naturalidade_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        26: {
            "label": "naturalidade_cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        27: {
            "label": "pis_pasep",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        28: {
            "label": "rg_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        29: {
            "label": "rg_orgao",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        30: {
            "label": "rg_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        31: {
            "label": "rg_data_expedicao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        32: {
            "label": "ctps_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        33: {
            "label": "ctps_serie",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        34: {
            "label": "ctps_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        35: {
            "label": "ctps_data_emissao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        36: {
            "label": "ctps_local_expedicao",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        37: {
            "label": "titulo_eleitoral_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        38: {
            "label": "titulo_eleitoral_zona",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        39: {
            "label": "titulo_eleitoral_secao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        40: {
            "label": "titulo_eleitoral_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        41: {
            "label": "identificador_segurado",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        42: {
            "label": "matricula",
            "valor": "",
            "size": 10,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        43: {
            "label": "categoria",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        44: {
            "label": "orgao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        45: {
            "label": "unidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        46: {
            "label": "lotacao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        47: {
            "label": "identificador_cargo",
            "valor": "",
            "size": 30,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        48: {
            "label": "nome_cargo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        49: {
            "label": "data_admissao",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        50: {
            "label": "identificador_fonte_pagadora",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        51: {
            "label": "nome_fonte_pagadora",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        52: {
            "label": "tipo_situacao_funcional",
            "valor": "",
            "size": 2,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        53: {
            "label": "data_situacao_funcional",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        54: {
            "label": "excluido_exonerado",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        55: {
            "label": "data_exclusao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        56: {
            "label": "motivo_exclusao",
            "valor": "",
            "size": 75,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        57: {
            "label": "fundo_previdenciario",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        58: {
            "label": "abono_permanencia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        59: {
            "label": "data_abono_permanencia",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        60: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "ContribuicoesMensal": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador_segurado",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {"label": "ano", "valor": "", "size": 4, "obrigatorio": "1*", "tipo": "num"},
        3: {"label": "mes", "valor": "", "size": 2, "obrigatorio": "1*", "tipo": "num"},
        4: {
            "label": "base_contribuicao",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "contribuicao_segurado",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        6: {
            "label": "contribuicao_patronal",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        7: {
            "label": "contribuicao_patronal_especial",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
            "decimais": 2,
        },
        8: {
            "label": "identificador_fonte_pagadora",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        9: {
            "label": "nome_fonte_pagadora",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        10: {
            "label": "numero_tipo_folha",
            "valor": "",
            "size": 20,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        11: {
            "label": "descricao_numero_tipo_folha",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        12: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "GuiaRecolhimento": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador_fonte_pagadora",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "nome_fonte_pagadora",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        3: {
            "label": "descricao_grupo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        4: {
            "label": "fundo_previdenciario",
            "valor": "",
            "size": 30,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "numero_tipo_folha",
            "valor": "",
            "size": 20,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        6: {
            "label": "descricao_numero_tipo_folha",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        7: {"label": "ano", "valor": "", "size": 4, "obrigatorio": "1*", "tipo": "num"},
        8: {"label": "mes", "valor": "", "size": 2, "obrigatorio": "1*", "tipo": "num"},
        9: {
            "label": "base_contribuicao",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        10: {
            "label": "contribuicao_segurado",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        11: {
            "label": "contribuicao_patronal",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        12: {
            "label": "contribuicao_patronal_especial",
            "valor": "0.00",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        13: {
            "label": "total_servidores",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        14: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "Dependentes": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador_responsavel",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "cpf_responsavel",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "nome_responsavel",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        4: {
            "label": "data_nascimento_responsavel",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "identificador_dependente",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        6: {
            "label": "cpf_dependente",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        7: {
            "label": "nome_dependente",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        8: {
            "label": "data_nascimento_dependente",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        9: {
            "label": "sexo",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        10: {
            "label": "cep",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        11: {
            "label": "logradouro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        12: {
            "label": "complemento",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        13: {
            "label": "bairro",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        14: {
            "label": "numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        15: {"label": "uf", "valor": "", "size": 2, "obrigatorio": "0", "tipo": "alfa"},
        16: {
            "label": "cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        17: {
            "label": "fone_residencial",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        18: {
            "label": "fone_celular",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        19: {
            "label": "fone_trabalho",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        20: {
            "label": "email_1",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        21: {
            "label": "mae",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        22: {
            "label": "pai",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        23: {
            "label": "estado_civil",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        24: {
            "label": "escolaridade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        25: {
            "label": "doenca_incapacitante",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        26: {
            "label": "portador_molestia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        27: {
            "label": "nacionalidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        28: {
            "label": "naturalidade_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        29: {
            "label": "naturalidade_cidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        30: {
            "label": "pis_pasep",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        31: {
            "label": "rg_numero",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "num",
        },
        32: {
            "label": "rg_orgao",
            "valor": "",
            "size": 20,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        33: {
            "label": "rg_uf",
            "valor": "",
            "size": 2,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        34: {
            "label": "rg_data_expedicao",
            "valor": "",
            "size": 15,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        35: {
            "label": "tipo_dependencia",
            "valor": "",
            "size": 2,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        36: {
            "label": "data_inicio_dependencia",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        37: {
            "label": "data_fim_dependencia",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        38: {
            "label": "condicao_dependente",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        39: {
            "label": "codigo_doenca_invalidez",
            "valor": "",
            "size": 200,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        40: {
            "label": "data_laudo_invalidez",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        41: {
            "label": "irrf",
            "valor": "",
            "size": 1,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        42: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "FolhaAtivos": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "matricula",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        4: {
            "label": "nome",
            "valor": "",
            "size": 75,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        6: {
            "label": "categoria",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        7: {
            "label": "data_inicio_vencimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        8: {
            "label": "data_fim_vencimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        9: {
            "label": "banco",
            "valor": "",
            "size": 9,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        10: {
            "label": "agencia",
            "valor": "",
            "size": 9,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        11: {
            "label": "dv_agencia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        12: {
            "label": "conta",
            "valor": "",
            "size": 12,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        13: {
            "label": "dv_conta",
            "valor": "",
            "size": 2,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        14: {
            "label": "pagamento_bloqueado",
            "valor": "N",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        15: {
            "label": "motivo_bloqueio",
            "valor": "",
            "size": 100,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        16: {
            "label": "data_bloqueio",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        17: {
            "label": "valor_beneficio_vencimento",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        18: {
            "label": "codigo_evento",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        19: {
            "label": "descricao_evento",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        20: {
            "label": "valor_evento",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        21: {
            "label": "tipo_evento",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        22: {
            "label": "compoe_base_contribuicao",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        23: {
            "label": "incide_irrf",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        24: {
            "label": "parcela_atual",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        25: {
            "label": "total_parcelas",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        26: {
            "label": "data_inicio_consignacao",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        27: {
            "label": "data_fim_consignacao",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        28: {
            "label": "ano",
            "valor": "",
            "size": 4,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        29: {
            "label": "mes",
            "valor": "",
            "size": 2,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        30: {
            "label": "referencia",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        31: {
            "label": "valor_referencia",
            "valor": 0.00,
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        32: {
            "label": "numero_tipo_folha",
            "valor": "",
            "size": 20,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        33: {
            "label": "descricao_tipo_folha",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        34: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "EvolucaoCarreira": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "matricula",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        4: {
            "label": "nome",
            "valor": "",
            "size": 75,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        6: {
            "label": "orgao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        7: {
            "label": "unidade",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        8: {
            "label": "lotacao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        9: {
            "label": "identificador_cargo",
            "valor": "",
            "size": 30,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        10: {
            "label": "nome_cargo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        11: {
            "label": "data_inicio",
            "valor": "",
            "size": 10,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        12: {
            "label": "data_fim",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        13: {
            "label": "referencia",
            "valor": "",
            "size": 6,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        14: {
            "label": "nivel",
            "valor": "",
            "size": 6,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        15: {
            "label": "classe",
            "valor": "",
            "size": 6,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        16: {
            "label": "padrao",
            "valor": "",
            "size": 6,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        17: {
            "label": "motivo_fim",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        18: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "TempoAnteriorRGPS": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "matricula",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        4: {
            "label": "nome",
            "valor": "",
            "size": 75,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        6: {
            "label": "data_inicio",
            "valor": "",
            "size": 10,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        7: {
            "label": "data_fim",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        8: {
            "label": "aposentadoria_especial",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        9: {
            "label": "tipo_tempo",
            "valor": "",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        10: {
            "label": "protocolo",
            "valor": "",
            "size": 30,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        11: {
            "label": "ano",
            "valor": "",
            "size": 4,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        12: {
            "label": "nome_empresa",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        13: {
            "label": "cargo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        14: {
            "label": "orgao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        15: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
    "TempoAnteriorRPPS": {
        "cfg": {"label": "", "valor": "", "size": 0, "tipo": ""},
        1: {
            "label": "identificador",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        2: {
            "label": "matricula",
            "valor": "",
            "size": 15,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        3: {
            "label": "cpf",
            "valor": "",
            "size": 11,
            "obrigatorio": "1*",
            "tipo": "num",
        },
        4: {
            "label": "nome",
            "valor": "",
            "size": 75,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        5: {
            "label": "data_nascimento",
            "valor": "",
            "size": 15,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        6: {
            "label": "data_inicio",
            "valor": "",
            "size": 10,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        7: {
            "label": "data_fim",
            "valor": "",
            "size": 10,
            "obrigatorio": "0",
            "tipo": "alfa",
        },
        8: {
            "label": "protocolo",
            "valor": "",
            "size": 30,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        9: {"label": "ano", "valor": "", "size": 4, "obrigatorio": "1*", "tipo": "num"},
        10: {
            "label": "nome_empresa",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        11: {
            "label": "cargo",
            "valor": "",
            "size": 100,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
        12: {
            "label": "orgao",
            "valor": "",
            "size": 100,
            "obrigatorio": "1*",
            "tipo": "alfa",
        },
        13: {
            "label": "separator",
            "valor": "ß",
            "size": 1,
            "obrigatorio": "1",
            "tipo": "alfa",
        },
    },
}
