# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estagio", "0007_auto_20190412_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrantescomissao",
            name="tipo_participante",
            field=models.CharField(
                choices=[
                    ("1", "PRESIDENTE"),
                    ("2", "SECRETÁRIO"),
                    ("3", "INTEGRANTE"),
                    ("4", "SUPLENTE"),
                ],
                default=4,
                max_length=1,
            ),
        ),
    ]
