# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0002_auto_20150810_1114"),
        ("contabilidade", "0002_auto_20150810_1114"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patrimonio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelaavaliacao",
            name="publicacao",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Publicacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="suspensao",
            name="aberto_por",
            field=models.ForeignKey(
                related_name="+", to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="suspensao",
            name="fechado_por",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="suspensao",
            name="nota_entrada",
            field=models.ForeignKey(
                related_name="suspensoes",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.NotaEntrada",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="prebaixa",
            name="portaria_commissao",
            field=models.ForeignKey(
                to="rh.Publicacao", on_delete=django.db.models.deletion.PROTECT
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimoniohistorico",
            name="autor",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimoniohistorico",
            name="localizacao",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Localizacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimoniohistorico",
            name="patrimonio",
            field=models.ForeignKey(
                related_name="historico",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Patrimonio",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimoniohistorico",
            name="responsavel",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimoniohistorico",
            name="utilizado_por",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimonio",
            name="documentos",
            field=models.ManyToManyField(
                related_name="documentos_do_patrimonio", to="patrimonio.Documento"
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimonio",
            name="item_entrada",
            field=models.ForeignKey(
                related_name="incorporacoes",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.ItemEntrada",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimonio",
            name="localizacao",
            field=models.ForeignKey(
                related_name="patrimonios",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Localizacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimonio",
            name="responsavel",
            field=models.ForeignKey(
                related_name="patrimonios",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="patrimonio",
            name="utilizado_por",
            field=models.ForeignKey(
                related_name="utilizando_patrimonios",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="parametroavaliacao",
            name="tabela",
            field=models.ForeignKey(
                related_name="valores_concervacao",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.TabelaAvaliacao",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaentrada",
            name="conta",
            field=models.ForeignKey(
                related_name="entradas",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Conta",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaentrada",
            name="documentos",
            field=models.ManyToManyField(
                related_name="documentos_de_entrada", to="patrimonio.Documento"
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaentrada",
            name="empenho",
            field=models.ForeignKey(
                related_name="movimentos_entrada_patrimonio",
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidade.NE",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaentrada",
            name="fornecedor",
            field=models.ForeignKey(
                related_name="movimentos_entrada_patrimonio",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Pessoa",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaentrada",
            name="tombado_por",
            field=models.ForeignKey(
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notaconvenio",
            name="conveniada",
            field=models.ForeignKey(
                related_name="convenios",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Pessoa",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notabaixa",
            name="conta",
            field=models.ForeignKey(
                related_name="baixas",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Conta",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="notabaixa",
            name="pre_baixa",
            field=models.ForeignKey(
                related_name="notas_baixa",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.PreBaixa",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentologstatus",
            name="atribuido_por",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentologstatus",
            name="movimento",
            field=models.ForeignKey(
                related_name="logs",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Movimento",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentoitem",
            name="movimento",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Movimento",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentoitem",
            name="patrimonio",
            field=models.ForeignKey(
                related_name="movement_items",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Patrimonio",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentoassinatura",
            name="movimento",
            field=models.ForeignKey(
                related_name="autorizacoes",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Movimento",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimentoassinatura",
            name="quem",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name="movimentoassinatura",
            unique_together=set([("movimento", "score")]),
        ),
        migrations.AddField(
            model_name="movimento",
            name="destino",
            field=models.ForeignKey(
                related_name="como_destino_em_movimentos",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Localizacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="documentos",
            field=models.ManyToManyField(
                related_name="documentos_de_movimentacao", to="patrimonio.Documento"
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="itens",
            field=models.ManyToManyField(
                related_name="movimentacoes",
                through="patrimonio.MovimentoItem",
                to="patrimonio.Patrimonio",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="movimentado_por",
            field=models.ForeignKey(
                related_name="movimentos",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="origem",
            field=models.ForeignKey(
                related_name="como_origem_em_movimentos",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Localizacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="recebido_por",
            field=models.ForeignKey(
                related_name="recebimentos",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="responsavel_destino",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="responsavel_origem",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Servidor",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="movimento",
            name="validado_por",
            field=models.ForeignKey(
                related_name="validacoes",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localizacao",
            name="dentro_de",
            field=models.ForeignKey(
                related_name="sub_espacos",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Localizacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="localizacao",
            name="lotacao_relacionada",
            field=models.ForeignKey(
                related_name="localizacoes_patrimoniais",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Lotacao",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="itementrada",
            name="especie",
            field=models.ForeignKey(
                related_name="itens",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Especie",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="itementrada",
            name="nota",
            field=models.ForeignKey(
                related_name="itens",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.NotaEntrada",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="itemavaliacao",
            name="especie",
            field=models.ForeignKey(
                related_name="itens_avaliacao",
                to="patrimonio.Especie",
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="itemavaliacao",
            name="grupo",
            field=models.ForeignKey(
                related_name="itens_avaliacao",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.GrupoEspecie",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="itemavaliacao",
            name="tabela",
            field=models.ForeignKey(
                related_name="itens",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.TabelaAvaliacao",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="especie",
            name="grupo",
            field=models.ForeignKey(
                related_name="especies",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.GrupoEspecie",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="documento",
            name="data",
            field=models.ForeignKey(
                related_name="como_documento_contabil",
                to="ged.Arquivo",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="conta",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Conta",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="empenho",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidade.NE",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="fornecedor",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Pessoa",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="nota",
            field=models.ForeignKey(
                related_name="criticas",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.NotaEntrada",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="por",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="criticarnotaentrada",
            name="respondido_por",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="conta",
            name="sequencia",
            field=models.ForeignKey(
                related_name="contas",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Sequencia",
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="baixatransferencia",
            name="favorecido",
            field=models.ForeignKey(
                related_name="favorecido_em_transferencias",
                to="patrimonio.Conta",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="baixaitem",
            name="nota",
            field=models.ForeignKey(
                related_name="itens",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.NotaBaixa",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="baixaitem",
            name="patrimonio",
            field=models.ForeignKey(
                related_name="baixas",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Patrimonio",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="baixadoacao",
            name="favorecido",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Pessoa",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="baixaalienacao",
            name="arrematante",
            field=models.ForeignKey(
                related_name="como_arrematantes",
                to="rh.Pessoa",
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="avaliacaoitem",
            name="avaliacao",
            field=models.ForeignKey(
                related_name="itens",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Avaliacao",
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="avaliacaoitem",
            name="discarded_by",
            field=models.ForeignKey(
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                null=True,
                on_delete=models.CASCADE,
            ),  # Parametro "on_delete" adicionado. (Django 2)
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="avaliacaoitem",
            name="patrimonio",
            field=models.ForeignKey(
                related_name="avaliacoes",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.Patrimonio",
            ),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name="avaliacaoitem",
            unique_together=set([("avaliacao", "patrimonio")]),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="executor",
            field=models.ForeignKey(
                related_name="+",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="tabela",
            field=models.ForeignKey(
                related_name="avaliacoes",
                on_delete=django.db.models.deletion.PROTECT,
                to="patrimonio.TabelaAvaliacao",
            ),
            preserve_default=True,
        ),
    ]
