# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-20 17:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patrimonio", "0014_add_notification_for_patrimonial_movement"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaixaAjusteInventario",
            fields=[
                (
                    "notabaixa_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="patrimonio.NotaBaixa",
                    ),
                ),
            ],
            bases=("patrimonio.notabaixa",),
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-modified_at",)},
        ),
    ]
