# Generated by Django 2.2.28 on 2024-02-14 17:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rh", "0294_load_fixture_gestor_batidas"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "menu_superior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="menus",
                        to="menu_permissoes.ItemMenu",
                    ),
                ),
            ],
            options={
                "ordering": ("titulo", "ativo"),
            },
        ),
        migrations.CreateModel(
            name="GrupoPermissao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Grupo"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "servidores",
                    models.ManyToManyField(
                        related_name="grupos_permissoes", to="rh.Servidor"
                    ),
                ),
            ],
            options={
                "ordering": ("nome", "ativo"),
            },
        ),
        migrations.CreateModel(
            name="ConfigsPermissaoItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acoes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissoes_configs",
                        to="menu_permissoes.GrupoPermissao",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissoes_configs",
                        to="menu_permissoes.ItemMenu",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permissoes_configs",
                        to="rh.Servidor",
                    ),
                ),
            ],
        ),
    ]
