# Generated by Django 2.2.28 on 2024-02-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grupopermissao",
            name="servidores",
        ),
        migrations.RemoveField(
            model_name="itemmenu",
            name="menu_superior",
        ),
        migrations.DeleteModel(
            name="ConfigsPermissaoItem",
        ),
        migrations.DeleteModel(
            name="GrupoPermissao",
        ),
        migrations.DeleteModel(
            name="ItemMenu",
        ),
    ]
