# Generated by Django 2.2.28 on 2024-02-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0003_auto_20240226_1917"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="ordem",
            field=models.SmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Ordem"
            ),
        ),
        migrations.AddField(
            model_name="menugrupo",
            name="ordem",
            field=models.SmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Ordem"
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="ordem",
            field=models.SmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Ordem"
            ),
        ),
    ]
