# Generated by Django 2.2.28 on 2024-02-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0004_auto_20240229_1210"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("ordem", "nome", "ativo")},
        ),
        migrations.AlterModelOptions(
            name="menugrupo",
            options={"ordering": ("ordem", "nome", "ativo")},
        ),
        migrations.AlterModelOptions(
            name="modulo",
            options={"ordering": ("ordem", "nome", "ativo")},
        ),
    ]
