# Generated by Django 2.2.28 on 2024-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0005_auto_20240229_1211"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("ordem", "nome")},
        ),
        migrations.AlterModelOptions(
            name="menugrupo",
            options={"ordering": ("ordem", "nome")},
        ),
        migrations.AlterModelOptions(
            name="modulo",
            options={"ordering": ("ordem", "nome")},
        ),
        migrations.AlterModelOptions(
            name="usuariogrupo",
            options={"ordering": ("nome",)},
        ),
        migrations.RemoveField(
            model_name="menu",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="menugrupo",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="modulo",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="usuariogrupo",
            name="ativo",
        ),
        migrations.AddField(
            model_name="menu",
            name="icone",
            field=models.TextField(blank=True, null=True, verbose_name="Ícone"),
        ),
        migrations.AddField(
            model_name="menu",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("PAUSADO", "Pausado"),
                ],
                db_index=True,
                default="ATIVO",
                max_length=20,
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="menugrupo",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="menugrupo",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("PAUSADO", "Pausado"),
                ],
                db_index=True,
                default="ATIVO",
                max_length=20,
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="modulo",
            name="sigla",
            field=models.CharField(
                db_index=True, max_length=50, null=True, verbose_name="Sigla"
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("PAUSADO", "Pausado"),
                ],
                db_index=True,
                default="ATIVO",
                max_length=20,
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="usuariogrupo",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("INATIVO", "Inativo"),
                    ("PAUSADO", "Pausado"),
                ],
                db_index=True,
                default="ATIVO",
                max_length=20,
                verbose_name="Ativo",
            ),
        ),
    ]
