# Generated by Django 2.2.28 on 2024-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0006_auto_20240305_1145"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariogrupo",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
