# Generated by Django 2.2.28 on 2024-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0007_usuariogrupo_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="url"
            ),
        ),
        migrations.AddField(
            model_name="menugrupo",
            name="icone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ícone"
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="icone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ícone"
            ),
        ),
        migrations.AddField(
            model_name="usuariogrupo",
            name="grupo_padrao",
            field=models.BooleanField(default=False, verbose_name="Grupo Padrão"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="icone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ícone"
            ),
        ),
    ]
