# Generated by Django 2.2.28 on 2024-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0009_auto_20240409_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariogrupo",
            name="servidores",
            field=models.ManyToManyField(
                related_name="grupos_permissao", to="rh.Servidor"
            ),
        ),
    ]
