# Generated by Django 4.2 on 2025-03-26 09:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_permissoes", "0015_menu_link_de_ajuda"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="cor",
            field=colorfield.fields.ColorField(
                default="#64748B", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="menugrupo",
            name="cor",
            field=colorfield.fields.ColorField(
                default="#64748B", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="cor",
            field=colorfield.fields.ColorField(
                default="#64748B", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menuconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menugrupo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usuariogrupo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
