# Generated by Django 2.2.24 on 2021-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_auto_20210428_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="position",
            field=models.IntegerField(
                blank=True, db_index=True, default=9999, null=True, verbose_name="Ordem"
            ),
        ),
    ]
