# Generated by Django 2.2.28 on 2023-09-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_load_fixture_lista_antiguidades_membros"),
        ("engine", "0016_auto_20230926_1751"),
    ]

    operations = []
