# Generated by Django 2.2.28 on 2023-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0017_merge_20230926_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllerpermission",
            name="manager_permission",
            field=models.BooleanField(
                default=False, verbose_name="Grupo de funcionalidade gestor"
            ),
        )
    ]
