# Generated by Django 4.2 on 2024-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0024_executar_create_job_users"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE auditlog_logentry ALTER COLUMN changes_text DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE auditlog_logentry ALTER COLUMN changes_text SET NOT NULL;
            """,
        ),
    ]
