# -*- coding: utf-8 -*-

NEOCONSIG = {
    "header": {  # Hearder de arquivo
        "cfg": {
            "label": "",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "tipo_de_registro", "value": 1, "size": 1, "type": "N"},
        2: {"label": "data_de_geracao", "value": 0, "size": 8, "type": "N"},
        3: {"label": "nome_do_arquivo", "value": "", "size": 20, "type": "A"},
    },
    "employees": {
        "cfg": {
            "label": "RETORNO_CONSIGNAÇÕES",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_secretaria", "value": 0, "size": 4, "type": "N"},
        4: {"label": "matricula", "value": 0, "size": 10, "type": "N"},
        5: {"label": "identificador", "value": 0, "size": 3, "type": "N"},
        6: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        7: {"label": "nome", "value": "", "size": 60, "type": "A"},
        8: {"label": "email", "value": "", "size": 50, "type": "A"},
        9: {"label": "endereco", "value": "", "size": 50, "type": "A"},
        10: {"label": "numero", "value": "", "size": 10, "type": "A"},
        11: {"label": "complemento", "value": "", "size": 20, "type": "A"},
        12: {"label": "bairro", "value": "", "size": 50, "type": "A"},
        13: {"label": "municipio", "value": "", "size": 50, "type": "A"},
        14: {"label": "uf", "value": "", "size": 2, "type": "A"},
        15: {"label": "cep", "value": 0, "size": 8, "type": "N"},
        16: {"label": "codigo_situacao", "value": 0, "size": 3, "type": "N"},
        17: {"label": "codigo_categoria", "value": 0, "size": 3, "type": "N"},
        18: {"label": "codigo_lotacao", "value": 0, "size": 7, "type": "N"},
        19: {"label": "admissao", "value": 0, "size": 8, "type": "N"},
        20: {"label": "afastamento", "value": 0, "size": 8, "type": "N"},
        21: {"label": "codigo_banco", "value": 0, "size": 3, "type": "N"},
        22: {"label": "codigo_agencia", "value": 0, "size": 6, "type": "N"},
        23: {"label": "conta", "value": 0, "size": 25, "type": "N"},
        24: {"label": "data_nascimento", "value": 0, "size": 8, "type": "N"},
        25: {"label": "telefone", "value": "", "size": 20, "type": "A"},
        26: {"label": "celular", "value": "", "size": 20, "type": "A"},
        27: {"label": "fonte_pagadora", "value": 0, "size": 2, "type": "N"},
    },
    "organs": {
        "cfg": {
            "label": "BASE_SALARIAL",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_secretaria", "value": 0, "size": 4, "type": "N"},
        4: {"label": "sigla", "value": "", "size": 20, "type": "A"},
        5: {"label": "nome", "value": "", "size": 50, "type": "A"},
    },
    "worklocations": {
        "cfg": {
            "label": "LOTACAO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_lotacao", "value": 0, "size": 7, "type": "N"},
        4: {"label": "nome", "value": "", "size": 50, "type": "A"},
    },
    "classifications": {
        "cfg": {
            "label": "CADCATEGORIA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_categoria", "value": 0, "size": 3, "type": "N"},
        4: {"label": "nome", "value": "", "size": 40, "type": "A"},
    },
    "situations": {
        "cfg": {
            "label": "CADSITFUNCIONAL",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_situacao", "value": 0, "size": 3, "type": "N"},
        4: {"label": "nome", "value": "", "size": 40, "type": "A"},
    },
    "events": {
        "cfg": {
            "label": "VANTAGEMDESCONTO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "rubrica", "value": 0, "size": 5, "type": "N"},
        4: {"label": "nome", "value": "", "size": 50, "type": "A"},
        5: {"label": "tipo", "value": "", "size": 1, "type": "A"},
        6: {"label": "participa_do_calculo", "value": "", "size": 1, "type": "A"},
    },
    "finacial": {
        "cfg": {
            "label": "FINANCEIRO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "competencia", "value": 0, "size": 6, "type": "N"},
        4: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        5: {"label": "matricula", "value": 0, "size": 10, "type": "N"},
        6: {"label": "identificador", "value": 0, "size": 3, "type": "N"},
        7: {"label": "tipo_lancamento", "value": "", "size": 1, "type": "A"},
        8: {"label": "codigo", "value": 0, "size": 4, "type": "N"},
        9: {"label": "valor_margem", "value": 0, "size": 15, "type": "N"},
    },
    "paidoff": {
        "cfg": {
            "label": "RETORNOQUITADAS",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "competencia", "value": 0, "size": 6, "type": "N"},
        4: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        5: {"label": "matricula", "value": 0, "size": 10, "type": "N"},
        6: {"label": "identificador", "value": 0, "size": 3, "type": "N"},
        7: {"label": "rubrica", "value": 0, "size": 5, "type": "N"},
        8: {"label": "valor_parcela", "value": 0, "size": 15, "type": "N"},
        9: {"label": "numero_da_parcela", "value": 0, "size": 3, "type": "N"},
        10: {"label": "total_de_parcelas", "value": 0, "size": 3, "type": "N"},
        11: {"label": "id_da_operacao", "value": 0, "size": 10, "type": "N"},
    },
    "history": {
        "cfg": {
            "label": "CARGAEMPRESTIMO",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "data_da_operacao", "value": 0, "size": 8, "type": "N"},
        4: {"label": "rubrica", "value": 0, "size": 5, "type": "N"},
        5: {"label": "matricula", "value": 0, "size": 10, "type": "N"},
        6: {"label": "identificador", "value": 0, "size": 3, "type": "N"},
        7: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        8: {"label": "valor_da_parcela", "value": 0, "size": 15, "type": "N"},
        9: {"label": "total_de_parcelas", "value": 0, "size": 3, "type": "N"},
        10: {"label": "parcela_atual", "value": 0, "size": 3, "type": "N"},
        11: {"label": "status_da_operacao", "value": 0, "size": 1, "type": "N"},
        12: {"label": "tipo_operacao", "value": 0, "size": 2, "type": "N"},
        13: {"label": "data_parcela_atual", "value": 0, "size": 8, "type": "N"},
    },
    "consignee": {
        "cfg": {
            "label": "CADCONSIGNATARIA",
            "value": 0,
            "size": 0,
            "type": "",
            "version": "01.0",
            "lenght": 0,
        },
        1: {"label": "inicial", "value": 2, "size": 1, "type": "N"},
        2: {"label": "sequencial", "value": 0, "size": 9, "type": "N"},
        3: {"label": "codigo_consignataria", "value": 0, "size": 4, "type": "N"},
        4: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        5: {"label": "razao_social", "value": "", "size": 60, "type": "A"},
        6: {"label": "nome_fantasia", "value": "", "size": 60, "type": "A"},
        7: {"label": "rubrica", "value": 0, "size": 5, "type": "N"},
    },
}
