# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0002_fixtures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reward",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "reward",
                "verbose_name_plural": "rewards",
            },
        ),
        migrations.AddField(
            model_name="reward",
            name="players",
            field=models.ManyToManyField(
                related_name="rewards",
                through="distribution.Match",
                to="distribution.Player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="incident_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Incidente 1"),
                    (2, "Incidente 2"),
                    (3, "Incidente 3"),
                    (4, "Incidente 4"),
                    (5, "Incidente 5"),
                ],
                default=1,
                verbose_name="Tipo de Incidente",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="distribution.Reward",
                verbose_name="Objeto",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_winner_of_rewards",
                to="distribution.Player",
                verbose_name="Escolhido",
            ),
        ),
    ]
