# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0003_auto_20190628_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="accumulated_score",
            field=models.IntegerField(default=0, verbose_name="Pontos acumulados"),
        ),
    ]
