# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_auto_20190207_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="genero",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="G\xeanero"
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="genero_can_edit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="genero_diff",
            field=models.BooleanField(default=False),
        ),
    ]
