# Generated by Django 2.2.12 on 2020-05-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0115_auto_20200506_1551"),
        ("registration", "0008_auto_20190725_1855"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_entry_condition",
            field=models.IntegerField(
                default=10, verbose_name="Condição de ingresso do imigrante"
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_entry_condition_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_entry_condition_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_residence_time",
            field=models.IntegerField(
                default=10, verbose_name="Tempo de residência do imigrante"
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_residence_time_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="immigrant_residence_time_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="nationality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rh.Pais",
                verbose_name="Nacionalidade",
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="nationality_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="nationality_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                ],
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_city_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_complement_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_country_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_district_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_number_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_outsider",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Endereço no exterior"
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_outsider_citty_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_outsider_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_public_place_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_type_address_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_type_street",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "AVENIDA"),
                    (2, "PRAÇA"),
                    (3, "VIELA"),
                    (4, "PONTO - SERA EXCLUIDO"),
                    (5, "VIADUTO"),
                    (7, "OUTROS - SERA EXCLUIDO"),
                    (8, "RUA"),
                    (9, "QUADRA"),
                    (100, "EXTERIOR"),
                ],
                null=True,
                verbose_name="Endereço - Tipo do Logradouro",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_type_street_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="address_zip_code_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="classe_reservista_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_categoria_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_expedition_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_first_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_state_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cnh_validity_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="contact_emergency_name_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="contact_emergency_name_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="contact_emergency_phone_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="contact_emergency_phone_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cpf_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cpf_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="cpf_doc_digital_required",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ctps_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ctps_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ctps_state_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="data_nascimento_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="data_nascimento_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="doador",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Doador de órgãos"
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="doador_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="doador_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="email_pessoal_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="email_pessoal_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="estado_civil_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="estado_civil_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="fator_rh",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "-"), (2, "+"), (3, "NAO INFORMADO")],
                default=2,
                null=True,
                verbose_name="Fator RH",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="fator_rh_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="fator_rh_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="foto_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="foto_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="genero_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="genero_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="grau_instrucao_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="grau_instrucao_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="municipio_naturalidade_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="municipio_naturalidade_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="municipio_titulo_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nis_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nis_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_conjuge_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_conjuge_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_doc_digital_required",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_mae_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_mae_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_pai_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nome_pai_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="phone_main_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="phone_main_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="phone_outsider",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Telefone no exterior"
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="phone_outsider_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="pis_pasep_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="pis_pasep_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="professional_council_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="professional_council_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="professional_council_expedition_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="professional_council_issuer_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="professional_council_state_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="raca_cor_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="raca_cor_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="reservista_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="reservista_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rg_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rg_data_expedicao_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rg_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rg_orgao_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rg_uf_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ric_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ric_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ric_expedition_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ric_issuer_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="ric_state_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rne_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rne_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rne_expedition_date_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rne_issuer_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="rne_state_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sangue",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "B"), (2, "AB"), (3, "O"), (4, "A"), (5, "NAO INFORMADO")],
                default=4,
                verbose_name="Tipo Sanguíneo",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sangue_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sangue_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="secao_titulo_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="serie_ctps_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sexo_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sexo_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sexual_orientation_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sexual_orientation_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="social_name_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="social_name_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="titulo_eleitor_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="titulo_eleitor_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="uniao_estavel",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="União Estável"
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="uniao_estavel_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="uniao_estavel_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="zona_titulo_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
