# Generated by Django 2.2.12 on 2020-05-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0117_auto_20200513_1732"),
        ("registration", "0009_auto_20200506_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="nationality_birth",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forminformation_nationality_birth",
                to="rh.Pais",
                verbose_name="Nacionalidade",
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="nationality_birth_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="nationality_birth_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="immigrant_entry_condition",
            field=models.IntegerField(
                choices=[
                    (10, "NÃO É IMIGRANTE"),
                    (1, "Refugiado"),
                    (2, "Solicitante de refúgio"),
                    (3, "Permanência no Brasil em razão de reunião familiar"),
                    (4, "Beneficiado pelo acordo entre países do Mercosul"),
                    (
                        5,
                        "Dependente de agente diplomático/consular de países que mantêm acordo de reciprocidade p/ exercício atividade remunerada",
                    ),
                    (
                        6,
                        "Beneficiado pelo Tratado de Amizade, Cooperação e Consulta entre a República Federativa do Brasil e República Portuguesa",
                    ),
                    (7, "Outra condição"),
                ],
                default=10,
                verbose_name="Condição de ingresso do imigrante",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="immigrant_residence_time",
            field=models.IntegerField(
                choices=[
                    (10, "NÃO É IMIGRANTE"),
                    (1, "PRAZO INDETERMINADO"),
                    (2, "PRAZO DETERMINADO"),
                ],
                default=10,
                verbose_name="Tempo de residência do imigrante",
            ),
        ),
    ]
