# Generated by Django 2.2.18 on 2021-02-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20200513_1732"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forminformation",
            options={
                "ordering": ("sent_at",),
                "permissions": (("registration_admin", "Admin"),),
                "verbose_name": "Formulário de Informações - Recadastramento",
            },
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (59, "COMPROVANTE DE VOTAÇÂO - ELEIÇÕES MUNICIPAIS 2020"),
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                ],
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="nationality_birth",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forminformation_nationality_birth",
                to="rh.Pais",
                verbose_name="País de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="validation",
            name="form_information",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validations",
                to="registration.FormInformation",
            ),
        ),
    ]
