# Generated by Django 2.2.20 on 2021-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0013_auto_20210713_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="address_new",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Endereço novo"
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="address_new_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
