# Generated by Django 2.2.27 on 2022-02-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0162_auto_20220214_1240"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0014_auto_20211008_1510"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                ],
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.CreateModel(
            name="DependentFormInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "EDIÇÃO DO SERVIDOR"),
                            (2, "ENVIADO AO DGPFP"),
                            (3, "RECEBIDO DGPFP"),
                            (4, "COM PENDÊNCIA"),
                            (5, "VALIDADO "),
                        ],
                        default=1,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cpf_dependent_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "cpf_dependent",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "cpf_dependent_doc_digital_required",
                    models.BooleanField(blank=True, default=True),
                ),
                ("cpf_dependent_diff", models.BooleanField(blank=True, default=False)),
                (
                    "data_inicio_dependent_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "data_inicio_dependent",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_inicio_dependent_diff",
                    models.BooleanField(blank=True, default=False),
                ),
                (
                    "data_nascimento_dependent_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "data_nascimento_dependent",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "data_nascimento_dependent_diff",
                    models.BooleanField(blank=True, default=False),
                ),
                (
                    "grau_parentesco_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "grau_parentesco",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO"),
                            (3, "FILHO(A)"),
                            (4, "PAI/MÃE"),
                            (5, "IRMÃO"),
                            (6, "ENTEADO"),
                            (7, "MENOR TUTELADO"),
                            (8, "EX-CÔNJUGE"),
                            (9, "NETOS"),
                            (10, "OUTROS"),
                            (11, "OUTROS - DEPENDÊNCIA ECONÔMICA"),
                        ],
                        null=True,
                        verbose_name="Grau de Parentesco",
                    ),
                ),
                (
                    "grau_parentesco_diff",
                    models.BooleanField(blank=True, default=False),
                ),
                (
                    "nome_dependent_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "nome_dependent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                ("nome_dependent_diff", models.BooleanField(blank=True, default=False)),
                (
                    "nome_dependent_doc_digital_required",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "sexo_dependent_can_edit",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "sexo_dependent",
                    models.CharField(
                        blank=True,
                        choices=[("M", "MASCULINO"), ("F", "FEMININO")],
                        max_length=1,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                ("sexo_dependent_diff", models.BooleanField(blank=True, default=False)),
                ("tipo_can_edit", models.BooleanField(blank=True, default=True)),
                (
                    "tipo",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "CÔNJUGE"),
                            (2, "COMPANHEIRO(A) - UNIÃO ESTÁVEL"),
                            (3, "FILHO(A) NÃO EMANCIPADO MENOR DE 21 ANOS"),
                            (
                                4,
                                "FILHO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (5, "PAI(MÃE) COM DEPENDÊNCIA ECONÔMICA"),
                            (
                                6,
                                "IRMÃO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                7,
                                "IRMAO(A) ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (8, "ENTEADO NÃO EMANCIPADO MENOR DE 21"),
                            (
                                9,
                                "ENTEADO ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (
                                10,
                                "MENOR TUTELADO NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA OU GUARDA JUDICIAL",
                            ),
                            (
                                11,
                                "MENOR ABSOLUTAMENTE INCAPAZ DO QUAL SEJA TUTOR OU CURADOR",
                            ),
                            (12, "AVÓS COM DEPENDENCIA ECONOMICA"),
                            (13, "BISAVÓS COM DEPENDENCIA ECONOMICA"),
                            (
                                14,
                                "NETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (
                                15,
                                "BISNETO(A) NÃO EMANCIPADO MENOR DE 21 ANOS COM DEPENDÊNCIA ECONÔMICA E GUARDA JUDICIAL",
                            ),
                            (16, " EX-CÔNJUGE"),
                            (
                                17,
                                "FILHO(A) OU ENTEADO(A) UNIVERSITÁRIO(A) OU CURSANDO ESCOLA TÉCNICA DE 2ºGRAU, ATÉ 24 ANOS",
                            ),
                            (18, "AGREGADO/OUTROS"),
                        ],
                        null=True,
                        verbose_name="Tipo de Dependete",
                    ),
                ),
                ("tipo_diff", models.BooleanField(blank=True, default=False)),
                ("incapacity_can_edit", models.BooleanField(blank=True, default=True)),
                (
                    "incapacity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Incapacidade física/mental",
                    ),
                ),
                ("incapacity_diff", models.BooleanField(blank=True, default=False)),
                (
                    "incapacity_doc_digital_required",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rh.Dependente",
                        verbose_name="Dependente",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rh.Servidor"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
    ]
