# Generated by Django 2.2.27 on 2022-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_auto_20220214_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="contact_emergency_phone_kinship",
            field=models.CharField(
                blank=True,
                default="",
                max_length=13,
                null=True,
                verbose_name="Grau de Parentesco/Contato de Emergência",
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="contact_emergency_phone_kinship_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="contact_emergency_phone_kinship_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
