# Generated by Django 2.2.28 on 2022-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_auto_20220412_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="dependentforminformation",
            name="sexo_dependent",
            field=models.CharField(
                blank=True,
                choices=[("M", "MASCULINO"), ("F", "FEMININO"), ("N", "NÃO INFORMADO")],
                max_length=1,
                null=True,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="digitaldocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (59, "COMPROVANTE DE VOTAÇÂO - ELEIÇÕES MUNICIPAIS 2020"),
                    (56, "COMPROVANTE VOTAÇÃO 2018 - GERAL"),
                    (55, "COMPROVANTE VOTAÇÃO 2018 - SUPLEMENTAR"),
                    (1, "TÍTULO DE ELEITOR"),
                    (2, "CNH"),
                    (3, "CTPS"),
                    (5, "NIS"),
                    (6, "PIS/PASEP"),
                    (9, "RESERVISTA"),
                    (10, "CONSELHO PROFISSIONAL"),
                    (11, "RIC"),
                    (12, "RNE"),
                    (13, "CPF"),
                    (14, "RG"),
                    (15, "PASSAPORTE"),
                    (50, "CERTIDÃO DE NASCIMENTO"),
                    (51, "CERTIDÃO DE CASAMENTO/DIVÓRCIO"),
                    (52, "COMPROVANTE DE ENDEREÇO"),
                    (53, "TERMO DE CUSTODIA DE MENOR"),
                    (54, "UNIAO ESTAVEL"),
                    (57, "ANEXO"),
                    (58, "ANOTAÇÃO"),
                    (60, "CURRÍCULO"),
                ],
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="raca_cor",
            field=models.IntegerField(
                choices=[
                    (1, "PARDA"),
                    (2, "AMARELA"),
                    (3, "NEGRA"),
                    (4, "INDÍGENA"),
                    (5, "NÃO INFORMADO"),
                    (6, "BRANCA"),
                ],
                default=5,
                null=True,
                verbose_name="Raça/Cor",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "MASCULINO"), ("F", "FEMININO"), ("N", "NÃO INFORMADO")],
                max_length=1,
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
