# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0019_auto_20221212_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forminformation",
            name="contact_emergency_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                null=True,
                verbose_name="Telefone de Emergência",
            ),
        ),
        migrations.AlterField(
            model_name="forminformation",
            name="phone_main",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                null=True,
                verbose_name="Telefone Principal",
            ),
        ),
    ]
