# Generated by Django 2.2.28 on 2023-02-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0020_auto_20230112_1053"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forminformation",
            old_name="email_pessoal",
            new_name="email_institucional",
        ),
        migrations.RenameField(
            model_name="forminformation",
            old_name="email_pessoal_can_edit",
            new_name="email_institucional_can_edit",
        ),
        migrations.RenameField(
            model_name="forminformation",
            old_name="email_pessoal_diff",
            new_name="email_institucional_diff",
        ),
    ]
