# Generated by Django 2.2.28 on 2023-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0021_auto_20230216_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forminformation",
            name="email_institucional",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                null=True,
                verbose_name="E-mail Institucional",
            ),
        ),
    ]
