# Generated by Django 2.2.28 on 2023-02-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0022_auto_20230216_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="forminformation",
            name="email_pessoal",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                null=True,
                verbose_name="E-mail Pessoal",
            ),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="email_pessoal_can_edit",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="forminformation",
            name="email_pessoal_diff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
