# -*- coding:utf-8 -*-

import importlib
from django.apps import AppConfig


class AFAConfig(AppConfig):
    name = "rh.afastamento"
    default_auto_field = "django.db.models.BigAutoField"

    controllers = [
        "rh.afastamento.views",
        "rh.afastamento.reports",
        "rh.afastamento.api.afastamento",
        "rh.afastamento.api.atuacaogrupotrabalho",
        "rh.afastamento.api.ausencia",
        "rh.afastamento.api.baselicencaafastamento",
        "rh.afastamento.api.cid",
        "rh.afastamento.api.desempenhofuncao",
        "rh.afastamento.api.feriasafastamento",
        "rh.afastamento.api.folgacompensacao",
        "rh.afastamento.api.folgaaniversario",
        "rh.afastamento.api.folgaeleitoral",
        "rh.afastamento.api.licenca",
        "rh.afastamento.api.licencasaude",
        "rh.afastamento.api.manager",
        "rh.afastamento.api.plantao",
        "rh.afastamento.api.recesso",
        "rh.afastamento.api.viagem",
        "rh.afastamento.api.bancodehoras",
        "rh.afastamento.api.healthcertificate",
        "rh.afastamento.api.healthprevent",
    ]

    def ready(self):
        """
        O carregamento de partes necessárias ao app.
        """
        register_statics()
        connect_signals()
        loaders()
        # carregar qualquer outra coisa necessária ao app


def connect_signals():
    pass


def register_statics():
    Application = importlib.import_module("default.views").Application

    js_paths = (
        "/%(context)s/static/rh/js/core.js",
        "/%(context)s/static/rh/js/rh.utils.js",
        "/%(context)s/static/rh/js/rh.gestorafastamento.utils.js",
        "/%(context)s/static/rh/js/rh.gestorafastamento.js",
        "/%(context)s/static/rh/afastamento/healthcertificate/Restful.js",
        "/%(context)s/static/rh/afastamento/healthcertificate/Window.js",
        "/%(context)s/static/rh/afastamento/healthcertificate/Grid.js",
        "/%(context)s/static/rh/afastamento/healthcertificate/Manage.js",
        "/%(context)s/static/rh/afastamento/baselicencaafastamento/Restful.js",
        "/%(context)s/static/rh/afastamento/baselicencaafastamento/Window.js",
        "/%(context)s/static/rh/afastamento/baselicencaafastamento/Grid.js",
        "/%(context)s/static/rh/afastamento/baselicencaafastamento/Manage.js",
        "/%(context)s/static/rh/afastamento/ManagerRestful.js",
        "/%(context)s/static/rh/afastamento/ManagerTab.js",
        "/%(context)s/static/rh/afastamento/ManagerGrid.js",
        "/%(context)s/static/rh/afastamento/ManagerWindow.js",
        "/%(context)s/static/rh/afastamento/ManagerSubstitutionWindow.js",
        "/%(context)s/static/rh/afastamento/Manager.js",
        "/%(context)s/static/rh/afastamento/council/ManagerGrid.js",
        "/%(context)s/static/rh/afastamento/council/ManagerTab.js",
        "/%(context)s/static/rh/afastamento/council/Manage.js",
        "/%(context)s/static/rh/afastamento/ManagerEmployeeRestful.js",
        "/%(context)s/static/rh/afastamento/ManagerEmployeeGrid.js",
        "/%(context)s/static/rh/afastamento/ManagerEmployeeWindow.js",
        "/%(context)s/static/rh/afastamento/ManagerEmployee.js",
        "/%(context)s/static/rh/afastamento/workassignment/Restful.js",
        "/%(context)s/static/rh/afastamento/workassignment/WorkassignmentGrid.js",
        "/%(context)s/static/rh/afastamento/workassignment/WorkAssignmentWindow.js",
        "/%(context)s/static/rh/afastamento/feriasafastamento/Restful.js",
        "/%(context)s/static/rh/afastamento/feriasafastamento/Window.js",
        "/%(context)s/static/rh/afastamento/feriasafastamento/Grid.js",
        "/%(context)s/static/rh/afastamento/feriasafastamento/Manage.js",
        "/%(context)s/static/rh/afastamento/folgacompensacao/Restful.js",
        "/%(context)s/static/rh/afastamento/folgacompensacao/Window.js",
        "/%(context)s/static/rh/afastamento/folgacompensacao/Grid.js",
        "/%(context)s/static/rh/afastamento/folgacompensacao/Manage.js",
        "/%(context)s/static/rh/afastamento/bancodehoras/Restful.js",
        "/%(context)s/static/rh/afastamento/bancodehoras/Window.js",
        "/%(context)s/static/rh/afastamento/bancodehoras/Grid.js",
        "/%(context)s/static/rh/afastamento/bancodehoras/Manage.js",
        "/%(context)s/static/rh/afastamento/recesso/Restful.js",
        "/%(context)s/static/rh/afastamento/recesso/Window.js",
        "/%(context)s/static/rh/afastamento/recesso/Grid.js",
        "/%(context)s/static/rh/afastamento/recesso/Manage.js",
        "/%(context)s/static/rh/afastamento/recesso/BatchRecessWindow.js",
        "/%(context)s/static/rh/afastamento/viagem/Restful.js",
        "/%(context)s/static/rh/afastamento/viagem/Window.js",
        "/%(context)s/static/rh/afastamento/viagem/Grid.js",
        "/%(context)s/static/rh/afastamento/viagem/Manage.js",
        "/%(context)s/static/rh/afastamento/atuacaogrupotrabalho/Restful.js",
        "/%(context)s/static/rh/afastamento/atuacaogrupotrabalho/Window.js",
        "/%(context)s/static/rh/afastamento/atuacaogrupotrabalho/Grid.js",
        "/%(context)s/static/rh/afastamento/atuacaogrupotrabalho/Manage.js",
        "/%(context)s/static/rh/afastamento/desempenhofuncao/Restful.js",
        "/%(context)s/static/rh/afastamento/desempenhofuncao/Window.js",
        "/%(context)s/static/rh/afastamento/desempenhofuncao/Grid.js",
        "/%(context)s/static/rh/afastamento/desempenhofuncao/Manage.js",
        "/%(context)s/static/rh/afastamento/folgaaniversario/Restful.js",
        "/%(context)s/static/rh/afastamento/folgaaniversario/Window.js",
        "/%(context)s/static/rh/afastamento/folgaaniversario/Grid.js",
        "/%(context)s/static/rh/afastamento/folgaaniversario/Manage.js",
        "/%(context)s/static/rh/afastamento/healthprevent/Restful.js",
        "/%(context)s/static/rh/afastamento/healthprevent/Window.js",
        "/%(context)s/static/rh/afastamento/healthprevent/Grid.js",
        "/%(context)s/static/rh/afastamento/healthprevent/Manage.js",
        "/%(context)s/static/rh/afastamento/folgaeleitoral/Restful.js",
        "/%(context)s/static/rh/afastamento/folgaeleitoral/Window.js",
        "/%(context)s/static/rh/afastamento/folgaeleitoral/Grid.js",
        "/%(context)s/static/rh/afastamento/folgaeleitoral/Manage.js",
        "/%(context)s/static/rh/afastamento/plantao/Restful.js",
        "/%(context)s/static/rh/afastamento/plantao/Window.js",
        "/%(context)s/static/rh/afastamento/plantao/Grid.js",
        "/%(context)s/static/rh/afastamento/plantao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamento/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamento/Window.js",
        "/%(context)s/static/rh/afastamento/afastamento/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamento/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentocomparecimentojuizo/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentocomparecimentojuizo/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentocomparecimentojuizo/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentocomparecimentojuizo/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentocandidatura/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentocandidatura/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentocandidatura/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentocandidatura/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentocompeticao/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentocompeticao/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentocompeticao/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentocompeticao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentocursoconcurso/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentocursoconcurso/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentocursoconcurso/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentocursoconcurso/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentodeslocamento/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentodeslocamento/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentodeslocamento/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentodeslocamento/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentoeleitoral/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentoeleitoral/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentoeleitoral/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentoeleitoral/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentoestudar/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentoestudar/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentoestudar/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentoestudar/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentoparcialestudar/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentoparcialestudar/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentoparcialestudar/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentoparcialestudar/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentomandatoeletivo/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentomandatoeletivo/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentomandatoeletivo/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentomandatoeletivo/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentomissao/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentomissao/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentomissao/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentomissao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentooutroorgao/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentooutroorgao/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentooutroorgao/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentooutroorgao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentodisponibilidade/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentodisponibilidade/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentodisponibilidade/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentodisponibilidade/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentoprisao/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentoprisao/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentoprisao/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentoprisao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentoservirjuri/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentoservirjuri/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentoservirjuri/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentoservirjuri/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentosuspensao/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentosuspensao/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentosuspensao/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentosuspensao/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentosindicanciaadm/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentosindicanciaadm/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentosindicanciaadm/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentosindicanciaadm/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentotreinamento/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentotreinamento/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentotreinamento/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentotreinamento/Manage.js",
        "/%(context)s/static/rh/afastamento/ausencia/Restful.js",
        "/%(context)s/static/rh/afastamento/ausencia/Window.js",
        "/%(context)s/static/rh/afastamento/ausencia/Grid.js",
        "/%(context)s/static/rh/afastamento/ausencia/Manage.js",
        "/%(context)s/static/rh/afastamento/ausenciacasamento/Restful.js",
        "/%(context)s/static/rh/afastamento/ausenciacasamento/Window.js",
        "/%(context)s/static/rh/afastamento/ausenciacasamento/Grid.js",
        "/%(context)s/static/rh/afastamento/ausenciacasamento/Manage.js",
        "/%(context)s/static/rh/afastamento/ausenciaconclusao/Restful.js",
        "/%(context)s/static/rh/afastamento/ausenciaconclusao/Window.js",
        "/%(context)s/static/rh/afastamento/ausenciaconclusao/Grid.js",
        "/%(context)s/static/rh/afastamento/ausenciaconclusao/Manage.js",
        "/%(context)s/static/rh/afastamento/ausenciadoacaosangue/Restful.js",
        "/%(context)s/static/rh/afastamento/ausenciadoacaosangue/Window.js",
        "/%(context)s/static/rh/afastamento/ausenciadoacaosangue/Grid.js",
        "/%(context)s/static/rh/afastamento/ausenciadoacaosangue/Manage.js",
        "/%(context)s/static/rh/afastamento/ausenciaeleitor/Restful.js",
        "/%(context)s/static/rh/afastamento/ausenciaeleitor/Window.js",
        "/%(context)s/static/rh/afastamento/ausenciaeleitor/Grid.js",
        "/%(context)s/static/rh/afastamento/ausenciaeleitor/Manage.js",
        "/%(context)s/static/rh/afastamento/ausenciafalecimento/Restful.js",
        "/%(context)s/static/rh/afastamento/ausenciafalecimento/Window.js",
        "/%(context)s/static/rh/afastamento/ausenciafalecimento/Grid.js",
        "/%(context)s/static/rh/afastamento/ausenciafalecimento/Manage.js",
        "/%(context)s/static/rh/afastamento/ausencianascimento/Restful.js",
        "/%(context)s/static/rh/afastamento/ausencianascimento/Window.js",
        "/%(context)s/static/rh/afastamento/ausencianascimento/Grid.js",
        "/%(context)s/static/rh/afastamento/ausencianascimento/Manage.js",
        "/%(context)s/static/rh/afastamento/licenca/Restful.js",
        "/%(context)s/static/rh/afastamento/licenca/Window.js",
        "/%(context)s/static/rh/afastamento/licenca/Grid.js",
        "/%(context)s/static/rh/afastamento/licenca/Manage.js",
        "/%(context)s/static/rh/afastamento/licencasaude/Restful.js",
        "/%(context)s/static/rh/afastamento/licencasaude/Window.js",
        "/%(context)s/static/rh/afastamento/licencasaude/Grid.js",
        "/%(context)s/static/rh/afastamento/licencasaude/Manage.js",
        "/%(context)s/static/rh/afastamento/licencasaudejuntamedica/Restful.js",
        "/%(context)s/static/rh/afastamento/licencasaudejuntamedica/Window.js",
        "/%(context)s/static/rh/afastamento/licencasaudejuntamedica/Grid.js",
        "/%(context)s/static/rh/afastamento/licencasaudejuntamedica/Manage.js",
        "/%(context)s/static/rh/afastamento/licencaadocao/Restful.js",
        "/%(context)s/static/rh/afastamento/licencaadocao/Window.js",
        "/%(context)s/static/rh/afastamento/licencaadocao/Grid.js",
        "/%(context)s/static/rh/afastamento/licencaadocao/Manage.js",
        "/%(context)s/static/rh/afastamento/licencaafastamentoconjuge/Restful.js",
        "/%(context)s/static/rh/afastamento/licencaafastamentoconjuge/Window.js",
        "/%(context)s/static/rh/afastamento/licencaafastamentoconjuge/Grid.js",
        "/%(context)s/static/rh/afastamento/licencaafastamentoconjuge/Manage.js",
        "/%(context)s/static/rh/afastamento/licencaatividadepolitica/Restful.js",
        "/%(context)s/static/rh/afastamento/licencaatividadepolitica/Window.js",
        "/%(context)s/static/rh/afastamento/licencaatividadepolitica/Grid.js",
        "/%(context)s/static/rh/afastamento/licencaatividadepolitica/Manage.js",
        "/%(context)s/static/rh/afastamento/licencacapacitacao/Restful.js",
        "/%(context)s/static/rh/afastamento/licencacapacitacao/Window.js",
        "/%(context)s/static/rh/afastamento/licencacapacitacao/Grid.js",
        "/%(context)s/static/rh/afastamento/licencacapacitacao/Manage.js",
        "/%(context)s/static/rh/afastamento/licencadoencapessoafamilia/Restful.js",
        "/%(context)s/static/rh/afastamento/licencadoencapessoafamilia/Window.js",
        "/%(context)s/static/rh/afastamento/licencadoencapessoafamilia/Grid.js",
        "/%(context)s/static/rh/afastamento/licencadoencapessoafamilia/Manage.js",
        "/%(context)s/static/rh/afastamento/licencainteresseparticular/Restful.js",
        "/%(context)s/static/rh/afastamento/licencainteresseparticular/Window.js",
        "/%(context)s/static/rh/afastamento/licencainteresseparticular/Grid.js",
        "/%(context)s/static/rh/afastamento/licencainteresseparticular/Manage.js",
        "/%(context)s/static/rh/afastamento/licencamandatoclassista/Restful.js",
        "/%(context)s/static/rh/afastamento/licencamandatoclassista/Window.js",
        "/%(context)s/static/rh/afastamento/licencamandatoclassista/Grid.js",
        "/%(context)s/static/rh/afastamento/licencamandatoclassista/Manage.js",
        "/%(context)s/static/rh/afastamento/awardlicense/Restful.js",
        "/%(context)s/static/rh/afastamento/awardlicense/Window.js",
        "/%(context)s/static/rh/afastamento/awardlicense/Grid.js",
        "/%(context)s/static/rh/afastamento/awardlicense/Manage.js",
        "/%(context)s/static/rh/afastamento/licencamaternidade/Restful.js",
        "/%(context)s/static/rh/afastamento/licencamaternidade/Window.js",
        "/%(context)s/static/rh/afastamento/licencamaternidade/Grid.js",
        "/%(context)s/static/rh/afastamento/licencamaternidade/Manage.js",
        "/%(context)s/static/rh/afastamento/licencasaude30dias/Restful.js",
        "/%(context)s/static/rh/afastamento/licencasaude30dias/Window.js",
        "/%(context)s/static/rh/afastamento/licencasaude30dias/Grid.js",
        "/%(context)s/static/rh/afastamento/licencasaude30dias/Manage.js",
        "/%(context)s/static/rh/afastamento/licencasaude3dias/Restful.js",
        "/%(context)s/static/rh/afastamento/licencasaude3dias/Window.js",
        "/%(context)s/static/rh/afastamento/licencasaude3dias/Grid.js",
        "/%(context)s/static/rh/afastamento/licencasaude3dias/Manage.js",
        "/%(context)s/static/rh/afastamento/licencasaudehoras/Restful.js",
        "/%(context)s/static/rh/afastamento/licencasaudehoras/Window.js",
        "/%(context)s/static/rh/afastamento/licencasaudehoras/Grid.js",
        "/%(context)s/static/rh/afastamento/licencasaudehoras/Manage.js",
        "/%(context)s/static/rh/afastamento/licencaservicomilitar/Restful.js",
        "/%(context)s/static/rh/afastamento/licencaservicomilitar/Window.js",
        "/%(context)s/static/rh/afastamento/licencaservicomilitar/Grid.js",
        "/%(context)s/static/rh/afastamento/licencaservicomilitar/Manage.js",
        "/%(context)s/static/rh/afastamento/cid/Restful.js",
        "/%(context)s/static/rh/afastamento/cid/Window.js",
        "/%(context)s/static/rh/afastamento/cid/Grid.js",
        "/%(context)s/static/rh/afastamento/cid/Manage.js",
        "/%(context)s/static/rh/afastamento/cid/code/Restful.js",
        "/%(context)s/static/rh/afastamento/cid/code/Window.js",
        "/%(context)s/static/rh/afastamento/cid/code/Grid.js",
        "/%(context)s/static/rh/afastamento/cid/code/Manage.js",
        "/%(context)s/static/rh/afastamento/afastamentorecessoforense/Restful.js",
        "/%(context)s/static/rh/afastamento/afastamentorecessoforense/Window.js",
        "/%(context)s/static/rh/afastamento/afastamentorecessoforense/Grid.js",
        "/%(context)s/static/rh/afastamento/afastamentorecessoforense/Manage.js",
    )

    for path in js_paths:
        scope = "rh"
        if isinstance(path, list):
            scope = path[1]
            path = path[0]
        Application.register_javascript(path, scope="rh")


def loaders():
    importlib.import_module("rh.afastamento.signals.afastamento")
