# Generated by Django 2.2.28 on 2023-01-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("concurso", "0002_auto_20150810_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selecaoestagio",
            name="ano_conclusao",
            field=models.DateField(db_index=True, verbose_name="Previsão de Conclusão"),
        ),
        migrations.AlterField(
            model_name="selecaoestagio",
            name="ano_periodo",
            field=models.CharField(max_length=8, verbose_name="Ano/Período"),
        ),
        migrations.AlterField(
            model_name="selecaoestagio",
            name="disponibilidade",
            field=models.IntegerField(
                choices=[(1, "Manhã"), (2, "Tarde")], default=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="selecaoestagio",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="para_estagio",
                to="concurso.Inscricao",
                verbose_name="Inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="selecaoestagio",
            name="matricula",
            field=models.CharField(
                db_index=True, max_length=80, verbose_name="Número de Matrícula"
            ),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="area",
            field=models.CharField(db_index=True, max_length=384, verbose_name="Área"),
        ),
    ]
