# -*- coding: utf-8 -*-

DIRF = {
    "DIRF": {  # Hearder de arquivo
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {"label": "identificador_registro", "value": "DIRF", "size": 4, "type": "A"},
        2: {"label": "ano_referencia", "value": 2017, "size": 4, "type": "N"},
        3: {"label": "ano_calendario", "value": 2016, "size": 4, "type": "N"},
        4: {"label": "indicador_retificadora", "value": "N", "size": 1, "type": "A"},
        5: {
            "label": "numero_recibo",
            "value": "",
            "size": 12,
            "type": "N",
            "fixed": False,
            "required": False,
        },
        6: {"label": "identificador_layout", "value": "", "size": 7, "type": "A"},
    },
    "RESPO": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "RESPO",
            "size": 5,
            "type": "A",
        },
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        4: {"label": "ddd", "value": 63, "size": 2, "type": "N"},
        5: {"label": "telefone", "value": "", "size": 9, "type": "N", "fixed": False},
        6: {
            "label": "ramal",
            "value": "",
            "size": 6,
            "type": "N",
            "fill": None,
            "fixed": False,
        },
        7: {
            "label": "fax",
            "value": "",
            "size": 9,
            "type": "N",
            "fill": None,
            "fixed": False,
        },
        8: {
            "label": "email",
            "value": "",
            "size": 50,
            "type": "A",
            "fill": None,
            "fixed": False,
        },
    },
    "DECPJ-2017": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "DECPJ",
            "size": 5,
            "type": "A",
        },
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {
            "label": "nome_empresarial",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        4: {"label": "natureza_declarante", "value": 2, "size": 1, "type": "N"},
        5: {"label": "cpf_responsavel", "value": 0, "size": 11, "type": "N"},
        6: {"label": "indicador_socio_SCP", "value": "N", "size": 1, "type": "A"},
        7: {
            "label": "indicador_depositario_judicial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        8: {
            "label": "indicador_clube_investimento",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        9: {"label": "indicador_exterior", "value": "N", "size": 1, "type": "A"},
        10: {
            "label": "indicador_plano_saude_privado",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        11: {
            "label": "indicador_jogos_olimpicos",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        12: {
            "label": "indicador_situacao_especial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        13: {"label": "data_evento", "value": "", "size": 8, "type": "A", "fill": ""},
    },
    "DECPJ-2018": {
        "cfg": {"label": "", "value": "", "version": "2018"},
        1: {
            "label": "identificador_registro",
            "value": "DECPJ",
            "size": 5,
            "type": "A",
        },
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {
            "label": "nome_empresarial",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        4: {"label": "natureza_declarante", "value": 2, "size": 1, "type": "N"},
        5: {"label": "cpf_responsavel", "value": 0, "size": 11, "type": "N"},
        6: {"label": "indicador_socio_SCP", "value": "N", "size": 1, "type": "A"},
        7: {
            "label": "indicador_depositario_judicial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        8: {
            "label": "indicador_clube_investimento",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        9: {"label": "indicador_exterior", "value": "N", "size": 1, "type": "A"},
        10: {
            "label": "indicador_plano_saude_privado",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        11: {
            "label": "indicador_jogos_olimpicos",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        12: {
            "label": "indicador_uniao_maioria_capital",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        13: {
            "label": "indicador_situacao_especial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        14: {"label": "data_evento", "value": "", "size": 8, "type": "A", "fill": ""},
    },
    "DECPJ": {
        "cfg": {"label": "", "value": "", "version": "2018"},
        1: {
            "label": "identificador_registro",
            "value": "DECPJ",
            "size": 5,
            "type": "A",
        },
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {
            "label": "nome_empresarial",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        4: {"label": "natureza_declarante", "value": 2, "size": 1, "type": "N"},
        5: {"label": "cpf_responsavel", "value": 0, "size": 11, "type": "N"},
        6: {"label": "indicador_socio_SCP", "value": "N", "size": 1, "type": "A"},
        7: {
            "label": "indicador_depositario_judicial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        8: {
            "label": "indicador_clube_investimento",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        9: {"label": "indicador_exterior", "value": "N", "size": 1, "type": "A"},
        10: {
            "label": "indicador_plano_saude_privado",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        11: {
            "label": "indicador_uniao_maioria_capital",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        12: {
            "label": "indicador_fundacao_publica_dir_privado",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        13: {
            "label": "indicador_situacao_especial",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        14: {"label": "data_evento", "value": "", "size": 8, "type": "A", "fill": ""},
    },
    "IDREC": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "IDREC",
            "size": 5,
            "type": "A",
        },
        2: {"label": "codigo_receira", "value": 0, "size": 4, "type": "N"},
    },
    "BPFDEC-2017": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "BPFDEC",
            "size": 6,
            "type": "A",
        },
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        4: {
            "label": "data_laudo_molestia",
            "value": "",
            "size": 8,
            "type": "A",
            "fill": "",
        },
    },
    "BPFDEC": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "BPFDEC",
            "size": 6,
            "type": "A",
        },
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        4: {
            "label": "data_laudo_molestia",
            "value": "",
            "size": 8,
            "type": "A",
            "fill": "",
        },
        5: {
            "label": "indicador_identificacao_alimentando",
            "value": "N",
            "size": 1,
            "type": "A",
        },
        6: {
            "label": "indicador_identificacao_prev_complementar",
            "value": "N",
            "size": 1,
            "type": "A",
        },
    },
    "BPJDEC": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "BPJDEC",
            "size": 6,
            "type": "A",
        },
        2: {"label": "cnpj", "value": 0, "size": 14, "type": "N"},
        3: {
            "label": "nome_empresarial",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
    },
    "RRA": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {"label": "identificador_registro", "value": "RRA", "size": 3, "type": "A"},
        2: {"label": "identificador_rra", "value": 1, "size": 1, "type": "N"},
        3: {
            "label": "numero_processo",
            "value": "",
            "size": 20,
            "type": "A",
            "fixed": False,
        },
        4: {
            "label": "indicador_tipo_advogado",
            "value": None,
            "size": 1,
            "type": "N",
            "fixed": False,
            "required": False,
        },
        5: {
            "label": "cpf_cnpj_advogado",
            "value": None,
            "size": 14,
            "type": "N",
            "fixed": False,
            "required": False,
        },
        6: {
            "label": "nome_advogado",
            "value": "",
            "size": 150,
            "type": "A",
            "fixed": False,
        },
        7: {
            "label": "valor_pago_advogado",
            "value": None,
            "size": 13,
            "type": "N",
            "fixed": False,
            "required": False,
        },
    },
    "BPFRRA-2017": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "BPFRRA",
            "size": 6,
            "type": "A",
        },
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        4: {
            "label": "natureza_rra",
            "value": "",
            "size": 50,
            "type": "A",
            "fill": None,
            "fixed": False,
        },
        5: {
            "label": "data_laudo_molestia",
            "value": "",
            "size": 8,
            "type": "A",
            "fill": "",
        },
    },
    "BPFRRA": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "BPFRRA",
            "size": 6,
            "type": "A",
        },
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        4: {
            "label": "natureza_rra",
            "value": "",
            "size": 50,
            "type": "A",
            "fill": None,
            "fixed": False,
        },
        5: {
            "label": "data_laudo_molestia",
            "value": "",
            "size": 8,
            "type": "A",
            "fill": "",
        },
        6: {
            "label": "indicador_identificacao_alimentando",
            "value": "N",
            "size": 1,
            "type": "A",
        },
    },
    "INFPA": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "INFPA",
            "size": 5,
            "type": "A",
        },
        2: {
            "label": "cpf_alimentando",
            "value": None,
            "size": 11,
            "type": "N",
            "fixed": True,
            "required": False,
        },
        3: {
            "label": "data_nascimento",
            "value": None,
            "size": 8,
            "type": "A",
            "fixed": False,
            "required": False,
        },
        4: {"label": "nome", "value": "", "size": 60, "type": "A", "fixed": False},
        5: {"label": "relacao_dependencia", "value": 4, "size": 2, "type": "N"},
    },
    "VALUES": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "RTRT",
            "size": 5,
            "type": "A",
            "fixed": False,
        },
        2: {
            "label": "m01",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        3: {
            "label": "m02",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        4: {
            "label": "m03",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        5: {
            "label": "m04",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        6: {
            "label": "m05",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        7: {
            "label": "m06",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        8: {
            "label": "m07",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        9: {
            "label": "m08",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        10: {
            "label": "m09",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        11: {
            "label": "m10",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        12: {
            "label": "m11",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        13: {
            "label": "m12",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
        14: {
            "label": "m13",
            "value": "",
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
            "required": False,
        },
    },
    "RIO": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {"label": "identificador_registro", "value": "RIO", "size": 3, "type": "A"},
        2: {
            "label": "valor_pago_ano",
            "value": 0,
            "size": 13,
            "type": "N",
            "decimal": 2,
            "fixed": False,
        },
        3: {
            "label": "descricao_rendimentos",
            "value": "",
            "size": 60,
            "type": "A",
            "fixed": False,
        },
    },
    "QTMESES": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "QTMESES",
            "size": 7,
            "type": "A",
            "fixed": False,
        },
        2: {
            "label": "m01",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        3: {
            "label": "m02",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        4: {
            "label": "m03",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        5: {
            "label": "m04",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        6: {
            "label": "m05",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        7: {
            "label": "m06",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        8: {
            "label": "m07",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        9: {
            "label": "m08",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        10: {
            "label": "m09",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        11: {
            "label": "m10",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        12: {
            "label": "m11",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
        13: {
            "label": "m12",
            "value": "",
            "size": 4,
            "type": "N",
            "decimal": 1,
            "fixed": False,
            "required": False,
        },
    },
    "INF": {
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {"label": "identificador_registro", "value": "INF", "size": 3, "type": "A"},
        2: {"label": "cpf", "value": 0, "size": 11, "type": "N"},
        3: {
            "label": "informacoes_complementares",
            "value": "",
            "size": 500,
            "type": "A",
            "fixed": False,
        },
    },
    "FIMDIRF": {  # Trailer de arquivo
        "cfg": {"label": "", "value": "", "version": "2017"},
        1: {
            "label": "identificador_registro",
            "value": "FIMDirf",
            "size": 7,
            "type": "A",
        },
    },
}
