# Generated by Django 2.2.27 on 2022-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scmmp", "0002_auto_20160728_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membroprocesso",
            name="situacao",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Em Trâmite"),
                    (2, "Sobrestado"),
                    (3, "Julgado"),
                    (4, "Pendente de Recurso"),
                    (5, "Transitado em Julgado: procedente"),
                    (6, "Transitado em Julgado: improcedente"),
                ],
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="sancaojudicial",
            name="cumprimento",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "SIM"), (2, "NÃO")],
                null=True,
                verbose_name="Houve Cumprimento?",
            ),
        ),
        migrations.AlterField(
            model_name="sancaojudicial",
            name="ext_punibilidade",
            field=models.SmallIntegerField(
                choices=[(1, "SIM"), (2, "NÃO")],
                verbose_name="Houve Extinção da Punibilidade?",
            ),
        ),
        migrations.AlterField(
            model_name="sancaojudicial",
            name="reabilitacao",
            field=models.SmallIntegerField(
                choices=[(1, "SIM"), (2, "NÃO")], verbose_name="Reabilitação?"
            ),
        ),
    ]
