# -*- coding: utf-8 -*-
from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LineLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        verbose_name="ID",
                        serialize=False,
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                ("dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.IntegerField(
                        db_index=True,
                        null=True,
                        choices=[
                            (0, "CHECK_ACCESS"),
                            (1, "ADD"),
                            (2, "UPDATE"),
                            (3, "PROFILE_CHANGEPASSWORD"),
                            (4, "DELETE"),
                            (5, "PROFILE_CHANGEINFORMATION"),
                            (8, "AUDIT_VIEW"),
                            (16, "AUDIT_UPDATE"),
                            (32, "AUTENTICATE_LOGIN"),
                            (64, "AUTENTICATE_LOGOUT"),
                            (65, "PROTOCOLO_EDOCBOX_DELETE"),
                            (66, "PROTOCOLO_EDOCBOX_RECEBER"),
                            (67, "PROTOCOLO_EDOCBOX_NEW_COMMIT"),
                            (68, "PROTOCOLO_EDOCBOX_NEW_COMMIT_MOV"),
                            (69, "PROTOCOLO_EDOCBOX_NEW_COMMIT_IMPRIMIR"),
                            (70, "PROTOCOLO_EDOCBOX_INSERIR_MOVIMENTACAO"),
                            (72, "PROTOCOLO_EDOCBOX_MARCAR_NAO_RECEBIDO"),
                            (71, "RH_SERVIDOR_ESPECIALIZADO"),
                            (96, "RH_FRS_CONFIGURACAO"),
                            (97, "RH_FRS_PA_CREATE"),
                            (98, "RH_FRS_PAS_CREATE"),
                            (99, "RH_FRS_GERENCIAMENTO"),
                            (100, "RH_FRS_MARCACAO"),
                            (101, "RH_FRS_AUTORIZACAO"),
                            (128, "RH_CONFIGURATION_COMMIT"),
                            (256, "GFP_LANCADOR_RECALC"),
                            (512, "GFP_LANCADOR_EVENT_INFORMATION"),
                            (1024, "GFP_LANCADOR_EVENT_ADD"),
                            (2048, "GFP_LANCADOR_EVENT_DELETE"),
                            (130, "CONCURSO_HOMOLOGAR_INSCRICAO"),
                            (131, "CONCURSO_DEFERIR_RECURSO"),
                            (2049, "GECAP_CREATE_CAPACITACAO_INVESTIMENTO"),
                            (2050, "GECAP_UPDATE_CAPACITACAO_INVESTIMENTO"),
                            (2051, "GECAP_DELETE_CAPACITACAO_INVESTIMENTO"),
                            (2052, "GECAP_CREATE_INSCRICAO"),
                            (2053, "GECAP_UPDATE_INSCRICAO"),
                            (2054, "GECAP_DELETE_INSCRICAO"),
                            (2055, "GECAP_CREATE_INSCRICAO_INVESTIMENTO"),
                            (2056, "GECAP_UPDATE_INSCRICAO_INVESTIMENTO"),
                            (2057, "GECAP_DELETE_INSCRICAO_INVESTIMENTO"),
                            (2058, "GECAP_INSCRICAO_HOMOLOGACAO"),
                            (2059, "GECAP_INSCRICAO_CERTIFICADO"),
                            (2060, "GECAP_COPY_INSCRICAO_INVESTIMENTO"),
                            (2000, "CMS_CREATE_AREA"),
                            (2001, "CMS_UPDATE_AREA"),
                            (2002, "CMS_DELETE_AREA"),
                            (2003, "CMS_CREATE_LINK"),
                            (2004, "CMS_UPDATE_LINK"),
                            (2005, "CMS_DELETE_LINK"),
                            (2006, "CMS_CREATE_POST"),
                            (2007, "CMS_UPDATE_POST"),
                            (2008, "CMS_DELETE_POST"),
                            (2009, "CMS_CREATE_FILE"),
                            (2010, "CMS_UPDATE_FILE"),
                            (2011, "CMS_DELETE_FILE"),
                            (2012, "CMS_CREATE_IMAGE"),
                            (2013, "CMS_UPDATE_IMAGE"),
                            (2014, "CMS_DELETE_IMAGE"),
                            (2015, "CMS_CREATE_AUDIO"),
                            (2016, "CMS_UPDATE_AUDIO"),
                            (2017, "CMS_DELETE_AUDIO"),
                            (2018, "CMS_CREATE_VIDEO"),
                            (2019, "CMS_UPDATE_VIDEO"),
                            (2020, "CMS_DELETE_VIDEO"),
                            (2021, "CMS_CREATE_PUBLICATION"),
                            (2022, "CMS_DELETE_PUBLICATION"),
                            (2028, "CMS_RELATE_USER"),
                            (2029, "CMS_UNRELATE_USER"),
                            (2030, "CMS_RELATE_FILE"),
                            (2031, "CMS_RELATE_IMAGE"),
                            (2032, "CMS_RELATE_AUDIO"),
                            (2033, "CMS_RELATE_VIDEO"),
                            (2034, "CMS_CREATE_POLL"),
                            (2035, "CMS_UPDATE_POLL"),
                            (2036, "CMS_DELETE_POLL"),
                            (2037, "CMS_CREATE_CHOICE"),
                            (2038, "CMS_UPDATE_CHOICE"),
                            (2039, "CMS_DELETE_CHOICE"),
                            (2040, "CMS_VOTE_POLL"),
                            (2041, "CMS_CREATE_PROSECUTOR_ACTION_STATUS"),
                            (2042, "CMS_UPDATE_PROSECUTOR_ACTION_STATUS"),
                            (2043, "CMS_DELETE_PROSECUTOR_ACTION_STATUS"),
                            (2044, "CMS_CREATE_PROSECUTOR_ACTION"),
                            (2045, "CMS_UPDATE_PROSECUTOR_ACTION"),
                            (2046, "CMS_DELETE_PROSECUTOR_ACTION"),
                            (3001, "COMMON_SAFE_POLL_CREATE"),
                            (3002, "COMMON_SAFE_POLL_UPDATE"),
                            (3003, "COMMON_SAFE_POLL_DELETE"),
                            (3004, "COMMON_SAFE_POLL_CHOCIE_CREATE"),
                            (3005, "COMMON_SAFE_POLL_CHOCIE_UPDATE"),
                            (3006, "COMMON_SAFE_POLL_CHOCIE_DELETE"),
                            (3007, "COMMON_SAFE_POLL_PUBLICATION"),
                            (3008, "COMMON_SAFE_POLL_VOTE"),
                            (3009, "COMMON_SAFE_POLL_COUNT"),
                            (3010, "COMMON_SAFE_POLL_BLOCK_USER"),
                            (3011, "COMMON_SAFE_POLL_REMOVE_BLOCKED_USER"),
                        ],
                    ),
                ),
                (
                    "controller",
                    models.CharField(max_length=200, null=True, db_index=True),
                ),
                ("action", models.CharField(max_length=200, null=True, db_index=True)),
                (
                    "status",
                    models.IntegerField(
                        null=True,
                        choices=[(0, "FAILED"), (1, "SUCCESS"), (2, "WARNING")],
                    ),
                ),
                ("json_description", models.TextField(null=True)),
                ("host_address", models.CharField(max_length=100, null=True)),
                ("host_name", models.CharField(max_length=250, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        on_delete=models.CASCADE,
                    ),
                ),  # Parametro "on_delete" adicionado. (Django 2)
            ],
            options={
                "ordering": ("-dt",),
            },
            bases=(models.Model,),
        ),
    ]
