# Generated by Django 2.2.28 on 2022-10-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarkPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.TimeField(verbose_name="Marcação")),
                ("day", models.DateField(verbose_name="Dia")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_point",
                        to="rh.Servidor",
                        verbose_name="Servidor",
                    ),
                ),
            ],
        ),
    ]
