# Generated by Django 2.2.28 on 2023-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registerpoint", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markpoint",
            options={"ordering": ("-day", "-mark")},
        ),
        migrations.AddField(
            model_name="markpoint",
            name="ip",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="IP"
            ),
        ),
    ]
