# Generated by Django 2.2.28 on 2024-01-12 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registerpoint", "0002_auto_20230518_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="markpoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-01-01 00:10:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="markpoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="markpoint",
            name="justificativa",
            field=models.TextField(blank=True, null=True, verbose_name="Justificativa"),
        ),
        migrations.AddField(
            model_name="markpoint",
            name="marcacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Marcação de Ponto"
            ),
        ),
        migrations.AddField(
            model_name="markpoint",
            name="marcacao_valida",
            field=models.BooleanField(default=True, verbose_name="Marcação Válida"),
        ),
        migrations.AddField(
            model_name="markpoint",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="markpoint",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="markpoint",
            name="tipo_justificativa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "ESQUECEU DE REGISTRAR"),
                    ("2", "ESQUECEU O CRACHÁ"),
                    ("3", "FERIADO MUNICIPAL."),
                    ("4", "LUTO OFICIAL"),
                    ("5", "PARTICIPANDO DE CURSO"),
                    ("6", "JORNADA REDUZIDA - PERÍODO DE PROVAS"),
                    ("7", "LICENÇA-PRÊMIO."),
                    ("8", "FOLGA CONCURSO ESTAGIÁRIO"),
                    ("9", "FOLGA PLANTÃO SERVIDOR "),
                    ("10", "RECESSO REMUNERADO"),
                    ("11", "RECESSO ANO NOVO."),
                    ("12", "A SERVIÇO DA SINDSEMP-MT"),
                    ("13", "SISTEMA EM MANUTENÇÃO."),
                    ("14", "HORÁRIO COMPENSADO"),
                    ("15", "LICENÇA PARA TRATAR INTERESSE PARTICULAR"),
                    ("16", "SUSPENSÃO DO EXPEDIENTE"),
                    ("17", "SISTEMA EM MANUTENCAO"),
                    ("18", "LICENÇA PARA QUALIFICAÇÃO PROFISSIONAL"),
                    ("19", "HORÁRIO COMPENSADO."),
                    ("20", "LICENÇA PATERNIDADE"),
                    ("21", "FERIADO"),
                    ("22", "PONTO NÃO REGISTRADO"),
                    ("23", "A SERVIÇO FORA DA SEDE"),
                    ("24", "PONTO FACULTATIVO"),
                    ("25", "DEMITIDO"),
                    ("26", "DISPENSADO DO PONTO."),
                    ("27", "SEM CRACHÁ"),
                    ("28", "LICENÇA LUTO"),
                    ("29", "FERIADO MUNICIPAL"),
                    ("30", "SISTEMA EM MANUTENÇÃO"),
                    ("31", "DISPENSADO DO PONTO"),
                    ("32", "ATIVIDADES NÃO INICIADAS"),
                    ("33", "LICENÇA GESTACIONAL"),
                    ("34", "FOLGA RECESSO FORENSE"),
                    ("35", "DISPENSA ELEITORAL."),
                    ("36", "FÉRIAS"),
                    ("37", "DISPENSA ELEITORAL"),
                    ("38", "LICENÇA PARA ATIVIDADE POLÍTICA"),
                    ("39", "FÉRIAS."),
                    ("40", "SUSPENSÃO DO EXPEDIENTE."),
                    ("41", "LICENÇA GALA"),
                    ("42", "RECESSO NATALINO."),
                    ("43", "RECESSO ANO NOVO"),
                    ("44", "PONTO NÃO REGISTRADO."),
                    ("45", "A SERVIÇO DA JUSTIÇA ELEITORAL"),
                    ("46", "LICENÇA MÉDICA"),
                    ("47", "DISPENSA POR DOAÇÃO DE SANGUE"),
                    ("48", "DIA SEM ESTÁGIO"),
                    ("49", "LICENÇA SEM REMUNERAÇÃO - ESTAGIÁRIOS"),
                    ("50", "ATIVIDADE DISCENTE OBRIGATÓRIA"),
                    ("51", "VIAGEM A SERVIÇO"),
                    ("52", "LICENÇA-PRÊMIO"),
                    ("53", "ESQUECEU DE REGISTRAR."),
                    ("54", "ATESTADO MÉDICO."),
                    ("55", "VIAGEM À SERVIÇO"),
                    ("56", "EM PROCESSO DE REMOÇÃO."),
                    ("57", "ATIVO"),
                    ("58", "TRIBUNAL DO JÚRI"),
                    ("59", "ATESTADO MÉDICO"),
                    ("60", "EM PROCESSO DE REMOÇÃO"),
                    ("61", "RECESSO REMUNERADO."),
                    ("62", "RECESSO NATALINO"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
