# Generated by Django 2.2.28 on 2024-01-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registerpoint", "0003_auto_20240112_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="markpoint",
            name="codigo_import",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Código - Importação",
            ),
        ),
        migrations.AddField(
            model_name="markpoint",
            name="tabela_import",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Tabela de Importação",
            ),
        ),
    ]
