# Generated by Django 2.2.28 on 2024-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registerpoint", "0005_auto_20240207_2215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markpoint",
            name="day",
            field=models.DateField(blank=True, null=True, verbose_name="Dia"),
        ),
        migrations.AlterField(
            model_name="markpoint",
            name="mark",
            field=models.TimeField(blank=True, null=True, verbose_name="Marcação"),
        ),
    ]
