# Generated by Django 2.2.28 on 2024-02-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registerpoint", "0006_auto_20240223_1112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markpoint",
            options={"ordering": ("-marcacao",)},
        ),
    ]
