# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_auto_20190605_2009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankpartnership",
            name="charge_code",
            field=models.CharField(
                default="3179485", max_length=7, verbose_name="Codigo de Cobranca"
            ),
        ),
        migrations.AlterField(
            model_name="bankpartnership",
            name="partnertship_code",
            field=models.CharField(
                default="319875",
                max_length=6,
                verbose_name="Codigo de Convenio de Com. Eletronico",
            ),
        ),
    ]
