# Generated by Django 2.2.16 on 2020-10-22 16:09

from datetime import timedelta

from django.db import migrations, transaction


def forwards(apps, schema_editor):
    Boleto = apps.get_model("payments", "TicketPay")
    boletos = Boleto.objects.filter(creation_date__isnull=True)
    with transaction.atomic():
        for boleto in boletos:
            boleto.creation_date = boleto.expiration_date - timedelta(days=10)
            boleto.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_auto_20201022_0927"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
