# Generated by Django 2.2.16 on 2020-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_populate_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketpay",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Emissão"
            ),
        ),
    ]
