# Generated by Django 2.2.24 on 2021-11-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Título do Relatório"
                    ),
                ),
                ("sql", models.TextField(verbose_name="Consulta SQL")),
            ],
        ),
    ]
