# Generated by Django 2.2.26 on 2022-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queryregistration", "0004_auto_20211216_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="download",
            field=models.BooleanField(default=False, verbose_name="Download"),
        ),
    ]
