# Generated by Django 2.2.26 on 2022-01-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queryregistration", "0005_consultation_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
