# Generated by Django 2.2.28 on 2022-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queryregistration", "0006_consultation_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
