# Generated by Django 2.2.28 on 2022-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queryregistration", "0009_cachetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachetag",
            name="field_name",
            field=models.CharField(
                default="debug", max_length=128, verbose_name="Nome do Campo"
            ),
            preserve_default=False,
        ),
    ]
