# Generated by Django 2.2.28 on 2022-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queryregistration", "0010_cachetag_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagfield",
            name="sql_in",
            field=models.BooleanField(default=False, verbose_name="Sql in"),
        ),
    ]
